CHANGELOG.rst, enterprise/api.py, test_utils/factories.py, tests/test_api.py
Added a helper method to retrieve EC branding details.
=> ENT-32 added a helper method to retrieve EC branding details

CHANGELOG.rst, enterprise/__init__.py, enterprise/api.py, enterprise/apps.py, enterprise/validators.py, tests/test_api.py, tests/test_models.py
@mattdrayer @zubair-arbi Can you guys take a look ? 
[ENT-32](https://openedx.atlassian.net/browse/ENT-32) & [ENT-83](https://openedx.atlassian.net/browse/ENT-83)
=> ENR-32/83 Return branding information on the basis of EC uuid.

CHANGELOG.rst, enterprise/__init__.py, enterprise/api/v1/serializers.py, tests/api/test_views.py
@saleem-latif @mattdrayer are we ready to merge ?
=> ENT-179: Include 'id' in EnterpriseCustomerUserSerializer fields.

CHANGELOG.rst
**Description:** Fixes CHANGELOG format (and CI build)
**Merge deadline:** ASAP - build is broken on master.
`make docs` passes and CI build is green 
**Reviewers:**
=> [HOTFIX] Fixed docs build

.github/PULL_REQUEST_TEMPLATE.md, README.rst, enterprise/__init__.py
**Description:** Bumps version (missed from #44 )
**JIRA:** [ENT-172](https://openedx.atlassian.net/browse/ENT-172)
**Merge deadline:** Yesterday :)
=> Version bumped edx-enterprise missed from #44

docs/conf.py
Follow-up PR for ENT-226 after learning how all this stuff works in #48 😄 
@e-kolpakov @grantgoodmanedX let me know how this one looks -- if it's better I'll close the original PR.
=> ENT-226: Fix broken conf.py

docs/conf.py
@grantgoodmanedX -- here's another attempt at making the docs work -- let's see how it goes.
=> ENT-226: Repair Sphinx build

README.rst
**Description:** This small PR updates the content and links included in the README.rst file for this code project.
**JIRA:** No JIRA ticket.
**Dependencies:** No dependencies
**Merge deadline:** No merge deadline
**Installation instructions:** No installation instructions, should be able to view in an RST renderer.
1. Checkout branch
2. Review RST source for errors
3. View output in an RST-capable browser, utility, or online tool
**Author concerns:** No concerns
=> mattdrayer/update-readme: Revise content

CHANGELOG.rst, api-compact.yaml, api.yaml, enterprise/__init__.py
**Description:**  Introduce catalogs API endpoints in enterprise api.yaml file for amazon swagger 
@mattdrayer @saleem-latif This is a WIP PR to get feedback. It is fully dependent on [PR#62](https://github.com/edx/edx-enterprise/pull/62/)
**JIRA:** [ENT-250](https://openedx.atlassian.net/browse/ENT-250)
=> ENT-250 Introduce catalog api endpoints in enterprise api.yaml

CHANGELOG.rst, api-compact.yaml, api.yaml, enterprise/__init__.py
Hi @mattdrayer , @asadiqbal08 ,
Please take a look at this PR, I have fixed the problems I was facing trying to test api-manager.
=> ENT-238: Updated api.yaml to comply with swagger specifications.

tests/api/test_views.py
**Description:** This PR addresses an apparent conflict with test state scaffolding between the API views.  @brittneyexline @saleem-latif FYI
**JIRA:** N/A
**Merge deadline:** 3/21
**Installation instructions:** Pull branch, set up virtualenv.
1. On master, run pytest -v tests/api/test_views.py, observe SegmentationFault
2. Check out PR branch, re-run tests
3. Observe error is fixed!
=> Split catalog api assertions into separate test class

CHANGELOG.rst, enterprise/__init__.py, integrated_channels/integrated_channel/learner_data.py, integrated_channels/integrated_channel/models.py, integrated_channels/sap_success_factors/models.py, requirements/base.txt, requirements/dev.txt, requirements/doc.txt, requirements/js_test.txt, requirements/quality.txt, requirements/test.txt, tests/test_learner_data.py, tests/test_management.py
**Description:** We were informed that courseCompleted should be false if the learner received a failing grade. Additionally, I updated the instructor paced grades to be sent as Pass/Fail like the self paced grades were.
**JIRA:** https://openedx.atlassian.net/browse/ENT-286
**Merge deadline:** 3/31/2017
**Installation instructions:** n/a
I'm not sure if any additional verification is necessary beyond the unit tests.
**Author concerns:**
=> ENT-286 Adjustment to grade and courseCompleted values

AUTHORS
**Description:** Adding myself to the AUTHORS file -- can't believe I haven't done it yet!
**JIRA:** N/A
**Merge deadline:** SOON
~~- [ ] Regenerate requirements with `make upgrade && make requirements` (and make sure to fix any errors).~~
~~- [ ] Version bumped~~ (will do as part of #99)
~~- [ ] Changelog record added~~
~~- [ ] Documentation updated (not only docstrings)~~
~~- [ ] Translations are updated~~
~~- [ ] Create a tag~~
~~- [ ] Check new version is pushed to PyPi after tag-triggered build is finished.~~
**Author concerns:** Only that I'll be doing less authoring going forward  😄
=> mattdrayer/add-author: Add "mattdrayer" as author

enterprise/lms_api.py, enterprise/utils.py, enterprise/views.py, tests/test_lms_api.py, tests/test_views.py
**Description:** This change adds a check to the enterprise course enrollment view that forwards the user directly to the course home page when the user is already enrolled in the course.
**JIRA:** [ENT-355](https://openedx.atlassian.net/browse/ENT-355)
**Dependencies:** No dependencies.
**Merge deadline:** May 19th
**Installation instructions:**
1. Setup a devstack on `master`
1. Clone ecommerce into `/edx/src/edx-ecommerce`
1. Checkout this branch: `git checkout bdero/ent-355`
1. Install the local ecommerce:
```
sudo -Hu edxapp bash
pip install -e file:///edx/src/edx-enterprise#egg=edx-enterprise==localdev
./manage.py lms migrate enterprise --settings=devstack
```
1. Create a new EnterpriseCustomer in the [admin …
=> ENT-355 Skip Landing pages if learner already enrolled

CHANGELOG.rst, enterprise/__init__.py
=> Bump version to v0.36.1

CHANGELOG.rst, enterprise/__init__.py, enterprise/static/enterprise/enterprise_course_enrollment_page.css, enterprise/templates/enterprise/enterprise_course_enrollment_page.html, enterprise/templates/enterprise/grant_data_sharing_permissions.html, enterprise/views.py, tests/test_views.py
@saleem-latif @asadiqbal08 @douglashall
**Description:** Styling feedback changes for enterprise course enrollment page
* Header and placement of PP statement are not same as on signing/register. (Here the PP statement Is a paragraph tag, which is right) "Welcome to edX" has disappeared. It should be identical.
* Confirm your Course is an H3. Needs to be an H2
* Title element on the page is "choose your track," when it should be "confirm your course."
* Modal is not responsive. It should function and look like the other modals in this flow (e.g., Terms of Service or data sharing consent, but even these do not look alike).
**JIRA:** [ENT-450](https://openedx.atlassian.net/browse/ENT-450)
**Merge deadline:** 30 June, 2017
**Installation instructions:** Install …
=> ENT-450 UAT Feedback: Enterprise Landing Page Styling

CHANGELOG.rst, enterprise/__init__.py, enterprise/decorators.py, enterprise/signals.py, enterprise/tpa_pipeline.py, enterprise/utils.py, enterprise/views.py, test_utils/__init__.py, tests/test_decorators.py, tests/test_utilities.py, tests/test_views.py
**Description:** The first commit in this PR is a refactor which moves edx-enterprise decorators out of the enterprise.utils module and into an enterprise.decorators module. The second commit in this PR is a refactor of the work done in https://github.com/edx/edx-enterprise/pull/130. I have moved the session termination logic into its own decorator so that it can be applied to only the views that need it.
**JIRA:** https://openedx.atlassian.net/browse/ENT-454
**Installation instructions:** Standard Installation with this version of edx-enterprise.
1. Go to https://business.sandbox.edx.org/enterprise/2b5a2956-7746-4fc9-9587-bc887ba45973/course/course-v1:edX+DemoX+Demo_Course/enroll/ and register a new user, going …
=> ENT-454 Refactor session management logic.

CHANGELOG.rst, enterprise/__init__.py, enterprise/static/enterprise/enterprise_course_enrollment_page.css
**Description:** Text cutoff in the bottom of the course info overlay.
I am building a sandbox, Will share soon.
**JIRA:** [ENT-522](https://openedx.atlassian.net/browse/ENT-522)
=> ENT-522 Text cutoff in the bottom of the course info overlay.

CHANGELOG.rst, enterprise/__init__.py, enterprise/management/commands/create_enterprise_course_enrollments.py, tests/test_enterprise/management/test_create_enterprise_course_enrollments.py
@saleem-latif @asadiqbal08 @douglashall 
**Description:** Add django management command for adding enterprise audit enrollments
**JIRA:** [ENT-557](https://openedx.atlassian.net/browse/ENT-557)
**Remaining:**
* Add tests for the management command
**Merge deadline:** 11 August, 2017
**Installation instructions:**  Install `edx-enterprise` from this branch `zub/ENT-557-enterprise-audit-enrollment` in `edx-platform`.
1. Add courses and enterprise
2. Add enterprise learners for the enterprise
3. Manually enroll the enterprise learners in courses and make sure there is not enterprise course enrollment record from enterprise django admin (delete if there are enterprise course enrollments).
4. Run the django management command …
=> ENT-557 Management Command for Creating EnterpriseCourseEnrollments

api-compact.yaml, api.yaml
=> Fixing swagger doc for API gateway.

CHANGELOG.rst, enterprise/__init__.py, integrated_channels/integrated_channel/management/commands/transmit_courseware_data.py, test_utils/fake_enterprise_api.py, tests/test_management.py
@asadiqbal08 @saleem-latif @douglashall @mattdrayer 
**Description:** Add exception handling for transmit course data task so that course data transmission for multiple integrated channels continues even if any of these integrated channels fails to transmit its catalog data.
**JIRA:** [ENT-592](https://openedx.atlassian.net/browse/ENT-592)
**Merge deadline:** 22 September, 2017
**Installation instructions:** Install `edx-enterprise` from this branch `zub/ENT-592-ocn-catalog-push-command-failure-tolerance` in `edx-platform`.
1. Create enterprise with a course catalog
2. Create two SAP integrated channels: First integrated channel with some bad configuration so that the management command `transmit_courseware_data` fails to transmit its data …
=> ENT-592 Add exception handling for transmit course data task

CHANGELOG.rst, enterprise/__init__.py, enterprise/views.py
**Description:** Added some log messages to trace possible reasons for 404.
[ENT-591](https://openedx.atlassian.net/browse/ENT-591)
=> asadiqbal08/ENT-591 - Added some log messages to get the actual reasons for 404

CHANGELOG.rst, enterprise/__init__.py, enterprise/models.py
Part 2 of enrollment_email_template change. Removes site from model. Does NOT include migration.
WL-1240
Stage 1 already merged to edx-enterprise. Release currently moving out to stage. Must wait to deploy until 0.48.1 has deployed to prod.
N/A
**Installation instructions:** List any non-trivial installation instructions.
N/A
N/A
solutions, hacks, quick-and-dirty implementations, …
=> Remove site from enrollment template model

enterprise/migrations/0030_auto_20171005_1600.py
Migration to remove site from enrollmentnotificationemailtemplate. Part 3/3.
WL-1240
None
None
instructions.
None
None
=> Part 3 of 3-stage deployment of WL-1240. Just the final migration

CHANGELOG.rst, enterprise/__init__.py, enterprise/api_client/lms.py
**Description:** Change the log level from `error` to `info`.
**JIRA:** [ENT-648](https://openedx.atlassian.net/browse/ENT-648)
**Testing instructions:** Ensure there's no typos :)
=> [ENT-648] Change log level from `error` to `info`

CHANGELOG.rst, enterprise/__init__.py, enterprise/migrations/0031_auto_20171012_1249.py
instructions.
1. Open page A
2. Do thing B
=> ENT-694 -Quick update for migration

CHANGELOG.rst, enterprise/__init__.py, enterprise/admin/views.py, enterprise/api/v1/serializers.py, enterprise/models.py
**Description:** This PR adds two small follow up items from the enrollment api work. The first is to make sure that the links in the email notification trigger SSO login if the enterprise has an identity provider. The second is to fire a tracking event for enrollments being created through the endpoint.
**JIRA:** https://openedx.atlassian.net/browse/ENT-806
instructions.
1. Hit the enrollment api endpoint with an enrollment for a pending user (one that doesn't exist yet) with email_students set to true.
```
POST /enterprise/api/v1/enterprise-customer/2b5a2956-7746-4fc9-9587-bc887ba45973/course_enrollments/ HTTP/1.1
Host: …
```
=> ENT-806 Make sure links sent in proxy enroll emails trigger SSO pipeline

CHANGELOG.rst, enterprise/__init__.py, enterprise/admin/__init__.py
**Description:** update django admin list view for enterprise customer model to:
1. ~~Display Enterprise Customer name only in green message bar at top of screen (versus "`<Enterprise Customer uuid-asf123das-d1fsad-fa32se: name>`"~~
2. Replace "logo" column values in list table with a checkbox
3. Add "consent" column with checkboxes for values
4. Replace identity provider column values with checkboxes
5. Replace catalog column values with checkboxes
6. Replace coupon column values with checkboxes
**JIRA:** [ENT-396](https://openedx.atlassian.net/browse/ENT-396)
**Merge deadline:** N/A
**Installation instructions:** Install `edx-enterprise` from this branch `zub/ENT-396-update-enterprise-customer-admin-list-view` in `edx-platform`.
1. Go to …
=> update django admin list view for enterprise customer model

CHANGELOG.rst, enterprise/__init__.py, integrated_channels/degreed/migrations/0003_auto_20180109_0712.py, integrated_channels/sap_success_factors/migrations/0012_auto_20180109_0712.py
**Description:** This PR adds missing migrations for https://github.com/edx/edx-enterprise/pull/270
**JIRA:** [ENT-431](https://openedx.atlassian.net/browse/ENT-431)
**Merge deadline:** Merge before https://github.com/edx/edx-platform/pull/17136
=> Add missing migrations for degreed and sap_success_factors

api-compact.yaml, api.yaml
Missed a reference to course_run_id in the copy/paste.
=> Fix course_key parameter specification for the catalog courses endpoint.

CHANGELOG.rst, enterprise/__init__.py, enterprise/views.py, tests/test_enterprise/views/test_course_enrollment_view.py
[ENT-645](https://openedx.atlassian.net/browse/ENT-645)
=> [ENT-645]-Updated the messages when a learner leave an organization.

.gitignore, CHANGELOG.rst, enterprise/__init__.py, enterprise/admin/__init__.py, enterprise/admin/forms.py, enterprise/api/v1/serializers.py, enterprise/migrations/0044_reporting_config_multiple_types.py, enterprise/models.py, enterprise/settings/test.py, package-lock.json, package.json, tests/test_enterprise/api/test_views.py, tests/test_models.py, tests/test_utilities.py
**Description:** This PR adds some new fields we'll need to make direct integration for customers through CSV format possible.
**JIRA:** https://openedx.atlassian.net/browse/ENT-872
**Dependencies:** https://github.com/edx/edx-enterprise-data/pull/27
You'll need to install this into your LMS as normal, run the migration, and then follow testing instructions on https://github.com/edx/edx-enterprise-data/pull/27.
=> [ENT-872] Push catalogs to direct integration customers in CSV format (SFTP, SMTP)

CHANGELOG.rst, integrated_channels/sap_success_factors/migrations/0014_drop_historical_table.py, integrated_channels/sap_success_factors/migrations/0015_auto_20180510_1259.py, integrated_channels/sap_success_factors/models.py
**Description:** Drops the table specified for https://openedx.atlassian.net/browse/EDUCATOR-2681 . 
=> drop sap_success_factors_historicalsapsuccessfactorsenterprisecus80ad

CHANGELOG.rst, enterprise/__init__.py
Properly updates the version, for the sake of releasing my previous PR on PyPi.
=> Update version in __init__

CHANGELOG.rst, enterprise/__init__.py, enterprise/views.py
**Description:** 500 error when attempting to enroll using course-level URL
**JIRA:** [ENT-1029](https://openedx.atlassian.net/browse/ENT-1029)
Prior, Error was generating on hitting that [URL which contains course_key](https://business.sandbox.edx.org/enterprise/d583b097-7bd9-4a7e-a98d-c15dea220354/course/Mattx+TIPC1/enroll)
=> [ENT-1029]- 500 error when attempting to enroll using course-level URL

CHANGELOG.rst, enterprise/__init__.py, enterprise/views.py
**Description:** Direct-to-Audit enrollment issue in case of course.
**JIRA:** [ENT-995](https://openedx.atlassian.net/browse/ENT-995)
@georgebabey @UmanShahzad @zubair-arbi can you please look into the quick fix for [ENT-995](https://openedx.atlassian.net/browse/ENT-995)
=> [ENT-995] Quick-Fix the Direct-to-Audit enrollment issue in case of course.

CHANGELOG.rst, enterprise/__init__.py
https://github.com/edx/edx-enterprise/pull/347
=> Version bump

CHANGELOG.rst
Updated changelog for ENT-1100
**JIRA:**
https://openedx.atlassian.net/browse/ENT-1100
=> ENT-1100: Updated changelog

CHANGELOG.rst, enterprise/__init__.py, integrated_channels/xapi/migrations/0002_auto_20180726_0142.py
**JIRA:** [ENT-1018](https://openedx.atlassian.net/browse/ENT-1018)
=> ENT-1018:  Updated migrations.

enterprise/admin/__init__.py
**Description:** Preview field that takes user to Discovery with elastic search results for the catalog
**JIRA:** https://openedx.atlassian.net/browse/ENT-1121
1. Open admin page /admin/enterprise/enterprisecustomercatalog/
2. Create a test record
3. Verify preview option
=> ENT-1121 Preview field that takes user to Discovery with elastic search results for the catalog

CHANGELOG.rst, enterprise/__init__.py, enterprise/admin/__init__.py, enterprise/admin/forms.py, enterprise/migrations/0053_auto_20180911_0811.py, enterprise/models.py, requirements/dev.txt, requirements/test.txt
Added country field to EnterpriseCustomer model
**JIRA:** 
https://openedx.atlassian.net/browse/ENT-1197
1. Open page http://business.sandbox.edx.org/admin/enterprise/enterprisecustomer/
2. Verify country field
3. Create new enterprise customer
4. Verify that country is stored
=> Added country field

.gitignore, consent/models.py, enterprise/utils.py, requirements/dev.txt, requirements/doc.txt, requirements/js_test.txt, requirements/quality.txt, requirements/test-master.txt, requirements/test.txt, requirements/travis.txt, test_utils/__init__.py, tests/test_admin/test_view.py, tests/test_consent/api/test_permissions.py, tests/test_enterprise/api/test_filters.py, tests/test_enterprise/api/test_serializers.py, tests/test_enterprise/api/test_views.py, tests/test_utilities.py
This PR fixes a bunch of style/linter errors that were now being checked in edx-lint
=> Quality fixes

AUTHORS, CHANGELOG.rst, enterprise/__init__.py, enterprise/utils.py, requirements/dev.txt, requirements/doc.txt, requirements/js_test.txt, requirements/quality.txt, requirements/test-master.in, requirements/test-master.txt, requirements/test.txt, requirements/travis.txt, tests/test_enterprise/views/test_router_view.py, tests/test_models.py, tests/test_utilities.py
**Description:** In order to ensure that all context information needed for Segment events is provided, a method was defined in the LMS that is used by all Segment events in the LMS.  Rather than cut-and-paste that logic here, this PR simply calls out to that method. 
**JIRA:** DE-1152
**Merge deadline:** Looking to merge this and all other additions of 'host' to Segment events in the coming week.
**Installation instructions:** No special instructions.
1. Enable the LMS with a development Segment key.
2. Generate an enterprise enrollment event.
a. Create a new enterprise customer, using admin/enterprise/enterprisecustomer
b. Click on the customer to edit, then click on the "Manage Learners" …
=> Use LMS-defined segment track() method

CHANGELOG.rst, enterprise/__init__.py
instructions.
1. Open page A
2. Do thing B
=> Bump to version 1.2.7

.annotation_safe_list.yml, .pii_annotations.yml, consent/models.py, enterprise/models.py, integrated_channels/degreed/models.py, integrated_channels/integrated_channel/models.py, integrated_channels/sap_success_factors/models.py, integrated_channels/xapi/models.py
**Description:** Change PII annotations from :: to : per OEP-30 update. This fixes warnings further down the documentation toolchain.
=> Update annotations from :: to :

CHANGELOG.rst, consent/admin/__init__.py, enterprise/__init__.py
instructions.
1. Open page A
2. Do thing B
=> ENT-1515: Enable Admins to Update DSC Records

CHANGELOG.rst, enterprise/__init__.py
**Description:** Version bumped and added changelog
instructions.
1. Open page A
2. Do thing B
=> Version bumped and added changelog

CHANGELOG.rst, enterprise/__init__.py, enterprise/templates/enterprise/enterprise_course_enrollment_page.html
**Description:** This PR has changes to fix 500 error when enterprise user enrolls in audit track of course.
instructions.
1. Open page A
2. Do thing B
=> Ziafazal/wl-1902: Fix for enrollment failure on audit track

enterprise/models.py
[ENT-1735
](https://openedx.atlassian.net/browse/ENT-1711)
instructions.
1. Open page A
2. Do thing B
=> add role metadata for edx-openedx-operator

CHANGELOG.rst, enterprise/__init__.py, enterprise/constants.py, enterprise/models.py, tests/test_models.py
**Description:** Add `*` as context for `enterprise-openedx-operator` role
instructions.
1. Open page A
2. Do thing B
=> update context for enterprise-openedx-operator role

enterprise/__init__.py
instructions.
1. Open page A
2. Do thing B
=> Version Bump to 1.4.1.

CHANGELOG.rst, enterprise/__init__.py, enterprise/views.py
**Description:** Fix invalid object attribute references from pull request #455   @christopappas FYI
**JIRA:** ENT-1748
=> ENT-1748: Fix invalid object attribute references in exception message

CHANGELOG.rst, enterprise/__init__.py, enterprise/admin/__init__.py
**Description:** Update the list display django admin interface for `SystemWideEnterpriseUserRoleAssignment` with enterprise customer attached with user and add search by enterprise customer 
**JIRA:** [ENT-1877](https://openedx.atlassian.net/browse/ENT-1877)
=> update admin for systemwide role assignments

.travis.yml, openedx.yaml, setup.py
instructions.
1. Open page A
2. Do thing B
=> Updating travis file to use python 3.6

CHANGELOG.rst, enterprise/__init__.py
instructions.
1. Open page A
2. Do thing B
=> Bump version to 1.5.6

enterprise/__init__.py
instructions.
1. Open page A
2. Do thing B
=> ENT-1971 version bump

api-compact.yaml, api.yaml
**Description:** Remove old-style enterprise catalogs endpoints from api-gateway
**JIRA:** [ENT-1947](https://openedx.atlassian.net/browse/ENT-1947)
**Note to Reviewers:** How to test and deploy changes in this PR?
=> api-gateway: remove old-style catalog endpoints

CHANGELOG.rst, enterprise/__init__.py, enterprise/rules.py, requirements/base.in, requirements/dev.txt, requirements/doc.txt, requirements/quality.txt, requirements/test-master.txt, requirements/test.txt
The goal of this PR is to unblock others from making updates to edx-enterprise that can go out to edx-platform. There is a bug (ENT-2002) with using the edx-drf-extensions functions for getting the jwt from the request. Until that is fixed, we need to use the old rbac functions, and pin edx-rbac to the version with the functions we were using before. Then we'll be able to safely upgrade edx-enterprise in edx-platform and others can get their edx-enterprise changes.
instructions.
1. Open page A
2. Do thing B
4. …
=> Go back to using get_decoded_jwt_from_request until we can safely use edx-drf-extensions

CHANGELOG.rst, enterprise/__init__.py
instructions.
1. Open page A
2. Do thing B
=> Bump version to 1.6.8

CHANGELOG.rst, enterprise/__init__.py, enterprise/api/v1/views.py, requirements/base.in, requirements/dev.txt, requirements/doc.txt, requirements/js_test.txt, requirements/quality.txt, requirements/test-master.txt, requirements/test.txt, requirements/travis.txt
instructions.
1. Open page A
2. Do thing B
=> Change DjangoFilterBackend import location

CHANGELOG.rst, enterprise/__init__.py, enterprise/models.py
instructions.
1. Open page A
2. Do thing B
=> Update api clients to call the correct site

CHANGELOG.rst, enterprise/__init__.py
instructions.
1. Open page A
2. Do thing B
=> Bump Version to 1.6.15

tests/test_enterprise/api_client/test_discovery.py, tests/test_models.py
instructions.
1. Open page A
2. Do thing B
=> tests for get_course_id

tests/test_enterprise/api_client/test_discovery.py, tests/test_models.py
instructions.
1. Open page A
2. Do thing B …
=> Revert tests

enterprise/utils.py, integrated_channels/degreed/exporters/content_metadata.py, tests/test_integrated_channels/test_degreed/test_exporters/test_content_metadata.py, tests/test_utilities.py
**Description:** Added course duration info in degreed course description.
**JIRA:** ENT-1598
**Dependencies:** This [PR](https://github.com/edx/course-discovery/pull/1970)
instructions.
1. Open page A
2. Do thing B
=> ENT-1598 | Added course duration info in degreed course description.

CHANGELOG.rst, enterprise/__init__.py, enterprise/api/v1/serializers.py, enterprise/api/v1/views.py
**Description:** This PR adds additional logging for the enterprise api
**JIRA:** https://openedx.atlassian.net/browse/ENT-1949
=> ENT-1949 Additional logging for enterprise api

CHANGELOG.rst, MANIFEST.in, Makefile, enterprise/__init__.py, requirements/base.in, requirements/dev.in, requirements/dev.txt, requirements/doc.in, requirements/doc.txt, requirements/edx-platform-constraints.txt, requirements/js_test.txt, requirements/test-master.in, requirements/test-master.txt, requirements/test.in, requirements/test.txt, setup.py
Dependencies have been troublesome recently. I'd like to have some assurance we can run into trouble less often.
There are two core problems that this PR is solving is for this library, which could only ever be installed into edx-platform. One is to be way less opinionated about what version of packages it requires when setup.py is run. The second is that, when we are testing and developing, our opinion on what version of packages are installed should largely be whatever is in edx-platform.
`base.in` now has the authoritative list of requirements that are declared as dependencies when the library is installed. You will see that most of the versions have been unpinned, which means edx-platform should be free to choose the correct version it needs without being concerned …
=> Let's try to not pin so much.

CHANGELOG.rst, enterprise/__init__.py, enterprise/admin/__init__.py
**Description:** Show linked enterprise customer on `Enterprise Customer Learners` screen and `System wide Enterprise User Role Assignments` screen.
**JIRA:** https://openedx.atlassian.net/browse/ENT-2046
**Testing:** Code is deployed on sandbox. Please follow the below links to see the changes in action
1. https://mammar.sandbox.edx.org/admin/enterprise/systemwideenterpriseuserroleassignment/
2. https://mammar.sandbox.edx.org/admin/enterprise/enterprisecustomeruser/
=> show linked enterprise customer

CHANGELOG.rst, enterprise/__init__.py, enterprise/api/v1/views.py
instructions.
1. Open page A
2. Do thing B …
=> Log success of coupon code request email send.

CHANGELOG.rst, enterprise/__init__.py, enterprise/api/v1/views.py, enterprise/apps.py, requirements/dev.txt, requirements/doc.txt, requirements/edx-platform-constraints.txt, requirements/test.txt, requirements/travis.txt
**Description:** Zendesk does not like it when it receives an email with the from address set to the email address that is configured as the support address. This causes tickets generated from email to end up in the "Suspended Tickets" view. This change will fix that problem by using the enterprise-integrations@edx.org email address as the from address on the email that is sent to customersuccess@edx.org.
instructions.
1. Open page A
2. Do thing B
- `base.in` if needed …
=> Make coupon code request email from address the one supplied by the user.

CHANGELOG.rst, consent/api/v1/views.py, enterprise/__init__.py, enterprise/views.py, enterprise/views_error_codes.txt
**Description:** Add/Improve logging to monitoring the DSC flow.
**JIRA:** https://openedx.atlassian.net/browse/ENT-1953
=> improve monitoring for DSC flow

CHANGELOG.rst
instructions.
1. Open page A
2. Do thing B …
=> Updates changelog for pending release that adds history models

CHANGELOG.rst, README.rst, integrated_channels/README.md, integrated_channels/cornerstone/exporters/content_metadata.py, integrated_channels/degreed/exporters/content_metadata.py, integrated_channels/integrated_channel/exporters/content_metadata.py, integrated_channels/integrated_channel/transmitters/content_metadata.py, integrated_channels/sap_success_factors/exporters/content_metadata.py, test_utils/__init__.py, tests/test_admin/test_actions.py, tests/test_enterprise/api/test_views.py
**Description:** Fix image link and typos
=> Fix image link and typos

CHANGELOG.rst, enterprise/__init__.py, enterprise_learner_portal/api/v1/serializers.py
instructions.
1. Open page A
2. Do thing B …
=> Once again prevent errors happen if certificate_info is None

CHANGELOG.rst, enterprise/__init__.py, enterprise/migrations/0073_enterprisecustomerreportingconfiguration_uuid.py
instructions.
1. Open page A
2. Do thing B …
=> Corrected issue with missing information in a migration.

CHANGELOG.rst, enterprise/__init__.py, enterprise/views.py
**Description:** This PR improves the Enterprise Enrollment Workflow logs for efficient monitoring in Splunk
**JIRA:** https://openedx.atlassian.net/browse/ENT-1952
=> ENT-1952 Updated logs for splunk monitoring

enterprise/api/v1/views.py
instructions.
1. Open page A
2. Do thing B …
=> Rename edx-portal to frontend-app-admin-portal

CHANGELOG.rst
=> Changelog update

CHANGELOG.rst
=> Changelog version

CHANGELOG.rst, enterprise/__init__.py, integrated_channels/sap_success_factors/exporters/content_metadata.py, tests/test_integrated_channels/test_sap_success_factors/test_exporters/test_content_metadata.py
=> ENT-2223: Field update for image url

CHANGELOG.rst, enterprise/__init__.py, enterprise/api_client/ecommerce.py
=> Add manual enrollment order API method

CHANGELOG.rst, enterprise/__init__.py, enterprise/admin/__init__.py
=> Separate enterprise enrollments from all other enrollments in django admin

CHANGELOG.rst, enterprise/__init__.py, integrated_channels/xapi/serializers.py, integrated_channels/xapi/utils.py, tests/test_integrated_channels/test_xapi/test_serializers.py
JIRA: https://openedx.atlassian.net/browse/ENT-2346
=> ENT-2346 Set the active enterprise for xapi

CHANGELOG.rst, docs/decisions/0001-multiple-enterprise-support.rst, enterprise/__init__.py
JIRA: https://openedx.atlassian.net/browse/ENT-2016
https://openedx.atlassian.net/browse/ENT-2017
=> ENT-2017 Document for multiple enterprises decision

enterprise/__init__.py, enterprise/migrations/0028_link_enterprise_to_enrollment_template.py, enterprise/migrations/0029_auto_20170925_1909.py, enterprise/migrations/0032_reporting_model.py, enterprise/migrations/0044_reporting_config_multiple_types.py, enterprise/models.py, integrated_channels/degreed/migrations/0001_initial.py, integrated_channels/degreed/migrations/0002_auto_20180104_0103.py, integrated_channels/integrated_channel/migrations/0005_auto_20180306_1251.py, integrated_channels/integrated_channel/models.py, integrated_channels/sap_success_factors/migrations/0011_auto_20180104_0103.py, integrated_channels/xapi/migrations/0001_initial.py, integrated_channels/xapi/models.py
JIRA Link : https://openedx.atlassian.net/browse/BOM-1153
=> BOM-1153 : Applied django codemods to edx-enterprise

CHANGELOG.rst, enterprise/__init__.py, integrated_channels/sap_success_factors/exporters/content_metadata.py, tests/test_integrated_channels/test_sap_success_factors/test_exporters/test_content_metadata.py
=> ENT-2604: Remove totalHours from Successfactors content-metadata export

tests/test_management.py
=> Fixing tests

CHANGELOG.rst, enterprise/__init__.py, integrated_channels/xapi/client.py, integrated_channels/xapi/management/commands/send_course_completions.py, integrated_channels/xapi/utils.py
=> xAPI: Improve completion event logging.

.travis.yml, CHANGELOG.rst, enterprise/__init__.py
Added new release tag `3.2.4`.
=> Added new tag and specified python version for release

CHANGELOG.rst, enterprise/__init__.py, enterprise/models.py
=> Improve EnterpriseRoleAssignment exception message.

CHANGELOG.rst, enterprise/__init__.py
=> Version bump.

.github/PULL_REQUEST_TEMPLATE.md
I'm deleting the merge checklist, because well A. that's the thing I'm updating and B. **do I really need to version this and update edx-platform just for a PR template update?**
=> DOC: Make PR template a bit more informative/descriptive.

CHANGELOG.rst, enterprise/__init__.py, enterprise/models.py
=> Migrations added

CHANGELOG.rst, enterprise/__init__.py, enterprise/api_client/discovery.py, integrated_channels/xapi/management/commands/send_course_completions.py, integrated_channels/xapi/management/commands/send_course_enrollments.py, integrated_channels/xapi/statements/base.py, integrated_channels/xapi/utils.py, tests/test_integrated_channels/test_xapi/test_statements/test_course_completion.py, tests/test_integrated_channels/test_xapi/test_statements/test_learner_course_enrollment.py, tests/test_integrated_channels/test_xapi/test_utils.py
=> xAPI: Include course UUID in activity extensions collection

CHANGELOG.rst, enterprise/__init__.py, enterprise/api_client/discovery.py, tests/test_enterprise/api_client/test_discovery.py
=> Discovery API Client: Fix invalid key references

CHANGELOG.rst, enterprise/__init__.py, enterprise/api_client/discovery.py, enterprise/api_client/ecommerce.py, enterprise/api_client/enterprise_catalog.py, enterprise/api_client/lms.py, enterprise/heartbeat/__init__.py, enterprise/heartbeat/checks.py, enterprise/heartbeat/exceptions.py, enterprise/heartbeat/throttles.py, enterprise/heartbeat/utils.py, enterprise/heartbeat/views.py, enterprise/settings/test.py, enterprise/urls.py, test_utils/decorators.py, test_utils/fake_heartbeat_responses.py, tests/test_enterprise/heartbeat/__init__.py, tests/test_enterprise/heartbeat/test_checks.py, tests/test_enterprise/heartbeat/test_utils.py, tests/test_enterprise/heartbeat/test_views.py
=> ENT-2657: Added health checks for enterprise service.

enterprise/rules.py
=> Make docstrings in enterprise/rules.py truthful.

CHANGELOG.rst, enterprise/__init__.py, enterprise/views.py
=> fixing enrollment issue, adding logging for course mode info

requirements/dev.txt, requirements/doc.txt, requirements/edx-platform-constraints.txt, requirements/test-master.txt, requirements/test.txt, requirements/travis.txt
https://openedx.atlassian.net/browse/BOM-1929
=> unpin drf-jwt -- BOM-1929

CHANGELOG.rst, enterprise/__init__.py, enterprise/api/v1/serializers.py, tests/test_enterprise/api/test_views.py
=> add hide_original_course_price to EntCus serializer

CHANGELOG.rst, enterprise/__init__.py, integrated_channels/canvas/dev_docs/README.md, integrated_channels/canvas/dev_docs/postman_collections/Canvas.postman_collection.json
=> ENT-3284 postman collection and readme

CHANGELOG.rst, enterprise/__init__.py, enterprise/api/v1/serializers.py, enterprise/models.py, test_utils/factories.py, tests/test_enterprise/api/test_views.py, tests/test_models.py, tests/test_utilities.py
https://openedx.atlassian.net/browse/ENT-2892
Backend PR 3 of 4. …
=> ENT-2982 | Remove refs to deprecated color fields.

CHANGELOG.rst, enterprise/__init__.py, enterprise/api/v1/serializers.py, enterprise/models.py
=> ENT-3330 | Added logging in enrollment endpoint for test purposes.

CHANGELOG.rst, enterprise/__init__.py, enterprise/admin/__init__.py, enterprise/admin/forms.py, enterprise/admin/views.py, enterprise/templates/enterprise/admin/clear_learners_data_sharing_consent.html
=> ENT-3304 | Changed the strings.

docs/decisions/0003-canvas-integrated-channel.rst, integrated_channels/canvas/docs/decisions/0001-integration-classic-vs-lti.rst
ADR Reference:
https://open-edx-proposals.readthedocs.io/en/latest/oep-0019-bp-developer-documentation.html#adrs
Also, because it is a doc only change, I was going to skip doing version, changelog etc as well. but I can be corrected if that is not desirable.
- It may or may not make a migration depending on …
=> ENT-3243: ADR for canvas integration

CHANGELOG.rst, enterprise/__init__.py, enterprise/management/commands/create_missing_dsc_records.py, tests/test_enterprise/management/test_create_missing_dsc_records.py
**Description:** Create missing DSC records.
**JIRA:** [ENT-3328](https://openedx.atlassian.net/browse/ENT-3328) …
=> create missing DSC records

CHANGELOG.rst, enterprise/__init__.py, integrated_channels/integrated_channel/exporters/learner_data.py, tests/test_management.py
=> adding more informative logs to the integrated channels

CHANGELOG.rst, enterprise/__init__.py, integrated_channels/integrated_channel/exporters/learner_data.py, integrated_channels/integrated_channel/tasks.py, integrated_channels/utils.py, tests/test_management.py
=> including enterprise customer within logs

CHANGELOG.rst, enterprise/__init__.py, requirements/constraints.txt, requirements/dev.txt, requirements/doc.txt, requirements/edx-platform-constraints.txt, requirements/test-master.txt, requirements/test.txt, requirements/travis.txt
=> WIP: Upgrade celery to 4.4.7

CHANGELOG.rst, enterprise/__init__.py, integrated_channels/canvas/client.py
Locally, was able to get name updated, via update method, by manually changing name in the content metadata and running task again. Verified in canvas the name was changed
Now this code will find the course by integration_id (it must be url encoded for it to work) …
=> search course by integration_id urlencoded

CHANGELOG.rst, enterprise/__init__.py, enterprise/views.py
Updates language in Data Sharing Consent modal per specifications in ticket https://openedx.atlassian.net/browse/ENT-3395?atlOrigin=eyJpIjoiZDEyMjAyYTUxZGE5NGJiMGI4M2E4ZWU2ZTQ0NmM0OTMiLCJwIjoiaiJ9
- This …
=> DSC language update

integrated_channels/canvas/client.py, integrated_channels/degreed/client.py, integrated_channels/exceptions.py, integrated_channels/integrated_channel/transmitters/content_metadata.py, integrated_channels/integrated_channel/transmitters/learner_data.py, integrated_channels/moodle/client.py, integrated_channels/sap_success_factors/client.py, integrated_channels/sap_success_factors/transmitters/learner_data.py, tests/test_integrated_channels/test_canvas/test_client.py, tests/test_integrated_channels/test_cornerstone/test_exporters/test_learner_data.py, tests/test_integrated_channels/test_degreed/test_client.py, tests/test_integrated_channels/test_sap_success_factors/test_client.py, tests/test_integrated_channels/test_sap_success_factors/test_transmitters/test_learner_data.py
=> better exception handling for canvas learner data transmission

CHANGELOG.rst, enterprise/__init__.py, enterprise/views.py, tests/test_enterprise/views/test_grant_data_sharing_permissions.py
=> enroll learner in course when DSC is disabled

enterprise/__init__.py
Looks like there was a merge/rebase error (version should have been 3.8.28 not 3.8.27) …
=> fix version to 3.8.28

CHANGELOG.rst, enterprise/__init__.py, integrated_channels/moodle/client.py, tests/test_integrated_channels/test_moodle/test_client.py, tests/test_integrated_channels/test_moodle/test_transmitters/test_learner_data.py
Base transmitter expects a tuple of (code, body) …
=> [BUG] Moodle client return error fix

CHANGELOG.rst, enterprise/__init__.py, enterprise/api/v1/views.py, enterprise/models.py
Doing this as a first part of https://openedx.atlassian.net/browse/ENT-3414
Makes no functional changes, just refactors the revoke endpoint into smaller parts, so that implementing new logic is easier to manage.
- It may or may not make a migration depending on exactly what you modified, but it should still …
=> Refactor license_revoke endpoint into bite-sized pieces.

CHANGELOG.rst, enterprise/__init__.py, enterprise/api/v1/urls.py, enterprise/api/v1/views.py
=> ENT-3511 API for fetching user token from tableau

integrated_channels/moodle/client.py
Moodle is incredibly inconsistent with return types and we are experiencing errors due to grades returning ints and sometimes strings.
This aims to handle that.
- This should be run from either a venv …
=> BUG Fix: Moodle - fix handling of certain return statuses

CHANGELOG.rst, enterprise/__init__.py, enterprise/api/v1/views.py
=> ENT-3513 Authenticate Tableau user with username without enterprise

CHANGELOG.rst
=> ENT-3513 update changelog

CHANGELOG.rst, enterprise/__init__.py, enterprise/views.py, tests/test_enterprise/views/test_grant_data_sharing_permissions.py
ENT-3553
- This should be run from either a venv with all the lms/edx-enterprise requirements installed or if you checked out edx-enterprise into the src directory used by lms, you can run this command …
=> add check for license_uuid that got accidentally deleted

CHANGELOG.rst, enterprise/messages.py, enterprise/views.py, enterprise/views_error_codes.txt, test_utils/mixins.py, tests/test_enterprise/views/test_course_enrollment_view.py
=> ENT-3603 | improved EnrollmentView's logging for better debugging.

enterprise/__init__.py
=> updated version

CHANGELOG.rst, enterprise/__init__.py, enterprise/admin/forms.py, enterprise/admin/utils.py, enterprise/admin/views.py, enterprise/api/v1/fields.py, enterprise/api/v1/serializers.py, enterprise/api/v1/views.py, enterprise/api_client/lms.py, enterprise/utils.py, tests/test_admin/test_utilities.py, tests/test_admin/test_view.py, tests/test_enterprise/api/test_views.py, tests/test_enterprise/test_utils.py, tests/test_utilities.py
=> ENT-3116: Adds in API endpoint that mimics admin manager_learner functionality

CHANGELOG.rst, enterprise/__init__.py, enterprise/api/v1/views.py, enterprise/signals.py, enterprise/utils.py
=> ENT-3512 change username with user_id for tableau

docs/testing.rst
Notably: talks about the `pytest.local.ini` file.
=> improve the testing doc

integrated_channels/moodle/exporters/content_metadata.py, tests/test_integrated_channels/test_moodle/test_exporters/test_content_metadata.py
Enrollment link text updated and updated to automatically open link in new tab. …
=> minor enrollment link updates for Moodle

enterprise/forms.py, enterprise/models.py, enterprise/utils.py, enterprise/views.py, tests/test_enterprise/views/test_enterprise_login_view.py
=> updated EnterpriseLoginView for multiple IDPs.

enterprise/decorators.py
=> ENT-3590: Updated decorator to account for multiple IDPs

enterprise/models.py
**JIRA**: https://openedx.atlassian.net/browse/ENT-3593 …
=> ENT-3593: update sync_learner_profile_data logic

enterprise/admin/__init__.py, enterprise/tpa_pipeline.py, integrated_channels/sap_success_factors/exporters/learner_data.py
=> ENT-3592: Updated pipeline and admin methods for multiple identity providers

CHANGELOG.rst, enterprise/__init__.py, enterprise/views.py
ENT-3722
- This should be run from either a venv with all the lms/edx-enterprise requirements installed or if you checked out edx-enterprise into the src directory used by lms, you can run this command …
=> add logs for enterprise course enrollment page

enterprise/decorators.py, enterprise/models.py, tests/test_models.py, tests/test_utilities.py
=> Multiple idps new approach

enterprise/api/v1/serializers.py, enterprise/models.py, enterprise/tpa_pipeline.py, integrated_channels/sap_success_factors/exporters/learner_data.py, tests/test_management.py
=> Fixed remaining test failures

CHANGELOG.rst, enterprise/__init__.py, enterprise/templates/enterprise/base.html, enterprise/views.py
=> use logo from `get_platform_logo_url` in django template base.html

CHANGELOG.rst, enterprise/__init__.py, enterprise/urls.py, integrated_channels/api/urls.py, integrated_channels/api/v1/canvas/serializers.py, integrated_channels/api/v1/canvas/urls.py, integrated_channels/api/v1/canvas/views.py, integrated_channels/api/v1/urls.py, tests/test_integrated_channels/test_api/test_canvas/test_views.py
=> ENT-3614: Adds in API for CanvasEnterpriseCustomerConfiguration

integrated_channels/blackboard/client.py
External here refers to which column is viewable outside of the course by students (in the student grades view), not what grades are externally reported to Blackboard.  ¯\_(ツ)_/¯
Tested locally 👍 
- This …
=> Change grade columns to be not external

CHANGELOG.rst, enterprise/__init__.py, integrated_channels/api/v1/blackboard/serializers.py, integrated_channels/api/v1/blackboard/urls.py, integrated_channels/api/v1/blackboard/views.py, integrated_channels/api/v1/urls.py, test_utils/factories.py, tests/test_integrated_channels/test_api/test_blackboard/test_views.py
Thanks to @taliaedX for the initial work that I just easily modeled after.
WIP- 
TODO:
Unit testing
Tweaking based on frontend work
General cleanup …
=> Backend support for blackboard user facing configurations

CHANGELOG.rst, enterprise/__init__.py, integrated_channels/api/v1/sap_success_factors/serializers.py, integrated_channels/api/v1/sap_success_factors/urls.py, integrated_channels/api/v1/sap_success_factors/views.py, integrated_channels/api/v1/urls.py, tests/test_integrated_channels/test_api/test_sap_success_factors/test_views.py
Adds SAP Success Factors API endpoints to the new Integrated Channels API.
(This is going to need conflict fixes once Canvas is merged) …
=> Success Factors Config API endpoints

CHANGELOG.rst, enterprise/__init__.py, integrated_channels/sap_success_factors/admin/__init__.py, integrated_channels/sap_success_factors/client.py
=> ENT-3688: Added missing error handler for SAPSuccessFactorsAPIClient

.github/workflows/ci.yml, Makefile, requirements/celery44.txt, requirements/celery50.txt, requirements/constraints.txt, requirements/dev.txt, requirements/doc.txt, requirements/edx-platform-constraints.txt, requirements/js_test.txt, requirements/test-master.txt, requirements/test.txt, tox.ini
https://openedx.atlassian.net/browse/BOM-2167
- Adding celery 5.0 testing using tox.
=> Adding celery with tox.

.github/workflows/ci.yml, CHANGELOG.rst, Makefile, enterprise/__init__.py, requirements/celery44.txt, requirements/celery50.txt, requirements/constraints.txt, requirements/dev.txt, requirements/doc.txt, requirements/edx-platform-constraints.txt, requirements/test-master.txt, requirements/test.txt, setup.py, tox.ini
Upgrading celery to 5.0.4
Bump the version.
=> Upgrading celery to 5.0.4

CHANGELOG.rst, enterprise/models.py, enterprise/utils.py, integrated_channels/integrated_channel/tasks.py, tests/test_integrated_channels/test_cornerstone/test_models.py, tests/test_utilities.py
=> Edx abolger/ent 3559 learner signals

CHANGELOG.rst, enterprise/__init__.py
=> Version bump for previously unreleased changes.

CHANGELOG.rst, enterprise/__init__.py
=> bump version

CHANGELOG.rst, enterprise/__init__.py, integrated_channels/api/v1/degreed/serializers.py, integrated_channels/api/v1/degreed/urls.py, integrated_channels/api/v1/degreed/views.py, integrated_channels/api/v1/urls.py, tests/test_integrated_channels/test_api/test_degreed/test_views.py
This adds endpoints for the Degreed LMS to the Integrated Channels API. Tests are completed as well.
**NOTE**: Will do versioning post approval to avoid millions of rebases.
I am also likely aware of the many quality failures (not getting the right quality checks running locally which is annoying) so please don't point those out.
- *Note*: This **must** be run if …
=> Degreed API Endpoints

CHANGELOG.rst, enterprise/__init__.py, enterprise/views.py
and EnterpriseLoginView
- This should be run from either a venv with all the lms/edx-enterprise requirements installed or if you checked out edx-enterprise into the src directory used by lms, you can run …
=> ENT-3909 | added missing context for EnterpriseSelectionView and EnterpriseLoginView

CHANGELOG.rst, enterprise/__init__.py, integrated_channels/api/v1/cornerstone/serializers.py, integrated_channels/api/v1/cornerstone/urls.py, integrated_channels/api/v1/cornerstone/views.py, integrated_channels/api/v1/urls.py, tests/test_integrated_channels/test_api/test_cornerstone/test_views.py
Does what it says.
There is 1 extra addition here and that is me removing unused imports in Degreed's serializer file. …
=> Cornerstone API Endpoints

docs/decisions/0004-explicitly-declare-enterprise-for-role-assignments.rst
=> ADR for explicit customer role assignments.

CHANGELOG.rst, enterprise/__init__.py, enterprise/decorators.py, enterprise/models.py, enterprise/views.py, tests/test_decorators.py, tests/test_enterprise/views/test_enterprise_proxy_login_view.py, tests/test_enterprise/views/test_router_view.py
=> ENt-3992 | added check for linked identity provider.

CHANGELOG.rst, enterprise/__init__.py, enterprise/utils.py
=> ENT-4063: Added a catch all block to analytics user sync

CHANGELOG.rst, enterprise/__init__.py, integrated_channels/integrated_channel/admin/__init__.py
=> add content metadata to django admin

CHANGELOG.rst, enterprise/__init__.py, integrated_channels/integrated_channel/exporters/learner_data.py
Logging here is temporary and set to be removed once we're able to identify the issue. …
=> Adding temporary logging to track down transmission oddities

CHANGELOG.rst, enterprise/__init__.py, enterprise/admin/forms.py, tests/test_admin/test_forms.py
There should be a default idp provider in case an enterprise has multiple idp providers …
=> ENT-4086- There should be a default idp provider in case an enterprise has multiple idp providers

CHANGELOG.rst, enterprise/__init__.py, enterprise/admin/forms.py, enterprise/admin/views.py, enterprise/api/v1/views.py, enterprise/models.py, enterprise/utils.py, tests/test_admin/test_view.py, tests/test_models.py, tests/test_utilities.py
=> allow linking the same learner to multiple enterprises

CHANGELOG.rst, enterprise/__init__.py, integrated_channels/integrated_channel/exporters/learner_data.py
Logs were added to investigate [this Jira ticket](https://openedx.atlassian.net/browse/ENT-3621). Investigations are now done so removing said logs. …
=> Removing temporarily logs

CHANGELOG.rst, enterprise/__init__.py, integrated_channels/cornerstone/exporters/content_metadata.py, integrated_channels/cornerstone/views.py, tests/test_integrated_channels/test_cornerstone/test_views.py
=> rename cornerstone owners key to partners

CHANGELOG.rst, enterprise/__init__.py, enterprise/admin/utils.py, tests/test_admin/test_utilities.py
**JIRA:** [ENT-3895](https://openedx.atlassian.net/browse/ENT-3895) …
=> Read CSV files using `utf-8-sig` encoding to handle Byte Order Mark

CHANGELOG.rst, enterprise/__init__.py, enterprise/models.py, enterprise/tpa_pipeline.py, integrated_channels/sap_success_factors/exporters/learner_data.py
Give the priority to the `default provider IDP` when getting the user from the `Social Auth` table. …
=> ENT-4086- Give the priority to default IDP for getting the social auth user.

enterprise/templates/enterprise/_enterprise_customer_sidebar.html, enterprise/views.py
=> ENT-4214 Bug fix: Changing flag name

CHANGELOG.rst, enterprise/utils.py
=> Removing deprecated parameter from call

enterprise/__init__.py
=> Enterprise platform actual version bump

CHANGELOG.rst, enterprise/__init__.py, enterprise/api/v1/serializers.py, enterprise/api/v1/views.py, enterprise/utils.py, tests/test_enterprise/api/test_views.py
[Jira](https://openedx.atlassian.net/browse/ENT-4313) bugbash 
- This should be run from either a venv with all the lms/edx-enterprise requirements installed or if you checked out edx-enterprise into the …
=> Refactoring django serializers and bug clean up of bulk enrollment

CHANGELOG.rst, enterprise/__init__.py, enterprise/api/v1/serializers.py, tests/test_enterprise/api/test_views.py
=> ENT-4368, Multiple IDPs pass in Enterprise Customer API

CHANGELOG.rst, enterprise/__init__.py, enterprise/models.py, tests/test_models.py
=> in-activate other enterprises upon linking a learner from manage learners page

CHANGELOG.rst, enterprise/__init__.py, enterprise/management/commands/email_drip_for_missing_dsc_records.py, tests/test_enterprise/management/test_email_drip_for_missing_dsc_records.py
=> ENT-4392: Added url to dsc drip email

CHANGELOG.rst, enterprise/__init__.py, enterprise/management/commands/email_drip_for_missing_dsc_records.py
=> ENT-4522: Fixed Segment json string issue for DSC drip email

docs/decisions/0005-bulk-enrollment.rst
ADR for bulk enrollment backend in edx-enterprise (with reference also to the one in license-manager)
- This should be run from either a venv with all the lms/edx-enterprise requirements installed or if …
=> docs: ADR for bulk enrollment endpoint

CHANGELOG.rst, enterprise/__init__.py, enterprise/management/commands/email_drip_for_missing_dsc_records.py
=> ENT-4567: Send long dsc url as individual params

CHANGELOG.rst, enterprise/__init__.py, enterprise/management/commands/unlink_enterprise_customer_learners.py
=> ENT-4655 |unlink enterprise learners command

integrated_channels/canvas/client.py, tests/test_integrated_channels/test_canvas/test_client.py
[jira](https://openedx.atlassian.net/browse/ENT-4622)
Canvas API's default to 10 objects per response with [pagination](https://canvas.instructure.com/doc/api/file.pagination.html) handled through the [Link header](https://www.w3.org/Protocols/9707-link-header.html)
Because of this, when any student completed an assignment or triggered a course completion after 10 other assignments/course completion had transmitted, the response for assignments within the course from the Canvas API would cap out at 10 and never return the 11'th assignment. Thus our client would believe the assignment did not exist and would create another duplicate. 
This PR adds pagination logic into the assignment retrieval/creation process that allows for request of additional pages of data if the assignment isn't …
=> bug: properly handling Canvas API pagination responses

CHANGELOG.rst, enterprise/__init__.py
=> Adding left out change log and version bump

CHANGELOG.rst, enterprise/__init__.py, enterprise/utils.py
=> ENT-4611: Added logs for enterprise users created in tableau

CHANGELOG.rst, enterprise/__init__.py, enterprise/api/v1/views.py
[Original JIRA ticket  
](https://openedx.atlassian.net/browse/ENT-4619)
**Testing Notes:**
- Verified with bulk enrollment action on admin portal  …
=> ENT-4619: removing order creation

CHANGELOG.rst, enterprise/__init__.py, enterprise/models.py, enterprise/views.py, test_utils/factories.py, tests/test_models.py
=> ENT4379: Route to default_idp if no tpa_hint is added in query_param

CHANGELOG.rst, enterprise/__init__.py, enterprise/forms.py, tests/test_enterprise/views/test_enterprise_login_view.py
=> ENT-4571|Enterprise slug login use default idp if there are multiple.

CHANGELOG.rst, enterprise/__init__.py, integrated_channels/blackboard/client.py, integrated_channels/canvas/client.py, integrated_channels/canvas/utils.py, integrated_channels/cornerstone/client.py, integrated_channels/degreed/client.py, integrated_channels/integrated_channel/client.py, integrated_channels/integrated_channel/exporters/learner_data.py, integrated_channels/integrated_channel/management/commands/cleanup_duplicate_assignment_records.py, integrated_channels/integrated_channel/models.py, integrated_channels/integrated_channel/tasks.py, integrated_channels/integrated_channel/transmitters/learner_data.py, integrated_channels/moodle/client.py, tests/test_integrated_channels/test_canvas/test_client.py, tests/test_integrated_channels/test_integrated_channel/test_exporters/test_learner_data.py
[Jira](https://openedx.atlassian.net/browse/ENT-4665)
WIP gotta fix doc strings. 🙃  …
=> maint: adding management command to remove duplicate assignments from Canvas

CHANGELOG.rst, enterprise/__init__.py
Binod messed up in prior commit, needed one more rebasing which did not happen …
=> feat: fix version to 3.27.7

CHANGELOG.rst, enterprise/__init__.py, enterprise/migrations/0140_update_enrollment_sources.py, enterprise/models.py, enterprise/utils.py, enterprise/views.py, tests/test_admin/test_view.py, tests/test_enterprise/api/test_views.py
=> feat: adding customer_admin enrollment source

CHANGELOG.rst, enterprise/__init__.py, integrated_channels/sap_success_factors/admin/__init__.py
tried creating new config, saving existing with and without idp id …
=> feat: add idp id to django form

enterprise/settings/test.py
For details see [Here](https://openedx.atlassian.net/browse/ENT-4545?focusedCommentId=567712). …
=> fix: Added default TIME_ZONE as 'UTC' in test.py.

CHANGELOG.rst, enterprise/__init__.py, integrated_channels/moodle/client.py, integrated_channels/moodle/exporters/content_metadata.py
- adding additional logging to better understand scope of error type and customer impact
- ensure parsed timestamp represents UTC time even if system's timezone is something else (test stability)
[ENT-4902](https://openedx.atlassian.net/browse/ENT-4902)
- It may or may not make a migration depending on …
=> fix: Moodle: Integrated channel experiences "unknown error" scenario

CHANGELOG.rst, enterprise/__init__.py, enterprise/management/commands/backfill_learner_role_assignments.py, enterprise/utils.py, tests/test_management.py
=> feat: ENT-4936 | adding management command to backfill role assignments

integrated_channels/canvas/client.py, integrated_channels/integrated_channel/management/commands/backfill_course_end_dates.py
=> Backfilling course end dates for canvas

CHANGELOG.rst, enterprise/__init__.py
Related to this PR that was merged about Canvas backfill for courses 
https://github.com/edx/edx-enterprise/commit/f20209905777de0762d2ac551f5a7cd9b538bc15
=> fix: version bump 

CHANGELOG.rst, enterprise/__init__.py, integrated_channels/utils.py, tests/test_integrated_channels/test_utils.py
- format change
- new test
- [ENT-5189](https://openedx.atlassian.net/browse/ENT-5189) …
=> feat: reformat integrated channels logging to be more splunk friendly

CHANGELOG.rst, enterprise/__init__.py, enterprise/admin/__init__.py, enterprise/api/filters.py, enterprise/api/v1/serializers.py, enterprise/models.py, tests/test_enterprise/api/test_filters.py
- Add usage count to serializer
- Update filter backend to support filtering by enterprise customer uuid
- This should be run from either a venv with all the lms/edx-enterprise requirements installed or …
=> feat: update invite key filter and serializer

CHANGELOG.rst, enterprise/__init__.py, integrated_channels/api/v1/degreed2/serializers.py, integrated_channels/api/v1/degreed2/urls.py, integrated_channels/api/v1/degreed2/views.py, integrated_channels/api/v1/urls.py, tests/test_integrated_channels/test_api/test_degreed2/test_views.py
Jira ticket: https://openedx.atlassian.net/browse/ENT-5286 
new CRUD viewsets for integrated channel degreed2 customer configurations in order to prepare for degreed2 configurations frontend work
- This …
=> feat: new crud viewset for IC degreed2 configurations

consent/admin/__init__.py, consent/api/urls.py, consent/api/v1/urls.py, consent/models.py, consent/urls.py, enterprise_learner_portal/api/urls.py, enterprise_learner_portal/api/v1/serializers.py, enterprise_learner_portal/api/v1/urls.py, enterprise_learner_portal/api/v1/views.py, enterprise_learner_portal/urls.py, test_utils/admin_urls.py, tests/test_enterprise/test_utils.py
Jira Issue: [BOM-3277](https://openedx.atlassian.net/browse/BOM-3277)
=> Fix RemovedInDjango40 warnings

integrated_channels/api/urls.py, integrated_channels/api/v1/urls.py, integrated_channels/blackboard/urls.py, integrated_channels/canvas/models.py, integrated_channels/canvas/urls.py, integrated_channels/cornerstone/models.py, integrated_channels/cornerstone/urls.py, integrated_channels/integrated_channel/management/commands/__init__.py, integrated_channels/integrated_channel/management/commands/cleanup_duplicate_assignment_records.py, integrated_channels/integrated_channel/management/commands/reset_sapsf_learner_transmissions.py, integrated_channels/integrated_channel/management/commands/transmit_learner_data.py, integrated_channels/integrated_channel/management/commands/transmit_subsection_learner_data.py, integrated_channels/integrated_channel/models.py, integrated_channels/moodle/admin/__init__.py, integrated_channels/moodle/models.py, integrated_channels/sap_success_factors/exporters/content_metadata.py, integrated_channels/sap_success_factors/models.py, integrated_channels/xapi/models.py
Jira Issue: [BOM-3277](https://openedx.atlassian.net/browse/BOM-3277)
=> Fixed RemovedInDjango40 warnings

CHANGELOG.rst, enterprise/__init__.py, enterprise/api/filters.py, tests/test_enterprise/api/test_filters.py
* support filtering by a list of user_ids so we don't have to make multiple calls to fetch enterprise customer users. …
=> feat: support filtering by a list of user ids for enterprise customer users

integrated_channels/cornerstone/views.py
- aid in monitoring, audits, investigations
- log if-modified-since
- log content modified min/max
- help ensure this endpoint is doing what we expect
- [ENT-5366](https://openedx.atlassian.net/browse/ENT-5366)
=> feat: log if-modified-since + content metadata for CSOD

integrated_channels/cornerstone/admin/__init__.py
- help & fix investigate customer issues
- [ENT-5463](https://openedx.atlassian.net/browse/ENT-5463)
=> feat: adding CornerstoneLearnerDataTransmissionAudit admin view

CHANGELOG.rst, enterprise/__init__.py, integrated_channels/cornerstone/views.py
Version bump for:
- https://github.com/openedx/edx-enterprise/pull/1477
- https://github.com/openedx/edx-enterprise/pull/1478
=> edx-enterprise version bump to 3.40.5

CHANGELOG.rst
=> fix: update changelog

CHANGELOG.rst, enterprise/__init__.py, integrated_channels/api/v1/blackboard/serializers.py, integrated_channels/api/v1/canvas/serializers.py, integrated_channels/api/v1/cornerstone/serializers.py, integrated_channels/api/v1/degreed/serializers.py, integrated_channels/api/v1/degreed2/serializers.py, integrated_channels/api/v1/moodle/serializers.py, integrated_channels/api/v1/sap_success_factors/serializers.py, integrated_channels/api/v1/urls.py, integrated_channels/api/v1/views.py, integrated_channels/blackboard/models.py, integrated_channels/canvas/models.py, integrated_channels/cornerstone/models.py, integrated_channels/degreed/models.py, integrated_channels/degreed2/models.py, integrated_channels/moodle/models.py, integrated_channels/sap_success_factors/admin/__init__.py, integrated_channels/sap_success_factors/models.py, tests/test_integrated_channels/test_api/test_base_views.py, tests/test_integrated_channels/test_api/test_blackboard/test_views.py, tests/test_integrated_channels/test_api/test_canvas/test_views.py, tests/test_integrated_channels/test_api/test_cornerstone/test_views.py, tests/test_integrated_channels/test_api/test_degreed/test_views.py, tests/test_integrated_channels/test_api/test_degreed2/test_views.py, tests/test_integrated_channels/test_api/test_moodle/test_views.py, tests/test_integrated_channels/test_api/test_sap_success_factors/test_views.py
=> feat: new field  on all IC api views

.readthedocs.yml, enterprise/api_client/enterprise_catalog.py
=> fix: edx-enterprise readthedocs build broken

CHANGELOG.rst, enterprise/__init__.py, integrated_channels/degreed2/models.py, integrated_channels/utils.py, tests/test_integrated_channels/test_api/test_degreed2/test_views.py
=> fix: making  degreed token base url optional

.github/workflows/mysql8-migrations.yml, enterprise/settings/test.py
Adding a workflow to test migrations against mysql8.
Right now its failing due to long column name.
=> build: Running migrations on mysql8.

CHANGELOG.rst, enterprise/__init__.py, integrated_channels/integrated_channel/management/commands/backfill_missing_foreign_keys.py
- remove unused cli flags
- [ENT-5605](https://openedx.atlassian.net/browse/ENT-5605)
- https://tools-edx-jenkins.edx.org/job/enterprise/job/stage-edx-backfill_missing_foreign_keys/1/console
=> feat: management command to backfill missing fks

CHANGELOG.rst, enterprise/__init__.py, integrated_channels/cornerstone/admin/__init__.py, integrated_channels/degreed2/admin/__init__.py
- Degreed2EnterpriseCustomerConfiguration admin registration / config
- ran this locally
- [ENT-5598](https://openedx.atlassian.net/browse/ENT-5598)
- https://github.com/edx/app-permissions/pull/1723
=> fix: configure django admin for degreed2 audit records

CHANGELOG.rst, enterprise/__init__.py, integrated_channels/degreed2/admin/__init__.py, integrated_channels/integrated_channel/admin/__init__.py
- larger list sizes for reviewing data
- hide secrets from list view
- show modified dates in more places
- ENT-5598
=> feat: improvements to admin views

CHANGELOG.rst, enterprise/__init__.py, enterprise/management/commands/email_drip_for_missing_dsc_records.py, enterprise/views.py
=> chore: add logs for dsc

CHANGELOG.rst, enterprise/__init__.py, enterprise/management/commands/email_drip_for_missing_dsc_records.py, enterprise/views.py
=> feat: add source query param in data sharing consent url

CHANGELOG.rst, enterprise/__init__.py, integrated_channels/integrated_channel/admin/__init__.py, integrated_channels/sap_success_factors/admin/__init__.py
I am investigating a sync issue with an SAP customer...
- need to be able to edit transmission size on SAP, some legacy configs have it set to 1 meanwhile SAP supports up to 500 at a time
- need to make deleted content more obvious from the list view
=> feat: admin tweaks to aid debugging

enterprise/admin/__init__.py
**Description:** This PR fixes the IDENTITY PROVIDER flag in the Enterprise Customer section of LMS Admin Panel. 
**JIRA** [ENT-3906](https://2u-internal.atlassian.net/browse/ENT-3906)
- This should be …
=> fix: has identity provider check in admin panel of enterprise customer.

enterprise/api/v1/urls.py, enterprise/api/v1/views.py, tests/test_models.py
=> feat: adding patch functionality for logo upload

CHANGELOG.rst, enterprise/__init__.py, enterprise/api_client/enterprise_catalog.py, integrated_channels/integrated_channel/exporters/content_metadata.py, integrated_channels/utils.py, tests/test_integrated_channels/test_utils.py
I am investigating a couple of customer reported issues with CSOD content not being properly deleted. We made previous changes which should have fixed this but we're not seeing the results we'd expect. These changes should add some more context to our investigation.
- https://2u-internal.atlassian.net/browse/ENT-6081
=> feat: add debug logging to investigate missing CSOD deletes

CHANGELOG.rst, enterprise/__init__.py, integrated_channels/moodle/client.py, integrated_channels/sap_success_factors/client.py, tests/test_integrated_channels/test_sap_success_factors/test_client.py
https://2u-internal.atlassian.net/browse/ENT-4680
when combining base urls with paths, we want to use urljoin. 
note urljoin has some weird behaviors, namely 
```
>>> urljoin('www.foobar.com', '/something/api')
'/something/api'
```
when joining a base url without domain/schema it will not actually join the two strings (see https://stackoverflow.com/questions/10893374/python-confusions-with-urljoin). However, with our self service tools we require base urls to contain http or https schemas so we are fine. …
=> chore: properly joining urls and adhering to existing patterns

enterprise/constants.py
=> fix: updating colors to new branding defaults

CHANGELOG.rst, enterprise/__init__.py, integrated_channels/integrated_channel/admin/__init__.py
adding status code to the content metadata record django admin table view for easier viewing …
=> chore: adding http status code to cm admin table view

CHANGELOG.rst, enterprise/__init__.py, enterprise/api/v1/urls.py, enterprise/api/v1/views.py, enterprise/settings/test.py, tests/test_enterprise/api/test_views.py
**JIRA:** https://2u-internal.atlassian.net/browse/ENT-6434
**edx-internal for plotly secret:** https://github.com/edx/edx-internal/pull/7299
**Plotly docs link for auth:** https://enterprise-plotly.edx.org/Docs/embedded-middleware/authentication _This url is behind edx vpn_ …
=> feat: add signed token generation for plotly

CHANGELOG.rst, enterprise/__init__.py, integrated_channels/integrated_channel/admin/__init__.py
- make api response field readonly
- add new admin view for api response table …
=> fix: make integrated channels api response record field readonly in admin view

CHANGELOG.rst, enterprise/__init__.py, integrated_channels/api/v1/urls.py, integrated_channels/api/v1/views.py, integrated_channels/canvas/client.py, integrated_channels/integrated_channel/client.py, integrated_channels/utils.py, tests/test_integrated_channels/test_api/test_base_views.py, tests/test_integrated_channels/test_canvas/test_client.py
[Jira Ticket](https://2u-internal.atlassian.net/browse/ENT-5607) …
=> feat: Add health check for canvas integrated channels

CHANGELOG.rst, enterprise/__init__.py, enterprise/api/v1/views.py
=> fix: internal service error fix

CHANGELOG.rst, enterprise/__init__.py, enterprise/api/v1/serializers.py, enterprise/api/v1/urls.py, enterprise/api/v1/views.py, test_utils/factories.py, tests/test_enterprise/api/test_views.py
https://2u-internal.atlassian.net/browse/ENT-6934 …
=> feat: added enterprise fulfillment viewset

CHANGELOG.rst, enterprise/__init__.py, integrated_channels/degreed2/exporters/content_metadata.py, tests/test_integrated_channels/test_degreed2/test_exporters/test_content_metadata.py
https://2u-internal.atlassian.net/browse/ENT-7005
https://2u-internal.atlassian.net/browse/ENT-7006
- Prepend "owner" metadata in square brackets to the beginning of the description field
- Truncate the full description down to the max limit rather than falling back to the short description
- It may or may …
=> feat: include owners and longer descriptions for degreed2

.gitignore, CHANGELOG.rst, enterprise/__init__.py, enterprise/admin/views.py, enterprise/utils.py, tests/test_admin/test_view.py
- *Note*: Assets will be added automatically. You just need to provide a tag (should match your version number) and title and description.
- Each step in the release build has a condition flag that checks if the rest of the steps are done and if so will deploy to PyPi.
(so basically once your build finishes, after maybe a minute you should see the new version in PyPi automatically (on refresh))
- This **must** be done after the version is visible in PyPi as `make upgrade` in edx-platform will look for the latest version in PyPi.
- Note: the edx-enterprise constraint in edx-platform **must** also be bumped to the latest version in PyPi.
=> feat: more logging in the bulk enrollment flow

CHANGELOG.rst, enterprise/__init__.py, enterprise/logging.py
=> fix: fix logging

CHANGELOG.rst, enterprise/__init__.py, enterprise/api/throttles.py, enterprise/api/v1/views/enterprise_subsidy_fulfillment.py
https://2u-internal.atlassian.net/browse/ENT-7333 …
=> chore: fixing doc string linter errors

CHANGELOG.rst, enterprise/__init__.py, enterprise_learner_portal/api/v1/serializers.py
=> feat: add more metadata into `EnterpriseCourseEnrollmentView`

CHANGELOG.rst, enterprise/__init__.py, enterprise_learner_portal/api/v1/serializers.py
=> fix: pick first object from CourseDetails

CHANGELOG.rst, enterprise/__init__.py, integrated_channels/blackboard/admin/__init__.py, integrated_channels/canvas/admin/__init__.py, integrated_channels/cornerstone/admin/__init__.py, integrated_channels/degreed/admin/__init__.py, integrated_channels/degreed2/admin/__init__.py, integrated_channels/moodle/admin/__init__.py, integrated_channels/sap_success_factors/admin/__init__.py
https://2u-internal.atlassian.net/jira/software/c/projects/ENT/boards/630?modal=detail&selectedIssue=ENT-7485
- This should be run from either a venv with all the lms/edx-enterprise requirements installed …
=> fix: make api-record in lms admin read only

CHANGELOG.rst, enterprise/__init__.py, enterprise/api/v1/views/enterprise_customer_api_credentials.py, tests/test_enterprise/api/test_views.py
=> fix: properly fetching user application records in the enterprise api endpoint

CHANGELOG.rst, enterprise/__init__.py, enterprise/api/v1/serializers.py, enterprise/api/v1/urls.py, enterprise/api/v1/views/enterprise_customer_sso_configuration.py, integrated_channels/integrated_channel/exporters/content_metadata.py, tests/test_enterprise/api/test_views.py
https://2u-internal.atlassian.net/browse/ENT-7576 …
=> feat: enterprise sso orchestration record table api implementation

docs/decisions/0012-enterprise-feature-flags-waffle.rst
=> docs: update ADR 0012 to make its title correct

CHANGELOG.rst, enterprise/__init__.py, enterprise/utils.py, integrated_channels/sap_success_factors/exporters/content_metadata.py
=> fix: fixed how we determine active value for SAP

.readthedocs.yaml
Cribbed off of https://github.com/openedx/edx-analytics-dashboard/pull/1500/files#diff-03efc769b870804394632e45d7885272b44c16939517fb31c9d7c614d2ffae57R8
- This should be run from either a venv with all …
=> chore: updating read the docs yaml file

CHANGELOG.rst, enterprise/__init__.py, enterprise/api/v1/views/enterprise_customer_sso_configuration.py, enterprise/models.py
=> chore: orchestrator exception handling and submission refinements

requirements/ci.in, requirements/ci.txt, requirements/dev.in, requirements/dev.txt, tox.ini
Issue: https://github.com/edx/edx-arch-experiments/issues/130
=> Replaced whitelist_externals with allowlist_externals in tox and removed tox-battery

enterprise/api/v1/views/enterprise_customer_catalog.py
This is needed to support robust provisioning, editing, and displaying of Learner Credit Plans linked to "predefined" catalogs. The previous behavior was to rely on reading the catalog title and use string manipulation (fragile) to infer the catalog query type. Exposing the query ID allows the LC provisioning tool to more directly understand the query used.
ENT-7922 …
=> feat: add enterprise_catalog_query to output of catalog list endpoint

CHANGELOG.rst, enterprise/__init__.py, integrated_channels/moodle/client.py
Description:
Added log for learner data transmission so that exact data for core_grades_update_grades moodle function can be logged and its response can also get recorded.
JIRA:
=> Added log for learner data transmission

CHANGELOG.rst, enterprise/__init__.py
Description:
Updated build version.
JIRA:
=> Updating build version

CHANGELOG.rst, enterprise/__init__.py, integrated_channels/degreed2/apps.py, integrated_channels/degreed2/client.py, integrated_channels/integrated_channel/management/commands/assign_skills_to_degreed_courses.py
=> feat: job to assign skills to Degreed courses

CHANGELOG.rst, enterprise/__init__.py, integrated_channels/moodle/client.py, integrated_channels/utils.py
Description:
Restructured moodle course completion request and allowed continuous learner transmission till course completion
JIRA:
=> Restructuring moodle course completion request and allowed continuous learner transmission till course completion

integrated_channels/moodle/client.py
Description:
Fixed create_course_completion request's response handling in case reponse body is '0'
JIRA:
=> Fixed create_course_completion request's response handling in case reponse body is '0'

CHANGELOG.rst, enterprise/__init__.py
Description:
Updated build version for learner transmission failure fix  of ENT 7837
JIRA:
=> Updated build version for learner transmission failure fix  of ENT 7837

CHANGELOG.rst, enterprise/__init__.py, integrated_channels/integrated_channel/exporters/learner_data.py
=> ENT-8130 - Remove debugging logs

CHANGELOG.rst, enterprise/__init__.py, enterprise/api_client/enterprise_catalog.py, enterprise/management/commands/compare_discovery_and_enterprise_catalogs.py
- needed to adjust the way we were retrieving the catalog count from the enterprise catalog service
=> feat: create/use an ENT-CAT count method

CHANGELOG.rst, enterprise/__init__.py, enterprise/management/commands/compare_discovery_and_enterprise_catalogs.py
- good spot checks so far but i want a more thorough set of data
=> feat: tweaks for better data

CHANGELOG.rst, enterprise/__init__.py, enterprise/management/commands/add_exec_ed_exclusion_to_catalogs.py, enterprise/management/commands/compare_discovery_and_enterprise_catalogs.py
- mgmt command to enumerate the catalog filters and add course_type exclusions where required
- https://github.com/openedx/edx-enterprise/pull/1989
- https://2u-internal.atlassian.net/browse/ENT-7893
=> feat: mgmt command to migrate catalog exclusions

CHANGELOG.rst, enterprise/__init__.py, integrated_channels/degreed/client.py, integrated_channels/degreed2/client.py
Description:
Changes to degreed client to record degreed api calls in DB.
JIRA:
https://2u-internal.atlassian.net/jira/software/c/projects/ENT/issues/ENT-8371
=> Record Degreed API calls

integrated_channels/sap_success_factors/client.py
Description:
Changes to sap success factors client to record sap success factors api calls in DB.
JIRA:
https://2u-internal.atlassian.net/jira/software/c/projects/ENT/issues/ENT-8370
=> Record SAP success factors API calls

CHANGELOG.rst, enterprise/__init__.py, integrated_channels/integrated_channel/admin/__init__.py, integrated_channels/integrated_channel/management/commands/remove_stale_integrated_channel_api_logs.py, tests/test_management.py
Description:
Added management command to clear out excessive records for integrated channel API request log table.
JIRA:
https://2u-internal.atlassian.net/jira/software/c/projects/ENT/issues/ENT-8020
=> Added management command to clear out excessive records for integrated channel API request log table

CHANGELOG.rst, enterprise/__init__.py, enterprise/admin/__init__.py, enterprise/api/v1/views/enterprise_group.py, enterprise/models.py
=> feat: admin pages for enterprise groups and enterprise group memberships

enterprise/api/v1/views/enterprise_subsidy_fulfillment.py, tests/test_enterprise/api/test_views.py
This shouldn't normaly be needed, but this extra check is added for safety in case the database integrity is compromised and enterprise enrollments go out of sync with course enrollments.
ENT-8991
Performance implications
===
This theoretically adds N SQL queries, where N is the number of recently unenrolled enterprise enrollments.  Given our filter params used in the cron job, we only ever deal with [at most 30 unenrollments](https://splunk.edx.org/en-US/app/search/search?earliest=-30d%40d&latest=now&q=search%20%22Found%22%20%22recent%20Enterprise%20unenrollments%22%20index%3D%22prod-edx%22%20%7C%20rex%20field%3D_raw%20%22Found%20(%3F%3Cnum_unenrollments%3E%5B0-9%5D*)%20recent%20Enterprise%20unenrollments%22%20%7C%20timechart%20max(num_unenrollments)%20span%3D6h&sid=1718747816.4424286&dis …
=> feat: When listing unenrolled fulfillments, exclude ones with active enrollments

CHANGELOG.rst, enterprise/__init__.py
=> chore: bump version to 4.20.8

CHANGELOG.rst, enterprise/__init__.py, enterprise/admin/__init__.py, requirements/base.in, requirements/dev.txt, requirements/doc.txt, requirements/edx-platform-constraints.txt, requirements/test-master.txt, requirements/test.txt
=> feat: Added SFTP connection testing support

CHANGELOG.rst, enterprise/__init__.py, enterprise/api/v1/views/enterprise_customer.py, enterprise/constants.py, tests/test_enterprise/api/test_views.py
=> feat: allow PAs to read/write all enterprise customers

CHANGELOG.rst, enterprise/__init__.py, integrated_channels/integrated_channel/admin/__init__.py
Description:
Fixed 500 error for search filter for api request logs in admin view
JIRA:
https://2u-internal.atlassian.net/jira/software/c/projects/ENT/issues/ENT-9175
=> Fixed 500 error for search filter for api request logs in admin view

CHANGELOG.rst, enterprise/__init__.py
=> feat: bump enterprise to 4.22.1

CHANGELOG.rst, enterprise/__init__.py
feat: adding enterprise-customer-support-endpoint version bump 2 …
=> feat: adding enterprise-customer-support-endpoint version bump 2

CHANGELOG.rst, enterprise/__init__.py
=> chore: bump edx-enterprise to 4.22.5

CHANGELOG.rst, enterprise/__init__.py, enterprise/api/v1/decorators.py
Description:
Added logs for data dog inspection for permission check in handler function.
JIRA:
https://2u-internal.atlassian.net/jira/software/c/projects/ENT/issues/ENT-9248
=> Added logs for data dog inspection for permission check in handler function

CHANGELOG.rst, enterprise/__init__.py, enterprise/api/v1/views/enterprise_customer_support.py
Updating enterprise-customer-support endpoint based on search and ordering criteria
JIRA: https://2u-internal.atlassian.net/browse/ENT-9277
**TESTING**
1. Order by ascending ID
2. Order by descending ID
3. Filter by email
4. Filter by is_admin and then first name …
=> feat: Updating enterprise-customer-support endpoint 

CHANGELOG.rst, enterprise/__init__.py, enterprise/api/v1/views/enterprise_customer_reporting.py
=> feat: expanded page_size for reporting configurations

CHANGELOG.rst, enterprise/__init__.py, enterprise/settings/test.py
=> refactor: Removed unused django setting.

CHANGELOG.rst, enterprise/__init__.py, enterprise/management/commands/update_enterprise_social_auth_uids.py
=> feat: Added management command to update UIDs

enterprise/management/commands/validate_default_enrollment_intentions.py, tests/test_enterprise/management/test_validate_default_enrollment_intentions.py
=> fix: gracefully handle case where intention has no related catalogs

CHANGELOG.rst, enterprise/__init__.py, enterprise/management/commands/backfill_ecu_table_user_foreign_key.py
=> fix: backfill ecu table command

CHANGELOG.rst, enterprise/__init__.py
=> chore: minor version bump

CHANGELOG.rst, enterprise/__init__.py, integrated_channels/integrated_channel/exporters/content_metadata.py
Reverts openedx/edx-enterprise#2376
=> Revert "[ENT-10198] - chore: add logs for debugging"

CHANGELOG.rst, enterprise/__init__.py, enterprise/api/__init__.py, enterprise/signals.py, tests/test_enterprise/test_signals.py
=> feat: adding EnterpriseCustomerAdmin creation to post save signal

CHANGELOG.rst, enterprise/__init__.py, enterprise/toggles.py, tests/test_enterprise/api/test_filters.py, tests/test_enterprise/api/test_views.py
[Jira Ticket](https://2u-internal.atlassian.net/browse/ENT-10577) …
=> feat: adds EDIT_HIGHLIGHTS_ENABLED toggle

CHANGELOG.rst, enterprise/__init__.py, enterprise/admin/__init__.py
[Jira Ticket](https://2u-internal.atlassian.net/browse/ENT-10792)
- Deploy this change
- Navigate to http://localhost:18000/admin/enterprise/enterprisecustomeradmin/
- Verify existing `EnterpriseCustomerAdmin` instances are shown in list
- Click `Add Enterprise Customer Admin` button and fill out the form to create a new instance
- *Note*: This **must** be run if …
=> feat: Add django admin interface for EnterpriseCustomerAdmin
