AUTHORS
CHANGELOG.rst
enterprise/__init__.py
enterprise/admin.py
enterprise/apps.py
enterprise/migrations/0002_enterprisecustomerbrandingconfiguration.py
enterprise/models.py
enterprise/validators.py
tests/test_models.py

[ENT-20](https://openedx.atlassian.net/browse/ENT-20)
@mattdrayer @e-kolpakov your initial thoughts ? 
**Reviewers:**
**Checklist:**

ENT-20 Enterprise Customer Setup: Configure Cobranding

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/apps.py
enterprise/course_catalog_api.py
enterprise/models.py
enterprise/signals.py
enterprise/utils.py
test_utils/factories.py
tests/test_apps.py
tests/test_models.py
tests/test_signals.py
tests/test_util_functions.py

**Description:** Fixes migration/DB deployment error caused by User.post_save handler.
**Related:** #8
**JIRA:** [ENT-48](https://openedx.atlassian.net/browse/ENT-48)
* Run bokchoy test suite - should get past "Loading the fixture data from the filesystem into the default MySQL DB." and actually run the suite. ([failed bokchoy run](https://build.testeng.edx.org/job/edx-platform-accessibility-pr/27918/console) for reference).
* Migrate `commerce` and `enterprise` to zero (you might need to fake `commerce` 0001 and manually delete auth_user record)
* Apply commerce 0001 migration only. *Expected result:* migration works. *Failure condition:* migration fails complaining about missing enterprise_pendingenterprisecustomeruser table.
* Unapply commerce 0001 (might need …

Manage Learners: fixed User.post_save handler causing migrations to fail

---

.travis.yml
CHANGELOG.rst
enterprise/admin/forms.py
enterprise/api.py

Fixes an issue in 0.4.0 where the catalog field is required to be non-null for the EnterpriseCustomer form.
Related to #7.
**Dependencies**: None
**Merge deadline**: ASAP
**Testing instructions**:
1. With edx-enterprise 0.4.0, go to create a new EnterpriseCustomer.
2. Note that you cannot leave the default "None" value for the catalog field; an error prevents you from saving.
3. Update to this branch.
4. Note that you can now create a new EnterpriseCustomer with a blank catalog. 
**Notes**
1. This PR also adds a Python 2.7 quality check to Travis, per @bradenmacdonald's request.
**Reviewers**

Set catalog field to optional in admin form

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/admin/__init__.py
enterprise/admin/forms.py
enterprise/static/enterprise/admin/enterprise_customer.js
enterprise/utils.py
test_settings.py
tests/test_utilities.py

Hi @mattdrayer , @asadiqbal08 , @e-kolpakov 
Kindly take a look at this PR, This PR adds alphabetical ordering for course catalog dropdown in enterprise customer admin page. It also adds a link for viewing catalog details of the currently selected catalog.
__Description of [ENT-111](https://openedx.atlassian.net/browse/ENT-111):__
As an edX Admin, I need to select an existing catalog for an Enterprise.
__Acceptance Criteria__
1. Catalog dropdown ordered alphabetically by name
2. Display currently-selected catalog next to dropdown list/selector as a hyperlink (see #3)
3. Displayed catalog links to location discovery app. https://prod-edx-discovery.edx.org/admin/catalogs/catalog/47/change/
__Testing Instructions:__
1. Go to course discovery admin page at …

ENT-111: Added alphabetical ordering for catalog drop down and displayed catalog details link next to selected catalog

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/v1/urls.py
tests/api/test_views.py

Hi @mattdrayer , @asadiqbal08 , @zubair-arbi 
Kindly take a look at this PR, URL for `users` api endpoint was conflicting with a url of edx-platform's user api endpoint. 
__Description of Changes:__
edx-platform defines API endpoint for `User` model coming from `django.contrib.auth` app, these endpoints are defined [here](https://github.com/edx/edx-platform/blob/master/openedx/core/djangoapps/user_api/serializers.py#L14) and [here](https://github.com/edx/edx-platform/blob/master/lms/djangoapps/mobile_api/users/serializers.py#L105). These urls were conflicting with the one added in https://github.com/edx/edx-enterprise/pull/30. So, I renamed urls to a unique pattern so that they do not conflict with existing ones.

ENT-112: Resolve conflicting urls for User API endpoint.

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/admin/forms.py
enterprise/admin/utils.py
enterprise/admin/views.py
enterprise/conf/locale/en/LC_MESSAGES/django.po
enterprise/conf/locale/en/LC_MESSAGES/djangojs.po
enterprise/static/enterprise/admin/manage_learners.js
enterprise/templates/enterprise/admin/manage_learners.html
spec/javascripts/enterprise_admin_spec.js
spec/javascripts/fixtures/manage_learners_form.html
tests/admin/test_view.py

This pull request adds two main capabilities; one which was the goal, and one which was a side effect of the goal:
1. Admin users can select multiple existing EnterpriseCustomerUsers and PendingEnterpriseCustomerUsers to be enrolled in a course that they choose using the standard enrollment form, which is also used to link new users.
2. Users may enter comma-separated values in the enrollment form, rather than just upload a CSV file, to process multiple linkings/enrollments at once.
**JIRA:** [ENT-95](https://openedx.atlassian.net/browse/ENT-95)
**Dependencies:** Pending pull request from @e-kolpakov to have the ability to enroll users in Programs as well as courses. Should also wait on #26 so that we can put the new Javascript stuff under Jasmine testing.
**Merge …

ENT-95: Add ability to enroll existing users in course

---

MANIFEST.in
enterprise/__init__.py

Adds *.txt to the manifest so that templates like `user_notification.txt` are include in the distribution.
**JIRA tickets**: [ENT-97](https://openedx.atlassian.net/browse/ENT-97)
**Discussions**: See stacktrace reported in [this comment](https://openedx.atlassian.net/browse/ENT-97?focusedCommentId=240522&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-240522)
**Merge deadline**: ASAP - as this is holding up feature development
**Testing instructions**:
To verify the issue:
1. Clone this repo at master.
1. Create a virtualenv, and install the requirements with `make requirements`
1. Create a distribution tar file by running `python setup.py sdist`
1. Dump the list of files included in the tar file using `tar xfz dist/edx-enterprise-0.21.0.tar.gz`.
1. Note this …

ENT-97: Add txt templates

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/v1/serializers.py
enterprise/api/v1/views.py
enterprise/models.py
tests/api/test_serializers.py
tests/api/test_views.py
tests/test_models.py

Hi @mattdrayer , @asadiqbal08 ,
Kindly take a look at the PR, it adds an API endpoint to fetch enterprise learner's entitlements.
__Instructions for Testing:__
1. Add an Enterprise Customer with the following configurations.
1.  Enable data sharing consent: [x] (Checked)
2.  Enforce data sharing consent: 'at_enrollment'
3. Add an enterprise customer entitlement using section "Enterprise Customer Entitlements" at the bottom
2. Create three user accounts and associate them with the enterprise customer using enterprise learner management console at "http://localhost:8000/admin/enterprise/enterprisecustomer/{enterprise_customer_uuid}/manage_learners"
3. Make sure that user-1 has consented to data sharing, user-2 has not consented to data sharing and user-3 has not set any value. (If user is …

ENT-181: Add API endpoint to fetch enterprise learner entitlements

---

enterprise/__init__.py
enterprise/api/permissions.py
enterprise/api/throttles.py
enterprise/api/utils.py
enterprise/api/v1/serializers.py
enterprise/api/v1/urls.py
enterprise/api/v1/views.py
enterprise/templates/enterprise/grant_data_sharing_permissions.html
enterprise/views.py
test_utils/factories.py
tests/api/test_views.py
tests/test_views.py

This allows for ecommerce to collect consent by redirecting users
to the usual enterprise data consent page before the user has an
EnterpriseCourseEnrollment.
**JIRA tickets**: ENT-134.
**Discussions**: Architecture discussed extensively on the wiki and in meetings, then the revised proposal was presented to the Arch Council on Oct. 21 and given thumbs up.
**Dependencies**: None
**Testing instructions**:
Test this PR by following the testing instructions on https://github.com/edx/ecommerce/pull/1127.
**Reviewers**

ENT-134/ENT-162: Add option to defer enrollments in the course-specific consent gate

---

CHANGELOG.rst
MANIFEST.in
enterprise/__init__.py

**Description:** This file controls what gets pulled down from the package, and we were missing
our migration files for the new apps, which was causing some mild mayhem.
**JIRA:** https://openedx.atlassian.net/browse/ENT-191
instructions.
1. In a provisioned devstack, Edit requirements/edx/base.txt, change the edx-enterprise version to 0.26.2.
2. Run  paver install_python_prereqs.
3. Run ./scripts/reset-test-db.sh from the root of edx-platform, the script should fail with an error: django.db.utils.IntegrityError: (1215, 'Cannot add foreign key constraint')
4. Edit …

ENT-191 Adding all integrated channels files to be included in MANIFEST.in

---

AUTHORS
CHANGELOG.rst
docs/configuration_and_usage.rst
enterprise/__init__.py
enterprise/lms_api.py
enterprise/models.py
integrated_channels/integrated_channel/management/__init__.py
integrated_channels/integrated_channel/management/commands/__init__.py
integrated_channels/integrated_channel/management/commands/transmit_learner_data.py
integrated_channels/integrated_channel/models.py
integrated_channels/sap_success_factors/models.py
integrated_channels/sap_success_factors/transmitters/learner_data.py
requirements/dev.txt
requirements/doc.txt
requirements/js_test.txt
tests/test_lms_api.py
tests/test_management.py
tests/test_models.py

**Description:** Adds a management command and updates supporting classes to collect learner completion data records, and prepare them for submission to the SAP SuccessFactors integration channel.
**JIRA:** [ENT-220](https://openedx.atlassian.net/browse/ENT-220), [ENT-223](https://openedx.atlassian.net/browse/ENT-223)
**Dependencies:** 
* https://github.com/edx/edx-platform/pull/14563
* https://github.com/edx/edx-enterprise/pull/61 (merged here)
**Sandbox:**
* LMS: https://ent-pr59.sandbox.opencraft.hosting/
* Studio: https://studio-ent-pr59.sandbox.opencraft.hosting/
Also created an edX Sandbox: https://ent-220-ent-223-pomegranited.sandbox.edx.org
I've added github keys for @haikuginger , @brittneyexline , @mattdrayer , so you can shell in as `pomegranited` and test the management …

ENT-220/ENT-223 Collect learner completion data for SAP SuccessFactors

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/admin/views.py
test_settings.py

This PR uses the new `settings.ENTERPRISE_PUBLIC_ENROLLMENT_API_URL` for client-side requests  to the LMS Enrollments API.  This public URL is rooted at the ENV-configured, fully-qualified `LMS_ROOT_URL`.
This allows `settings.ENTERPRISE_ENROLLMENT_API_URL` to use `localhost` as its root, for use by internal, server-side requests.
We need this because in certain situations, the edxapp server cannot contact itself over https by its fully-qualified `LMS_ROOT_URL`.
Currently, edxapp servers are configured with an [`/etc/hosts` entry which maps their FQDN hostname to `127.0.0.1`](https://github.com/edx/configuration/blob/0aa9bfa07853d319c487de1690309d2b3cf38c2b/playbooks/roles/common/templates/hosts.j2#L1), e.g.
127.0.0.1	pr14671.sandbox.opencraft.hosting	localhost
Load …

Adds ENTERPRISE_PUBLIC_ENROLLMENT_API_URL to settings

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/v1/views.py

**Description:** According to @clintonb, `OAuth2Authentication` is not a DRF authentication class that we use in Open edX, so I've removed it from this project.  I've also reordered the authentication classes such that `JwtAuthentication` is the first one in the list, followed by `BearerAuthentication`, and lastly `SessionAuthentication`.
**JIRA:** ENT-264, ENT-275
**Merge deadline:** Now
**Installation instructions:** No special installation instructions.
**Testing instructions:** Unsure of how to test at the moment.

Remove OAuth2 authentication class from API viewsets

---

enterprise/__init__.py

**Description:** When I merged PR #65 I forgot to actually bump the version...
**JIRA:** ENT-218/ENT-221
**Dependencies:** 
**Installation instructions:** N/A
After this is merged, see that https://github.com/edx/edx-platform/pull/14779 is passing.
**Author concerns:** I don't know why I always struggle with these...

ENT-218/ENT-221 Missing version bump for 0.30.0

---

AUTHORS
CHANGELOG.rst
enterprise/__init__.py
enterprise/tpa_pipeline.py
tests/test_tpa_pipeline.py

ENT-277
@saleem-latif @asadiqbal08 @mattdrayer 
**Description:** Fixed `IntegrityError` getting raised for existing enterprise users (manually added/linked from enterprise django admin `Manage Learners`)  when the data sharing consent is disabled for the related enterprise.
**JIRA:** [ENT-277](https://openedx.atlassian.net/browse/ENT-277)
**Merge deadline:** 7 April 2017
1. Setup edx-platform (master) with enterprise branch set to this.
2. Set up a TestShib SAML integration with the instructions [found here](http://edx.readthedocs.io/projects/edx-installing-configuring-and-running/en/latest/configuration/tpa/tpa_SAML_SP.html).
3. Create an EnterpriseCustomer in the Django admin.
1. Link the EnterpriseCustomer …

ENT-277: Fix IntegrityError getting raised for existing enterprise users

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/admin/__init__.py

@saleem-latif @asadiqbal08 @mattdrayer 
**Description:** Display enterprise customers by name on enterprise customers django admin
**JIRA:** [ENT-297](https://openedx.atlassian.net/browse/ENT-297)
**Merge deadline:** 21 April, 2017
**Installation instructions:** Install `edx-enterprise` from this branch `zub/ENT-297-display-enterprise-customers-by-name` in `edx-platform`.
1. Add multiple enterprises
2. Go to enterprise customers django admin at `admin/enterprise/enterprisecustomer/`
3. Check that the enterprises are sorted by name.
solutions, hacks, quick-and-dirty …

ENT-297 Sort Enterprise Customers by names

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/templates/enterprise/grant_data_sharing_permissions.html
enterprise/views.py
tests/test_views.py

@saleem-latif @asadiqbal08 @mattdrayer 
**Description:** Update Data Sharing Consent message
**JIRA:** [ENT-316](https://openedx.atlassian.net/browse/ENT-316)
**Merge deadline:** 21 April, 2017
**Installation instructions:** Install `edx-enterprise` from this branch `zub/ENT-316-update-data-sharing-consent-message` in `edx-platform`
1. Create and Enterprise with Data sharing consent option enabled and Enforced.
2. Create a coupon with this Enterprise containing courses in its catalog.
3. Create/link a user with this Enterprise
4. As an enterprise user login
5. Open the voucher redeem link in the coupon from step 2
6. Click on the button `Enroll Now` on any course.
7. A consent message page will show, verify the message changes on it.
**Merge …

ENT-316 Update Data Sharing Consent message

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/apps.py
enterprise/validators.py
test_settings.py
tests/test_models.py

@saleem-latif @asadiqbal08 @mattdrayer 
**Description:** Increase the max size limit for enterprise logo
**JIRA:** [ENT-247](https://openedx.atlassian.net/browse/ENT-247)
**Dependencies:** https://github.com/edx/edx-platform/pull/14907
**Merge deadline:** 21 April, 2017
**Installation instructions:** Install `edx-enterprise` from this branch `zub/ENT-247-update-enterprise-logo-image-size` in `edx-platform`.
2. Try to add a new enterprise with a `png` image of size upto `512 KB`
3. Verify that enterprise is saved successfully with an image of size upto `512 KB`
4. Try again to a new enterprise with a `png` image of size greater than `512 KB`
5. Verify that a validation error is …

ENT-247 Increase the max size limit for enterprise logo

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/course_catalog_api.py
tests/test_course_catalog_api.py

**Description:** This PR fixes a bug that was causing 500 errors on enterprise customer admin.
1. Go to enterprise customer admin page at /admin/enterprise/enterprisecustomer/ 
2. Click on any enterprise customer to open its details page.
3. There should not be a 500 error.

Update calls to get_edx_api_data as its signature has changed in openedx

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/validators.py
tests/test_models.py

@saleem-latif @asadiqbal08 @mattdrayer
**Description:** Fix enterprise logo validation message for max image size limit
**JIRA:** [ENT-364](https://openedx.atlassian.net/browse/ENT-364)
**Merge deadline:** 5 May, 2017
**Installation instructions:** Install edx-enterprise from this branch `zub/ENT-364-fix-enterprise-log-validation-message` in `edx-platform`.
2. Try to add a new enterprise with a `png` image of size upto `512 KB`
3. Verify that enterprise is saved successfully with an image of size upto `512 KB`
4. Try again to a new enterprise with a `png` image of size greater than `512 KB`
5. Verify that a validation error is raise with message: `The logo …

ENT-364 fix enterprise logo validation message

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/sap_success_factors/utils.py
tests/test_sap_successfactors.py

**Description:** We weren't adding the tpa_hint of the enterprise customer identity provider to the launchURL's of the courses, which we need in order to take advantage of all of our SSO logic.
**JIRA:** https://openedx.atlassian.net/browse/ENT-351
**Dependencies:** Soft dependency on https://github.com/edx/edx-enterprise/pull/94 for sandbox testing purposes - so you will notice the code is included here, but I can separate those changes out once this is approved.
**Merge deadline:** 5/5/2017
**Installation instructions:** Requires an environment with the catalog service running.
Edxapp sandbox: https://brittneyexline.sandbox.edx.org
1. Set up a configuration for an enterprise customer and success factors against our test SAP instance. (This has been done already …

ENT-351 Add tpa_hint to urls in SAP course export

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/static/enterprise/enterprise_course_enrollment_page.css
enterprise/templates/enterprise/enterprise_course_enrollment_page.html
enterprise/urls.py
enterprise/views.py
test_settings.py
tests/test_views.py

**WIP**
@saleem-latif @asadiqbal08 @mattdrayer @douglashall 
**Description:** Add static enterprise landing page with course mode selection.
**JIRA:** [ENT-330](https://openedx.atlassian.net/browse/ENT-330)
**Merge deadline:** 5 May, 2017
**Installation instructions:**  Install `edx-enterprise` from this branch `zub/ENT-330-enterprise-landing-page` in `edx-platform`.
2. Add enterprise customer with logo
3. Add a course in the enterprise customer catalog
4. View the enterprise landing page for the enterprise course by accessing the url with enterprise customer uuid `ec_uuid` from step no 2, e.g: `http://zubair.localhost:8000/enterprise/course/course-v1:edX+TES …

ENT-330 Add enterprise landing page

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/static/enterprise/enterprise_course_enrollment_page.css
enterprise/templates/enterprise/enterprise_course_enrollment_page.html

ENT-330
**Description:** Additional minor UI updates for enterprise landing page
**JIRA:** [ENT-330](https://openedx.atlassian.net/browse/ENT-330)
**Related PR (merged):** https://github.com/edx/edx-enterprise/pull/97
**Merge deadline:** 19 May, 2017
**Installation instructions:**  Install `edx-enterprise` from this branch `zub/ENT-330-enterprise-landing-page-ui-updates` in `edx-platform`.
1. Go to enterprise customers django admin at admin/enterprise/enterprisecustomer/
2. Add enterprise customer with logo
3. Add a course in the enterprise customer catalog
4. View the enterprise landing page for the enterprise course by accessing the enterprise course enrollment url with enterprise customer uuid from …

minor UI updates for enterprise landing page

---

api-compact.yaml
api.yaml

**Description:** After troubleshooting the API Gateway connection yesterday it appears that we need to specify the actual Enterprise service endpoints in `api.yaml` and `api-compact.yaml`.
**JIRA:** N/A
1. After merging we will update the API Gateway code with the new hash and try again on the stage instance -- no one is using these broken endpoints right now!
~~- [ ] Regenerate requirements with `make upgrade && make requirements` (and make sure to fix any errors).~~
~~- [ ] Documentation updated (not only docstrings)~~
~~- [ ] Translations are updated~~
- [ x] PR author is listed in AUTHORS
**Author concerns:** Hopefully this is the correct fix or else we're going to have to …

Update API Gateway configuration to use correct service endpoints

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/lms_api.py
integrated_channels/sap_success_factors/models.py
tests/test_lms_api.py
tests/test_management.py

**Description:** After we retested ENT-359 with verified, I noticed the call was failing on getting the remote id, because the url was not properly formatted. I also noticed that sending some of the fields as empty strings in the call was causing issues for the SAP API, so I omitted those empty values that we don't want to send anyway from the payload.
**JIRA:** https://openedx.atlassian.net/browse/ENT-359
**Dependencies:** based on https://github.com/edx/edx-enterprise/pull/98
**Installation instructions:** Ideally we would test this with an environment that had the standard enterprise set up with a verified course available.
Sandbox: https://brittneyexline.sandbox.edx.org/
With a fully operating environment (ie stage):
1. Ensure there …

ENT-359 Fix a couple bugs with sending learner data

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/admin/__init__.py

@asadiqbal08 @saleem-latif @zrana @douglashall 
This PR is to support the QA for the story [ENT-39](https://openedx.atlassian.net/browse/ENT-390)
**Description:** add django admin for the models "`EnterpriseCourseEnrollment`" and "`PendingEnrollment`".
**JIRA:** N/A
**Merge deadline:** 16 May, 2017
**Installation instructions:** Install `edx-enterprise` from this branch `zub/add-enterprise-course-enrollment-django-admin` in `edx-platform`.
1. Open enterprise django admin at `admin/enterprise/`
2. Check that you can view the 2 new django admin panels for `Enterprise course enrollments` and `Pending enrollments`
**Author concerns:** List any …

add django admin for enterprise course enrollment models

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/static/enterprise/enterprise_course_enrollment_page.css
enterprise/templates/enterprise/enterprise_course_enrollment_page.html
enterprise/tpa_pipeline.py
enterprise/utils.py
enterprise/views.py
test_settings.py
tests/test_tpa_pipeline.py
tests/test_utilities.py
tests/test_views.py

ENT-347
**Description:**  	Display account created/linked message on enterprise course enrollment page (enterprise landing page).
**JIRA:** [ENT-347](https://openedx.atlassian.net/browse/ENT-347)
**Merge deadline:** 19 May, 2017
**Installation instructions:** Install `edx-enterprise` from this branch `zub/ENT-347-enterprise-landing-page-display-messages` in `edx-platform`.
2. Add enterprise customer with logo and with consent disabled and link it with an `idp`.
3. Create/publish a course in studio
4. As an anonymous user view the enterprise landing page for the enterprise course by accessing the enterprise course …

Display account created/linked message on enterprise landing page

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/static/enterprise/grant_data_sharing_permissions.css
enterprise/templates/enterprise/base.html
enterprise/templates/enterprise/enterprise_course_enrollment_page.html
enterprise/templates/enterprise/grant_data_sharing_permissions.html
enterprise/templates/enterprise/templatetags/alert_messages.html
enterprise/templates/enterprise/templatetags/fa_icon.html
enterprise/templates/enterprise/widgets/segment-io.html
enterprise/templatetags/enterprise.py
enterprise/views.py
test_settings.py
tests/test_templatetags.py
tests/test_views.py

**Description:** This PR converts all mako templates in edx-enterprise to django templates
**JIRA:** [ENT-399](https://openedx.atlassian.net/browse/ENT-399)
**Dependencies:** https://github.com/edx/edx-platform/pull/15179
**Installation instructions:** Simply install edx-enterprise no other setup required.
1. Open data sharing consent page
2. Make sure it works as expected i.e. there are no errors
3.Open enterprise landing page
4.Make sure it works as expected i.e. there are no errors

ENT-399: Convert enterprise templates to django template

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/static/enterprise/enterprise_course_enrollment_page.css
enterprise/templates/enterprise/enterprise_course_enrollment_page.html

Hi @douglashall , @brittneyexline , @zubair-arbi , @asadiqbal08 ,
Please take a look at this PR.
**Description:** When only one course mode is available on the Enterprise Landing page, the UI of the page needs to be modified to hide certain design elements and text associated with multiple course modes.
**JIRA:**[ENT-400](https://openedx.atlassian.net/browse/ENT-400)
**Installation instructions:** Simply install edx-enterprise and enable it in edx-platform.
1. Create a Course that has only one mode.
2. Create an enterprise customer at /admin/enterprise/enterprisecustomer/add/
3. Open enterprise landing page at /enterprise/<enterprise-uuid>/course/<course-id>/enroll
4. Use enterprise-uuid and course-id of above created enterprise customer and course.
5. Make sure …

EMT-400: Update enterprise landing page for single course mode

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/lms_api.py
tests/test_lms_api.py

**Description:** This PR adds a missing changelog for the ENT-355 PR, and addresses a missing case from that PR where in some instances, the single enrollment data endpoint may respond with an empty string without throwing a 404 when there is no enrollment data for the given user+course pair.
**Dependencies:** None.
Follow the installation and testing instructions in: https://github.com/edx/edx-enterprise/pull/105
Simply navigating to the enterprise landing page while logged in with a newly registered user not enrolled in any courses should be enough to verify this change. If it doesn't redirect to the courseware in this case, that's the correct behavior
**DO NOT** just add dependencies to `requirements/*.txt` …

ENT-355: Address missing enterprise endpoint case and add missing changelog entry

---

enterprise/utils.py
test_utils/factories.py
tests/api/test_throttles.py
tests/api/test_views.py
tests/test_models.py
tests/test_utilities.py

**Description:** This PR removes the code introduced in [ENT-32](https://openedx.atlassian.net/browse/ENT-32) where the enteprise logo was displayed. The PRs associated with that work were https://github.com/edx/edx-enterprise/pull/18 and https://github.com/edx/edx-enterprise/pull/20
**JIRA:** [ENT-378](https://openedx.atlassian.net/browse/ENT-378)
**Installation instructions:** Standard Enterprise installation
These were mostly helper methods used for displaying the enterprise customer logo in the platform when the enterprise learner logged in so, there's no UI testing to do on the enteprise side. See https://github.com/edx/edx-platform/pull/15187 which removes the associated UI code in edx-platform.
**DO NOT** just …

[ENT-378] Remove code for custom header logo

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/sap_success_factors/utils.py
test_utils/fake_catalog_api.py
tests/test_management.py

**Description:** There was unexpected data in one of the catalogs on prod where an image was
explicitly set to None, and our transformation logic assumed the key would
either not exist or be an object with keys of its own. Now we are accounting
for this case.
**JIRA:** https://openedx.atlassian.net/browse/ENT-384
I am not testing against the full course export script, the unit test replicated the error with the code fix missing.

ENT-384 Fixing course export bug

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/templates/enterprise/grant_data_sharing_permissions.html

**Description:** When enterprise learner clicks "No, take me back" link from data sharing consent page, HTML tags appear in decline DSC popup.
**JIRA:** [ENT-427](https://openedx.atlassian.net/browse/ENT-427)

ENT-427  tags appear in decline DSC pop up.

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/static/enterprise/enterprise_course_enrollment_page.css
enterprise/templates/enterprise/templatetags/alert_messages.html

Hi @zubair-arbi , @asadiqbal08 , @douglashall , @brittneyexline 
Please review this PR, it fixes the UI issues explained in [ENT-425](https://openedx.atlassian.net/browse/ENT-425).
1. Spacing between main text body and price information does not match with spacing between course card image and partner name.
2. HTML appears in notification messages i.e account activation message and account created message on enterprise landing page.
**JIRA:** [ENT-425](https://openedx.atlassian.net/browse/ENT-425)
**Installation instructions:** Simply install edx-enterprise app in edx-platform

ENT-425: Fixed UI issues on enterprise landing page.

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/v1/serializers.py
enterprise/models.py
integrated_channels/sap_success_factors/utils.py
test_utils/fake_catalog_api.py
tests/api/test_serializers.py
tests/test_management.py
tests/test_models.py
tests/test_utilities.py

**Description:** This updates both the enterprise api and SAP course export to use the new
landing page url, but without transitioning the SAP course export to use
the enterprise api endpoint.
**JIRA:** https://openedx.atlassian.net/browse/ENT-356
**Dependencies:** n/a, though it is related to https://github.com/edx/edx-enterprise/pull/107

ENT-356 Simple version of using the new landing page url

---

CHANGELOG.rst
enterprise/urls.py
enterprise/utils.py
enterprise/views.py
tests/test_utilities.py
tests/test_views.py

**Description:** Enable "Continue" button on enterprise course enrollment page (enterprise landing page).
**JIRA:** [ENT-379](https://openedx.atlassian.net/browse/ENT-379)
* ~~[ENT-348](https://openedx.atlassian.net/browse/ENT-348) https://github.com/edx/edx-enterprise/pull/109~~ **Merged**
**Merge deadline:** 16 June, 2017
**Installation instructions:** Install `edx-enterprise` from this branch `zub/ENT-379-ent-landing-page-enable-continue-button` in `edx-platform`.
2. Add enterprise customer with logo and with/without (2 different flows) consent disabled and link it with an `idp`.
3. Create/publish a course in studio
4. …

enable continue button on enterprise course enrollment page

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/templates/enterprise/enterprise_course_enrollment_page.html
enterprise/views.py
tests/test_views.py

**Description:** This PR shows discounted prices for course modes in the landing page and course modal. The discounts are retrieved from the Ecommerce service.
This PR was created on top of https://github.com/edx/edx-enterprise/pull/110.
**JIRA:** [ENT-357](https://openedx.atlassian.net/browse/ENT-357)
**Dependencies:** https://github.com/edx/ecommerce/pull/1307. 
**Merge deadline:** None.
**Installation instructions:** Standard enterprise installation.
**Screenshots:**
1. Add an Enterprise Customer in the Django admin. Check its ID
2. Add a course in the customer catalog. Check its ID
3. In Ecommerce create a verified Course associated with the one in step 2. Use $500 for the price
4. In Ecommerce create a single course coupon with 25% discount and associated …

[ENT-357] Display course run price with entitlement on Landing page & course description modal

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/pagination.py
tests/api/test_pagination.py

Hi @douglashall , @zubair-arbi , @asadiqbal08 
Please take a look at the changes. 
The "next" and "previous" fields appear to be returning invalid page references when requesting pages other than the first (ie, no page value specified). This also happens when other parameters are specified, such as "limit" and "offset".
This PR fixes this problem for next and previous urls in API response.
**JIRA:** [ENT-442](https://openedx.atlassian.net/browse/ENT-442)
1. In Postman, with a valid authentication code for a staff user, attempt to access: /enterprise/api/v1/catalogs/124/courses/?page=2

ENT-442: Fix query string parameters in next and previous pages of enterprise catalog courses endpoint.

---

CHANGELOG.rst
enterprise/tpa_pipeline.py
enterprise/utils.py
enterprise/views.py
tests/test_lms_api.py
tests/test_tpa_pipeline.py
tests/test_views.py

**Description:** Old [python-social-auth](https://github.com/python-social-auth) was a monolithic repository and the version we utilize is almost a year old. We are looking to upgrade to the latest, split version of python-social-auth which is more modular, and provides several new features, including a configurable maximum session length, a DB-packed partial pipeline, utilizing the latest backend (provider) versions, and so on.
**JIRA:** Implements [ENT-365](https://openedx.atlassian.net/browse/ENT-365).
**Dependencies:** [Complementary PR at edx-platform](https://github.com/edx/edx-platform/pull/15135).
**Merge deadline:** Mostly handles technical debt, so not that urgent.
**Installation instructions:** N/A for now.
**Testing instructions:** See [edx-platform …

[ENT-365] Move from old python-social-auth to latest, split PSA

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/v1/views.py
enterprise/course_catalog_api.py

Hi @mattdrayer , @douglashall , @brittneyexline , @zubair-arbi , @asadiqbal08 
This PR addresses the issue of limit, offset and page_size parameters being lost in the request.
**JIRA:** [ENT-442](https://openedx.atlassian.net/browse/ENT-442)

ENT-442: Add the ability to pass limit, offset and page_size parameters to enterprise catalog courses.

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/course_catalog_api.py
tests/test_course_catalog_api.py

**Description:** The file that we were importing to generate catalog api clients was removed
and replaced with a mixin. In order for us to have full functionality on
the enterprise api client, we need to fix this contract change.
**Merge deadline:** asap
instructions.
1. Open page A
2. Do thing B
migrations, …

Fixing import of the catalog api client after change in edx-platform

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/utils.py
tests/test_utilities.py
tests/test_views.py

**Description:** We had to implement a decorator (https://github.com/edx/edx-platform/pull/14896/files) for the track selection page when we were testing SAP that terminated any existing session coming into the page if coming in through SSO. Since we are using this new landing page, we need the same logic here in order to stay in compliance with SAPs expectations.
**JIRA:** https://openedx.atlassian.net/browse/ENT-454
**Dependencies:** 
**Installation instructions:** Standard Installation with this version of edx-enterprise.
1. Set up a SAML Configuration and SAML IdP Provider Configuration against TestShib, and set up an Enterprise Customer linked to the Provider Configuration. Ensure that the provider configuration has the following …

ENT-454 Apply session management logic to new Enterprise landing page

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/tpa_pipeline.py
tests/test_tpa_pipeline.py

**Description:** When signing in via SSO for an Enterprise customer who requires data sharing consent, this consent should only be required at login if the consent required is `AT_LOGIN`.  All other consent requirements (`AT_ENROLLMENT`, `OPTIONAL`, `EXTERNALLY_MANAGED`) will be handled at a later time.
**JIRA:** [ENT-452](https://openedx.atlassian.net/browse/ENT-452)
**Dependencies:** None.
**Merge deadline:** 04/Jul/17
**Installation instructions:**
Standard Enterprise Customer setup, with TPA/SSO enabled.
**Sandbox**
Deployed to https://business.sandbox.edx.org, and:
LMS: https://pr15359-2.sandbox.opencraft.hosting
Studio: https://studio-pr15359-2.sandbox.opencraft.hosting
1. As `staff` via [LMS Admin](https://pr15359-2.sandbox.opencraft.hosting/admin/enterpris …

ENT-452 Enforce data sharing consent at login for SSO users iff data sharing consent is requested AT_LOGIN

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/sap_success_factors/migrations/0006_sapsuccessfactors_use_enterprise_enrollment_page_waffle_flag.py
integrated_channels/sap_success_factors/utils.py
requirements/base.in
requirements/base.txt
requirements/test.txt
setup.py
test_settings.py
tests/test_management.py
tests/test_utilities.py

**Description:** We attempted to use site configuration to decide which launchUrl to send to SAP, but that wasn't working because of the management command context that this code is run in. This PR introduces waffle so that we can use that to control the feature, and to use for future feature development.
**JIRA:** https://openedx.atlassian.net/browse/ENT-471
Will fill out shortly.

ENT-471 Introducing waffle to enable configuration of sending SAP launchUrl

---

CHANGELOG.rst
enterprise/__init__.py
setup.py

Due to a failure to think properly on my part, the current version of edx-enterprise does not actually install its requirements - rather than having a list of requirements, it has an open file pointer to the relevant requirements file. This change fixes that.
1. Checkout this version, and then, in a clean virtual environment, do `pip install /path/to/enterprise/repo`. Verify that in addition to `edx-enterprise`, `django-object-actions` and `django-waffle` are installed.

Fix requirements installation

---

CHANGELOG.rst
api-compact.yaml
api.yaml
enterprise/__init__.py

The Enterprise Service returns a "next" field in the case of a large response which requires pagination. This field contains a fully-qualified URL specifying the service host (eg, courses.edx.org), which makes sense for clients interacting directly with the service.
However, this breaks down for clients interacting with the Enterprise Service via the API Gateway. In this case, the "next" parameter must NOT specify the service host, it must instead specify the gateway host (api.gateway.com).
**JIRA:** [ENT-472](https://openedx.atlassian.net/browse/ENT-472)

ENT-472: Add page_size in querystring and Host in Header for aws gateway integration request.

---

CHANGELOG.rst
MANIFEST.in
enterprise/__init__.py

**Description:** Fixes error where deploying latest version of enterprise causes requests to the application to 500.
**JIRA:** 
**Dependencies:** 
1. Install the previous version of enterprise, observe that all requests 500 due to an import error.
2. Install this version of enterprise, observe that requests are returning normally.
**Author concerns:**

ENT-492 Properly make the consent package installable by PyPI

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/v1/decorators.py
enterprise/api/v1/serializers.py
enterprise/api/v1/views.py
tests/test_enterprise/api/test_decorators.py
tests/test_enterprise/api/test_serializers.py
tests/test_enterprise/api/test_views.py

If a client tries to access catalog courses through enterprise API, and the user associated with the request is not associated with any enterprise customer then the API returns a `500` error. This PR fixes that issue, now for API request with users not associated with any enterprise customer API will return a response with `200` status instead of `500`. 
**JIRA:** [ENT-554](https://openedx.atlassian.net/browse/ENT-554)
1. Fetch catalog courses via `http://localhost:8000/enterprise/api/v1/catalogs/{id}/courses/` request should be made using JWT credentials, use client-id and client-secret for a user that is not associated with any enterprise customer.
2. Catalog courses endpoint should return a proper response with `200` status code.
**Merge …

ENT-554: Fix 500 errors on catalog courses API endpoint for users that are not associated with any enterprise customer.

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/permissions.py
enterprise/api/v1/views.py
enterprise/models.py
tests/test_enterprise/api/test_views.py

**Description:** The previous iteration of this endpoint took a catalog id, inferred the enterprise customer based on that catalog, and if the request user was not an EnterpriseCustomerUser associated with that enterprise, then there would be a permissions error.
This new endpoint will pull the courses in the catalog linked to the provided enterprise, which is explicitly stated in the call. There will be appropriate responses if:
*there is no catalog linked to the given enterprise
*if the request user is neither staff nor associated with the enterprise
*if the catalog api returns an empty response (different than having no courses)
On success, it will return the catalog api courses response format with augmented enterprise specific data as the earlier endpoint did.
**JIRA:** …

ENT-476 New enterprise endpoint for courses by enterprise

---

CHANGELOG.rst
api-compact.yaml
api.yaml
enterprise/__init__.py

**Description:** I have removed usages of VTL macros as they are not supported by AWS API Gateway.
**JIRA:** [ENT-472](https://openedx.atlassian.net/browse/ENT-472)
instructions.
1. Execute the following to get JWT access token.
`curl -H "Content-Type:application/x-www-form-urlencoded" -X POST -d "grant_type=client_credentials&client_id=<client-id>&client_secret=<client-secret>&token_type=jwt" "https://api.stage.edx.org/oauth2/v1/access_token"`
2. Execute to get the catalogs
`curl -H "Authorization:JWT <jwt-token>"  -X GET "https://20enjrmi05.execute-api.us-west-2.amazonaws.com/edx_api/enterprise/v1/catalogs?limit=2&offset=2"`
3. Make sure `next` and `previous` in response has correct domain i.e. …

ENT-472: Remove Macro use from swagger api config as it is not supported by AWS.

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/sap_success_factors/transmitters/learner_data.py
tests/test_sap_success_factors/test_transmitters.py

**Description:** Previously, we were allowing multiple completion events per enrollment to be sent in case something had changed that was relevant to send again. We were using the timestamp to determine whether an even has changed. However, for audit/self paced enrollments, the completed timestamp is incorrect and reflects the time the job runs. This is because the grades api doesn't return the date the grade was passing. So for now, we will send just one event per enrollment since there is no strong need to do otherwise.
**JIRA:** https://openedx.atlassian.net/browse/ENT-581
**Merge deadline:** Tomorrow (8/3/2017)
**Post …

ENT-581 Record one completion event per enrollment record

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api_client/discovery.py
enterprise/api_client/lms.py
enterprise/messages.py
enterprise/static/enterprise/enterprise_course_enrollment_page.css
enterprise/templates/enterprise/enterprise_course_enrollment_page.html
enterprise/utils.py
enterprise/views.py
requirements/dev.txt
requirements/doc.txt
requirements/quality.txt
requirements/test-ficus.in
requirements/test-ficus.txt
requirements/test-ginkgo.in
requirements/test-ginkgo.txt
requirements/test-hawthorn.in
requirements/test-hawthorn.txt
requirements/test-master.in
requirements/test-master.txt
requirements/test.txt
test_utils/fake_catalog_api.py
tests/test_enterprise/api_client/test_discovery.py
tests/test_views.py

Previously we were using the LMS courses API.
ENT-585
**JIRA:** https://openedx.atlassian.net/browse/ENT-585
1. Open page A
2. Do thing B
**Author concerns:** None

ENT-585 Use the catalog service API for retrieving course metadata for display on the course enrollment landing page.

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/views.py

This PR fixes the 500 error appearing on enterprise landing page.
**JIRA:** [ENT-612](https://openedx.atlassian.net/browse/ENT-612)
1. Open enterprise landing page (preferably for a course with no `full_description`)
2. Page should open without 500 error.

ENT-612: Fix 500 server error on enterprise course enrollment page.

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/views.py
tests/test_views.py

ENT-612
**Description:** We need to be careful about checking for null values returned from the discovery API.
**JIRA:** https://openedx.atlassian.net/browse/ENT-612

Fix course enrollment landing page when the course does not have a course image configured.

---

CHANGELOG.rst
consent/api/v1/views.py
consent/helpers.py
consent/migrations/0002_migrate_to_new_data_sharing_consent.py
consent/models.py
enterprise/__init__.py
enterprise/decorators.py
enterprise/models.py
enterprise/utils.py
enterprise/views.py
integrated_channels/integrated_channel/learner_data.py
tests/test_consent/api/test_permissions.py
tests/test_consent/api/test_views.py
tests/test_consent/test_helpers.py
tests/test_enterprise/api/test_views.py
tests/test_management.py
tests/test_migrations.py
tests/test_models.py
tests/test_sap_success_factors/test_learner_data.py
tests/test_utilities.py
tests/test_views.py

**Description:** This PR migrates the codebase to use the new `DataSharingConsent` model created in #167. It also introduces a data migration in order to make that code migration meaningful, and this data migration comes with tests to build confidence.
**JIRA:** [ENT-496](https://openedx.atlassian.net/browse/ENT-496)
**Dependencies:** Not a hard dependency because I've already incorporated the changes and expect them to be merged soon -- #158.
**Merge deadline:** Before next sprint starts, hopefully
1. Ensure that all enterprise flows work fine as before.
1. Ensure that data sharing consent screens properly render, or don't.
1. Ensure that data sharing consent is properly saved.
1. Ensure that any management commands that depend on consent (like …

[ENT-496] Migrate to new DataSharingConsent model

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/v1/serializers.py

**Description:** I discovered an error on the business sandbox where the user wasn't being enrolled in the course when doing a verified purchase. The root cause was that we were calling the enterprise-course-enrollment endpoint attempting to write the consent_granted field. However, the record existed with consent_granted set to NULL, as expected from the changes from ENT-496, but the api save method used get_or_create with that and threw an DB integrity error. There is an associated edx-platform PR to address how we call this (https://github.com/edx/edx-platform/pull/15950)
**Installation instructions:** List any non-trivial installation …

ENT-496 Posting to enterprise-course-enrollment shouldn't write consent_granted anymore

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/views.py
test_settings.py
tests/test_enterprise/views/test_course_enrollment_view.py
tests/test_enterprise/views/test_grant_data_sharing_permissions.py

The reason we weren't getting page events sent to segment for the course landing page
was because the LMS_SEGMENT_KEY wasn't getting passed in the context for that view.
We should always be passing that so that we can take advantage of segment for all pages.
instructions.
For the business sandbox:
Log into our test segment account (ask me for details), and go to the debug tab. Go to the course landing page, note that each new page generates a page event in segment's debug tab, particularly for the course landing page which previously …

ENT-617 Ensure that LMS_SEGMENT_KEY is passed in the context for all enterprise views

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/v1/serializers.py
enterprise/models.py
tests/test_enterprise/api/test_views.py

ENT-638
**Description:** We were including the deprecated UserDataSharingConsentAudit model
data with the enterprise-learner API endpoint result payload. This
fixes that so we now return the new DataSharingConsent model data.
The Enterprise Offers feature I am adding to ecommerce will make use of the DataSharingConsent data returned via the enterprise-learner API endpoint.
**JIRA:** https://openedx.atlassian.net/browse/ENT-638
1. Visit https://business.sandbox.edx.org/enterprise/api/v1/enterprise-learner/?username=myself2e86.
2. Verify that the results contain a `data_sharing_consent_records` key.

ENT-638 Fix enterprise-learner API endpoint serializer.

---

AUTHORS
CHANGELOG.rst
enterprise/__init__.py
enterprise/admin/forms.py
enterprise/admin/views.py
enterprise/models.py
tests/test_admin/test_forms.py
tests/test_admin/test_view.py

This adds functionality to allow an existing enterprise customer to be
enrolled in multiple courses. The current behavior would incorectly
limit the user to only be enrolled once via the django-admin page.
WL-1221
**Installation instructions:** Install branch
1. As admin, Open Enterprise Customer->Manage Learners page
2. As admin, enroll new User A into Course A, verify enrollment email sent and User A put into Pending Linked Learner
3. As admin, Enroll User A into Course B, verify enrollment email sent and User A still in Pending List
4. As User A, create an account on edX
5. As User A, verify that Course A and Course B show up in Courses Dashboard
6. As admin, verify that User A was moved from Pending to Linked …

Allow multi-course enrollment for enterprise users in admin

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/v1/urls.py
enterprise/api/v1/views.py
tests/test_enterprise/api/test_views.py

**Description:** Please see the [ENT-640 ticket](https://openedx.atlassian.net/browse/ENT-640) for more details.
**JIRA:** [ENT-640](https://openedx.atlassian.net/browse/ENT-640)
1. Make sure you can no longer go to `/enterprise/api/v1/auth-user/` or `/enterprise/api/v1/auth-user/{id}/` as any type of user (unauthenticated, authenticated, staff, non-staff, etc.).

[ENT-640] Remove `auth-user` endpoint.

---

AUTHORS
CHANGELOG.rst
enterprise/__init__.py
enterprise/admin/views.py
enterprise/utils.py
tests/test_admin/test_view.py

Currently the enterprise emails assume they are being ran with a
marketing site. This allows for instances without a marketing site
(e.g. devstack, sandbox, WL) to send emails correctly.
**JIRA:**
[WL-1124]
None
None. Sooner the better?
**Installation instructions:** List any non-trivial installation instructions.
None
1. Open the enterprise customer admin page in LMS
2. Click "Manage Learners" in the top right
3. Add a leaner to a program or course
4. Note in email how the link is formatted correctly based on whether the site has an admin page or not.
**DO NOT** just add dependencies to …

Make enrollment emails marketing site aware

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/messages.py
enterprise/models.py
enterprise/utils.py
enterprise/views.py
tests/test_enterprise/api/test_serializers.py
tests/test_enterprise/api/test_views.py
tests/test_enterprise/views/test_course_enrollment_view.py
tests/test_enterprise/views/test_grant_data_sharing_permissions.py
tests/test_enterprise/views/test_handle_consent_enrollment.py
tests/test_enterprise/views/test_program_enrollment_view.py
tests/test_management.py
tests/test_models.py
tests/test_utilities.py

**Description:** This PR removes our hard requirement on `configuration_helpers` by abstracting all uses of it into a single utility function which can be easily modified in the future in case we decide to officially drop the need for `configuration_helpers`.
**JIRA:** [ENT-428](https://openedx.atlassian.net/browse/ENT-428)
**Merge deadline:** N/A
Just see that the abstraction is occurring properly and that tests are still passing.
To be safe, go to the course enrollment landing page with this PR's code installed, and make sure the platform name and other values we get through `configuration_helpers` are still gotten.

[ENT-428] Remove hard requirement on `configuration_helpers`.

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/admin/__init__.py
enterprise/api/v1/serializers.py
enterprise/api/v1/urls.py
enterprise/api/v1/views.py
enterprise/migrations/0026_remove_old_consent.py
enterprise/models.py
enterprise/utils.py
test_utils/factories.py
tests/test_decorators.py
tests/test_enterprise/api/test_views.py
tests/test_enterprise/views/test_course_enrollment_view.py
tests/test_enterprise/views/test_grant_data_sharing_permissions.py
tests/test_management.py
tests/test_migrations.py
tests/test_models.py
tests/test_sap_success_factors/test_learner_data.py
tests/test_utilities.py

**Description:** This removes any remaining traces of account-level consent and consent for courses tracked by the `EnterpriseCourseEnrollment` model.
**JIRA:** [ENT-644](https://openedx.atlassian.net/browse/ENT-644)
**Merge deadline:** N/A
Since account-level consent and course-level consent through `EnterpriseCourseEnrollment` were both deprecated in favor of `DataSharingConsent`, this should not have any effect on functionality. However, to be safe, it may be recommended to try out our data sharing consent flows to make sure everything still works as intended.

[ENT-644] Remove account-level & `EnterpriseCourseEnrollment` consent.

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/models.py
tests/test_utilities.py

**Description:** This PR removes `require_account_level_consent` in code only, to prepare for the last PR of making the migrations to delete all of the fields/models associated with account-level consent.
**JIRA:** [ENT-644](https://openedx.atlassian.net/browse/ENT-644)
**Merge deadline:** ASAP.

[ENT-644] Remove `require_account_level_consent` in code only. (Step 2)

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/migrations/0027_remove_account_level_consent.py

**Description:** This PR adds all the migrations to be released as a separate version for removing account-level consent.
**JIRA:** [ENT-644](https://openedx.atlassian.net/browse/ENT-644)
**Dependencies**: #197 which is step 2 in this process.
**Merge deadline:** ASAP.
1. Make sure the migrations run safely.

[ENT-644] Perform migrations for removing account-level consent. (Step 3)

---

CHANGELOG.rst
api-compact.yaml
api.yaml
enterprise/__init__.py
enterprise/api/v1/decorators.py
enterprise/api/v1/urls.py
enterprise/api/v1/views.py
enterprise/api_client/discovery.py
enterprise/migrations/0029_auto_20170925_1909.py
enterprise/models.py
test_utils/__init__.py
test_utils/fake_catalog_api.py
tests/test_enterprise/api/test_views.py
tests/test_enterprise/api_client/test_discovery.py
tests/test_utilities.py

ENT-638
**Description:** This extends both the EnterpriseCustomer and EnterpriseCustomerCatalog endpoints to include a `contains_content` detail endpoint which will return whether or not the given content items exist within the specified EnterpriseCustomerCatalog or any of the EnterpriseCustomerCatalogs associated with the given EnterpriseCustomer.
These endpoints are needed to support [Enterprise Offers](https://github.com/edx/ecommerce/pull/1475) in ecommerce.
The second commit in this PR changes the EnterpriseCustomerCatalog API endpoint paths to use underscores instead of dashes. We will follow up with the remaining Enterprise API endpoints with ENT-668.
**JIRA:** https://openedx.atlassian.net/browse/ENT-638
1. Login to https://business.sandbox.edx.org with a …

Add API endpoints for checking the existence of content contained in EnterpriseCustomerCatalogs.

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/models.py
tests/test_models.py

**Description:** This updates the EnterpriseCustomer.catalog_contains_course method to check related EnterpriseCustomerCatalogs for the existence of the specified course run as well as the discovery service catalog. This method is used by the data sharing consent code when determining if consent is required for a given EnterpriseCustomer/user/course run combination.
1. Visit https://business.sandbox.edx.org/enterprise/1b542b06-d353-45e6-9867-9579d9e12745/course/course-v1:edX+Test101+course/enroll/.
2. Verify that you are redirected to the DSC page during the onboarding workflow.

Update EnterpriseCustomer.catalog_contains_course to take EnterpriseCustomerCatalogs into account.

---

enterprise/admin/forms.py
tests/test_admin/test_forms.py

**Description:** fix regression caused by previous fix. Now check for null site when creating a new enterprise_customer. Added a test for this as well.
1. Create a new enterprise_customer via http://localhost:18000/admin/enterprise/enterprisecustomer/add/
2. Make sure the form is properly displayed

fix null site when creating new enterprise_customer

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/v1/mixins.py
enterprise/api/v1/serializers.py
enterprise/models.py
enterprise/utils.py
test_utils/__init__.py
test_utils/fake_catalog_api.py
test_utils/fake_enterprise_api.py
tests/test_enterprise/api/test_serializers.py
tests/test_enterprise/api/test_views.py
tests/test_utilities.py

@zubair-arbi @saleem-latif can you please take a look on that PR?
**Description:** Added UTM parameters to marketing/enrollment URLs returned by Enterprise API.
**JIRA:** [ENT-653](https://openedx.atlassian.net/browse/ENT-653)

[ENT-653] Added UTM parameters to marketing/enrollment URLs

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/constants.py
enterprise/migrations/0031_auto_20171012_1249.py
enterprise/models.py

**JIRA:** [ENT-694](https://openedx.atlassian.net/browse/ENT-694)
[SANDBOX](https://business.sandbox.edx.org/admin/enterprise/enterprisecustomercatalog/)

Added enabled_course_modes JSONField to EnterpriseCustomerCatalog

---

CHANGELOG.rst
consent/migrations/0003_historicaldatasharingconsent_history_change_reason.py
enterprise/__init__.py
enterprise/migrations/0033_add_history_change_reason_field.py
integrated_channels/sap_success_factors/migrations/0008_historicalsapsuccessfactorsenterprisecustomerconfiguration_history_change_reason.py
requirements/dev.txt
requirements/doc.txt
requirements/quality.txt
requirements/test-hawthorn.in
requirements/test-hawthorn.txt
requirements/test-master.in
requirements/test-master.txt
requirements/test.txt

Add migration which adds change_reason field to history tables.
Bump version to 0.52.4.
**Description:** We are currently attempting to upgrade edx-platform to Django 1.11. We've removed all usage of django-simple-history from edx-platform. However, edx-enterprise still uses the module, which needs to upgrade to version 1.9.0 in order to add Django 1.11 support. This PR performs the upgrade in edx-enterprise.
I'm unsure how these upgrades are usually performed in edx-enterprise, so this is my best guess. After this PR is approved and merged, we'd then upgrade edx-platform to use version 0.52.4 of edx-enterprise in a separate edx-platform PR.

Upgrade django-simple-history to 1.9.0 to add Django 1.11 support.

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/models.py
tests/test_models.py

**Description:** Added EnterpriseCustomerCatalog UUID as query parameter on enrollment URLs
**JIRA:** [ENT-695](https://openedx.atlassian.net/browse/ENT-695)

[ENT-695] Added catalog UUID as query parameter on enrollment URLs

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/messages.py
enterprise/models.py
enterprise/templates/enterprise/enterprise_course_enrollment_page.html
enterprise/views.py
test_utils/mixins.py
tests/test_enterprise/views/test_course_enrollment_view.py

**Description:** update course enrollment view for enabled course mode in enterprise catalogs
**JIRA:** [ENT-696](https://openedx.atlassian.net/browse/ENT-696)
**Merge deadline:** 20 Oct, 2017
**Installation instructions:** Install `edx-enterprise` from this branch `zub/ENT-696-update-course-enrollment-for-catalog-queryparam` in `edx-platform`.
1. Create enterprise with a catalog
2. Add a record in table `Enterprise Customer Catalogs` against the above enterprise.
3. Provide desired course mode (in order) to display on enterprise course enrollment page
4. Now go to enterprise course enrollment page as a learner and verify that the displayed course modes are from the list provided in table `Enterprise …

ENT-696 update course enrollment view for enterprise enabled course modes

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/v1/serializers.py
tests/test_enterprise/api/test_views.py

**Description:** Update the call for level from EnterpriseCustomer to EnterpriseCustomerCatalogs
**JIRA:** [ENT-718](https://openedx.atlassian.net/browse/ENT-718)

ENT-718 Updated the call level to enrollment URLs

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/migrations/0034_auto_20171023_0727.py

@asadiqbal08 @saleem-latif 
**Description:** Fix migration issue for `enabled-course-modes` field of `EnterpriseCustomerCatalog` model.
**History:** When we introduce the `enabled-course-modes` field for `EnterpriseCustomerCatalog` model (https://github.com/edx/edx-enterprise/pull/211/files) we were having difficulty reading the existing records for `EnterpriseCustomerCatalog` model as we wanted to provide a default list of course modes instead of just an empty value. So after creating the migration we manually edited the migration and changed the default for the `jsonfield` from `enterprise.constants.json_serialized_course_modes` to 
`enterprise.constants.COURSE_MODE_SORT_ORDER` (https://github.com/edx/edx-enterprise/pull/223/files). This resolved our issue but this change created …

ENT-694 Fix migration issue for enabled-course-modes field

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/decorators.py
tests/test_decorators.py

**Description:** Fix alteration in querystring parameters for decorator "enterprise_login_required" when learner is redirected from `SSO`.
**JIRA:** [ENT-726](https://openedx.atlassian.net/browse/ENT-726)
**Merge deadline:** End of sprint `V`.
**Installation instructions:** Install `edx-enterprise` from this branch `zub/ENT-726-fix-enterprise-login-querysting-alteration` in `edx-platform`.
1. Create a SAML IDP for while enabling the setting "Drop existing session"
2. Create enterprise with the above IDP
3. Create a related catalog in model `EnterpriseCustomerCatalog`
4. Access the enterprise course enrollment url with the catalog query parameter (value should be the UUID of above created …

ENT-726 Fix alteration in querystring parameters for enterprise login decorator

---

CHANGELOG.rst
enterprise/__init__.py
requirements/dev.txt
requirements/doc.txt
requirements/quality.txt
requirements/test-ficus.in
requirements/test-ficus.txt
requirements/test-ginkgo.in
requirements/test-ginkgo.txt
requirements/test-hawthorn.in
requirements/test-hawthorn.txt
requirements/test-master.in
requirements/test-master.txt
requirements/test.txt

**Description:** Removes the dependency on django-extensions, which doesn't seem to actually be used.  Trying to upgrade it in edx-platform to a version which fully supports Django 1.11 is causing errors in seemingly unrelated edx-enterprise migrations, so I'm attempting removal instead.
**JIRA:** [PLAT-1780](https://openedx.atlassian.net/browse/PLAT-1780)
**Installation instructions:** None
1. Verify that automated tests pass
**Author concerns:** It looks like this dependency was never actually used; it may have been added in confusion because of `TimeStampedModel`, which exists in both django-extensions and …

PLAT-1780 Remove dependency on django-extensions

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/views.py
tests/test_enterprise/views/test_course_enrollment_view.py

@saleem-latif @asadiqbal08 @douglashall 
**Description:** Preserve catalog querystring on declining DSC
**JIRA:** [ENT-731](https://openedx.atlassian.net/browse/ENT-731)
**Merge deadline:** Urgently required for Microsoft enterprise integration
**Installation instructions:** Install `edx-enterprise` from this branch `zub/ENT-731-preserve-querystring-dsc-decline-url` in `edx-platform`.
1. Create a SAML IDP for while enabling the setting "Drop existing session"
2. Create enterprise with the above IDP
3. Create a related catalog in model `EnterpriseCustomerCatalog`
4. Access the enterprise course enrollment url with the catalog query parameter (value should be the UUID of above created `EnterpriseCustomerCatalog` records) with url like:
``` …
```

ENT-731 Preserve catalog querystring on declining DSC

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api_client/enterprise.py

`transmit_courseware_data` management command errors out with 429. This PR fixes this issue.
**JIRA:**  [ENT-735](https://openedx.atlassian.net/browse/ENT-735)

ENT-735: Fetch catalog courses in large chunks to avoid API limit

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/views.py
tests/test_enterprise/views/test_grant_data_sharing_permissions.py

@asadiqbal08 @saleem-latif @douglashall
**Description:** Fix error for empty course start date
**JIRA:** [ENT-737](https://openedx.atlassian.net/browse/ENT-737)
**Related PR:** https://github.com/edx/edx-enterprise/pull/216/
**Installation instructions:** Install `edx-enterprise` from this branch `zub/ENT-737-fix-error-for-course-start-date-not-set` in `edx-platform`.
1. Create a SAML IDP for while enabling the setting "Drop existing session"
2. Create enterprise with the above IDP
3. Create a related catalog in model `EnterpriseCustomerCatalog`
4. Add a course in the catalog which don't have any start data (null value in discovery API response for the catalog).
5. Access the enterprise course enrollment url with the …

ENT-737 Fix error for empty course start date

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/admin/__init__.py

**Description:** This adds an inline admin form to the EnterpriseCustomer admin for creating/updating EnterpriseCustomerCatalog models.
1. Visit https://business.sandbox.edx.org/admin/enterprise/enterprisecustomer/2b5a2956-7746-4fc9-9587-bc887ba45973/.
2. Verify the "Enterprise Customer Catalogs" section is visible.

Add EnterpriseCustomerCatalog inline admin to EnterpriseCustomer admin.

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/templates/enterprise/_enterprise_customer_sidebar.html
enterprise/templates/enterprise/enterprise_course_enrollment_error_page.html
enterprise/templates/enterprise/enterprise_course_enrollment_page.html
enterprise/templates/enterprise/grant_data_sharing_permissions.html
enterprise/views.py
tests/test_enterprise/views/test_course_enrollment_view.py

@asadiqbal08 @saleem-latif 
**Description:** Show generic info message on enterprise course enrollment page in case there was an error getting course or course run information.
**JIRA:** [ENT-717](https://openedx.atlassian.net/browse/ENT-717)
**Merge deadline:** 3 November, 2017 
**Installation instructions:** Install `edx-enterprise` from this branch `zub/ENT-717-course-enrollment-show-generic-messages-for-error` in `edx-platform`.
1. Create a SAML IDP for while enabling the setting "Drop existing session"
2. Create enterprise with the above IDP
3. Create a related catalog in model `EnterpriseCustomerCatalog`
4. Access the enterprise course enrollment url with the catalog query parameter (value should be the UUID of above created …

ENT-717 Show generic info message on enterprise course enrollment page

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/v1/serializers.py
enterprise/models.py
enterprise/utils.py
test_utils/fake_catalog_api.py
tests/test_enterprise/api/test_views.py
tests/test_models.py

**Description:** Applied appropriate content filtering for courseruns to the EnterpriseCustomerCatalog detail endpoint
**JIRA:** [ENT-687](https://openedx.atlassian.net/browse/ENT-687)

Applied appropriate content filtering to the EnterpriseCustomerCatalog detail endpoint

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/sap_success_factors/migrations/0009_sapsuccessfactors_remove_enterprise_enrollment_page_waffle_flag.py
integrated_channels/sap_success_factors/utils.py
tests/test_management.py
tests/test_utilities.py

Originally the launch URLs we were publishing to SuccessFactors directed learners to the track selection page in LMS. Subsequently, we implemented the enterprise course enrollment landing page. In order to ease the rollout of the course enrollment landing page we created the `SAP_USE_ENTERPRISE_ENROLLMENT_PAGE` waffle switch and used it to toggle between publishing the track selection URL and the course enrollment landing page URL. The course enrollment landing page URL should now be the only URL we publish.
**Acceptance Criteria:**
1. Remove the `SAP_USE_ENTERPRISE_ENROLLMENT_PAGE` waffle switch from the codebase.
2. Ensure that we always publish the course enrollment landing page URL to SuccessFactors.
3. Create a data migration for removing the …

ENT-711: Remove SAP_USE_ENTERPRISE_ENROLLMENT_PAGE waffle switch.

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/decorators.py
enterprise/tpa_pipeline.py
tests/test_tpa_pipeline.py

@douglashall @zubair-arbi Can you please look around the change set. 
I will create a corresponding PR in edx-platform.
**Description:** Authenticating directly using "tpa_hint" URL does not link learner to enterprise customer
**JIRA:** [ENT-729](https://openedx.atlassian.net/browse/ENT-729)

ENT-729/Authenticating directly using "tpa_hint" URL does not link learner to enterprise customer

---

AUTHORS
CHANGELOG.rst
enterprise/__init__.py
enterprise/utils.py
requirements/dev.txt
requirements/doc.txt
requirements/quality.txt
requirements/test-ficus.in
requirements/test-ficus.txt
requirements/test-ginkgo.in
requirements/test-ginkgo.txt
requirements/test-hawthorn.in
requirements/test-hawthorn.txt
requirements/test-master.in
requirements/test-master.txt
requirements/test.txt
tests/test_utilities.py

**Description:** Switch from `PyCrypto` (which hasn't been maintained in years) to the `cryptography` package, which provides equivalent functionality and has been used in edx-platform since at least Ficus.
**JIRA:** [PLAT-1199](https://openedx.atlassian.net/browse/PLAT-1199)
**Installation instructions:** None
1. A newly generated `EnterpriseCustomerReportingConfiguration` should still get an encrypted random password
2. The correct decrypted password should still be shown in Django admin
**Author concerns:**
* I'm a little fuzzy on the exact testing instructions, but the features above are the only ones where the …

PLAT-1199 Replace PyCrypto with cryptography

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/v1/serializers.py
tests/test_enterprise/api/test_views.py

**Description:** This PR is related to https://github.com/edx/edx-platform/pull/16556 , We needed to access `identity_provider` from enterprise customer API response. This PR makes sure to provide `identity_provider` in the API response.
**JIRA:** [ENT-740](https://openedx.atlassian.net/browse/ENT-740)
**Installation instructions:** Simply install edx-enterprise using this branch
1. Open page enterprise customer details page (/enterprise/api/v1/enterprise-customer/<enterprise-customer-uuid>)
2. Make sure identity_provider field is present with appropriate value.

ENT-740: Add identity_provider to enterprise customer API  response.

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/models.py
tests/test_models.py

We do not want to generate a new password every time someone saves
an EnterpriseCustomerReportingConfiguration model.

Do not change EnterpriseCustomerReportingConfiguration.password on update.

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/admin/views.py
enterprise/api/v1/serializers.py
enterprise/api/v1/views.py
enterprise/api_client/lms.py
enterprise/models.py
enterprise/utils.py
enterprise/views.py
tests/test_admin/test_view.py
tests/test_enterprise/api/test_views.py
tests/test_enterprise/api_client/test_lms.py
tests/test_enterprise/views/test_router_view.py
tests/test_models.py

Introduces a new endpoint for enrolling a single user in a single course run for a given enterprise.
See https://github.com/edx/edx-enterprise/pull/237 for the initial prototype this is based on.
**JIRA:** https://openedx.atlassian.net/browse/ENT-742
The endpoint can be accessed using POST calls only at: {base_url}/enterprise/api/v1/enterprise-customer/{enterprise_uuid}/course_enrollments
Only users that have create access to Enterprise Customer models can hit this endpoint. This is temporary until the Authorization story is handled.
The fields to be sent in the POST data are as follows:
lms_user_id - the edX user id …

ENT-742 Enrollment API

---

CHANGELOG.rst
docs/index.rst
docs/segment_events.rst
enterprise/__init__.py
enterprise/admin/views.py
enterprise/api/v1/serializers.py
enterprise/management/commands/create_enterprise_course_enrollments.py
enterprise/signals.py
enterprise/utils.py
enterprise/views.py
package-lock.json
package.json
requirements/dev.txt
requirements/quality.txt
tests/test_admin/test_view.py
tests/test_enterprise/api/test_views.py
tests/test_enterprise/test_signals.py
tests/test_enterprise/views/test_course_enrollment_view.py
tests/test_enterprise/views/test_handle_consent_enrollment.py
tests/test_enterprise/views/test_router_view.py
tests/test_utilities.py

**Description:** This patch adds `track_event` calls to all call sites where `EnterpriseCourseEnrollment` instances get created.
**JIRA:** [ENT-744](https://openedx.atlassian.net/browse/ENT-744)
1. Install this patch & run the migration.
2. Create some enterprise course enrollments (direct from admin, pending from admin, course landing page...).
4. Verify tracking events are emitted whenever course enrollment objects get created. One way to do that is to temporarily patch the `enterprise.utils.track_event` method to log its calls.
**Author concerns:** 
There are many different flows and it is hard to capture all of them without threading a …

[ENT-744] Track enterprise course enrollment events.

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/integrated_channel/transmitters/learner_data.py

**Description:** I recently observed an exception that was triggered during the learner data transmission job.  
```
Dec  1 06:55:17 ip-10-2-70-239 [service_variant=lms][integrated_channels.integrated_channel.transmitters.learner_data][env:prod-edx-edxapp] ERROR [ip-10-2-70-239  4428] [learner_data.py:84] - Failed to send completion status call for enterprise enrollment 4995 with payload <SapSuccessFactorsLearnerDataTransmissionAudit None for enterprise enrollment 4995, SAPSF user 417218, and course course-v1:ANUx+EBM02x+2T2017>
Error message: 403 Client Error: Forbidden for url: {customer url}
```
While troubleshooting OData callback permissioning issues  a while back we determined that it was possible to capture the actual system message returned by SuccessFactors, so I'm adding that …

Log additional context in learner data transmission exceptions

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api_client/lms.py
enterprise/views.py
requirements/base.txt
requirements/dev.txt
requirements/doc.txt
requirements/js_test.txt
requirements/quality.txt
requirements/test-ficus.in
requirements/test-ficus.txt
requirements/test-ginkgo.in
requirements/test-ginkgo.txt
requirements/test-hawthorn.in
requirements/test-hawthorn.txt
requirements/test-master.in
requirements/test-master.txt
requirements/test.txt
test_utils/mixins.py
tests/test_enterprise/views/test_course_enrollment_view.py
tests/test_enterprise/views/test_program_enrollment_view.py

Redirect the user to the embargo restriction page if their access
to the given course run/program is restricted.
**JIRA:** https://openedx.atlassian.net/browse/ENT-767
**Testing Instructions:**
1. Visit https://business.sandbox.edx.org/enterprise/2b5a2956-7746-4fc9-9587-bc887ba45973/course/course-v1:edX+DemoX+Demo_Course/enroll/?catalog=cff09318-1358-4703-a277-bc2596480ed5&utm_medium=enterprise&utm_source=pied-piper.
2. Register a new account. Choose "Canada" as your country.
3. Verify that the Embargo restriction message page is displayed.

ENT-767 Check embargo restrictions when rendering enterprise landing pages.

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/utils.py
tests/test_utilities.py

**Description:** Adds from_email_address to the email notification template so we can customize the email per enterprise. Defaults to `settings.DEFAULT_FROM_EMAIL`. 
**JIRA:** https://openedx.atlassian.net/browse/WL-1373
**Merge deadline:** Soon?
**Installation instructions:** N/A
1. Migrate migrations
2. Add enterprise enrollment notification template http://localhost:18000/admin/enterprise/enrollmentnotificationemailtemplate/add/ 
3. Set from_email_address
4. Add a learner to a enterprise/course via "Manage Learners" http://localhost:18000/admin/enterprise/enterprisecustomer/<ENTERPRISE_UUID>/manage_learners
5. See new email address in email log
**Post …

Add from email address to enrollment notification template model

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/management/commands/create_enterprise_course_enrollments.py
tests/test_enterprise/management/test_create_enterprise_course_enrollments.py

This updates the create_enterprise_course_enrollment command to
allow us to identify missing EnterpriseCourseEnrollment records
and create them.
**Testing Instructions**
1. $ ssh [username]@business.sandbox.edx.org
2. $ edxapp
3. $ python manage.py lms create_enterprise_course_enrollments --settings=aws

ENT-794 Update create_enterprise_course_enrollments command.

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/migrations/0035_auto_20171212_1129.py
enterprise/models.py
test_utils/__init__.py
tests/test_models.py

If publish_audit_enrollment_url flag is True on EnterpriseCustomerCatalog
courses will be published with the direct-to-audit querystring url (?audit=true)
https://openedx.atlassian.net/browse/ENT-738
1. In django-admin, update an EnterpriseCustomerCatalog to set the publish_audit_enrollment_url flag
2. Run the transmit_course_metadata admin job
3. From the LMS set up to use the catalog from step 1, verify that when a user clicks through a course they are taken directly to the course (based on direct-to-audit work done in https://openedx.atlassian.net/browse/ENT-738)
solutions, hacks, quick-and-dirty …

ENT-738 Added publish_audit_enrollment_url flag

---

CHANGELOG.rst
api-compact.yaml
api.yaml
enterprise/__init__.py

This adds the swagger specification for the course_enrollments API
endpoint so that this endpoint can be made accessible via the
API gateway.
The only feasible way to test this is to get it merged, update the api-manager swagger doc to point to the new git hash, and then deploy api-manager to stage. I'm going to merge this when the tests pass.

ENT-809 Add swagger spec for course_enrollments API endpoint.

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/admin/views.py
enterprise/models.py

**Description:** We discovered that proxy enrollment emails sent from prod weren't getting the host name properly filled in because it was trying to read from site configuration. So now we're sending a sensible default.
**JIRA:** 
instructions.

ENT-806 Make sure root url has a fallback for proxy enrollment email links

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/templates/enterprise/grant_data_sharing_permissions.html

**Description:** For some reason, this worked in the past and now it stopped working. I'm just correcting the Javascript syntax and moving on.
1. Visit https://business.sandbox.edx.org/enterprise/2b5a2956-7746-4fc9-9587-bc887ba45973/course/course-v1:edX+DemoX+Demo_Course/enroll/.
2. Login as alterego/alterego.
3. Click continue on the course enrollment landing page.
4. Verify that you can reject consent on the DSC page.

Add quotes to fix Javascript syntax in Django template.

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/templates/enterprise/base.html

**Description:** Bootstrap.js relies on popper.js. In order to fix some bundling issues, we've switched to using the combined bootstrap + popper file now. bootstrap.js and popper.js are no longer in the CDN which is causing 404s and some pages to fail.
**JIRA:** N/A
**Merge deadline:** Soon?
**Installation instructions:** N/A
1. Open any enterprise page on stage/prod and see 404s
2. Merge this fix
3. No longer see those 404s
**Author concerns:** 
Hard to test the failures except or stage or prod as Doug said the old files are still working on sandboxes.

Update enterprise to use new bundled bootstrap libary

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/decorators.py
test_utils/mixins.py
tests/test_decorators.py
tests/test_enterprise/views/test_course_enrollment_view.py
tests/test_enterprise/views/test_handle_consent_enrollment.py
tests/test_enterprise/views/test_program_enrollment_view.py

Forcing a fresh edX session should not be optional when users are
accessing the enrollment landing pages. This removes the option.
**Related PRs**
https://github.com/edx/edx-platform/pull/16987 which I will update with the edx-enterprise version bump once this PR merges.
**Testing Instructions**
1. Clear your browser cookies.
2. Login to https://business.sandbox.edx.org with known user credentials.
3. Open new browser tab and visit https://business.sandbox.edx.org/enterprise/2b5a2956-7746-4fc9-9587-bc887ba45973/course/course-v1:edX+DemoX+Demo_Course/enroll/.
4. Login via Testshib.
5. Verify you are taken to either the registration or login page.
6. Refresh the first browser tab and verify that you are taken to the login page.

ENT-779 Remove references to ProviderConfig.drop_existing_session.

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/management/commands/save_enterprise_customer_users.py
tests/test_enterprise/management/test_save_enterprise_customer_users.py

We need to be able to back-populate enterprise data on
SailThru users. The easiest way to do this is to run
through all EnterpriseCustomerUsers and save them which
will cause a signal receiver in LMS to fire off tasks
for updating the SailThru user via the SailThru API.
1. Shell into business.sandbox.edx.org.
2. $ edxapp
3. $ python manage.py lms save_enterprise_customer_users --settings=aws

ENT-799 Add save_enterprise_customer_users command.

---

integrated_channels/integrated_channel/management/commands/__init__.py
tests/test_management.py

Do not execute channel jobs for inactive enterprise customer profiles	
https://openedx.atlassian.net/browse/ENT-784
1. In django admin, disable an enterprise customer
2. Run the transmit_course_metadata_task
3. Verify in the logs this message no longer is displayed for the customer `Processing course runs for integrated channel using configuration: [<XXXXXXEnterpriseCustomerConfiguration for COMPANY>]`

ENT-784 Added check for active companies when getting channels

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/admin/__init__.py
enterprise/admin/forms.py
enterprise/api/v1/serializers.py
enterprise/migrations/0036_sftp_reporting_support.py
enterprise/models.py
tests/test_admin/test_forms.py
tests/test_models.py

**Description:** This PR adds the ability to configure the EnterpriseCustomerReportingConfig for SFTP. It finally utilizes the delivery method field, which now has sftp in addition to email. It also adds 5 new fields for sftp: hostname, port, username, password, and file path. These fields are required when sftp is selected as the delivery method. The sftp password field is stored encrypted in the database, just as the existing password field is.
Additionally, this PR now enables editing of the existing password field as well as the sftp password. After migrations are run, the existing decrypted password display will be replaced by a text box that displays the decrypted password, and making changes to the password in the text box will be updated on save just as any other field.
Finally, …

ENT-775 Add sftp configuration support for EnterpriseCustomerReportingConfig

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/views.py

When the waffle switch for localized currency is enabled, this will update the display price on the enterprise landing page so it displays in the users local currency based on their ip address
https://openedx.atlassian.net/browse/ENT-763
1. Using a new session (log out of any existing lms session) utilize a VPN to access a course through one of the LMS channels (ie. SuccessFactors) from another country (ie. Canada)
2. Verify the landing page has the price updated in the users local currency.
3. Turn off waffle switch and verify the currency is in USD
4. Turn on waffle switch and disable the VPN, verify the currency shows in USD.
Requires https://github.com/edx/edx-platform/pull/17153

ENT-763 Show pricing in local currency

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/integrated_channel/exporters/course_metadata.py
tests/test_integrated_channels/test_degreed/test_exporters/test_course_metadata.py
tests/test_integrated_channels/test_sap_success_factors/test_exporters/test_course_metadata.py

@asadiqbal08 @saleem-latif @georgebabey 
**Description:** Include start date in all course runs title when pushing to Integrated Channels.
**JIRA:** [ENT-842](https://openedx.atlassian.net/browse/ENT-842)
**Merge deadline:** 26-Jan-2018
**Installation instructions:** Install `edx-enterprise` from this branch `zub/ENT-842-include-start-date-in-course-runs-title` in `edx-platform`.
1. Add enterprises with catalogs
1. Add configurations for integrated channels for `Degreed` and `SAP Success Factors`
2. Run django management command `transmit_course_metadata` and verify that all course runs (including both `instructor-paced` and `self-paced`) have start date in their title with the format `edX Demonstration Course (Starts: February 2013)` …

ENT-842 Include start date in all course runs title

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/admin/__init__.py
enterprise/admin/forms.py
enterprise/migrations/0037_auto_20180110_0450.py
enterprise/models.py
enterprise/utils.py
tests/test_admin/test_forms.py

**Description:** Django admin EnterpriseCustomer Fields formatting.
**JIRA:** [ENT-840](https://openedx.atlassian.net/browse/ENT-840)
1. Visit EnterpriseCustomer [admin page](https://business.sandbox.edx.org/admin/enterprise/enterprisecustomer/8087b663-78bd-421e-8117-74eb03d22741/) to see the changes listed in ticket.

[ENT-840] EnterpriseCustomer Fields formatting

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api_client/lms.py
enterprise/constants.py
tests/test_enterprise/api_client/test_lms.py

1. Visit https://business.sandbox.edx.org/enterprise/2b5a2956-7746-4fc9-9587-bc887ba45973/course/course-v1:edX+DemoX+Demo_Course/enroll/?catalog=cff09318-1358-4703-a277-bc2596480ed5.
2. Create new account.
3. Verify the course enrollment page does not list a credit option.

ENT-846 Do not display credit mode on course enrollment page.

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/renderers.py
enterprise/api/v1/views.py
requirements/base.in
tests/test_enterprise/api/test_views.py

**Description:** Provided option for enterprise to pull enterprise/catalog API in XML format (not just JSON)
**JIRA:** [ENT-849](https://openedx.atlassian.net/browse/ENT-849)
- Hit [enterprise catalog api](https://business.sandbox.edx.org/enterprise/api/v1/enterprise_catalogs/) on business sandbox.
- By default, JSON response would be returned. 
- To get an xml response, Add the suffix **.xml** at the end of URL --> e.g. https://business.sandbox.edx.org/enterprise/api/v1/enterprise_catalogs.xml . An xml response would be returned

asadiqbal08/ENT-849 enterprise catalog API in XML format.

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/sap_success_factors/exporters/course_metadata.py

Per SAP technical support, while the SuccessFactors Learning API does support payloads up to 1000 records per request, this is too much data for most tenants to handle in a single request.  SAPSF recommends sending no more than 500 records per request.

Decrease SAPSF chunk size from 1000 to 500

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/v1/serializers.py
enterprise/migrations/0041_auto_20180212_1507.py
enterprise/models.py
requirements/base.in
requirements/dev.txt
requirements/doc.txt
requirements/js_test.in
requirements/js_test.txt
requirements/quality.txt
requirements/test-ficus.txt
requirements/test-ginkgo.txt
requirements/test-hawthorn.txt
requirements/test-master.txt
requirements/test.txt
requirements/travis.txt
tests/test_enterprise/api/test_views.py

**Description:** Introduces a new field in the reporting configuration admin page to support multiple email input. Also included is a change to the verification such that an email is required only when the delivery method is set to "email." [Related PR](https://github.com/edx/edx-enterprise-data/pull/21) for `edx-enterprise-data`.
**JIRA:** [ENT-833](https://openedx.atlassian.net/browse/ENT-833)
1. Open the Enterprise Django admin, and navigate to the reporting configurations.
2. Verify that it's possible to add/save multiple emails (one per line).
3. Ensure that an email is required only when "email" is selected as the delivery method.
4. Verify that the email field returned by the [`enterprise_customer_reporting` API …

ENT-833 Support sending data reports to multiple emails

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/integrated_channel/exporters/course_metadata.py
tests/test_integrated_channels/test_sap_success_factors/test_exporters/test_course_metadata.py

@asadiqbal08 @saleem-latif @georgebabey 
**Description:** Indicate when a course is no longer open for enrollment by adding the message `Enrollment Closed` in the title along with the start date with the format `edX Demonstration Course (February 2013 - Enrollment Closed)`.
* The enrollment is considered closed when a course is Archived
* Course run `enrollment_end` is less than now if `enrollment_end` is set 
* Current date for course run is not between `enrollment_start` and `enrollment_end` date if both `enrollment_start` and `enrollment_end` are set 
**JIRA:** [ENT-850](https://openedx.atlassian.net/browse/ENT-850)
**Related PR:** https://github.com/edx/edx-enterprise/pull/283
**Merge deadline:** 23 Mar, 2018
**Installation instructions:**  Install …

ENT-850 Update course title on the basis of enrollment start and end dates

---

CHANGELOG.rst
api-compact.yaml
api.yaml
consent/models.py
enterprise/__init__.py
enterprise/api/v1/serializers.py
enterprise/api/v1/views.py
enterprise/api_client/discovery.py
enterprise/constants.py
enterprise/models.py
enterprise/urls.py
enterprise/utils.py
enterprise/views.py
test_utils/__init__.py
test_utils/fake_catalog_api.py
test_utils/fake_enterprise_api.py
tests/test_decorators.py
tests/test_enterprise/api/test_views.py
tests/test_enterprise/views/test_course_enrollment_view.py
tests/test_enterprise/views/test_router_view.py
tests/test_models.py
tests/test_utilities.py

This will enable us to define EnterpriseCustomerCatalogs with a `"content_type": "course"` content filter and provide a way for direct integrators to pull the full details for each course in the catalog (including course run data).
I have a [WIP branch](https://github.com/edx/edx-enterprise/pull/293) which refactors the `integrated_channels` codebase to allow it to manage content metadata for more than just course runs (which is what it is limited to currently). I'd like to get these changes merged as I continue to work on that refactoring.
1. Visit https://business.sandbox.edx.org/enterprise/api/v1/enterprise_catalogs/f8f13d0b-58a1-4708-b1be-6accc88acfb1/. This is the detail endpoint for an EnterpriseCustomerCatalog which uses the `"content_type": "course"` content filter.
2. Grab a …

ENT-823 Add course detail endpoint to EnterpriseCustomerCatalog API.

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/admin/views.py
enterprise/templates/enterprise/admin/manage_learners.html
tests/test_admin/test_view.py

**Sandox**
https://business.sandbox.edx.org/admin/enterprise/enterprisecustomer/2b5a2956-7746-4fc9-9587-bc887ba45973/manage_learners

ENT-916 Temporarily disable linked learners list on manage learners Django admin page for performance reasons.

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/admin/views.py
tests/test_admin/test_view.py

@georgebabey @brittneyexline FYI. 
**Description:** Enterprise Django admin tool not loading correctly in manage learner form.
**JIRA:** [ENT-947](https://openedx.atlassian.net/browse/ENT-947)
1. Login to django admin tool on business sandbox. 
2. Visit manage learner tool under enterprise customer view e.g. [example](https://business.sandbox.edx.org/admin/enterprise/enterprisecustomer/905a19f5-a9a7-406f-8c24-d5f04eecef1e/manage_learners)
3. Add data in Link Learners form.
4. Press submit. Page should be rendered properly on both Chrome and Firefox

[ENT-947] Enterprise Django admin tool not loading correctly

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/models.py
enterprise/tpa_pipeline.py
enterprise/views.py
package-lock.json
package.json

**Description:** This PR will allow the request session to update with the latest Enterprise Customer for the user that just became an Enterprise user.
**JIRA:** https://openedx.atlassian.net/browse/ENT-962
**Dependencies:** https://github.com/edx/edx-platform/pull/17969
**Merge deadline:** ASAP.
See https://github.com/edx/edx-platform/pull/17969
However in addition, you'll want to see that your request session is updated when your user becomes linked to an Enterprise through some request.
1. Go to `/enterprise/{enterprise_uuid}/course/{course_run_key}/enroll/`.
2. After going through the process, your user should be linked and that data should be in the session. If the customer had `replace_sensitive_sso_username` on, this'll give you a new username on the …

[ENT-962] Update sessions whenever Enterprise Customer is created.

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/migrations/0043_auto_20180507_0138.py
enterprise/models.py

Since updating to Django 1.11 we are getting a number of warnings in the log:
UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: `<class 'enterprise.models.EnterpriseCustomerUser'>` QuerySet
This PR fixes this by adding ordering to our ViewSets that don't include it already.
**JIRA:** [ENT-965](https://openedx.atlassian.net/browse/ENT-965)
**Installation instructions:**
Simply Install edx-enterprise with this branch.
1. Open all the enterprise API endpoints one by one, API endpoints are listed below
- https://business.sandbox.edx.org/enterprise/api/v1/enterprise_catalogs/
- https://business.sandbox.edx.org/enterprise/api/v1/enterprise-course-enrollment/
- …

ENT-965: Added order_by on queries inside view set to resolve Pagination warning.

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/v1/permissions.py
enterprise/api/v1/views.py
test_utils/factories.py
tests/test_enterprise/api/test_permissions.py
tests/test_enterprise/api/test_views.py

**Description:** Update enrollment api authorization to check group permissions
**JIRA:** [ENT-958](https://openedx.atlassian.net/browse/ENT-958)
Testing Instructions: 
1. Go to admin portal on [sandbox ](http://business.sandbox.edx.org/admin/) and add a new group with name **enterprise_enrollment_api_access**.
2. Hit the [course_enrollments](https://business.sandbox.edx.org/enterprise/api/v1/enterprise-customer/0a35930c-168c-4955-886c-db99eb699007/course_enrollments/) API endpoint via using Postman tool or the normal flow. 
3. Try to execute the following test cases. 
- If a user is not staff or not belong to 'enterprise_enrollment_api_access' group then permission denied should be raised with a message u"User is not allowed to access the view."
- A staff user or a user belong to …

[ENT-958]Update enrollment api authorization to check group permissions

---

AUTHORS
CHANGELOG.rst
enterprise/__init__.py
enterprise/admin/__init__.py
enterprise/migrations/0049_auto_20180531_0321.py
enterprise/models.py
tests/test_models.py

ENT-897
**Description:** update EnterpriseCustomerCatalog model and admin 
* Increased character limit from 20 to 255 for field `title` in `EnterpriseCustomerCatalog` model 
* Reorder list display for `EnterpriseCustomerCatalogAdmin`
* Add sorting order for `EnterpriseCustomerCatalogAdmin`
**JIRA:** https://openedx.atlassian.net/browse/ENT-897
TBD

update EnterpriseCustomerCatalog model and admin

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/views.py

The direct-to-audit enrollment feature does not appear to work for enrollment URLs containing a Course identifier. After doing some investigation, I came to know that, the following condition is returning False in case of course key instead of course_run_id. [eligible_for_direct_audit_enrollment](https://github.com/edx/edx-enterprise/blob/master/enterprise/views.py#L1386)
> request.path == self.COURSE_ENROLLMENT_VIEW_URL.format(enterprise_customer.uuid, course_run_id)
**JIRA:** [ENT-995](https://openedx.atlassian.net/browse/ENT-995)

[ENT-995] Fix the Direct-to-Audit enrollment issue in case of course.

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/sap_success_factors/admin/__init__.py
integrated_channels/sap_success_factors/exporters/content_metadata.py
integrated_channels/sap_success_factors/migrations/0016_sapsuccessfactorsenterprisecustomerconfiguration_additional_locales.py
integrated_channels/sap_success_factors/models.py
tests/test_models.py

ENT-1027
Add and transmit customer specific locales so that SuccessFactors show course title and description.
**JIRA:** https://openedx.atlassian.net/browse/ENT-1027
1. Set the locale other than `English` for a `user` on SuccessFactors, for example, `Japanese`
2. Do not add `Japanese` in `Additional Locales` field for a `success factors enterprise customer configuration`.
3. Then transmit the data from enterprise customer admin interface.
4. Login with `admin` user on SuccessFactors and import the course and add it `user` assigned tasks.
5. Login with`user` on SuccessFactors, open the imported course and you should not see the course `title` and `description`
6. Now add `Japanese` in `Additional Locales` field.
7. Transmit the data again and now …

SuccessFactors: Support customer-specific default locales

---

CHANGELOG.rst
enterprise/__init__.py
requirements/dev.txt
requirements/doc.in
requirements/doc.txt
requirements/js_test.txt
requirements/quality.txt
requirements/test-ficus.in
requirements/test-ficus.txt
requirements/test-ginkgo.in
requirements/test-ginkgo.txt
requirements/test-hawthorn.in
requirements/test-hawthorn.txt
requirements/test-master.in
requirements/test-master.txt
requirements/test.txt
requirements/travis.txt
tests/test_enterprise/api/test_views.py

**Description:** I wasn't able to run make upgrade and make requirements in order to run manage.py to make migrations, so I went down a rabbit hole that led to pinning readme_renderer in doc.in and html5lib in the release.in files. This is all to keep us at bleach==1.4, which is what edx-platform is pinned to.
**JIRA:** In service of ENT-1006, but not directly related.
**Merge deadline:** soon?
Pull this repo, checkout this branch. Create a virtual environment and run `make upgrade`, then `make requirements`. There should be no errors.
solutions, …

ENT-1006 Fixing requirements snafoo

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/admin/__init__.py
enterprise/admin/forms.py
enterprise/migrations/0051_add_enterprise_slug.py
enterprise/migrations/0052_create_unique_slugs.py
enterprise/models.py
requirements/dev.in
requirements/dev.txt
requirements/js_test.txt
requirements/quality.txt
requirements/travis.in
requirements/travis.txt
test_utils/factories.py
tests/test_admin/test_forms.py
tests/test_utilities.py

**Description:** Adding slug field to enterprise customer model
**JIRA:** https://openedx.atlassian.net/browse/ENT-1007
Go to the business sandbox, where the migrations have been run, and see that the slugs are populated.

ENT-1007 Adding slug field to enterprise customer model

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/admin/paginator.py
enterprise/admin/utils.py
enterprise/admin/views.py
enterprise/constants.py
enterprise/templates/enterprise/admin/manage_learners.html
tests/test_admin/test_view.py

**Description:** The purpose of this PR is to add pagination support to linked learners list on manage learners admin view.
1. Open Enterprise customer detail view.
2. Click manage learners
3. Expect linked learners list to be paginated.

Paginate linked learners on manage learners admin view - ENT-933

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/v1/serializers.py
enterprise/api/v1/views.py
test_utils/__init__.py
test_utils/factories.py
tests/test_enterprise/api/test_views.py

**Description:** We need an api that takes the enterprise slug and returns the branding config. The existing branding config api isn't used and lists details by id, but we would rarely ever know the specific branding config id, so I changed it to use enterprise slug.
**JIRA:** https://openedx.atlassian.net/browse/ENT-1008
Hit the following endpoint on the business sandbox using JWT authentication: https://business.sandbox.edx.org/enterprise/api/v1/enterprise-customer-branding/
This should list all branding configs and now include the enterprise slug.
Then hit https://business.sandbox.edx.org/enterprise/api/v1/enterprise-customer-branding/aviato
(or use any enterprise slug value you wish) …

ENT-1008 Modify branding config api to look up by enterprise slug

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api_client/ecommerce.py
enterprise/templates/enterprise/enterprise_course_enrollment_page.html
enterprise/views.py
tests/test_enterprise/views/test_course_enrollment_view.py
tests/test_enterprise/views/test_handle_consent_enrollment.py

@asadiqbal08 @saleem-latif @muhammad-ammar @irfanuddinahmad @georgebabey 
**Description:** Add/Show discount for enterprise learners by provided valid enterprise catalog UUID.
**JIRA:** [ENT-1052](https://openedx.atlassian.net/browse/ENT-1052)
**Remaining tasks:** Unittests
1. edx-platform: https://github.com/edx/edx-platform/pull/18470
2. Ecommerce: https://github.com/edx/ecommerce/pull/1830
**Merge deadline:** 29 Jun 2018
1. Checkout edx-platform to branch `zub/ENT-1052-discount-by-enterprise-catalog`.
2. Install `edx-enterprise` from this branch `zub/ENT-1052-discount-by-enterprise-catalog` in `edx-platform`.
3. Checkout ecommerce to  branch `zub/ENT-1052-discount-by-enterprise-catalog`.
4. In ecommerce django admin …

ENT-1052 discount by enterprise catalog

---

enterprise/api_client/ecommerce.py
enterprise/templates/enterprise/enterprise_course_enrollment_page.html
enterprise/views.py
tests/test_enterprise/views/test_course_enrollment_view.py
tests/test_enterprise/views/test_handle_consent_enrollment.py

**Description:** Add/Show discount for enterprise learners by provided valid enterprise catalog `UUID`. This enterprise catalog `UUID` can be provided by passing the queryparam `catalog={enterprise_catalog_uuid}` to enterprise course enrollment urls.
**JIRA:** [ENT-1052](https://openedx.atlassian.net/browse/ENT-1052)
1. edx-platform: https://github.com/edx/edx-platform/pull/18508
2. ecommerce: https://github.com/edx/ecommerce/pull/1844/
**Installation instructions:**  
1. Checkout edx-platform to branch `zub/ENT-1052-rename-enterprise-customer-catalog-uuid-queryparam`.
2. Install `edx-enterprise` from branch `zub/ENT-1052-rename-enterprise-customer-catalog-uuid-queryparam` in `edx-platform`.
3. Checkout ecommerce to branch …

ENT-1052 Rename enterprise customer catalog uuid in queryparam to catalog

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/degreed/exporters/learner_data.py
integrated_channels/integrated_channel/exporters/learner_data.py
integrated_channels/integrated_channel/transmitters/learner_data.py
integrated_channels/sap_success_factors/exporters/learner_data.py
tests/test_integrated_channels/test_degreed/test_exporters/test_learner_data.py
tests/test_integrated_channels/test_integrated_channel/test_exporters/test_learner_data.py
tests/test_integrated_channels/test_sap_success_factors/test_transmitters/test_learner_data.py
tests/test_management.py

**Description:** Since we have started sending courses to SuccessFactors instead of course runs, we need to attempt to send transmissions with course keys and course run ids in order to ensure that we account for whether courses or course runs exist in the SuccessFactors instance. If the transmission with the course key succeeds, the next one will get skipped. If it fails, the one with the course run id will be attempted and (presumably) succeed.
**JIRA:** https://openedx.atlassian.net/browse/ENT-1074
**Testing instructions:** 
I've _sort of_ tested this on the business sandbox, but I am having issues testing the successful transmission of course key because a content object with a course key doesn't seem to …

ENT-1074 Attempt to send SAPSF learner data transmissions with course keys first

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/templates/enterprise/enterprise_course_enrollment_page.html

**Description:** Add/Show discount for enterprise learners by provided valid enterprise catalog `UUID`. This enterprise catalog `UUID` can be provided by passing the queryparam `catalog={enterprise_catalog_uuid}` to enterprise course enrollment urls. If catalog `UUID` is provided in course enrollment url then the default enterprise coupon (first enterprise offer) will be applied.
**JIRA:** [ENT-1052](https://openedx.atlassian.net/browse/ENT-1052)
1. ecommerce: https://github.com/edx/ecommerce/pull/1851
**Installation instructions:**  
1. Checkout edx-platform to branch ``.
2. Install `edx-enterprise` from branch `zub/ENT-1052-pass-catalog-input-only-when-provided` in `edx-platform`.
3. Checkout ecommerce to branch ``.
4. In ecommerce django admin (admin/waffle/switch/) …

ENT-1052 pass catalog value only when provided

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/admin/__init__.py
enterprise/constants.py
enterprise/models.py
enterprise/settings/test.py
enterprise/utils.py
test_utils/factories.py
tests/test_models.py

[ENT-1070](https://openedx.atlassian.net/browse/ENT-1070)
This PR adds a default content filter value to `EnterpriseCustomerCatalog` model, which is configurable by open edX.
Related platform PR: https://github.com/edx/edx-platform/pull/18551
[Business Sandbox Admin URL](https://business.sandbox.edx.org/admin/enterprise/enterprisecustomercatalog/add)

Change default content filter to include only courses

---

enterprise/admin/__init__.py

UI of enterprise customer catalog model updated for long enterprise customer names.
**JIRA:** 
https://openedx.atlassian.net/browse/ENT-1100
1. Open https://business.sandbox.edx.org/admin/enterprise/enterprisecustomercatalog/
2. Verify that UUID field is not wrapped

ENT-1100: UI of enterprise customer catalog model updated for long enterprise customer names.

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/messages.py
tests/test_enterprise/views/test_course_enrollment_view.py

Gracefully handle invalid Enterprise Customer Catalog references in B2B enrollment workflow
**JIRA:** 
https://openedx.atlassian.net/browse/ENT-1092
**Test Instructions:**
1: Hit a course run URL with an invalid catalog UUID, or a catalog which doesn't exist for the provided enterprise.
2: Verify that the following message is returned:
"This course link is currently invalid. Please reach out to your Administrator for assistance to this course."

ENT-1092 Gracefully handle invalid Enterprise Customer Catalog references in B2B enrollment workflow

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/degreed/exporters/content_metadata.py
integrated_channels/sap_success_factors/exporters/content_metadata.py
tests/test_integrated_channels/test_degreed/test_exporters/test_content_metadata.py
tests/test_integrated_channels/test_sap_success_factors/test_exporters/test_content_metadata.py

**Description:** For `SAP SuccessFactors` add thumbnail images in exported metadata content by content type. Previously we were unable to fetch the image url as the content structure we were expecting earlier was changed due to modified endpoints. 
**JIRA:** [ENT-1067](https://openedx.atlassian.net/browse/ENT-1067)
**Installation instructions:** Install `edx-enterprise` from branch `zub/ENT-1067-add-courses-thumbnail-uri` in `edx-platform`.
1. Create an enterprise with a catalog which contains different content types, e.g. `course`, `course_run` and `program` and also make sure that each content type item have images (`image_url` or `card_image_url`) set in course discovery service.
2. Create integrated channel for SAP Success Factors and …

ENT-1067 SuccessFactors: Fetch image url base on content type

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/v1/permissions.py
enterprise/api/v1/serializers.py
enterprise/api/v1/views.py
enterprise/constants.py
tests/test_enterprise/api/test_permissions.py
tests/test_enterprise/api/test_views.py

**JIRA:** https://openedx.atlassian.net/browse/ENT-1125
**Testing instructions:** 
Deployed on the business sandbox.
Using a staff user, hit the following endpoint: https://business.sandbox.edx.org/enterprise/api/v1/enterprise-customer/with_access_to?permissions=enterprise_enrollment_api_access
A list of all the enterprises should get returned.
Using a non-staff, enterprise "admin" user that is part of the enterprise_enrollment_api_access group, hit the same endpoint. You should only get only the enterprise that is linked to the user back.
If you use a non-staff user who is not linked to any enterprise but happens to have group membership, the result should be an empty list of enterprises.
If …

ENT-1125 Adjustments/additions to enterprise api around django group access

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/xapi/serializers.py
tests/test_integrated_channels/test_xapi/test_serializers.py

Write utility functions/serializers to collect learner and enrollment data that would be sent as part of the xAPI statement.
**JIRA:** [ENT-1083](https://openedx.atlassian.net/browse/ENT-1083)
**Dependencies:**  https://github.com/edx/edx-enterprise/pull/328

[ENT-1083]: Write Serializer to Collect Learner and Enrollment data

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/degreed/admin/__init__.py
integrated_channels/degreed/client.py
integrated_channels/degreed/migrations/0005_auto_20180807_1302.py
integrated_channels/degreed/models.py
test_utils/factories.py
tests/test_integrated_channels/test_degreed/test_client.py
tests/test_management.py

**Description:** Some of the fields we placed on the global configuration can change from customer to customer, so they need to be moved to the customer specific configuration.
**JIRA:** https://openedx.atlassian.net/browse/ENT-1135
On the sandbox, change the catalog query of the Degreed catalog, so that a different set of courses are in the catalog. Check the integrated_channel_contentmetadataitemtransmission table to see what content has been transmitted already to Degreed.
Run the transmit course metadata command:
`$ ./manage.py lms --settings=aws transmit_content_metadata --catalog_user=staff`
Inspect the integrated_channel_contentmetadataitemtransmission table to see that courses …

ENT-1135 Move fields from DegreedGlobalConfiguration to DegreedEnterpriseCustomerConfig

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/management/commands/create_enterprise_course_enrollments.py

ENT-1149: Include all potentially-applicable enrollment records in management command query
**Description:** Revises query to better-match CourseEnrollment records which should have corresponding EnterpriseCourseEnrollment records, but do not.
**JIRA:** https://openedx.atlassian.net/browse/ENT-1149
1. Connect to read replica database
2. Run the original query
3. Run the new query
4. Observe recordset that is orders of magnitude larger for new query vs. old query
5. Decide if new query is returning more accurate results vs. old query

ENT-1149: Include all potentially-applicable enrollment records in management command query

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/utils.py
integrated_channels/xapi/management/__init__.py
integrated_channels/xapi/management/commands/__init__.py
integrated_channels/xapi/management/commands/send_course_completions.py
integrated_channels/xapi/management/commands/send_course_enrollments.py
integrated_channels/xapi/serializers.py
integrated_channels/xapi/statements/base.py
integrated_channels/xapi/utils.py
test_utils/__init__.py
tests/test_integrated_channels/test_utils.py
tests/test_integrated_channels/test_xapi/test_commands/test_send_course_completions.py
tests/test_integrated_channels/test_xapi/test_commands/test_send_course_enrollments.py
tests/test_integrated_channels/test_xapi/test_serializers.py
tests/test_integrated_channels/test_xapi/test_utils.py

Write management commands to send xAPI statements.
These management commands would iterate through all xAPI configurations and be sending learner enrollment and course completion data for each configuration and its associated enterprise customer.
**JIRA:** [ENT-1082](https://openedx.atlassian.net/browse/ENT-1082)

ENT-1082:  Added management command to send course enrollment info.

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/v1/permissions.py
enterprise/api/v1/views.py
tests/test_enterprise/api/test_permissions.py
tests/test_enterprise/api/test_views.py

**Description:** We now need to restrict data api access for staff users on the basis of their group membership. To do this, there is a new permission class that only checks the user's group membership, regardless of whether or not they are staff. The with_access_to endpoint will use this new permission class and rely on the existing filtering to provide the correct list of enterprises for the user, so staff users will still see all enterprises whereas enterprise users will only see what they are linked to. Filtering on the name or enterprise id has also been included to accommodate the portal frontend, as well as the data api itself which will be modified to use the with_access_to endpoint.
**JIRA:** https://openedx.atlassian.net/browse/ENT-1177 …

ENT-1177 Modifying permissions and with_access_to to restrict staff user access

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/models.py

**Description:** Remove the SailThru Flags for enterprise learner. 
**JIRA:** [ENT-769](https://openedx.atlassian.net/browse/ENT-769)
**Testing Instructions:**
1. Go to login page and signin with third party auth e.g. TestShib 
2. Go to enterprise customer -> [Manage learner screen](https://business.sandbox.edx.org/admin/enterprise/enterprisecustomer/2f4235e7-c3e9-40ec-8d91-a7af697e4ea8/manage_learners) in Django admin. You see the user (that linked above) is linked with the Enterprise customer. 
3. After signing with identity provider, Go to user linked account screen and you can see user is linked with the provider account. 
4. In that screen, click on the "Unlink This Account" button and visit the enterprise customer -> Manage learner screen in Django admin again. You will see the user …

ENT-769 Remove SailThru Flags

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/admin/forms.py
enterprise/utils.py
tests/test_admin/test_forms.py
tests/test_decorators.py
tests/test_utilities.py

This PR fixes the 500 error on enterprise customer admin screen.
I have moved the imports from top to inside method definition because otherwise `ImportError` is raised and that causes the issues we are seeing.
**JIRA:** [ENT-1211](https://openedx.atlassian.net/browse/ENT-1211)
**Installation instructions:** Simply install edx-enterprise through this branch.
1. Open enterprise customer details page.
2. Try to update "ENTERPRISE CUSTOMER IDENTITY PROVIDERS"
3. Make sure dropdown menu is displayed instead of the text field
4. Make sure adding/updating identity provider is not throwing errors.
**Author concerns:** This is a quick fix to the CAT-2 …

ENT-1211: Fixed 500 error on enterprise customer screen.

---

enterprise/api/v1/serializers.py
enterprise/api_client/lms.py
enterprise/models.py
tests/test_enterprise/api/test_views.py
tests/test_enterprise/api_client/test_lms.py

**Description:** Adds an optional field, ``is_active`` to support unenrollment in the course-enrollments endpoint.
instructions.
1. Open page A
2. Do thing B

Added the ability to unenroll in the enrollment API

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/v1/views.py
tests/test_enterprise/api/test_views.py

This PR adds the ability to filter the with_access_to call by enterprise slug. This is needed for our enterprise admin dashboard frontend.
This Builds on #366 (so that tests run) so that should merge first

ENT-1244. Add filtering by slug to with_access_to

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/sap_success_factors/transmitters/content_metadata.py
tests/test_integrated_channels/test_sap_success_factors/test_transmitters/test_content_metadata.py

Currently, the edX system breaks up the set of OCN items into the specified batch/chunk size defined in a customer's SAPSuccessFactorsEnterpriseCustomerConfiguration record. The system then submits "total records/batch size" number of transactions to the SuccessFactors Learning API, one after the other. For example, given a total set of 100 records, and a batch size of 20, the edX system would submit 5 requests to the API.
Unfortunately, the SuccessFactors Learning API has a throttle constraint which currently allows for only one API request in a given cycle. So in the example above, the first request would be accepted, and the remaining four would be denied.
We keep trying to submit until we get a rate error exceeded or any error status and then will stop
**JIRA:** …

ENT-1199: SuccessFactors: Submit batch/chunk of OCN items to tenants until error status

---

enterprise/__init__.py
enterprise/api_client/discovery.py
enterprise/api_client/lms.py
enterprise/decorators.py
test_utils/fake_enterprise_api.py

**Description:** Replace usage of deprecated `JwtBuilder` class with new function in the `user_authn` Django app in edx-platform.
**JIRA:** https://openedx.atlassian.net/browse/ARCH-248

Refactor and move JwtBuilder to user_authn

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/views.py

**Description:** Enterprise Pages are not translating text according to user preferences. This PR fixes that.
**JIRA:** [ENT-1294](https://openedx.atlassian.net/browse/ENT-1294)
**Installation instructions:** Simply install this version of edx-enterprise into your LMS.
**Testing Instructions:**
- Go to enterprise landing page [here](https://business.sandbox.edx.org/enterprise/d583b097-7bd9-4a7e-a98d-c15dea220354/course/course-v1%3AedX%2BDemoX%2BDemo_Course/enroll/?new_enterprise_login=yes&tpa_hint=saml-bestrun)
- Login with the following credentials `edx_learner497:test123test`
- Make sure available translations are appearing
- If translations are not appearing make sure `Spanish` is selected as language in the [account settings page](https://business.sandbox.edx.org/account/settings) …

ENT-1294:  Fix translations for enterprise pages.

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/urls.py
enterprise/api/v1/urls.py
enterprise/api/v1/views.py
enterprise/apps.py
enterprise/errors.py
tests/test_enterprise/api/test_views.py

**Description:** An API to “Request More Codes”. This will trigger a notification to customersuccess@edx.org
**JIRA:** https://openedx.atlassian.net/browse/ENT-1169
1. Use any REST client to POST to ... enterprise/api/v1/request_codes
2. Test with and without the following json object
{
"email": "bob@alice.com",
"enterprise_name": "IBM",
"number_of_codes": "50"
}
3. Expect a HTTP 200 response for correct input and email to customersuccess@edx.org
4. Expect a HTTP 400 response for incorrect input.
5. Expect a HTTP 500 response for an email send issue.

ENT-1169 Request codes api

---

enterprise/views.py

**Description:** Several exception workflows may be encountered during the process of loading EnterpriseCustomerCatalog information during the generation of the B2B course landing page.  Some of these workflows write to the system log, and some do not, which can create troubleshooting insanity.  This PR adds some logging to some of the workflows.  More logging should/can/will be added as needed.
**JIRA:** How about a [Zendesk ticket](https://edxsupport.zendesk.com/agent/tickets/917793) instead.
**Merge deadline:** Soon!
instructions.
**Testing instructions:**  I think the easiest way to test would be to hit the B2B landing page with either an invalid catalog UUID value or an invalid course key -- the …

Add logging to EnterpriseCustomerCatalog-related exception workflows.

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api_client/lms.py
tests/test_enterprise/api_client/test_lms.py
tests/test_management.py

**Description:** Updating the course grade url for the lms api (because the lms api changed)
**JIRA:** https://openedx.atlassian.net/browse/ENT-1427
**Installation instructions:** None
Verify completion events that were once failing are no longer failing (are successfully reporting).

ENT-1427 | Updating grades api call in lms client

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api_client/discovery.py
enterprise/models.py
tests/test_enterprise/api/test_views.py
tests/test_enterprise/api_client/test_discovery.py
tests/test_enterprise/views/test_course_enrollment_view.py
tests/test_models.py

**Description:** Support large catalog queries using POST.
**JIRA:** [ENT-1416
](https://openedx.atlassian.net/browse/ENT-1416)
1. [This](https://business.sandbox.edx.org/admin/enterprise/enterprisecustomercatalog/c58fad29-7221-4416-b5f9-6e8ca18cdc8c/change/) is a big catalog.
2. Open https://business.sandbox.edx.org/enterprise/api/v1/enterprise_catalogs/c58fad29-7221-4416-b5f9-6e8ca18cdc8c/contains_content_items/?course_run_ids=course-v1:UniversityX+GB123+2018_1 and the response should be 
```
<root>
<contains_content_items>True</contains_content_items>
</root>
```
3. On stage and prod, this api hit will return the below response due to very large catalog
```
<root>
<contains_content_items>False</contains_content_items>
</root>
```
**DO …

Handle large catalog queries

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/urls.py
enterprise/views.py
tests/test_enterprise/views/test_course_enrollment_view.py
tests/test_enterprise/views/test_grant_data_sharing_permissions.py
tests/test_enterprise/views/test_handle_consent_enrollment.py
tests/test_enterprise/views/test_router_view.py

**Description:** This reverts commit 6f9f95ae1992e8ba45af620983e85e4f181ae773.
**JIRA:** https://openedx.atlassian.net/browse/ENT-1467
instructions.
With the current version of edx-enterprise, attempt to redeem a coupon (https://ecommerce-business.sandbox.edx.org/coupons/offer/?code=6I74JCNLR3HO6VAP). The expected behavior should be the bug we are seeing, which is that after the user accepts DSC, they are redirected to the dashboard without being enrolled in the course.
Next, install this version of edx-enterprise, and attempt to redeem the same coupon. The redemption should …

Revert "Remove a GET side-effect from consent flow"

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/models.py
tests/test_models.py

**Description:** This PR adds the catalog uuid back into the text of its string representation.
**JIRA:** https://openedx.atlassian.net/browse/ENT-1405
**Merge deadline:** asap
instructions.
On the business sandbox, go to the Enterprise Customer edit screen. See that each attached enterprise catalog now includes the UUID in the string representation.

ENT-1405 Include Enterprise Catalog UUID in Enterprise Customer django admin inline

---

README.rst

trivial change to fix the broken 404 link to the documentation.

fix the link to the documentation which was giving a 404

---

enterprise/tpa_pipeline.py
integrated_channels/sap_success_factors/exporters/learner_data.py
tests/test_management.py

Query indexed field of UserSocialAuth model to improve performance of `unlink_inactive_sap_learners` management command
instructions.
1. Open page A
2. Do thing B

WL-1893: Query indexed field of UserSocialAuth

---

integrated_channels/sap_success_factors/client.py
integrated_channels/sap_success_factors/exporters/learner_data.py
tests/test_management.py

This PR has changes to skip any further operations if we SAPSF does not return any inactive learners. It would prevent exception raised due to unavailability of inactive learners.
instructions.
1. Open page A
2. Do thing B

WL-1895: Skip operations if we don't have any inactive learners

---

enterprise/models.py
enterprise/signals.py
tests/test_enterprise/test_signals.py
tests/test_models.py

This PR moves `default_content_filter` signal to `signals.py` where rest of the signals are placed.

Move default_content_filter to signals.py for consistency

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/constants.py
enterprise/management/commands/assign_enterprise_user_roles.py
tests/test_management.py

This PR creates a management command that assigns enterprise roles to existing enterprise users.
1. This will  find existing users with `enterprise_data_api_access` django group and assigns an `enterprise_admin` role to them.
2. This also assigns existing `EnterpriseCustomerUsers` an `enterprise_learner` role.
**JIRA:** 
https://openedx.atlassian.net/browse/ENT-1685
Main ticket: https://openedx.atlassian.net/browse/ENT-1554

Assign enterprise roles to existing enterprise users

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/signals.py
tests/test_enterprise/test_signals.py
tests/test_management.py
tests/test_models.py

This PR creates a `post_save` signal that will assign a enterprise learner role to EnterpriseCustomerUser whenever a new record is created.
*JIRA:** 
https://openedx.atlassian.net/browse/ENT-1686
Main ticket: https://openedx.atlassian.net/browse/ENT-1554

Assign an enterprise learner role to EnterpriseCustomerUser

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/management/commands/assign_enterprise_user_roles.py
tests/test_management.py

The purpose of this PR is to add the capability to assign enterprise operator role to staff users with `enterprise_data_api_access` group in `assign_enterprise_user_roles` management command.
[ENT-1736](https://openedx.atlassian.net/browse/ENT-1736)

Assign edx enterprise operator role

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/admin/views.py
test_utils/fake_enrollment_api.py
tests/test_admin/test_view.py

Provide customer success team ability to add ECE records via "Manage Learners" admin tool
If Enrollment window is closed and there is already a SCE(student CourseEnrollment) record.
**JIRA:** [WL-1908](https://openedx.atlassian.net/browse/WL-1908)
instructions.
1. Open page A
2. Do thing B
**Author concerns:** List any concerns about this PR - inelegant …

WL-1908: Provide customer success team ability to add ECE records

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/utils.py
enterprise/api/v1/permissions.py
enterprise/api/v1/views.py
enterprise/constants.py
enterprise/migrations/0067_add_role_based_access_control_switch.py
enterprise/models.py
enterprise/rules.py
enterprise/settings/test.py
requirements/base.in
requirements/dev.txt
requirements/doc.txt
requirements/js_test.txt
requirements/quality.txt
requirements/test-master.in
requirements/test-master.txt
requirements/test.txt
requirements/travis.txt
test_utils/__init__.py
tests/test_enterprise/api/test_permissions.py
tests/test_enterprise/api/test_views.py
tests/test_enterprise/test_rules.py

Remaining work:
**JIRA:** https://openedx.atlassian.net/browse/ENT-1730
**Dependencies:** https://github.com/edx/edx-rbac/pull/14, https://github.com/edx/edx-rbac/pull/17
Waffle switch off:
Waffle switch on:
We will need to put the following setting in edx-platform/lms/envs/devstack_docker.py:
```
SYSTEM_TO_FEATURE_ROLE_MAPPING = {
ENTERPRISE_ADMIN_ROLE: [
ENTERPRISE_DASHBOARD_ADMIN_ROLE
],
}
```
There will be a separate ticket to set this setting in production.
Note that this PR does not cover staff role access. …

ENT-1730 Adding feature specific permission checks to edx-enterprise endpoints

---

AUTHORS
CHANGELOG.rst
enterprise/utils.py
enterprise/views.py
test_utils/fake_enrollment_api.py
tests/test_enterprise/views/test_router_view.py
tests/test_utilities.py

**Description:** Added an extra check of user's enrollment in `RouterView`
**JIRA:** [WL-1906](https://openedx.atlassian.net/browse/WL-1906)
instructions.
1. Open page A
2. Do thing B

WL-1906 | Added an extra check of user's enrollment in Enterprise API.

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/constants.py
enterprise/management/commands/assign_enterprise_user_roles.py
tests/test_management.py

This PR adds two feature specific role assignment functionality to the `assign_enterprise_user_roles` management command.
> For two of the feature specific roles, enterprise admins do not get mapped to them automatically.
We need to find the users who currently hit the enterprise catalog endpoints and grant them the feature specific catalog role. The best proxy would be any user who is linked to an enterprise but has also been granted client credentials api keys.
We also need to find the users who are in the enrollment_api_access_group and grant them the feature specific enrollment api admin role.
**JIRA:**
https://openedx.atlassian.net/browse/ENT-1785
** Testing Instructions **
a) _enrollment api admin role_
1. Create user and assign `enterprise_enrollment_api_access` …

Find users for feature specific enterprise roles

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/constants.py
enterprise/settings/test.py
tests/test_enterprise/test_signals.py

**Description:** Added availability key to default content filter for ECC
instructions.
1. Open page A
2. Do thing B

WL-1915: Added availability key to default content filter for ECC

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/views.py

**Description:** The original exception message dumped full course or course_run object data into the exception message, which made it hard to decipher what the issue was.  This change revises the exception message to only include key and name info.
**JIRA:** https://openedx.atlassian.net/browse/ENT-1748
**Merge deadline:** No hard deadline

ENT-1748: Revise course load exception message in CourseEnrollmentView

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/views.py

**Description:** Additionally records the course run id/key in the exception log message alongside the ECC id so we know which actual course run is lacking applicable modes.
**JIRA:** https://openedx.atlassian.net/browse/ENT-1692
**Merge deadline:** No hard deadline

ENT-1692: Revise course mode match exception message in CourseEnrollmentView

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/v1/views.py
enterprise/api_client/discovery.py
tests/test_enterprise/api_client/test_discovery.py

**Description:** In trying to get better debugging information for WL-1911, it seems that this endpoint might be behaving in unexpected ways. In particular, I noticed that it returns false for the contains_content_items call when an error occurs in calling the discovery service, and thus the error is masked from the client. We need this to be surfaced so that we can understand the failures better.
I also removed the new style permission decorator for the endpoint because it is an endpoint called by internal services, and I'd like to derisk it from any further issues.
**Installation instructions:** List any non-trivial installation …

WL-1911 We are masking discovery call failures from the client, and we should stop.

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/views.py

**Description:** The exception workflow in this case is more of an expected scenario -- in some cases such as a passed verification upgrade deadline a course will no longer have a seat that matches the modes filter of a particular enterprise customer catalog.  The "warning" level associated with this exception is creating some alerting noise, so we'll drop the level to "info" in order to be able to retroactively determine the cause of the UI error state when it occurs.
**Merge deadline:** No hard deadline.

Reduce course mode match exception log level

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/v1/serializers.py
enterprise/models.py
tests/test_enterprise/api/test_views.py

The new account settings MFE needs access to the sync_learner_profile_data flag in order to determine which fields should be editable/visible on the account settings form.

ARCH-727 Adding sync_learner_profile_data flag to data returned by enterprise-learner endpoint.

---

consent/helpers.py
consent/models.py
enterprise/api_client/discovery.py
enterprise/models.py
enterprise/utils.py
enterprise/views.py
integrated_channels/degreed/exporters/learner_data.py
integrated_channels/integrated_channel/exporters/learner_data.py
integrated_channels/sap_success_factors/exporters/learner_data.py
test_utils/fake_catalog_api.py
tests/test_consent/api/test_permissions.py
tests/test_consent/api/test_views.py
tests/test_enterprise/api/test_views.py
tests/test_enterprise/api_client/test_discovery.py
tests/test_enterprise/views/test_course_enrollment_view.py
tests/test_enterprise/views/test_grant_data_sharing_permissions.py
tests/test_enterprise/views/test_program_enrollment_view.py
tests/test_enterprise/views/test_router_view.py
tests/test_integrated_channels/test_degreed/test_exporters/test_learner_data.py
tests/test_integrated_channels/test_integrated_channel/test_exporters/test_learner_data.py
tests/test_management.py
tests/test_models.py

The enterprise enrollment page (```enterprise/<enterprise-customer-id>/course/<course-id>/enroll/```) is failing in certain edge cases where the ```course_run_id``` and the ```course_id``` don't follow the expected format.
*Some back story to clarify the problem*:  Traditionally ```course_id```s have been substrings of ```course_run_id```s.  For example, for the course ```edX+DemoX``` has a course run ```course-v1:edX+DemoX+Demonstration_Course```.  However, ```course_id```s do not have to be substrings of their ```course_run_id```s.  You may have a course ```edX+DemoX``` with a course run ```course-v1:edX+DemoY+run_Y```.  Unfortunately, the ```edx-enterprise``` code assumes that ```course_id```s are always substrings of ```course_run_id```s.  Let's say a user tries to enroll in the …

ENT-1054: Fix enrollment page course key issues

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/rules.py
requirements/base.in
requirements/dev.txt
requirements/doc.txt
requirements/quality.txt
requirements/test-master.txt
requirements/test.txt
requirements/travis.txt

This PR updates the logic to get JWT data falls back to `request.auth` if JWT cookies are not present
**Installation instructions:** Simply install `edx-enterprise` using this branch.

ENT-1783: Fallback to request.auth if JWT cookies are not found.

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/cornerstone/models.py
integrated_channels/degreed/models.py
integrated_channels/sap_success_factors/models.py
requirements/base.in
requirements/dev.txt
requirements/doc.txt
requirements/quality.txt
requirements/test-master.txt
requirements/test.txt
requirements/travis.txt

**Description:** We broke our enterprise catalog endpoints because of the introduction of a call to is_jwt_authenticated in edx drf extensions when performing authz checks. This function has been fixed to resolve the error.
instructions.
1. Open page A
2. Do thing B
solutions, hacks, quick-and-dirty implementations, concerns …

Upgrading edx-drf-extensions to latest version

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/utils.py
integrated_channels/cornerstone/views.py

This PR has changes to use `OAuth2AuthenticationAllowInactiveUser` as oauth2 authentication instead of `BearerAuthentication` because `BearerAuthentication` requires `OAUTH2_USER_INFO_URL` settings which we don't have in LMS.

WL-1927: Using OAuth2AuthenticationAllowInactiveUser as oauth2 authentication class

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/v1/serializers.py
tests/test_enterprise/api/test_views.py

added enable_audit_data_reporting in EnterpriseCustomerSerializer 
to use in edx-analytics-data_api
https://openedx.atlassian.net/browse/WL-1920
instructions.
1. Open page A
2. Do thing B

WL-1920 | Audit track enrollments appearing in customer's learner progress report

---

Makefile
README.rst
requirements/base.in
requirements/dev.txt
requirements/doc.txt
requirements/quality.txt
requirements/test-master.in
requirements/test-master.txt
requirements/test.txt

We are trying to upgrade Django REST Framework in edx-platform.  This is needed to make it possible.
I also made "make upgrade" more flexible, and cleaned up the README a tad.

Upgrade django-config-models to unblock DRF upgrades

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/xapi/serializers.py
integrated_channels/xapi/utils.py
requirements/base.in
requirements/dev.txt
requirements/doc.txt
requirements/js_test.txt
requirements/quality.txt
requirements/test-master.txt
requirements/test.txt
requirements/travis.txt
tests/test_integrated_channels/test_xapi/test_serializers.py
tests/test_integrated_channels/test_xapi/test_utils.py

**Description:** This PR updates the xapi course_duration based on effort and weeks-to-complete
**JIRA:** https://openedx.atlassian.net/browse/ENT-1990
- Create an account at https://cloud.scorm.com
- Use the Sandbox endpoint
- Copy the key and secret from the Activity Providers tab to a new configuration in the  Enterprise xAPI Integration › Xapilrs configurations in LMS Admin.
- Setup the Catalog Integration and associated service user
- Setup course_metadata in the discovery admin to have values for weeks_to_complete and max_effort
- Run the management command /integrated_channels/xapi/management/commands/send_course_enrollments.py
- Verify that the course_duration is being correctly populated in the SCORM cloud LRS viewer
**DO NOT** just …

ENT-1990 updated duration based on effort and weeks-to-complete

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/tpa_pipeline.py
integrated_channels/sap_success_factors/client.py
integrated_channels/sap_success_factors/exporters/learner_data.py
tests/test_management.py

**Description:** Improved logging of unlink_inactive_sap_learners command
Matching social_auth user with uid field insteand of username field

ENT-2009: Improved logging of unlink_inactive_sap_learners command and match social auth user by `uid` field

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/utils.py
integrated_channels/cornerstone/exporters/content_metadata.py
tests/test_integrated_channels/test_cornerstone/test_exporters/test_content_metadata.py

This PR has changes to return language code instead of language name in `languages` field of course-list API in cornerstone integrated channel.
**JIRA:** https://openedx.atlassian.net/browse/WL-1941

WL-1941: Changes to return language code instead of language name

---

enterprise/api_client/discovery.py
enterprise/models.py

The ```edx-enterprise``` code could get into a state where it called the ```search/all``` endpoint in ```discovery``` with the query params ```key: [None]```.
This happened because the method ```get_course_id``` returns ```None`` when passed a ```course_identifier``` that has no valid ```course_key```.
The fix:
- Log when ```get_course_id``` cannot find a ```course_key```
- Filter out the course key ```None``` before calling discovery's search endpoint.  If ```None``` is the only course_key in the list, do not call discovery.
**Installation instructions:** List any …
```

Fix Issue: Calling Search API with ```None```

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/views.py
integrated_channels/cornerstone/utils.py
tests/test_integrated_channels/test_cornerstone/test_utils.py

added create_cornerstone_learner_data_transmission_audit util to create records
called that utility from RouterView
added unit tests
**JIRA:** https://openedx.atlassian.net/browse/WL-1938
instructions.
1. Open page A
2. Do thing B

WL-1938 | Capture user attributes sent by cornerstone

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/utils.py
tests/test_utilities.py

**Description:** converting course week_to_complete default None to 0 in is_course_run_about_to_end util
**JIRA:** 
https://openedx.atlassian.net/browse/WL-1943
instructions.
1. Open page A
2. Do thing B

WL-1943 | Server Error on enterprise course enroll url

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/sap_success_factors/client.py
tests/test_management.py

Changed page size of inactive user results from 500 to 1000 to avoid timeouts for those customers who has large number of in-active users.
**JIRA:** https://openedx.atlassian.net/browse/ENT-2009

ENT-2009: Changed page size of inactive user results from 500 to 1000

---

requirements/base.txt
requirements/dev.txt
requirements/doc.txt
requirements/edx-platform-constraints.txt
requirements/test-master.in
requirements/test.txt
requirements/travis.txt

Upgrade DRF to 3.7.7 to match edx-platform

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/cornerstone/exporters/content_metadata.py
integrated_channels/integrated_channel/exporters/content_metadata.py
tests/test_integrated_channels/test_cornerstone/test_views.py

Added ability to skip keys in content exporter if their value is None.

WL-1946: Added ability to skip keys if their value is None for content exporter

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/admin/__init__.py

**Description:** This will change the catalog preview url on [Enterprise Catalogs admin page](https://mammar.sandbox.edx.org/admin/enterprise/enterprisecustomercatalog/). Instead of calling the discovery `search/all` endpoint to get a catalog details, we will hit the `enterprise_catalogs` endpoint. We need this because discovery `search/all` GET endpoint cannot handle very large catalog queries.
**JIRA:** https://openedx.atlassian.net/browse/ENT-1295
**Testing:** This PR is deployed to sandbox
1. Login to https://mammar.sandbox.edx.org/admin
2. Goto https://mammar.sandbox.edx.org/admin/enterprise/enterprisecustomercatalog/
3. The Preview links should point to `enterprise_catalogs` endpoint
4. Upon click on a Preview link, it should show the catalog details.

update catalog preview url

---

CHANGELOG.rst
Makefile
enterprise/__init__.py
requirements/base.txt
requirements/dev.txt
requirements/doc.txt
requirements/edx-platform-constraints.txt
requirements/js_test.txt
requirements/test-master.in
requirements/test.txt

tl;dr, we should find a way to stop pinning as many dependencies as we can to avoid update conflicts with edx-platform.
Longer:
I started by running make upgrade in edx-platform against this branch, and adding things that failed as a constraint in requirements/test-master.in, and then running make upgrade in edx-enterprise, then repeating the process. There were several issues going on, but the main problem is that we are trying to stay in sync with edx-platform, but we pin explicitly when a package is upgraded, and it may be constrained for some reason in edx-platform. It took a while to come to this, and there is a corresponding change necessary in edx-platform because of transifex-client, which we would have had to resolve anyway in edx-platform.
Here is the …

Resolving conflicts in make upgrade

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/sap_success_factors/client.py
tests/test_management.py

Reverted page size of SAPSF inactive user results from 1000 to 500

Revert Changed page size of SAPSF inactive user results from 500 to 1000

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/rules.py
requirements/base.in
requirements/dev.txt
requirements/doc.txt
requirements/edx-platform-constraints.txt
requirements/test-master.txt
requirements/test.txt
requirements/travis.txt

**Description:** This upgrades the edx-rbac to latest version and as a result of this upgrade we are using jwt utils from edx-drf-extensions package because those jwt utils are now removed from edx-rbac.
**JIRA:** [ENT-2002](https://openedx.atlassian.net/browse/ENT-2002)

use edx-drf-extensions jwt utils

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/cornerstone/exporters/content_metadata.py
tests/test_integrated_channels/test_cornerstone/test_exporters/test_content_metadata.py
tests/test_integrated_channels/test_cornerstone/test_views.py

Cornerstone consumer was expecting course list API to have default values for all required fields
Now we are returning default values for required fields in Cornerstone Course List API
**JIRA:** https://openedx.atlassian.net/browse/WL-1952
instructions.
1. Open page A
2. Do thing B
**DO …

WL-1952 | Cornerstone consumer expects course list API to have default values for all required fields

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/cornerstone/exporters/content_metadata.py
tests/test_integrated_channels/test_cornerstone/test_exporters/test_content_metadata.py

**Description:** Handle corner cases for default values in CornerstoneCourseListAPI.
**JIRA:** https://openedx.atlassian.net/browse/WL-1952
instructions.
1. Open page A
2. Do thing B
solutions, hacks, …

WL-1952 | Handle corner cases for default values in CornerstoneCourseListAPI.

---

enterprise/api_client/discovery.py
tests/test_enterprise/api_client/test_discovery.py

**Description:** setting cache for get_catalog_results from discovery
**JIRA:** https://openedx.atlassian.net/browse/ENT-2168
instructions.
1. Open page A
2. Do thing B
solutions, hacks, quick-and-dirty …

ENT-2168 | setting cache for get_catalog_results from discovery

---

CHANGELOG.rst
integrated_channels/sap_success_factors/exporters/content_metadata.py
tests/test_integrated_channels/test_sap_success_factors/test_exporters/test_content_metadata.py

**Description:** Include course run dates and pacing type in the course description sent to SAP.
I'll update the version before merging this.
**JIRA:** https://openedx.atlassian.net/browse/ENT-1321

ENT-1321 Add course dates and pacing

---

CHANGELOG.rst
enterprise/__init__.py

**Description:** In the prior release (1.9.2) I forgot to increment the version in ___init__.py_ (or lost the increment in a rebase). Since I already tagged 1.9.2 in github, making a new release of 1.9.3 seems cleanest.
**JIRA:** https://openedx.atlassian.net/browse/ENT-1321
instructions.
1. Open page A
2. Do thing B
**DO NOT** just add dependencies to …

ENT-1321 Fix version increment

---

CHANGELOG.rst
enterprise/__init__.py
enterprise_learner_portal/api/v1/views.py
requirements/dev.txt
requirements/doc.txt
requirements/edx-platform-constraints.txt
requirements/js_test.txt
requirements/test-master.txt
requirements/test.txt
requirements/travis.txt
tests/test_enterprise_learner_portal/api/test_views.py

**Description:** Since learner portals will always be tied to a specific enterprise, we need to filter a user's enrollments by that enterprise to avoid error conditions when a user is linked to many.
instructions.
1. Open page A
2. Do thing B …

ENT-2203 Update learner portal enterprise enrollments endpoint to filter on enterprise_id

---

enterprise/views.py
enterprise/views_error_codes.txt

Logging exception if IntegrityError encountered while creating EnterpriseCourseEnrollment
**JIRA:** https://openedx.atlassian.net/browse/ENT-1860
instructions.
1. Open page A
2. Do thing B
**Author concerns:** List any concerns about this PR - inelegant …

ENT-1860 | 500 error observed during Data Sharing Consent

---

CHANGELOG.rst
enterprise/__init__.py
enterprise_learner_portal/api/v1/serializers.py
enterprise_learner_portal/api/v1/views.py
enterprise_learner_portal/utils.py
tests/test_enterprise_learner_portal/api/test_serializers.py
tests/test_enterprise_learner_portal/api/test_views.py
tests/test_enterprise_learner_portal/test_utils.py

instructions.
1. Open page A
2. Do thing B …

ENT-2230 Add patch method on learner portal enrollment endpoint

---

enterprise/__init__.py
enterprise/api/v1/serializers.py
enterprise/api/v1/views.py
enterprise/models.py
tests/test_enterprise/api/test_views.py

Added passwords for files to the API for reporting config

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/v1/serializers.py
enterprise/api/v1/views.py
tests/test_enterprise/api/test_views.py

add a new endpoint to get a list of enterprise customer with basic data only with search capability

ENT-2272 | Added endpoint to get list of enterprise customer with search support

---

requirements/dev.txt
requirements/doc.txt
requirements/edx-platform-constraints.txt
requirements/js_test.txt
requirements/test-master.txt
requirements/test.in
requirements/test.txt
requirements/travis.txt
tests/test_integrated_channels/test_sap_success_factors/test_client.py

Removed flaky package and flakiness in unit test,

ENT-2352: Removed flaky package and flakiness in unit test

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/admin/__init__.py
enterprise/api/v1/serializers.py
enterprise/api/v1/urls.py
enterprise/api/v1/views.py
enterprise/models.py
test_utils/factories.py
tests/test_enterprise/api/test_views.py
tests/test_models.py
tests/test_utilities.py

This needs to be merged and deployed AFTER the corresponding ecommerce  PR here: https://github.com/edx/ecommerce/pull/2612

ENT-1289 | Removing enterprise entitlement logic from codebase

---

integrated_channels/degreed/exporters/content_metadata.py
integrated_channels/utils.py
tests/test_integrated_channels/test_degreed/test_exporters/test_content_metadata.py

It appears Degreed accepts only plain text in course description. These changes strip html tags and entities from course description for degreed. ENT-2258

ENT-2258: Strip html tags and entities from course description for degreed

---

enterprise/api/v1/views.py
tests/test_enterprise/api/test_views.py

ENT-2322 | added startswith filter in enterprise customer basic list endpoint.

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/admin/__init__.py
enterprise/admin/forms.py
enterprise/admin/widgets.py
enterprise/utils.py
tests/test_admin/test_forms.py
tests/test_enterprise/views/test_router_view.py

added preview button for catalogs in enterprise customer admin page

ENT-1878 | Automate catalog query when updating enterprise customer catalog

---

enterprise/models.py
tests/test_models.py

ENT-1827 | Updated the 'contains_courses' function.

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/models.py
tests/test_enterprise/views/test_router_view.py
tests/test_models.py

This Pr code aimed to remove the Ended/Expired Course Runs from the following endpoint
**enterprise/api/v1/enterprise_catalogs/UUID/**
This Pr is dependent on [Course-Discovery PR](https://github.com/edx/course-discovery/pull/2211)
PRE-PR Results:
All course runs will be visible in results.
POST-PR Results:
Course runs which are expired will not be visible in results.
[ENT-1470](https://openedx.atlassian.net/browse/ENT-1470)

Exclude ended/expired course runs from endpoint

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/integrated_channel/exporters/learner_data.py
integrated_channels/integrated_channel/tasks.py
integrated_channels/sap_success_factors/exporters/learner_data.py
tests/test_integrated_channels/test_cornerstone/test_exporters/test_learner_data.py
tests/test_management.py

**Description**: Enterprise customers are seeing a course 'Pass' status for learners with 'Audit' enrollments. The transmit/export process, which does not differentiate between normal and audit learners, was recently changed to handle single grade transmissions instead of batch transmissions. This PR removes [this](https://github.com/edx/edx-enterprise/pull/574/files#diff-3051e117b960d55eba74f530e5050c0bR150) check in the recent code update which will enable correct population of completed_date and is_passing variables in the export and transmission log.
**JIRA**: https://openedx.atlassian.net/browse/ENT-2372
**Reference**: The [transmit/export process](https://github.com/edx/edx-enterprise/pull/574/files#diff-c36e78c76477eda2c1045fae45db0602R104) is assigning a grade based on the …

ENT-2372: Re-enabled the API calls to update completed_date and is_passing

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/cornerstone/exporters/content_metadata.py
integrated_channels/degreed/exporters/content_metadata.py
integrated_channels/sap_success_factors/exporters/content_metadata.py
integrated_channels/utils.py
tests/test_integrated_channels/test_cornerstone/test_exporters/test_content_metadata.py
tests/test_integrated_channels/test_degreed/test_exporters/test_content_metadata.py

JIRA: https://openedx.atlassian.net/browse/ENT-2428

ENT-2428: Updated image url field for cornerstone and degreed

---

enterprise/api/v1/serializers.py
enterprise/api/v1/views.py
enterprise/models.py
tests/test_admin/test_view.py
tests/test_enterprise/api/test_serializers.py
tests/test_enterprise/api/test_views.py

Added support to activate/deactivate learner's enterprise

ENT-2431:Added support to activate/deactivate learner's enterprise

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/v1/views.py
enterprise/management/commands/seed_enterprise_devstack_data.py
enterprise/models.py
integrated_channels/cornerstone/views.py

A management command to seed devstack LMS enterprise models with some data. A separate management command will exist for seeding devstack Ecommerce enterprise coupon/offer models.
The result of this script from within `lms-shell` is:

Add mgmt command for seeding enterprise data on devstack

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/models.py
enterprise/utils.py
tests/test_models.py

[ENT-2419]
- Update 'EnterpriseCustomerUser' model. During the 'enroll' call we will use EcommerceApiClient to create an order for any enrollments pending for user.
- Added method to retrieve ecommerce worker in 'utils.py' used when creating an instance of the EcommerceApiClient. 
[ENT-2419]: https://openedx.atlassian.net/browse/ENT-2419

ENT-2419 | Create ecommerce orders during user reg. from pending enrollments

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/admin/views.py
package-lock.json
tests/test_admin/test_view.py

Add order creation to the enterprise customer manual enroll tool

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/models.py

[ENT-2463]
- Handle IntegrityError/Race condition that can occur in EnterpriseCustomerUser.enroll() call.
[ENT-2463]: https://openedx.atlassian.net/browse/ENT-2463

ENT-2463 | Handle IntegrityError during course enroll in EnterpriseCustomerUser mdoel

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/degreed/client.py
integrated_channels/integrated_channel/transmitters/content_metadata.py
integrated_channels/integrated_channel/transmitters/learner_data.py
integrated_channels/sap_success_factors/client.py
integrated_channels/sap_success_factors/exporters/learner_data.py
integrated_channels/sap_success_factors/models.py
integrated_channels/sap_success_factors/transmitters/content_metadata.py
tests/test_integrated_channels/test_degreed/test_client.py
tests/test_integrated_channels/test_sap_success_factors/test_client.py

whenever an integrated channel returns non-json type of content, raising
RequestException and handling it with other RequestException handlers.
ENT-2468

ENT-2468 | Better handle when Integrated Channels return unexpected results

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/v1/serializers.py
enterprise/models.py
enterprise/signals.py
tests/test_enterprise/api/test_views.py

[ENT-2082]
Now [MICROBA-56]
This PR adds the Source to Enterprise CourseEnrollments and Pending
Enrollments that are made through the EnterpriseCustomer
Enrollment API.
[MICROBA-56]: https://openedx.atlassian.net/browse/MICROBA-56

[MICROBA-56] Added Source to the EnterpriseEnrollments for Enterprise APIs

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/forms.py
enterprise/static/enterprise/js/enterprise_selection_page.js
enterprise/templates/enterprise/enterprise_customer_select_form.html
enterprise/views.py
spec/javascripts/enterprise_select_spec.js
tests/test_enterprise/views/test_enterprise_selection.py

**Description:** Initially we have added validation on `success_url` with the assumption that it will always be a platform url and also the url will not raise `Resolver404` if we apply `django.urls.resolve` function but it turns out this is not the case, for example, When we sign in through Google, the `success_url` is set to `/auth/complete/google-oauth2/?` and  `django.urls.resolve` function raises `Resolver404 ` on such a url due to `?` in the end. So we have decided to remove the validation on `success_url`.
**Testing:** Now both the below urls will work fine. 
1. https://mammar.sandbox.edx.org/enterprise/select/active?success_url=/dashboard/?
2. https://mammar.sandbox.edx.org/enterprise/select/active?success_url=/dashboard
- `base.in` if needed in production but …

remove success url validation

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/models.py
tests/test_models.py

Description: This PR updates the Manager for EnterpriseCustomerUser model with an overridden get() method. This will enable a learner to be associated with multiple enterprises and the get() will pick the first entry from the queryset. As part of [ENT-2338](https://openedx.atlassian.net/browse/ENT-2338) it will be ensured that the first entry is always the one currently relevant for the learner.
JIRA: https://openedx.atlassian.net/browse/ENT-2346

ENT-2346 Overridden get in EnterpriseCustomerUser manager

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/tpa_pipeline.py
tests/test_tpa_pipeline.py

Mark the learner current enterprise-customer active flag to True and all other enterprise-customers active flag to false.

Mark the current learner enterprise-customer active flag to True 

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/views.py
tests/test_enterprise/views/test_enterprise_selection.py

**JIRA**: https://openedx.atlassian.net/browse/ENT-2497

ENT-2497: Updated session after multiple enterprise selection

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/tpa_pipeline.py

Mark the current learner enterprise-customer active flag to True and all other enterprise-customers active flag to false

Mark the current learner enterprise-customer active flag to True

---

tox.ini

JIRA: https://openedx.atlassian.net/browse/ENT-2017

ENT-2017 - Ignore decisions directory for doc8

---

CHANGELOG.rst
enterprise/admin/utils.py
test_utils/file_helpers.py
tests/test_admin/test_utilities.py

while uploading bulk users in manager learners from admin, better handling if invalid encoding found.
ENT-1231

ENT-1231 | Recommend utf8 csv files when manage learners bulk enroll fails

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/admin/views.py
enterprise/models.py
tests/test_admin/test_view.py
tests/test_models.py

Description: Audit type enrollment transactions would no longer create $0 orders for financial reporting.
JIRA: https://openedx.atlassian.net/browse/ENT-2513

ENT-2513: Disable manual enrollment orders for audit enterprise learners

---

CHANGELOG.rst
enterprise/__init__.py
requirements/dev.txt
requirements/doc.txt
requirements/edx-platform-constraints.txt
requirements/js_test.txt
requirements/test-master.txt
requirements/test.txt
requirements/travis.txt

ENT-2501: Updated edx-rbac

---

CHANGELOG.rst
enterprise/__init__.py
requirements/base.in
requirements/dev.txt
requirements/doc.txt
requirements/test-master.txt
requirements/test.txt

Use Tincan PYPI package insteade of git download

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api_client/discovery.py

added logging of discovery request size

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api_client/lms.py
integrated_channels/integrated_channel/exporters/learner_data.py
tests/test_integrated_channels/test_cornerstone/test_exporters/test_learner_data.py
tests/test_integrated_channels/test_integrated_channel/test_exporters/test_learner_data.py
tests/test_management.py

This PR is about replacing the `EDX-API-KEY` with `OAuth` authentication method using `JWT.` There are three clients that are relying on the `EDX-API-KEY` based authentication; `CourseApiClient,` `EnrollmentApiClient,` and `ThirdPartyAuthApiClient.` This PR only covers the `integrated_channels/integrated_channel/exporters/learner_data.py` endpoint by cloning the original `CourseApiClient` and using that one in the mentioned endpoint. It also covers all the test cases of the endpoint.

ENT-2042 Replaced Edx-Api-Key in CourseApiClient in exporter-learnerdata-endpoint

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/admin/views.py
enterprise/api_client/lms.py
tests/test_admin/test_view.py
tests/test_enterprise/api_client/test_lms.py

This PR is about replacing the `EDX-API-KEY` with `OAuth` authentication method using `JWT.` There are three clients that are relying on the `EDX-API-KEY` based authentication; `CourseApiClient,` `EnrollmentApiClient,` and `ThirdPartyAuthApiClient.` This PR only covers the `admin/views.py` endpoint by cloning the original `EnrollmentApiClient` and using that one in the mentioned endpoint.

ENT-2042 Replaced Edx-Api-Key in Enrollment Api Client admin-views-endpoint

---

CHANGELOG.rst
enterprise/__init__.py

ENT-2492 Version bump for adding discount to manual enrollments

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/models.py
tests/test_models.py

**Description** This PR updates the EnterpriseRoleAssignmentContextMixin to incorporate the case where a user may have multiple contexts e.g. a user with multiple linked enterprises
**JIRA** https://openedx.atlassian.net/browse/ENT-2501

ENT-2501: Updated context for user with multiple linked enterprises

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api_client/lms.py
enterprise/models.py
tests/test_enterprise/api_client/test_lms.py
tests/test_integrated_channels/test_degreed/test_exporters/test_learner_data.py
tests/test_integrated_channels/test_integrated_channel/test_exporters/test_learner_data.py
tests/test_models.py

This PR is about replacing the `EDX-API-KEY` with `OAuth` authentication method using `JWT.` There are three clients that are relying on the `EDX-API-KEY` based authentication; `CourseApiClient,` `EnrollmentApiClient,` and `ThirdPartyAuthApiClient.` This PR only covers the `enterprise/models/EntepriseCustomerUser` endpoint by cloning the original `ThirdPartyAuthApiClient` and using that one in the mentioned endpoint. It also covers all the test cases of the endpoint. It also covers all the test cases related to it.

ENT-2042 Replaced Edx-Api-Key in model-EnterpriseCustomerUser-endpoint

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/admin/__init__.py
enterprise/admin/forms.py
enterprise/api_client/lms.py
enterprise/models.py
enterprise/views.py
tests/test_admin/test_forms.py
tests/test_admin/test_view.py
tests/test_enterprise/api/test_views.py
tests/test_enterprise/api_client/test_lms.py
tests/test_enterprise/test_signals.py
tests/test_enterprise/views/test_course_enrollment_view.py
tests/test_enterprise/views/test_handle_consent_enrollment.py
tests/test_enterprise/views/test_router_view.py
tests/test_integrated_channels/test_integrated_channel/test_exporters/test_learner_data.py
tests/test_management.py
tests/test_models.py

This PR only covers the remaining endpoints of EnrollmentApiClient by cloning the original `EnrollmentApiClient` and using that one in all the remaining endpoints.

ENT-2042 Replaced Edx-Api-Key in Enrollment Api Client (remaining endpoints)

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/integrated_channel/management/commands/reset_sapsf_learner_transmissions.py

Added management command to reset SAPSF completion data.
It would allow us resend those completion enteries which are reset.
ENT-2464

ENT-2464: Added management command to reset SAPSF completion data

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/admin/__init__.py
enterprise/api_client/enterprise_catalog.py
tests/test_admin/test_model_admins.py
tox.ini

https://openedx.atlassian.net/browse/ENT-2476

Sync catalog admin to enterprise-catalog ida

---

enterprise/models.py
tests/test_admin/test_view.py
tests/test_models.py

**Description:** For enroll/unenroll, initialize the `EnrollmentApiClient` with servier user. 

initialize enrollmentapi client with service user

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/admin/views.py
enterprise/models.py
tests/test_admin/test_view.py
tests/test_models.py

EnrollmentApiClient should call enrollment API with enterprise service user instead of the user being enrolled manually to avoid 403/404 errors.

EnrollmentApiClient should call enrollment API with enterprise service user

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/admin/views.py
enterprise/models.py
tests/test_admin/test_view.py
tests/test_models.py

Revert EnrollmentApiClient should call enrollment API with enterprise service worker user

Revert EnrollmentApiClient initialization with service worker user

---

enterprise/admin/__init__.py
enterprise/admin/forms.py
enterprise/admin/views.py
enterprise/api_client/lms.py
enterprise/models.py
enterprise/views.py
integrated_channels/integrated_channel/exporters/learner_data.py
tests/test_enterprise/api_client/test_lms.py
tests/test_integrated_channels/test_cornerstone/test_exporters/test_learner_data.py
tests/test_integrated_channels/test_degreed/test_exporters/test_learner_data.py
tests/test_integrated_channels/test_integrated_channel/test_exporters/test_learner_data.py
tests/test_management.py
tests/test_models.py

Revert-ENT-2042-Edx-Api-Key-replacement-changes

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/admin/__init__.py
enterprise/admin/forms.py
enterprise/admin/views.py
enterprise/api_client/lms.py
enterprise/models.py
enterprise/views.py
integrated_channels/integrated_channel/exporters/learner_data.py
tests/test_admin/test_view.py
tests/test_enterprise/api_client/test_lms.py
tests/test_integrated_channels/test_cornerstone/test_exporters/test_learner_data.py
tests/test_integrated_channels/test_degreed/test_exporters/test_learner_data.py
tests/test_integrated_channels/test_integrated_channel/test_exporters/test_learner_data.py
tests/test_management.py
tests/test_models.py

Revert EnrollmentApiClient should call enrollment API with enterprise service worker user
Revert-Edx-Api-Key-replacement-changes
added-EnterpriseCatalogApiClient-import
Updated version and changelog

Revert Edx-Api-Key-replacement-changes

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/models.py
test_utils/factories.py
tests/test_models.py

**Description:** Currently whenever we unlink an Enterprise Learner from an Enterprise, all the Enterprise Course Enrollments for the learner gets deleted due to `CASCADING`. To avoid this we have added soft deletion for `EnterpriseCustomerUser` records. The behaviour will remain same and get queryset methods will not return a soft deleted `EnterpriseCustomerUser` record and its related `EnterpriseCourseEnrollment` records but all the creation methods like `get_or_create/update_or_create/create` will always return an `EnterpriseCustomerUser` record either by creating a new object in database or by updating an existing soft-deleted object.
**JIRA:** https://openedx.atlassian.net/browse/ENT-2538
- …

soft delete enterprisecustomeruser records

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/admin/views.py
enterprise/models.py

update calls to manual enrollment api to include enterprise customer data

ENT-2550 | capture enterprise customer info in manual enrollments

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/models.py
tests/test_models.py

Description: This PR ensures that the manual enrollment order is not created when the enrollment api call fails.
JIRA: https://openedx.atlassian.net/browse/ENT-2559

ENT-2559: Order not created when enrollment fails

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/integrated_channel/exporters/learner_data.py

Fixed TypeError when JSON is passed bytes instead of str.
This happens when  when grades API return `user_not_enrolled` error.
ENT-2614

ENT-2614: Fixed TypeError when JSON is passed bytes instead of str

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/tpa_pipeline.py
tests/test_tpa_pipeline.py

Learner attached to multiple enterprises, logging in via SSO(Google, Fb), show him multiple enterprise selection page.
**Testing Requirements:**
Please create 2 users. 
user1 should be linked to 2 or more enterprises.
User2 should be linked to 1 enterprise.
Please setup google social auth and Facebook social auth on your local machine.
**Pre PR:**
1- When you will log in with the Google or Facebook social auth and it has edx linked account.
If the linked edx account is the part of multiple enterprises then multiple enterprises page is not shown to the user.
**Post PR:**
**1-** When you will log in with the Google or Facebook social auth and it has edx linked account. If the linked edx account is the part of multiple enterprises then multiple enterprises page is shown to the user.
**2-** …

Learner attached to multiple enterprises, logging in via SSO(Google,FB)

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/admin/utils.py
enterprise/admin/views.py
tests/test_admin/test_view.py

This PR restricts a PendingEnterpriseCustomerUser to be linked with multiple enterprises at the same time. The user will be able to link with another enterprise once he/she registers or the other enterprise unlinks that user. 
Ticket: https://openedx.atlassian.net/browse/ENT-2482

ENT-2482: Restrict PendingEnterpriseCustomerUser for multiple EnterpriseCustomers

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/integrated_channel/exporters/content_metadata.py
tests/test_management.py

This logger is extremely noisy (over 150k per hour).

Update log level for content changes to debug

---

CHANGELOG.rst
enterprise/__init__.py

Version bump up from 2.4.1 to 2.4.2.

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/views.py

Changes to reset user authentication cookies after successfull selection of enterprise by learner. This should update JWT cookies which would help us accurately map learner's enterprise where we fetch learner's enterprise from JWT cookie.

ENT-2622: Reset user authentication cookies

---

consent/api/v1/views.py
enterprise/__init__.py
enterprise/api/v1/views.py
enterprise/utils.py
enterprise_learner_portal/api/v1/views.py
integrated_channels/cornerstone/views.py
tox.ini

According to our investigation using new relic custom metrics, BearerAuthentication class is not used and is safe for removal.
[PR that adds metric](https://github.com/edx/edx-drf-extensions/pull/105)

Removing use of BearerAuthentication + clean up

---

CHANGELOG.rst
enterprise/__init__.py

Updated the use of CourseOverview's method 'get_from_ids()'
with the xApi integrated channels
ENT-2703

Bumped version for previous commit

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/xapi/client.py
integrated_channels/xapi/management/commands/send_course_completions.py
integrated_channels/xapi/management/commands/send_course_enrollments.py
tests/test_integrated_channels/test_xapi/test_client.py

ENT-2537: Added logging around enrollment/completion transmission of xAPI

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api_client/enterprise_catalog.py
tests/test_enterprise/api_client/test_enterprise_catalog.py

Update enterprise catalog urls to match new paths

---

enterprise/api/v1/serializers.py
enterprise/api_client/lms.py
enterprise/models.py
tests/test_enterprise/api_client/test_lms.py

This PR has changes to Convert ThirdPartyAuthApiClient to JWT client.

ENT-2676: Converted ThirdPartyAuthApiClient to JWT client

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/v1/serializers.py
enterprise/utils.py
integrated_channels/sap_success_factors/exporters/content_metadata.py
integrated_channels/sap_success_factors/exporters/utils.py
test_utils/__init__.py
test_utils/fake_catalog_api.py
tests/test_utilities.py

added `active` key in enterprise catalog
https://openedx.atlassian.net/browse/ENT-2483

ENT-2483 | Return boolean value of whether or not the course is active

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/tpa_pipeline.py
tests/test_tpa_pipeline.py

ENT-2726 Bypass selection page for enrolment url triggered login

---

CHANGELOG.rst
enterprise/models.py
enterprise/settings/test.py
test_utils/factories.py
tests/test_enterprise/api/test_throttles.py
tests/test_enterprise/api/test_views.py
tests/test_models.py

Removed all auto-generated fields (e.g: id's) from factories to stop initializing them using `fake.random_int()`

ENT-2755 | Tests are failing due to UNIQUE constraint failed

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api_client/lms.py
tests/test_enterprise/api_client/test_lms.py

ENT-2675 | Converted EnrollmentApiClient to JWT client.

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/tpa_pipeline.py

Description: This PR fixes a TypeError issue when matching urls for redirect to the enterprise selection page.
JIRA: https://openedx.atlassian.net/browse/ENT-2726

ENT-2726 Fix issue with matching urls for enterprise selection page

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api_client/enterprise_catalog.py
enterprise/migrations/0094_add_use_enterprise_catalog_sample.py
enterprise/models.py
integrated_channels/integrated_channel/exporters/content_metadata.py
tests/test_models.py

This PR primarily swaps over the waffle flag to be a waffle sample. The reason for this is because waffle flags have a dependency on the `request` object to determine if the flag is active for a particular user/request. However, 2 of the places that we are migrating to the enterprise-catalog service are triggered by a management command, which inherently does not have any knowledge of a `request` object. As such, the conditional for `waffle.flag_is_active` will always be false in those cases.
By switching to a waffle sample, we will still be able to incrementally increase the percentage of traffic that hits the enterprise-catalog service, without needing to manage both a flag and sample.
https://waffle.readthedocs.io/en/stable/types/sample.html
**Summary**
1. Adds a …

Use waffle sample instead of waffle flag for using enterprise-catalog service

---

CHANGELOG.rst
enterprise/__init__.py

Fix version bump and CHANGELOG entry for waffle sample rollout

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api_client/enterprise_catalog.py
enterprise/models.py
tests/test_enterprise/api_client/test_enterprise_catalog.py
tests/test_models.py

This PR adds a conditional check to the `catalog_contains_course` method on the `EnterpriseCustomer` model to call the enterprise-catalog service when the `USE_ENTERPRISE_CATALOG` sample is active. If the sample is not active, the method uses the existing implementation.
Ticket: https://openedx.atlassian.net/browse/ENT-2574

Update catalog_contains_course to use enterprise-catalog service if waffle sample is active

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api_client/enterprise_catalog.py

fixing traversal of results

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/templates/enterprise/enterprise_course_enrollment_page.html

Fixes: https://openedx.atlassian.net/browse/ENT-2711

ENT-2711: Fixed HTML tags bug in course short_description

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/admin/__init__.py
enterprise/utils.py
requirements/constraints.txt
requirements/dev.txt
requirements/django.txt
requirements/doc.txt
requirements/edx-platform-constraints.txt
requirements/js_test.txt
requirements/test-master.txt
requirements/test.txt
requirements/travis.txt

ENT-2724 | removed get_cache_key and using it from edx-django-utils.

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/utils.py

- ~`base.in` if needed in production but edx-platform doesn't install it~
- ~`test-master.in` if edx-platform pins it, with a matching version~
- ~`make upgrade && make requirements` have been run to regenerate requirements~
Ref #736

Present course run as inactive when end date is within 24 hours.

---

CHANGELOG.rst
enterprise/__init__.py
requirements/js_test.txt

Downgrade jaraco versions to fix Travis build
ENT-2568

Make enrollment reason optional

---

.travis.yml
CHANGELOG.rst
requirements/constraints.txt
requirements/dev.txt
requirements/doc.txt
requirements/edx-platform-constraints.txt
requirements/js_test.txt
requirements/test-master.txt
requirements/test.txt
requirements/travis.txt
setup.py
tox.ini

**Issue:** [BOM-1567](https://openedx.atlassian.net/browse/BOM-1567)
- Changed `py36` with `py38`.
- Removed `django111`, `django20`, `django21`.
- Added `django30` in **Tox**.
- Updated version to `3.2.3`.

Travis and Tox Update

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/admin/__init__.py
enterprise/api_client/enterprise_catalog.py
tests/test_admin/test_model_admins.py

This PR modifies the save hook in `EnterpriseCustomerCatalogAdmin` for updating an existing enterprise catalog within the LMS. On an update, the save hook will now attempt to fetch the corresponding catalog in the enterprise-catalog service. If the catalog does not yet exist in the service, a new catalog will be created; otherwise, the existing catalog will be updated.

Fix EnterpriseCustomerCatalogAdmin save hook on update

---

CHANGELOG.rst
enterprise/__init__.py
pylintrc
pylintrc_tweaks
requirements/check_pins.py
requirements/dev.in
requirements/dev.txt
requirements/doc.txt
requirements/edx-platform-constraints.txt
requirements/js_test.txt
requirements/test-master.txt
requirements/test.txt
requirements/travis.txt
test_utils/file_helpers.py
tox.ini

**Background:** Any repositories which have already been updated to drop Python 2.7 support no longer need to depend on or use the caniusepython3 package, but some of them (such as edx-enterprise) still do. (https://openedx.atlassian.net/browse/BOM-1630)
This PR will remove caniusepython3 from edx-enterprise. - https://openedx.atlassian.net/browse/BOM-1641
**Things done:**
- Remove any executions of pylint using the --py3k option
- Remove caniusepython3.pylint_checker from pylintrc_tweaks and pylintrc
- Remove caniusepython3 as a dependency and run make upgrade
- `make upgrade && make requirements` have been run to regenerate …

BOM-1641 | Removed caniusepython3 from edx-enterprise

---

enterprise/admin/forms.py
enterprise/forms.py
enterprise/templates/enterprise/enterprise_customer_login_page.html
enterprise/urls.py
enterprise/utils.py
enterprise/views.py
test_utils/__init__.py
tests/test_enterprise/views/test_enterprise_login_view.py
tests/test_enterprise/views/test_enterprise_selection.py

ENT-2819 | Enterprise's slug login backend changes.

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/admin/__init__.py
enterprise/admin/forms.py
enterprise/api_client/enterprise_catalog.py
enterprise/utils.py
tests/test_admin/test_forms.py

update the catalog preview url to use the catalog service

---

CHANGELOG.rst
enterprise/api/v1/serializers.py
enterprise/api_client/enterprise_catalog.py
enterprise/management/commands/migrate_enterprise_catalogs.py
enterprise/signals.py

There is a signal for `post_save` on the `EnterpriseCustomerCatalog` model. It is triggered when a catalog gets created or updated (e.g., by ECS). In the signal, we attempt to get a catalog with no assumption that it actually exists yet in enterprise-catalog. If it 404s, we know it doesn't exist and we should create a new catalog in the service.
Since we expect to get a 404 when a catalog is first created in the LMS, we should no longer log it as an exception to avoid seeing false positives for the error in the email alerts.

reduce log exceptions that aren't really errors

---

CHANGELOG.rst
enterprise/signals.py
tests/test_enterprise/test_signals.py

The email alerts for enterprise often contain errors related to a user having an `enterprise_learner` system-wide role but not being linked to an enterprise, e.g.:
> May 30 13:17:16 ip-10-2-11-166 [service_variant=lms][enterprise.models][env:prod-edx-edxapp] WARNING [ip-10-2-11-166  23459] [user 4570228] [models.py:2113] - User 4570228 has a <class 'enterprise.models.SystemWideEnterpriseUserRoleAssignment'> of "enterprise_learner" but is not linked to an enterprise. (ID: 135504)
After some digging, I realized a change was implemented (via [ENT-2538](https://openedx.atlassian.net/browse/ENT-2538)) to soft delete `EnterpriseCustomerUser` records by setting `linked = False` instead of doing a full delete of records.
We previously had a signal that triggers the deletion of the …

delete enterprise_learner role assignment on soft delete of EnterpriseCustomerUser records

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/management/commands/seed_enterprise_devstack_data.py

Update seed_enterprise_devstack_data command to include name on user profiles when creating enterprise users since it's technically a required field (without name, things seem to break).

update seed_enterprise_devstack_data command to include name on profiles

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/v1/serializers.py

switch to logger.warning over logger.error

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/models.py
tests/test_models.py

JIRA: https://openedx.atlassian.net/browse/ENT-2912, https://openedx.atlassian.net/browse/ENT-2559

ENT-2912: Added enterprise course enrollment rollback

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/utils.py
tests/test_integrated_channels/test_sap_success_factors/test_exporters/test_content_metadata.py
tests/test_utilities.py

There are situations where a course run is considered "Current" and included in the API response, however it is flagged as "unpublished".  These runs should not be included in the API response.

Consider course run status when determining availability and enrollability

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/views.py
tests/test_enterprise/views/test_grant_data_sharing_permissions.py

JIRA: https://openedx.atlassian.net/browse/ENT-2876

ENT-2876: Update GrantDataSharingPermissionView to accept both, course_run_id as well as course_key in the course_id param

---

CHANGELOG.rst
enterprise/__init__.py
enterprise_learner_portal/api/v1/views.py
enterprise_learner_portal/utils.py
tests/test_enterprise_learner_portal/api/test_views.py

This change allows the client learner portal to simply use a boolean field true instead of a string based field, it does come at the cost of an extra string compare in backend but it used to be implicit now I explicitly check for case insensitive 'true' so works for both current and new usages 
This change will allow the client side code to be optimized to use boolean for marked_done rather than a string.
This is incremental and in near future we will update it to use patch body and process this field as boolean. right now it gets a string 'true' or 'false' due to string based payload. See https://github.com/edx/frontend-app-learner-portal-enterprise/pull/27
Fixes: ENT-3047
https://github.com/edx/frontend-app-learner-portal-enterprise/pull/27
- `base.in` if needed in …

Enrollments endpoint updates to optimize client side frontend learner portal

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/constants.py
enterprise/models.py
enterprise/validators.py
tests/test_models.py

This adds validation for the content_filter field's subfields (filter keys) in both EnterpriseCatalogQuery and EnterpriseCustomerCatalog.
**WIP** - Tests and the rest of this checklist forthcoming.
This is for ticket [ENT-2828](https://openedx.atlassian.net/browse/ENT-2828) 

ENH: Add validation for content filter

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/admin/__init__.py
enterprise/admin/utils.py
enterprise/models.py
enterprise/templates/enterprise/admin/enterprise_course_enrollments_list.html

**Description:** Provides a way to override enrollment attributes for learners.
**JIRA:** [ENT-2998](https://openedx.atlassian.net/browse/ENT-2998)
**Dependency:** https://github.com/edx/edx-platform/pull/24283 

override enrollment attributes for enterprise learners

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/admin/__init__.py
enterprise/api/v1/urls.py
enterprise/api/v1/views.py
enterprise/static/enterprise/admin/enterprise_customer_catalog.js
enterprise/utils.py
tests/test_enterprise/api/test_views.py

Between ENT-2845 and ENT-2577, we've unintentionally broken the saved EnterpriseCatalogQuery functionality.
This PR is selectively restoring it so that it behaves as it did before those changes and
is compatible with the new Enterprise Catalog Service.
**Related PRs:** 
https://github.com/edx/edx-enterprise/pull/776
https://github.com/edx/edx-enterprise/pull/763
Loading EnterpriseCatalogQuery django admin does not result in a 500 error and behaves normally (ie can create, update, and delete EnterpriseCatalogQueries.
Go to the EnterpriseCustomerCatalog django admin. When creating or updating a catalog from this django admin view (not the inline view for EnterpriseCustomers), you should be able to select an EnterpriseCatalogQuery and see the content filter updated …

ENT-2996 Restoring enterprise catalog functionality back to where it was originally

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/views.py

Rather than redirect to the dashboard if consent is not required
for a course, instead redirect to the success url, as if consent
had been granted. Otherwise, the course is inaccessible.
ENT-3049

Re-direct to success url, not dashboard

---

.github/PULL_REQUEST_TEMPLATE.md

update PR template to include bumping edx-platform constraint

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/rules.py

We have other mechanisms for restricting the set of objects visible to an enterprise-linked user; for example, on the enterprise catalog endpoint, there is a filter that only returns results of enterprises the user is linked to, and returns everything if they're staff.  This change should help us not have to worry about doing that kind of filtering in other views that require the `can_access_admin_dashboard` permission. …

Admin dashboard rules predicates now pass an object into the edx-rbac utility functions

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/cornerstone/exporters/content_metadata.py
integrated_channels/utils.py
tests/test_integrated_channels/test_cornerstone/test_exporters/test_content_metadata.py

Ticket: https://openedx.atlassian.net/browse/ENT-3145
There is an error parsing the list of subjects that the LMS gets back from enterprise-catalog when transmitting content metadata to Cornerstone:
```
File "/edx/app/edxapp/venvs/edxapp/lib/python3.5/site-packages/integrated_channels/cornerstone/exporters/content_metadata.py", line 141, in transform_subjects
if subject.lower() in [edx_subject.lower() for edx_subject in edx_subjects]:
AttributeError: 'dict' object has no attribute 'lower'
```
Cornerstone's integrated channel content exporter parses the metadata it gets back from the `get_content_metadata` endpoint in enterprise-catalog. We store this metadata in the enterprise-catalog DB from Discovery's `/api/v1/search/all` endpoint, which has `subjects` as a list of strings. Then, we …

handle when subjects is a list of dicts or list of strings for Cornerstone content exporter

---

enterprise/api/v1/serializers.py
enterprise/api/v1/urls.py
enterprise/api/v1/views.py
tests/test_enterprise/api/test_views.py

This viewset has some special logic to ensure that if the endpoint is called with data that already exists as either a PendingEnterpriseCustomerUser or EnterpriseCustomerUser, we return a 204 No Content. Without this, DRF would just return 400.
- It may or may not make a migration depending on exactly what …

ENT-3139 New viewset/endpoint to create PendingEnterpriseCustomerUser records

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/urls.py
enterprise/utils.py
enterprise/views.py
tests/test_enterprise/views/test_enterprise_proxy_login_view.py

This view exists to allow redirecting unauthenticated learners from the
enterprise learner portal through the appropriate logistration page
while taking advantage of the existing SSO we already have in place.
ENT-3141
- It may or may not make a migration depending on exactly what you modified, but it should …

Add enterprise proxy login view

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/canvas/models.py
tests/test_integrated_channels/test_canvas/test_client.py

This is step 2 of renaming the field 'key', just updating model no migrations here …

Remove field key, part 2 of field rename

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/canvas/exporters/content_metadata.py
integrated_channels/canvas/models.py
test_utils/factories.py
test_utils/fake_catalog_api.py
tests/test_integrated_channels/test_canvas/test_exporters/test_content_metadata.py

Canvas Metadata Exporter

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/v1/views.py
tests/test_enterprise/api/test_views.py

Previously, `LicensedEnterpriseCourseEnrollmentViewSet` used EnterpriseReadOnlyModelViewSet, which introduced model-level permissions for the endpoint, when we really only want to deal with JWTs.
I noticed an unused `EnterpriseWrapperApiViewSet` and tried using that for `LicensedEnterpriseCourseEnrollmentViewSet`, which fixes the permissions issue of a 403 for non-superusers.
Now, I get a valid 204 response without needing to deal with the model-level permissions.
- Checkout the [Database Migration](https://openedx.atlassian.net/wiki/spaces/AC/pages/2300 …

 fix permissions issues with license_revoke endpoint

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/cornerstone/exporters/content_metadata.py
integrated_channels/integrated_channel/constants.py
tests/test_integrated_channels/test_cornerstone/test_exporters/test_content_metadata.py

**JIRA**: https://openedx.atlassian.net/browse/ENT-3288
**Description**:
The modified date coming from CATALOG API is in correct format. However, in case if the modified date of a course_run OR course_run itself does not exist, we use the current datetime as last modified date. This was not being transformed into correct format before transmitting the data. This PR is a fix for it. 
- Checkout the [Database Migration](https://openedx.atlassian.net/wiki/spaces/AC/pages/23003228/Everything+About+Database+Migrations) Confluence page for helpful tips on …

ENT-3288: JSON datetime format error in Cornerstone catalog sync call

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/canvas/client.py
integrated_channels/canvas/models.py
integrated_channels/canvas/transmitters/content_metadata.py
integrated_channels/integrated_channel/management/commands/__init__.py
tests/test_integrated_channels/test_canvas/test_transmitters/test_content_metadata.py

Canvas transmitter

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/admin/views.py
enterprise/models.py
tests/test_models.py

ENT-3199 | Added course mode in ecommerce manual enrollment API.

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api_client/lms.py
tests/test_enterprise/api_client/test_lms.py

Fixed: Manual Order Not Fulfilled

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/filters.py
enterprise/api/v1/views.py
tests/test_enterprise/api/test_filters.py

**Description:** Currently an enterprise learner can still view the enterprise's Learner Portal if the learner was linked to the enterprise, and then unlinked. After these changes, learner will be able to view the learner portal.
**JIRA:** https://openedx.atlassian.net/browse/ENT-3251
- It may or may not …

don't return enterprise customer if learner is not linked

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/canvas/client.py
integrated_channels/canvas/exporters/content_metadata.py
tests/test_integrated_channels/test_canvas/test_client.py

Do an extra PUT to send course image once course is created (only done if image_url is present in content_metadata item) …

ENT-3388: post course image to canvas once course created

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/management/commands/seed_enterprise_devstack_data.py

Two improvements to the Devstack data-seeding command:
* It will now create system worker users (if they don't exist) and openedx_operator roles for them.
* The function to get or create an `EnterpriseCustomer` is now idempotent, by virtue of declaring non-identifying fields as `deafults`.
The hope is that we can begin to point to this script as step 1 of "please help cure my authorization problems".
- Checkout the [Database Migration](https://openedx.atlassian.net/wiki/spaces/AC/pages/23003228/Everything+About+Database+Migrations) Confluence page for …

seed_devstack_data command improvements

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/models.py
enterprise/signals.py
tests/test_models.py
tox.ini

Overrides the `EnterpriseContentCatalog.save()` method to sync the `content_filter` from an associated `EnterpriseCatalogQuery`, if appropriate.  We do this outside of the `post_save` signal handler because it's
an action that might result in a catalog instance having its data updated, which would (a) be inappropriate in a post-save signal handler, and (b) could result in an infinite loop if we weren't careful.
Also adds some logging to the `update_enterprise_catalog_query` signal. …

Sync catalog content from saved query during save() method

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/management/commands/seed_enterprise_devstack_data.py

Allows creation of a multiple enterprises by allowing users to specify an enterprise name
Turns on the learner portal access by default
Prints out the usernames of users created
Works in the same way as before if an enterprise name is not specified
- It may or may not make a migration depending on exactly …

Improve seed data command

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/canvas/client.py
integrated_channels/canvas/exporters/content_metadata.py
tests/test_integrated_channels/test_canvas/test_exporters/test_content_metadata.py

Ok, this PR will address the following changes:
- This one is interesting because course content_type does not have start field so we don't post it. But even if I send a PUT to update the course start date, it only shows on the settings page but not on the syllabus page. So this is a different issue going on. We do send start/end dates when the field is available (such as for course_runs content type)
It will not address the following changes since I cannot find a way to do that (will check with instructure tomorrow as well)
* “Include this course in the public course index”: true (is false by default)
* ”Add a "Join this Course" link to the course home page”: true (in the UI this only shows up once the prior setting is turned on)
* Publish course: do no think this can be done via our …

ENT-3411: Canvas discovery improvements (final touches before MVP)

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/utils.py

[Slack Thread](https://edx-internal.slack.com/archives/CD3L7U2SZ/p1600183223082500) …

using viewname in reverse as part of args to prevent IndexOutOfRange exception

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/views.py

It was noticed while testing SAPSF enrollment using BestRun on prod that SSO login redirect doesn't work for any LP URLs other than the for the dashboard. That's because of the way that the tpa_hint param was added to the URL used in the next param and how it didn't account for URLs that may already have query params. This PR makes use of the update_query_parameters utility function to replace the previous functionality which naively added "?tpa_hint=blah" to the end of the URL.  …

Fixing the construction of the next param in the proxy login view for SSO

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/signals.py

Fixes: https://openedx.atlassian.net/browse/ENT-3406 …

Resave EnterpriseCustomerBrandingConfiguration instance to save logo with correct name and path

---

CHANGELOG.rst
enterprise/__init__.py
tests/test_migrations.py

Trying to prevent the dreaded successful merge to master > fail in edx-platform pipeline.
- This should be run from either a venv with all the lms/edx-enterprise requirements installed or if you checked …

pull platform sync migration test to enterprise.

---

CHANGELOG.rst
enterprise/__init__.py

Bumping integrated channels exception handling improvement

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/signals.py
tests/test_models.py

JIRA: https://openedx.atlassian.net/browse/ENT-3482 …

ENT-3482:Add functionality to save logo in EnterpriseCustomerBrandingConfiguration at only one location

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/management/commands/seed_enterprise_devstack_data.py

Update seed cmd to enable subscription management

---

CHANGELOG.rst
integrated_channels/blackboard/exporters/content_metadata.py
tests/test_integrated_channels/test_blackboard/test_exporters/test_content_metadata.py

- Have a temporary solution to this by adding a link to enrollment_url in the description field but I am too psyched about it, will chat with Ken later today and explore ways to make this better. But this basically allows learners to find edX from the search page at least. …

ENT-3472: blackboard exporter

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/v1/serializers.py
tests/test_enterprise/api/test_views.py

**Description:** For enterprise reporting configuration with SFTP delivery, email field is incorrectly set as required. When we try to add a reporting config from admin portal we get an error. This is not correct behaviour because we don't use email in sftp delivery. Changes in this PR will make email field optional for sftp delivery. 
**JIRA:** [ENT-3442](https://openedx.atlassian.net/browse/ENT-3442)
- Checkout the [Database Migration](https://openedx.atlassian.net/wiki/spaces/AC/pages/23003228/Everything+About+Database+Migrations) Confluence page for …

handle email field for sftp enterprise reporting config

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/v1/views.py
enterprise/models.py
tests/test_enterprise/api/test_views.py

https://openedx.atlassian.net/browse/ENT-3414 …

During revocation, unenroll if audit track does not exist

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/tpa_pipeline.py

Using `strip(-saml)` did not work as intended. This would strip the prefix and part of the actual provider name/slug.
Since we always expect "-saml", I have just excluded the length of `saml-` (ie 5 characters). This will ensure it does not parse out valid parts of the slug as well.
- It may or may not make …

fix saml strip to no longer strip extra characters.

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/blackboard/views.py

WHY?
Since today's exception reporting actually fails during the raise line meaning we don't actually get to see what the `auth_response` details were. I am getting a failure in staging that does not reproduce locally for me and it's great to be able to see the status_text, response of the response object at least
also handles the two cases KeyError and ValueError differently since they are for different reasons and have different pieces of info available in except blocks …

ENT-3557: improve exception reporting for authfailure blackboard

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/blackboard/client.py
integrated_channels/blackboard/exporters/content_metadata.py
tests/test_integrated_channels/test_blackboard/test_client.py
tests/test_integrated_channels/test_blackboard/test_exporters/test_content_metadata.py

Adding blackboard course integration customization

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/moodle/exporters/content_metadata.py
tests/test_integrated_channels/test_moodle/test_exporters/test_content_metadata.py

- Adds transformations for shortname and title (known as fullname in Moodle) …

moodle - update to preferred format.

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/admin/__init__.py
enterprise/admin/actions.py
enterprise/api_client/enterprise_catalog.py
tests/test_enterprise/api_client/test_enterprise_catalog.py

add action to kick off refreshing catalogs

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/admin/__init__.py
enterprise/middleware.py
enterprise/signals.py
enterprise/utils.py
tests/test_admin/test_view.py
tests/test_middleware.py

ENT-3522: Unset learners language so that default_language from enterprise customer may take effect.

---

CHANGELOG.rst
enterprise/__init__.py

version upgrade

---

CHANGELOG.rst
consent/mixins.py
enterprise/__init__.py

add logs to know if data sharing consent is failing because catalog does not contain the course

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/blackboard/client.py
integrated_channels/blackboard/exporters/content_metadata.py
tests/test_integrated_channels/test_blackboard/test_client.py
tests/test_integrated_channels/test_blackboard/test_exporters/test_content_metadata.py

finalization on integrated Blackboard course content structure

---

.gitignore
CHANGELOG.rst
enterprise/__init__.py
enterprise/signals.py
requirements/constraints.txt
requirements/dev.txt
requirements/doc.txt
requirements/edx-platform-constraints.txt
requirements/js_test.txt
requirements/test-master.txt
requirements/test.txt
requirements/travis.txt
test_utils/factories.py
tests/test_enterprise/test_signals.py
tests/test_models.py

Why? To bring enterprise in line with platform wrt pytest
Notes:
1: pytest 6 now fails on logging errors (instead of prior where used to go to stderr), courtesy Alex:
[#6433:](https://github.com/pytest-dev/pytest/pull/7231/files) If an error is encountered while formatting the message in a logging call, for example logging.warning("oh no!: %s: %s", "first") (a second argument is missing), pytest now propagates the error, likely causing the test to fail.
Previously, such a mistake would cause an error to be printed to stderr, which is not displayed by default for passing tests. This change makes the mistake visible during testing.
You may supress this behavior temporarily or permanently by setting logging.raiseExceptions = False.
2: here is a logging exception in the signal handler that …

ENT-3279: Upgrade to pytest 6+ (and factoryboy 3+)

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/admin/__init__.py
enterprise/signals.py
tests/test_admin/test_view.py
tests/test_models.py

ENT-3522: Updated the logic to clear enterprise learner language in a way that db lock does not happen.

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/utils.py

ENT-3522: Fix timeout error on update

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/utils.py

ENT-3680: Fixes the issue where user preference value can not be null.

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/admin/forms.py
enterprise/admin/views.py
enterprise/api/v1/views.py
enterprise/api_client/lms.py
enterprise/utils.py
tests/test_admin/test_forms.py
tests/test_admin/test_view.py

ENT-3597
Modifies the bulk csv upload tool in the "Manage Learners" screen to accept an optional "course_id" column to support enrolling users in multiple courses at once. Currently, the form only allows a single course for all uploaded users.
- It may or may not make a migration depending on exactly what …

Allow bulk enroll in several courses via CSV from Manage Learners screen

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/signals.py
tests/test_enterprise/test_signals.py

ENT-3531
- This should be run from either a venv with all the lms/edx-enterprise requirements installed or if you checked out edx-enterprise into the src directory used by lms, you can run this command …

Refresh catalog metadata on create and update

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api_client/enterprise_catalog.py

**NOTE:** Most of the file changes here is just from me adding retry and running make upgrade. This is an optional change. Retry doesn't have any new dependencies so it seemed a simple lightweight wrapper to help with connection errors while I was dealing with them for other reasons.
- It may or may not make …

ENT-3700 Bug fix - raise instead of return empty

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/admin/views.py
enterprise/api/v1/views.py
enterprise/management/commands/seed_enterprise_devstack_data.py
enterprise/tpa_pipeline.py
enterprise/utils.py
integrated_channels/xapi/management/commands/send_course_enrollments.py

Previously, code from these djangoapps could be imported without
the 'common.djangoapps' prefix. For example, one could write
'from student import models' intead of
'from common.djangoapps.student import models'.
This import pattern unidiomatic and is now deprecated. See
[edx-platform/docs/decisions/0007-sys-path-modification-removal.rst](https://github.com/edx/edx-platform/blob/master/docs/decisions/0007-sys-path-modification-removal.rst)
for details and justification.
Related to https://github.com/edx/edx-platform/pull/25477
_____________________________
Update -- People are seeing this error on Devstack:
```
RuntimeError: Conflicting 'oauth2providerconfig' models in application 'third_party_auth': <class 'third_party_auth.models.OAuth2ProviderConfig'> and <class …
```

Prefix edx-platform/common/djangoapps imports with 'common.djangoapps'

---

enterprise/models.py
enterprise/tpa_pipeline.py
tests/test_models.py

ENT-3586 Change identity_provider property to support multiple identity_providers

---

enterprise/api/v1/serializers.py
tests/test_enterprise/api/test_views.py

ENT-3588: Updated EnterpriseCustomerCourseEnrollmentsSerializer.validate_tpa_user_id to account for multiple IdPs

---

enterprise/views.py
tests/test_enterprise/views/test_enterprise_proxy_login_view.py

JIRA: https://openedx.atlassian.net/browse/ENT-3591
**A.C:**
- enterprise/proxy-login should redirect to the IDP if there is only one IDP linked to the enterprise customer.
- if user has provided IDP in requested URL, user redirected to that IDP login Page.
- if there are multiple IDPs linked to the customer and tpa_hint is also not provided in query_string params then redirect to the normal login page.
- if there is not an IDP, then the user should be redirected to the normal login page. …

ENT-3591: update EnterpriseProxyLoginView

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/v1/serializers.py
enterprise/utils.py
test_utils/__init__.py
tests/test_utilities.py

ENT-3627: Add end date to course level metadata

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/utils.py
tests/test_utilities.py

ENT-3781: Course run end date bug fix in catalog api

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/utils.py
tests/test_utilities.py

This PR fixes the bug that came in catalog api `max() arg is an empty sequence`. The bug comes when all of the course runs end dates are `null`.
**JIRA**: https://openedx.atlassian.net/browse/ENT-3781
- …

ENT-3781: Empty sequence bugfix

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/v1/views.py
tests/test_enterprise/api/test_views.py

edx-platform gives error while upgrading drf version to 3.10 due to enterprise.
https://openedx.atlassian.net/browse/BOM-2130
This issue is caught by `make docs` inside edx-platform. Tests failed to capture this issue.
https://www.django-rest-framework.org/community/3.8-announcement/#action-decorator-replaces-list_route-and-detail_route
Both list_route and detail_route are now pending deprecation. They will be deprecated in 3.9 and removed entirely in 3.10.
The new action decorator takes a boolean detail argument.
Replace detail_route uses with @action(detail=True).
Replace list_route uses with @action(detail=False).

Both list_route and detail_route removed in drf = 3.10

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/constants.py
enterprise/utils.py
tests/test_enterprise/api/test_views.py
tests/test_enterprise/test_utils.py

**ENT-3723:**
As part of the rebranding effort, `get_logo_url` is being updated. Since `get_logo_url` will always return an absolute URL, we can remove the use of `urljoin` in `get_platform_logo_url`
[Associated edx-platform PR](https://github.com/edx/edx-platform/pull/25654) …

ENT-3723: Rebranding update: more robust get_platform_logo_url and Learner Portal default colors update

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/canvas/exporters/learner_data.py

Whoops, didn't retrieve course key correctly. …

BUG: course key retrieval fix

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/integrated_channel/tasks.py

Adding missed decorators to integrated channel tasks

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/models.py
enterprise/signals.py
enterprise/utils.py
test_utils/factories.py
tests/test_enterprise/test_signals.py

https://openedx.atlassian.net/browse/ENT-3884
Related PR: https://github.com/edx/frontend-app-admin-portal/pull/421
Previously, admin permissions were granted to the user based on the creation/update of an `EnterpriseCustomerUser` record through a Django signal. However, if a user is already linked to an `EnterpriseCustomer`, there is no creation/update of an `EnterpriseCustomerUser` record so the admin permissions were never granted on their next login.
Instead, the granting of admin permissions was moved to coincide whenever a user logs in instead so that we will always grant the correct access roles on each login.
- `make …

ENT-3884: refactor ``handle_user_post_save`` signal to account for admin permissions

---

.github/workflows/publish.yml

fix: use python38 in publish.yml as faker>5 dropped python35 support

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/blackboard/exporters/content_metadata.py

More tweaks to course creation may yet come but this refactors the content title within the integrated course.  …

First cleanup of changing content title

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/sap_success_factors/client.py

Description: This PR adds exception handling for TypeError when the OAuth2 response is, unexpectedly, of type list.
JIRA: https://openedx.atlassian.net/browse/ENT-3688
- This should be run from either a …

ENT-3688: Added TypeError exception handler

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/blackboard/exporters/content_metadata.py

^ no visual changes to the integrated blackboard edX content, just an html target added to the hyperlink
- This should be run from either a venv with all the lms/edx-enterprise requirements installed or …

Removing external link warning by opening enrollment url in a new tab

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/models.py
enterprise/signals.py
tests/test_enterprise/test_signals.py

fix: query EnterpriseCustomerUsers with both user_id and enterprise_customer

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/v1/views.py
enterprise/errors.py
enterprise/management/commands/seed_enterprise_devstack_data.py
tests/test_enterprise/api/test_views.py

**Overview**
As part of the work to expire a subscription plan we need to change active licensed course enrollments to be either in the audit track if available, or the learner gets unenrolled if it isn't.
- It may or may not make a migration depending on exactly what you modified, but it should still be …

refactor revoking a course enrollment, create task

---

CHANGELOG.rst
enterprise/__init__.py
enterprise_learner_portal/api/v1/serializers.py
enterprise_learner_portal/utils.py
tests/test_enterprise_learner_portal/test_utils.py

This PR modifies the `get_course_run_status` util function such that if a learner has a passing certificate, it will always return the course as "completed". This results in the following cases:
1. Enrollment saved for later --> `CourseRunProgressStatuses.SAVED_FOR_LATER`
1. Course has started but not ended --> `CourseRunProgressStatuses.IN_PROGRESS`
1. Course has ended --> `CourseRunProgressStatuses.COMPLETED`
1. Learner has passing certificate --> `CourseRunProgressStatuses.COMPLETED`
1. Course has not started --> `CourseRunProgressStatuses.UPCOMING` …

fix: always return "completed" course run status if learner has a passing certificate

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/tpa_pipeline.py

```
The correct import path is
`common.djangoapps.third_party_auth`.
Support for the unqualified import path will soon
be dropped.
Bump version to 3.17.9
```
This is related to the [the impending removal of support for deprecated edx-platform import paths](https://github.com/edx/edx-platform/pull/25932).

Fix deprecated third_party_auth import

---

integrated_channels/canvas/client.py
integrated_channels/canvas/exporters/content_metadata.py
tests/test_integrated_channels/test_canvas/test_exporters/test_content_metadata.py

In order to make the integrated course discoverable on Canvas, we need to set it to be a part of the public index.  …

Setting courses to the Canvas public index by default

---

CHANGELOG.rst

I forgot to actually release 3.17.11 and in the process we ended up with the same version having two different descriptions in the Changelog. I've merged these together.
We're fine with this going out whenever there is another release instead of an immediate push. …

fix changelog ordering

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/admin/__init__.py
enterprise/constants.py

Conditionally allows the deletion of individual EnterpriseCourseEnrollment records and related
LicensedEnterpriseCourseEnrollment records via the Django Admin site, so that site admins can manually
delete enterprise enrollments that were created in error.
This is only allowed if a Django settings feature flag is set to True.
How I manually tested - 
1. Create a licensed enterprise enrollment for the `verified@example.com` user in the pied-piper customer: 
2. As a site admin, visit the Django Admin for enterprise enrollments, see that I'm allowed to delete this one (I toggled the feature on in my local settings):
3. Click delete, get the confirmation screen that shows me I'll delete both the Enterprise Course Enrollment and the LicensedEnterpriseCourseEnrollment record: 
4. After …

Conditionally allows the deletion of individual EnterpriseCourseEnrollment records

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/models.py
tests/test_models.py

In ``SystemWideEnterpriseUserRoleAssignment``, Use either ``applies_to_all_contexts`` or ``enterprise_customer``
if they are True or non-null, respectively, in determining the result of ``get_context()``,
but continue to return list of all linked enterprise customer UUIDs if not, (which is the current behavior).
This is a small step on our journey to explicitly defining user-role assignments
*Manual Testing*
1. Give a user 2 explicit assignments for `enterprise_learner`, to two different enterprise customers, make sure there's a JWT role entry for both:
2. Give a user the `enterprise_admin` role with `applies_to_all_contexts` set to true, see that their JWT role has an `enterprise_admin:*` entry:
3. Give a user the `enterprise_openedx_operator` role, set `applies_to_all_contexts` to …

version 3.17.15 | Update get_context()

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/models.py
enterprise_learner_portal/api/v1/serializers.py
tests/test_enterprise_learner_portal/api/test_serializers.py

fix: add mode to enterprise_course_enrollments endpoint

---

integrated_channels/sap_success_factors/client.py

SAP's documentation (and our code) dictate an error format in the response of:
```
{error: {code: '', message: ''}}
```
However, certain errors are getting sent simply as a string, such as: `error: 'invalidResponse'`
This wraps the logging we were doing to allow us to log those string errors as well.
- It …

SAP Bug Fix: Handle Different Error Format.

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/integrated_channel/exporters/learner_data.py
integrated_channels/sap_success_factors/client.py
integrated_channels/utils.py
tests/test_integrated_channels/test_sap_success_factors/test_client.py

Bringing SAP integrated channel's client exception handling up to date with the other channels. Adding status code safeguard check to the `is already transmitted` method.
- This should be run from either …

Catching client errors in SAP IC.

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/blackboard/transmitters/learner_data.py
integrated_channels/canvas/exporters/learner_data.py
integrated_channels/canvas/transmitters/learner_data.py
integrated_channels/integrated_channel/transmitters/learner_data.py
tests/test_integrated_channels/test_canvas/test_transmitters/test_learner_data.py
tests/test_integrated_channels/test_cornerstone/test_exporters/test_content_metadata.py

Our assessment level transmissions were using the completion level audits as the model name. 
For testing, the bugs found addressed in this PR came from testing on staging, so testing will be done on stage after this is merged.
No migrations needed.
- It may or may not make a migration depending on exactly …

Assessment level transmissions deal should have assessment level audits

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/canvas/client.py

Hitting the endpoint via the browser reveals the response:
We are using the user's email to identify them on the edX side, so we need to use the `login_id` to accurately compare. I'm not sure if something changed here or what... it worked locally to use the id  ¯\_(ツ)_/¯
[jira ticket](https://openedx.atlassian.net/browse/ENT-4101)
- *Note*: This **must** be run if …

Erroneously comparing canvas user int ID to user email 

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/sap_success_factors/exporters/learner_data.py

When sap fails to create learner data records (due to remote user ID retrieval failing) we "logged" that it was unable to complete. BUT that log is set to debug so we don't actually see anything on prod. …

Change logging debug to info

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/integrated_channel/tasks.py

No migrations needed. No need to have a release just for this.
- This should be run from either a venv with all the lms/edx-enterprise requirements installed or if you checked out edx-enterprise into the …

changing docs to accurately reflect behavior

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/integrated_channel/exporters/learner_data.py
integrated_channels/integrated_channel/tasks.py

Jira: https://openedx.atlassian.net/browse/ENT-4101
It's difficult to tell if a particular learners transmission has begun as there are no logs except for the "completed transmission" one at the very end. …

Adding informative logs to the single learner transmission task

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/tpa_pipeline.py

Jira ticket: https://openedx.atlassian.net/browse/ENT-3568
[Since roughly Dec 2020](https://splunk.edx.org/en-US/app/search/search?q=search%20reverse(%27enterprise_select_active%27)&display.page.search.mode=smart&dispatch.sample_ratio=1&earliest=0&latest=&sid=1612887358.17411684) we have been throwing exceptions In the enterprise logistration flow. 
When an enterprise user signs in with SSO and the social user's account is new or already binded with an edx account (and has multiple enterprise customers), we attempt to insert the `select active enterprise` page redirect in between where they are currently and the user's next redirect (presumably the dashboard?). However, we are failing to concatenate the redirects with either `strategy.session_get('next')` or …

Prevent NoneType with string concatination exception 

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/moodle/exporters/content_metadata.py
tests/test_integrated_channels/test_moodle/test_exporters/test_content_metadata.py

JIRA: https://openedx.atlassian.net/browse/ENT-3994 …

Update course title to include '- via edX.org'

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/integrated_channel/management/commands/__init__.py
integrated_channels/integrated_channel/management/commands/transmit_subsection_learner_data.py
integrated_channels/integrated_channel/tasks.py
tests/test_management.py

Bulk assessment level data transmissions were being sent out to all channels, including those that don't support it.
Similarly single learner transmissions would be sent to unsupported channels.
Added a fix to support filtering on channel retrieval and unit testing to make sure newly supported channels are filtered.
- *Note*: This **must** be run if you modified any …

allowing for channel retrieval to filter for assessment reporting support.

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/models.py
enterprise/tasks.py
enterprise/views.py

https://openedx.atlassian.net/browse/ENT-4036
Ensure we always create an `EnterpriseCourseEnrollment` _after_ the regular `CourseEnrollment` is successfully created/updated. This may help with the `EnterpriseCourseEnrollments` existing without an associated `CourseEnrollment` record. Interestingly enough, of these affected enrollments, none of them have any corresponding data in the `CourseEnrollment` history table.
This PR also fixes a couple logger messages that weren't logging much useful for debugging purposes. …

[ENT-4036] reorder some enrollment logic and fix some logs

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/canvas/client.py
tests/test_integrated_channels/test_canvas/test_client.py

Jira ticket: https://openedx.atlassian.net/browse/ENT-4148
Since assessment level and completion reporting are both implemented independently of each other and both use the same Canvas assignment object system to post their data, if one or both aren't omitted from the learner's final grade then the points the user earned will be inconsistent.
Example of current behavior:
Because both assessment data and completion data are included in the user's final grade, we have the appropriate percentage, but the `Out of` points fraction has points from both.
There are two ways around this, we can either exclude the edx "final grade" or the assessment level grades from the user's final grade. As the assessments can be weighted inconsistently with the edX learner's total grade, and the "final grade" …

omitting integrated assessment level canvas grades from final grade

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/views.py
requirements/dev.txt
requirements/doc.txt
requirements/edx-platform-constraints.txt
requirements/test-master.txt
requirements/test.txt

Manually changed the django-ipware version because it is pinned in platform, and platform needs updated version in enterprise to work. 
Relevant JIRA : https://openedx.atlassian.net/browse/BOM-1982

BOM-1982 : Unpin django-ipware

---

enterprise/views.py

Supports: https://github.com/edx/frontend-app-learner-portal-enterprise/pull/206 and ENT-4024 …

Committing ability of request to override text that appears on page.

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/models.py
tests/test_integrated_channels/test_integrated_channel/test_exporters/test_learner_data.py

Property call here was causing rate limiting when used in bulk jobs for integrated channels. …

Removing uneeded API call in favor of direct model import.

---

enterprise/api/v1/views.py
tests/test_enterprise/api/test_views.py

JIRA: ENT-4091
Fixes:
Testing notes:
Tested by
[1] typing in multiline emails in textarea and hitting enroll learners and checking enrollments were created
[2] uploading csv file that looked like attached and repeating
```
email
learner1@example.com
learner2@example.com
```
as per required format (email first one is used as a header and also dict key)
at http://localhost:1991/test-enterprise/admin/catalog_management?features=BULK_ENROLLMENT
checked frontend response too like '2 learners enrolled' …

ENT-4091: handle email_csv case and also multi line when pasting emails on multiple lines in textfield

---

CHANGELOG.rst
enterprise/__init__.py

Just changelog missed in last PR. will release this one to release ENT-4091 …

feat: missed changelog ENT-4091

---

CHANGELOG.rst
enterprise/__init__.py

Whoops
- This should be run from either a venv with all the lms/edx-enterprise requirements installed or if you checked out edx-enterprise into the src directory used by lms, you can run this command …

Version bump that was forgotten in previous commit.

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/v1/serializers.py
enterprise/api/v1/views.py
enterprise/utils.py
enterprise/views.py
tests/test_enterprise/api/test_views.py
tests/test_enterprise/test_utils.py
tests/test_enterprise/views/test_grant_data_sharing_permissions.py

fetch the course modes instead and select the best fitting. …

removing course mode from bulk enrollment required params 

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/roles_api.py
tests/test_roles_api.py

fix: Adds the catalog admin role to roles_api.roles_by_name().

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/management/commands/update_role_assignments_with_customers.py
tests/test_management.py

The update_role_assignments_with_customers command no longer deletes open assignments.  Allowing it to do so
left us prone to error when an explicit enterprise_customer_uuid arg is provided.  We should modify this command
in the future to perform deletions of open assignments as its only action, and it should only be invoked this way
after we have verified that all backfilled enterprise_customer fields on the assignments have been set correctly.
ENT-4099.
- Checkout the [Database Migration](https://openedx.atlassian.net/wiki/spaces/AC/pages/23003228/Ever …

fix: Don't try to delete "open" assignments just yet

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/utils.py
test_utils/fake_catalog_api.py
tests/test_utilities.py

With current logic, even unpublished courses are considered when deciding which course run a course should resolve to, when a user hits the enrollment landing page. This change takes out the unpublished (or more accurately course_runs with status != 'published' ) from consideration
There are no known use cases when unpublished courses should be considered for this page. See: https://edx-internal.slack.com/archives/CDXAQ8G02/p1615818761060100
This is expected to fix course `course-v1:NYIF+CR.3x+2T2020`
There are two other courses mentioned in the ticket, which may or may not be handled by this fix. But I would love to verify from stage/prod before making any more changes.
Also this causes older course runs like the one reported in the ticket to be picked up which may not even have content …

fix: ENT-3954 filter out unpublished courses from enrollment

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/management/commands/update_role_assignments_with_customers.py
tests/test_management.py

It only creates new records, which helps de-risk the operation.
See updates AC in https://openedx.atlassian.net/browse/ENT-4099 for explanation of future steps.

fix: The update_role_assignments_with_customers command no longer updates records

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/v1/serializers.py
enterprise/api/v1/views.py
tests/test_enterprise/api/test_views.py

This PR also re-organizes tests; it may be best to review it commit by commit.
Much of the "new" code in the test file may just be code that is has been moved; please focus on the PendingEnterpriseCustomerUser stuff.
- It may or may not make a migration depending on exactly what you modified, but it should …

Add support for creating multiple pending users

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/v1/serializers.py
enterprise/api/v1/urls.py
enterprise/api/v1/views.py
tests/test_enterprise/api/test_views.py

Allows admins to link learners (ie, create EnterpriseCustomerUsers or PendingEnterpriseCustomerUsers) for their enterprise …

Add new endpoint for ent admins to link learners

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/utils.py
enterprise/views.py
tests/test_enterprise/views/test_grant_data_sharing_permissions.py

**For enterprises with DSC disabled:**
**For enterprises with DSC enabled:** …

allow upgrading from audit into verified for enrollments made in B2C

---

CHANGELOG.rst
consent/models.py
enterprise/__init__.py
tests/test_consent/test_helpers.py
tests/test_models.py

JIRA: https://openedx.atlassian.net/browse/ENT-2010 …

ENT-2010: Improve efficiency of the data sharing consent flow

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/blackboard/exporters/learner_data.py
integrated_channels/canvas/exporters/learner_data.py
integrated_channels/catalog_service_utils.py
integrated_channels/cornerstone/exporters/learner_data.py
integrated_channels/degreed/exporters/learner_data.py
integrated_channels/integrated_channel/exporters/content_metadata.py
integrated_channels/integrated_channel/exporters/learner_data.py
integrated_channels/lms_utils.py
integrated_channels/moodle/exporters/learner_data.py
integrated_channels/sap_success_factors/exporters/learner_data.py
tests/test_integrated_channels/test_catalog_service_utils.py
tests/test_integrated_channels/test_cornerstone/test_exporters/test_learner_data.py
tests/test_integrated_channels/test_integrated_channel/test_exporters/test_learner_data.py
tests/test_integrated_channels/test_lms_utils.py

Replace api calls with utils/database calls to fetch grade and cert info
These two remaining api calls should clear out all LMS api calls from IC code base (leaving just api calls to LMS-external services):
Reason:  I want to test this outgoing PR in staging with at least one LMS first then will add a new PR to handle this piece to avoid making this PR too large to test.
- Checkout the [Database Migration](https://openedx.atlassian.net/wiki/spaces/AC/pages/23003228/Everything+About+Database+Migrations) Confluence page for helpful tips on creating …

ENT-4222 : replace REST api calls to LMS for certificate and grade data fetch

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/v1/serializers.py
tests/test_enterprise/api/test_views.py

**Jira Ticket:** [ENT-4310](https://openedx.atlassian.net/browse/ENT-4310)
__Description:__
This PR adds the ability to link/unlink enterprise customer catalogs with enterprise reporting configuration via its API endpoint.
- It may or may not make a migration depending on exactly what you modified, but it …

ENT-4310: Added the ability to link/unlink enterprise customer catalogs with enterprise reporting configuration via its API endpoint.

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/admin/__init__.py

* allow searching of enterprise customer records with hyphenated uuid
* add typeahead search dropdown to imporve enterprise customer search on enterprise reporting configuration
- This …

feat: improve search for enterprise customer and enterprise customer reporting configuration

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/management/commands/email_drip_for_missing_dsc_records.py
tests/test_enterprise/management/test_email_drip_for_missing_dsc_records.py

ENT-4391: Added management command for tracking users without DSC

---

integrated_channels/integrated_channel/exporters/learner_data.py
integrated_channels/lms_utils.py
tests/test_integrated_channels/test_cornerstone/test_exporters/test_learner_data.py
tests/test_integrated_channels/test_integrated_channel/test_exporters/test_learner_data.py
tests/test_integrated_channels/test_lms_utils.py

Update:
Going to do a separate PR for this one:
The above needs a edx-platform PR to be merged first
This PR only includes the following: …

refactor: Refactor part 2 to remove additional remaining api calls to LMS via REST

---

CHANGELOG.rst
enterprise/__init__.py

forgot version in prior PR for ENT-4222
- This should be run from either a venv with all the lms/edx-enterprise requirements installed or if you checked out edx-enterprise into the src directory used by …

refactor: version update for ent-4222 part ii

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api_client/enterprise_catalog.py
enterprise/management/commands/migrate_enterprise_catalogs.py
enterprise/signals.py
test_utils/factories.py
tests/test_enterprise/api/test_views.py
tests/test_enterprise/api_client/test_enterprise_catalog.py
tests/test_enterprise/test_signals.py
tests/test_models.py

Fixes: [ENT-4428](https://openedx.atlassian.net/browse/ENT-4428)
Pass catalog query uuid into the update/create request to ent-catalog …

feat: passing catalog query uuids into update/create requests

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/management/commands/migrate_enterprise_catalogs.py
enterprise/signals.py

Related to adding ent catalog query uuid to the creation request to `enterrpise-catalog` work …

BUG: catalog query param should not be stringified when None

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/admin/__init__.py

* Deletes custom get_search_results() method, since `enterprise_customer__name` is now a viable search field
* Improves pagination by asking for an estimated row count from Mysql INFORMATION_SCHEMA.TABLES
* Turns 1 + N query into 1 query via proper use of list_select_related
https://openedx.atlassian.net/browse/ENT-4384
1. Select all the roles (very quick, small number of roles) for dropdown/filter.
2. Get an estimate of total rows from INFORMATION_SCHEMA (very quick)
2a. If the list is actually a search result, we'll do a real `count()` against the filtered queryset.  This will typically be a small queryset - most usage is to find assignments for specific learners, or all assignments for an enterprise customer.
3. One query to get assignments and all related objects, ordered by the PK of …

fix: improves performance of enterprise role assignment admin page

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/v1/urls.py
enterprise/api/v1/views.py
tests/test_enterprise/api/test_views.py

* Add dashboard admin rbac role permission on tableau auth view so that only enterprise dashboard admins can access this view.
* Add support to generate tableau auth token based on incoming enterprise uuid
**JIRA:** https://openedx.atlassian.net/browse/ENT-4413 …

feat: tableau auth view improvements

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/v1/serializers.py
enterprise/api/v1/views.py
tests/test_enterprise/api/test_views.py

[ENT-4154](https://openedx.atlassian.net/browse/ENT-4154)
```json
{
"next": null,
"previous": null,
"count": 2,
"num_pages": 1,
"current_page": 1,
"start": 0,
"results": [
{
"uuid": "bdd488ad-3f6e-49b7-9fb4-99443afad65f",
"name": "Test Enterprise",
"slug": "test-enterprise",
"enterprise_customer_catalogs": [
"d0e5d354-205c-4cae-85c2-eb9abdf5b382"
]
}
]
}
```
1. Ensure your devstack has at least one `EnterpriseCustomer` configured with an enterprise catalog.
2. Visit http://localhost:18000/enterprise/api/v1/enterprise-customer/.
3. Observe additional `enterprise_customer_catalogs` field in the response containing a list of catalog UUIDs.
- `make …

fix: add list of enterprise catalog uuids to EnterpriseCustomerSerializer

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/models.py

It's been removed in platform
- This should be run from either a venv with all the lms/edx-enterprise requirements installed or if you checked out edx-enterprise into the src directory used by lms, you …

fix: don't call into email_marketing anymore

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/v1/urls.py
enterprise/api/v1/views.py

**Description:** Make enterprise customer uuid mandatory for tableau auth view.
**JIRA:** https://openedx.atlassian.net/browse/ENT-4485 …

feat: make enterprise customer uuid mandatory for tableau auth view

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/management/commands/email_drip_for_missing_dsc_records.py

ENT-4522: Fixed timezone issue for course start date comparison

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/management/commands/email_drip_for_missing_dsc_records.py
package-lock.json
tests/test_enterprise/management/test_email_drip_for_missing_dsc_records.py

added support for enrollment_before and --no-commit in email_drip_for_missing_dsc_records command
https://openedx.atlassian.net/browse/ENT-3971 …

ENT-3971: Leverage ENT-3970's Drip to email historical enrollments with DSC issue

---

enterprise/management/commands/seed_enterprise_devstack_data.py

Allows for repeated running of the following command for easy creation of fresh enterprise setup on devstack:
By default no system level enterprise_admin user will exist in seed data.
Usage: 
1. `make lms-shell` to get into the lms. 
2. `./manage.py lms seed_enterprise_devstack_data --name '"My Test Enterprise for Ticket 1234"`
Result will be an admin, learners, enterprise etc all keyed to the new enterprise only.  …

feat: :construction: Add enterprise to seeded users and roles

---

CHANGELOG.rst
enterprise/__init__.py
enterprise_learner_portal/api/v1/views.py
tests/test_enterprise/management/test_email_drip_for_missing_dsc_records.py
tests/test_enterprise_learner_portal/api/test_views.py

Why?
Learners cannot even get into a course page or the learner portal in general in any useful way. until this is fixed. This case occurs when the `enterprise_course_enrollments` endpoint is called and it encounters even 1 EnterpriseCourseEnrollment records, whose self.course_enrollment is None. This can happen for direct integrations, even though the exact root cause is not yet known. Still since the learner is not even enrolled officially yet, we should really not block the learner
This is a high value add change that makes learners able to use the learner poratl even while we investigate the underluing causes of the bad records.
What is included?
* - [x] The fix: Just a filtering of the enrollments once they are fetched, to exclude any with absent course_enrollment properties (it's a …

fix: :bug: ENT-4525 do not process enterprise enrollments without matching courseEnrollment

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/management/commands/email_drip_for_missing_dsc_records.py
tests/test_enterprise/management/test_email_drip_for_missing_dsc_records.py

ENT-4522: Added support for checking course access by learner

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/management/commands/email_drip_for_missing_dsc_records.py

ENT-4522: Added check for enterprise DSC configuration in missing DSC drip

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/management/commands/email_drip_for_missing_dsc_records.py

ENT-4522: Added exception handling in consent missing email

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/management/commands/email_drip_for_missing_dsc_records.py
tests/test_enterprise/management/test_email_drip_for_missing_dsc_records.py

Description: This PR adds a sequential order to the multiple conditions that define the absence of a data sharing consent. This will reduce the computational and logging overhead of the command.
- This …

ENT-4567: Optimised handling of conditions defining the absence of a DSC

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/canvas/client.py

Going forward only conclude courses instead of delete, so we can bring it back to 'offer' state later with an update operatoin or create_or_update operation
Ref: https://canvas.instructure.com/doc/api/courses.html#method.courses.destroy
JIRA: ENT-4593
* send over a course: sent this one:
sent this https://edx.instructure.com/courses/6074/settings
* remove from catalog to 'conclude' it
removed `        "edX+99887766"` from catalog
* transmit again
```
Preparing to transmit deletion of [2] content metadata items with plugin configuration [<CanvasEnterpriseCustomerConfiguration for Enterprise Test Enterprise>]: [['course-v1:edX+99887766+2T2021', 'edX+99887766']]
```
there were two items: one for course and one for course run
* verify course shows in concluded state in canvas
checked that …

fix: :bug: Change delete to conclude, when processing delete_content_metadata

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/integrated_channel/admin/__init__.py

Tried to make these workflows available via app-permissions, but didn't realize we have code in place to prevent their access regardless of app-permissions.  This seems unnecessary to me, so I'm submitting this PR to remove the hardcoded constraints.
@georgebabey @edx-abolger FYI …

Remove hardcoded workflow constraints in order to utilize app-permissions framework

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/management/commands/email_drip_for_missing_dsc_records.py

ENT-4567: reduced the url params size for missing DSC Segment event

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/views.py

Log more specific information about HTTP client errors that are caught when using the LMS
enrollment API.  Also send an exception event to the monitoring service when this happens, even
though we handle the exception "gracefully".
https://openedx.atlassian.net/browse/ENT-4455
The current logged exception message is
```
Unable to create an LMS enrollment from the DSC view: 
Client Error 400: https://courses.edx.org/api/enrollment/v1/enrollment
```
...which is not helpful.  In the DSC `get()` handler, we do log some info about licensed enrollments failing (when catching the exception raised from `_enroll_learner_in_course()`, but that's only in the case that the enterprise customer has DSC disabled, and it doesn't tell us about _why_ the enrollment API objects to the client request.  This …

feat: log more specific information about HTTP client errors during enrollment

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/management/commands/unlink_enterprise_customer_learners.py

ENT-4655 | CAT-1 | added --skip-unlink param in unlink_enterprise_customer_learners command to just remove DSC records.

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api_client/lms.py
tests/test_enterprise/api_client/test_lms.py

**The problem**: Fetching course enrollments through our Enrollment API Client fails for users whose username starts with `_`. Seriously.
Slumber is just making `getattr` fail for resources that start with underscore: https://github.com/samgiles/slumber/blob/master/slumber/__init__.py#L29-L34 
This modifies the `EnrollmentApiClient` to do what slumber does _after_ raising an `AttributeError`, so that we'll get back a `slumber.Resource` object we can use to make our request:
```python
c = EnrollmentApiClient()
c.connect()
username = '_alex'
course_id = 'course-v1:abc'
endpoint = c._get_underscore_safe_endpoint('{},{}'.format(username, course_id))
endpoint.url()
c.get_course_enrollment(username, course_id)
```
Fixes:
* Many of the failures captured in …

fix: slumber underscore shenanigans

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/utils.py

ENT-4611: added an update api call to assign tableau user roles

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/blackboard/exporters/learner_data.py
integrated_channels/canvas/exporters/learner_data.py
integrated_channels/cornerstone/exporters/learner_data.py
integrated_channels/degreed/exporters/learner_data.py
integrated_channels/integrated_channel/exporters/learner_data.py
integrated_channels/integrated_channel/tasks.py
integrated_channels/integrated_channel/transmitters/learner_data.py
integrated_channels/moodle/exporters/learner_data.py
integrated_channels/sap_success_factors/client.py
integrated_channels/sap_success_factors/exporters/learner_data.py
integrated_channels/sap_success_factors/transmitters/learner_data.py
integrated_channels/utils.py
test_utils/__init__.py
tests/test_management.py

refactor(integrated_channels): 🔊 configure top level channel logs to always print standard config information
Types of changes you will see in this PR:
1. Modify top level/batch integrated channels logs to always log a standard set of information of integrated channels.
2. Modify as many log statements as possible to remove LMS username and LMS user email in favor of LMS user id. 
3. Modify tests to avoid test acceptance criteria based on logs.
4. Adding standardized stack trace information to Logger.error statements instead of either ignoring it or suppressing it in favor of home-grown error formats.
5. Updates to docstrings and log messages that give Python object type information about what has gone wrong for better debugging.
6. A standardized format for non-error messages of the form …

edx-abolger/ent 4103 log standardization

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/integrated_channel/tasks.py
tests/test_integrated_channels/test_integrated_channel/test_transmitters/test_learner_data.py

Caused in 3.26.7
- [n/a ] Any new requirements are in the right place (do **not** manually modify the `requirements/*.txt` files)
- [n/a ] `make static` has been run to update webpack bundling if any static content was updated
- [n/a] `./manage.py makemigrations` has been run …

fix(integrated_channels): :bug: fix forward for parameter rename bug

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/tpa_pipeline.py
tests/test_tpa_pipeline.py

Related Platform PR:
https://github.com/edx/edx-platform/pull/28057 …

ENT4083: Removed ENABLE_MULTIPLE_USER_ENTERPRISES_FEATURE waffle switch

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/canvas/client.py
integrated_channels/canvas/utils.py
integrated_channels/utils.py
tests/test_integrated_channels/test_canvas/test_client.py
tests/test_integrated_channels/test_canvas/test_utils.py

This change eliminates the failures encountered during create_content_metadata when a course is previously concluded (via a previous delete attempt). Instead, now we do a detection of course state before attempting to create it, and instead we update it if it's one of the following states in Canvas:
`'unpublished', 'completed' or 'available' `
After removing a course from catalog, verified it was in 'completed' workflow_state now. Then added back to catalog and ran transmit_content_metadata task and saw this in logs
```
2021-06-23 03:34:26,542 WARNING 49226 [integrated_channels.canvas.client] [user None] [ip None] client.py:129 - Course with canvas_id = 6072, integration_id = course-v1:edX+99887766+2T2021 found in workflow_state=completed,attempting to update instead of creating it …
```

feat: When a course is found in concluded/completed state, update instead of create ENT-4594

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/signals.py

…enterprises
- This should be run from either a venv with all the lms/edx-enterprise requirements installed or if you checked out edx-enterprise into the src directory used by lms, you can run this …

ENT-4666: Fixed issue with CourseEnrollment receiver when learner has multiple enterprises

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/utils.py

fix: ENT-4611 Fixed issue with API version in Tableau client

---

CHANGELOG.rst
docs/segment_events.rst
enterprise/__init__.py
enterprise/api/v1/views.py
tests/test_enterprise/api/test_views.py

***Background***
This adds bulk enrollment specific segment tracking to the enrollment action that occurs only via bulk enrollment.
***Screenshot*** …

feat: Add segment tracking for bulk enrollment

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/canvas/client.py

[Something's going wrong](https://splunk.edx.org/en-US/app/search/search?q=search%20cleanup_duplicate_assignment_records&display.page.search.mode=smart&dispatch.sample_ratio=1&earliest=-4h%40m&latest=now&sid=1625842146.5666551) with retrieving Canvas assignments in the deduplication process. This PR adds error handling to a previously unhandled API call and also provides a bit more clarity on the process with an exception log.
Note: if/when the client experiences an error in retrieving course assignments, I specifically set it up continue to the next course in the list of edX courses to be dedup'ed
- `make upgrade && make …

maint: added missing error handling

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api_client/enterprise_catalog.py

the enterprise-catalog service has a default page_size of 10.
This change means that we'll make a smaller overall number of SELECTs against the enterprise-catalog database.
The enterprise-catalog service supports a `page_size` query parameter: https://github.com/edx/enterprise-catalog/blob/0c795fccd4a4c9a10dbbb67acebeb0ca6d8dee44/enterprise_catalog/apps/api/v1/pagination.py#L10
You can try it yourself by making an authenticated request to https://enterprise-catalog.stage.edx.org/api/v1/enterprise-catalogs/{some_catalog_uuid}/get_content_metadata/?format=json&page_size=50
Possibly alleviates: https://openedx.atlassian.net/browse/ENT-4643
- `test-master.in` if edx-platform pins it, with a matching …

feat: set the EnterpriseCatalogApiClient get_content_metadata request page_size to 50

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api_client/enterprise_catalog.py
tests/test_enterprise/api_client/test_enterprise_catalog.py

Also adds a unit test for the ``EnterpriseCatalogApiClient.get_content_metadata()`` method,
which was previously untested.
https://openedx.atlassian.net/browse/ENT-4741
- This should be run from either a …

fix: fix the way that page_size is passed as a param to the get_content_metadat endpoint

---

enterprise/api_client/lms.py
enterprise/models.py
enterprise/utils.py
enterprise/views.py
test_utils/fake_enrollment_api.py
tests/test_admin/test_view.py
tests/test_enterprise/api/test_views.py
tests/test_enterprise/api_client/test_lms.py
tests/test_enterprise/test_signals.py
tests/test_enterprise/views/test_course_enrollment_view.py

[ERTE-5] feat: Added enterprise uuid support in course enrollment

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/signals.py
tests/test_enterprise/test_signals.py

ENT-4347
Prior to this change, when an `EnterpriseCustomerUser` is deleted or unlinked, their `enterprise_learner` system-wide roles are deleted for ALL enterprise customers. This PR ensures the `enterprise_learner` role only for the deleted/unlinked `EnterpriseCustomerUser` is removed.
**Testing Instructions**
1. Using two separate Enterprise Customers, create an `EnterpriseCustomerUser` record for each using the same user. This results in the user being linked to multiple enterprises at once, with 2 `enterprise_learner` system-wide roles.
2. Delete one of those `EnterpriseCustomerUser` records and verify that only the `enterprise_learner` system-wide role for the no longer existent `EnterpriseCustomerUser` was deleted.
- `base.in` if needed in …

fix: delete learner role for a single customer when ECU record is deleted or unlinked

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/blackboard/client.py
tests/test_integrated_channels/test_blackboard/test_client.py

[Jira](https://openedx.atlassian.net/browse/ENT-4635)
**Background:**
Through some investigations of the API documentation, we discovered that BB does indeed paginate their responses. In testing with our local instance it seems like the default size for an instance is `200` but it is unclear if this is customizable by the customer, so to be safe all sizes should be taken into account. Before this PR, if the number of assignments within a course got too high, we would not be able to verify the existence of further assignments. This would trigger our gradebook column (Blackboard's representation of our assignments) creation process, which would fail with a unique key integrity error. As such all further grade reporting would fail to be reported. 
**Code Changes in this PR**
- The Blackboard …

bug: fixing client to handle paginated responses from Blackboard

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/integrated_channel/management/commands/__init__.py
integrated_channels/integrated_channel/management/commands/transmit_content_metadata.py
tests/test_management.py

[Jira](https://openedx.atlassian.net/browse/ENT-4643)
Background:
Because Cornerstone is following a pull content model, the overridden transmission essentially is a NOOP whenever a scheduled job tries to export and transmit data for CSOD customers. It does still query our enterprise catalog service constant and in an effort to mitigate that, this PR removes CSOD from the available channels in the scheduled transmission job.
- Checkout the [Database Migration](https://openedx.atlassian.net/wiki/spaces/AC/pages/23003228/Everything+About+Database+Migration …

maint: removing cornerstone from scheduled content metadata job

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/utils.py
tests/test_utilities.py

We want to ensure only certain IDPs are selectable for enterprise customers. The particular location we want to change is the Django Admin Enterprise Customer form where you can select an Identity Provider.
With the changes in this PR, if an IDP is disabled for use in enterprise, it will not be visible in the dropdown.
- Adds conditional logic to the `get_idp_choices` method to utilize the new flag on the ProviderConfig model.
- Adds a test to actually test this method (it _kind_ of exists in the `test_forms` file, but not really testing the logic of the method).
- In order to test this you need the branch for PR https://github.com/edx/edx-platform/pull/28261 locally
- Apply the migration from that PR
- Pick or make a provider (search for `Provider Configuration` in Django Admin and …

feat: check for and only show enabled IDPs in Django Admin

---

CHANGELOG.rst
enterprise/__init__.py

My local master was behind and apparently so was Github's as my PR shows it being a version change from 3.27.4 to 3.27.5 where it should be 3.27.5 to 3.27.6
This fixes that.
- This should be run from …

fix: version was duplicated.

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/sap_success_factors/client.py
tests/test_integrated_channels/test_sap_success_factors/test_client.py

SAP's new endpoint appears to use true/false without quotes now.
As we're still not using the endpoint everywhere, instead of modifying `_payload_data` I've just modified the payload in the client in our particular conditional for using the new endpoint.
- loads and re-dumps Payload to trigger correct format of boolean field
- Also comments on this with both explanation and TODO
- updates test to match
- Checkout the [Database Migration](https://openedx.atlassian.net/wiki/spaces/AC/pages/23003228/Everything+About+Database+Migrations) Confluence page for …

fix: SAP requires true without quotes in JSON payload.

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/sap_success_factors/client.py
tests/test_integrated_channels/test_sap_success_factors/test_client.py

With Alex S.' help, we were able to get actual payload data so I could be certain that the test data matched and also go through the SAP transformations step by step.
The last pr didn't work because my test data ended up in a bad state (I didn't realize Python assigns references rather than performing a copy when you try to assign a variable to an existing dictionary) and I mistakenly matched the base code to the test data.
So this one fixes the test data, but also I used actual payload data to verify the functionality outside of the tests to ensure confidence in the code and thus verify the test data was the problem.
The very original problem still needed to be resolved (the endpoint does not support `"true"` as a parameter and it needed to be formatted for JS (`true` without quotes), …

Fix: SAP CourseCompleted Flag - This time using actual payload data

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/v1/views.py
enterprise/api_client/lms.py
enterprise/constants.py
enterprise/management/commands/email_drip_for_missing_dsc_records.py
enterprise/models.py
enterprise/tasks.py
enterprise/utils.py
integrated_channels/sap_success_factors/exporters/content_metadata.py
integrated_channels/utils.py
tests/test_enterprise/api/test_views.py
tests/test_enterprise/test_tasks.py
tests/test_integrated_channels/test_sap_success_factors/test_exporters/test_content_metadata.py
tests/test_integrated_channels/test_utils.py
tests/test_management.py
tests/test_utilities.py

Summary of changes (updated from what I had since last round of review):
- Added a task to send email notifications in `enterprise/tasks.py`
- Extracted out a method to only serialize the email_items list so that we can use it to call a celery task
- Now calling the celery task from the model's `notify_enrolled_learners` function so every caller of the notify_enrolled_learners function gets this ability, not just bulk enrollment
- Moved a function `parse_lms_api_datetime` to utils. Strictly speaking not needed for this PR but I decided to leave it there 
For bulk enrollment, no. of tasks created = no. of courses. Each task will email all learners for enrollment into that course
ENT-4779
* ADDED: Unit test for the new task
* UPDATED: Update tests that call the view to ensure the task is …

feat: emails in a celery task, for calls to `EnterpriseCustomer#notify_enrolled_learners()`

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/tasks.py
tests/test_enterprise/test_tasks.py

follow up to https://github.com/edx/edx-enterprise/pull/1312 per Brian's feedback
If one email send fails for any reason, avoid failure and log exception, includes a test
ENT-4779
- This should be run …

feat: Follow up to ENT-4779 PR to handle in loop exceptions

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/admin/__init__.py
enterprise/management/commands/bulk_update_catalog_query_id.py
enterprise/models.py
tests/test_enterprise/management/test_bulk_update_catalog_query_id.py

[jira](https://openedx.atlassian.net/browse/ENT-4783)
background:
deleting catalog query's is currently breaking for a few processes, so we want to log an exception if one get's deleted. Additionally, in order to ever rectify this kind of event in the future, we want to add management command to bulk change enterprise catalog's queries. 
- *Note*: This **must** be …

Catalog query deletes logging and bulk query ID updates

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/utils.py
tests/test_enterprise/test_utils.py

Should be proper learner portal course link, also add tests for both admin_enroll and self_enroll cases
What about when learner portal is off for enterprise?  Should this url be made different in that case?
ANSWERED: we want the prior behavior of sending users direct to register or login, with next url being the courseware page url
JIRA: ENT-4789
After fixing ENT-4789
Took me to this page when I click on Start my Course link (from devstack email file)
http://localhost:18000/login?next=/courses/course-v1%3AedX%2B808404707%2B2T2021/course%3F
which redirected me to
http://localhost:18000/courses/course-v1:edX+808404707+2T2021/course/
Invited non edx learner (abc@mouse.com) to subscription
Then directly enrolled them using bulk enrollment into a course
Email link was this: …

fix: Fix Start my course URL for admin enrollment email

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/management/commands/bulk_update_catalog_query_id.py
tests/test_enterprise/management/test_bulk_update_catalog_query_id.py

args from database require the params be optional :( …

maint: making params options so things work

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/utils.py
tests/test_integrated_channels/test_utils.py

This PR only addresses part of the requirements to make Cornerstone course pulls safe
There is an additional set of work, which will be done in a new PR, 
ENT-4663
- This should be run from either a venv …

feat: Safe encode/decode functions for course key reversible transform for use with LMS (cornerstone mainly)

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/integrated_channel/exporters/content_metadata.py

```
(Pdb++) content_last_modified
datetime.datetime(1, 1, 1, 0, 0)
(Pdb++) catalog_modified
datetime.datetime(2021, 7, 16, 15, 11, 10, 592956, tzinfo=<UTC>)
(Pdb++) catalog_last_modified = max(content_last_modified, catalog_modified)
*** TypeError: can't compare offset-naive and offset-aware datetimes
```
- …

bug: localize min datetimes

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/integrated_channel/exporters/content_metadata.py

Recent changes to track when catalogs and their content were last modified are throwing key errors due to the fact that the `content_last_modified` value isn't present from the payload coming from enterprise catalog. Conditionally check if the value is present before attempting to pop it.
- It may or may not …

bug: content_last_modified is not always present within the payload

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/cornerstone/client.py
integrated_channels/cornerstone/exporters/content_metadata.py
integrated_channels/utils.py
tests/test_integrated_channels/test_cornerstone/test_exporters/test_content_metadata.py

[jira](https://openedx.atlassian.net/browse/ENT-4663)
CSOD customers cannot accept courses that contain keys with invalid chars- thus for any **invalid course key**  we export, encoded it. When exporting learner data, make sure to encode the course ID if it's invalid as well in order to find the right course.
- *Note*: This **must** be run if you modified any …

bug: invalid CSOD related course keys are now encoded

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/blackboard/client.py
integrated_channels/moodle/client.py
tests/test_integrated_channels/test_blackboard/test_client.py
tests/test_integrated_channels/test_moodle/test_client.py

[jira](https://openedx.atlassian.net/browse/ENT-4082)
When the integrated channels sends a delete request to external LMS' and receive a 404 meaning the course is not found, it shouldn't be treated as a failure, but instead a success. 
- It may or may not make a migration depending on exactly what you …

bug: 404s on integrated channel metadata deletions should not error

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/sap_success_factors/client.py
tests/test_integrated_channels/test_sap_success_factors/test_client.py

While starting to work on ENT-4784 I realized this log may help us, also this was mentioned as lacking in the ticket, because we had to lookup error in snowflake
- This should be run from either a venv …

feat: log response code and message if SAP post fails

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/management/commands/email_drip_for_missing_dsc_records.py
tests/test_enterprise/management/test_email_drip_for_missing_dsc_records.py

We were using time zone aware time in the test but not in command that could have caused flakiness.

Fix: ENT-4545 | updated time objects to be timezone aware in email_drip_for_missing_dsc_records

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/degreed/exporters/learner_data.py
tests/test_integrated_channels/test_degreed/test_exporters/test_learner_data.py

After a recent change, we can now pass idp_id (the slug of the idp provider) into the get_remote_id() call. If the Integrated channel config does not provide this value it will be passed as None or empty and we get toda's behavior. If we do set it though, we can now resolve the correct remote id based on idp slug.
I am hoping this will fix issues with not being able to send learner data completions for Degreed going forward. It won't fix previously missed completions. we have to find a different way to re-send those. …

feat: pass idp_id to get_remote_id for degreed

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/views.py
tests/test_enterprise/views/test_grant_data_sharing_permissions.py

fix: add failure_reason to failure url when dsc is denied

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/blackboard/transmitters/learner_data.py
integrated_channels/canvas/transmitters/learner_data.py
integrated_channels/cornerstone/transmitters/learner_data.py
integrated_channels/degreed/transmitters/learner_data.py
integrated_channels/integrated_channel/transmitters/__init__.py
integrated_channels/integrated_channel/transmitters/learner_data.py
integrated_channels/moodle/transmitters/learner_data.py
integrated_channels/sap_success_factors/transmitters/learner_data.py
tests/test_integrated_channels/test_integrated_channel/test_transmitters/test_learner_data.py

Applies to all channels and we get free logging from base class
Also renamed `payload` to `exporter` in transmit() method docstrings
ENT-4929
there is a except block that catches and handles logging for ClientError around the completion call, so I took advantage of that:
```
except ClientError as client_error:
```
does not fix any existing issue, this is logging-only that makes up for missing logs in some cases when we don't necessarily catch and re-raise/log >=400 cases …

feat: :goal_net: catch/report status code >=400 for create_course_completion calls

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/signals.py
tests/test_enterprise/test_signals.py

It was observed that we had ~650 `EnterpriseCustomerUser` records (`linked=True`) that had missing "enterprise_learner" system-wide role assignments. In digging through the relevant history tables, I noticed that for many of these cases, the `EnterpriseCustomerUser` record is updated to be unlinked and then later re-linked at a future date.
In the Django signals that create/delete these "enterprise_learner" roles, we handle the case where a learner is unlinked (i.e., delete their "enterprise_learner" role), but do not handle the case where a learner is re-linked. As such, the "enterprise_learner" role is never recreated.
This PR ensures we handle that re-linking case.
- `test-master.in` if …

fix: recreate enterprise_learner role when ECU is relinked

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/integrated_channel/exporters/learner_data.py
tests/test_integrated_channels/test_integrated_channel/test_exporters/test_learner_data.py

if audit course completed, and no date from api, then fill in with now() for completed audit courses
this is needed since we get None completed_date for audit courses in some cases when we decide to call it completed based on incomplete_count == 0
JIRA: https://openedx.atlassian.net/browse/ENT-4918
if for some rason a date does come back from api it still honors it
if audit complete is not completed (based on incomplete_count), it still avoid filling in
if track isn't even audit, it avoid filling date in
so only sets date to now() when audit + completed + date_not_coming_from_api
ENT-4918
- `make upgrade && make requirements` have …

feat: fill in now() for completed date for audit: ENT-4918

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/canvas/client.py
integrated_channels/utils.py
tests/test_integrated_channels/test_canvas/test_client.py

Adds some logging of the decoded payload and contextual info for failure. We are getting key errors during delete_content_metadata.
Once we find out more from logging, we may be able to actually fix the issue or determine what causes it in the first place
ENT-4953 …

feat: Log better on key error during extract_integration_id

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/management/commands/backfill_learner_role_assignments.py
tests/test_management.py

fix: Add error handling for role assignment backfill management command

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/canvas/client.py
integrated_channels/canvas/exporters/content_metadata.py
tests/test_integrated_channels/test_canvas/test_exporters/test_content_metadata.py

Description updated with dates:
Course looks like this after create, on syllabus page
https://edx.instructure.com/courses/6554
```
participation type fix
Jump to Today 
Go to edX course page (Links to an external site.)
lk
Starts: Fri Oct 01 2021 16:00:00
Ends: Thu Oct 28 2021 16:00:00
```
Course participation type
Also added the enforcement of course participation type to the update_content_metadata, so we get 'free' backfills when updates run
- Checkout the [Database Migration](https://openedx.atlassian.net/wiki/spaces/AC/pages/23003228/Everything+Abou …

Canvas integrated channel: add start/end dates to description and use 'Course' participation type ENT-5011

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/v1/urls.py
enterprise/api/v1/views.py
enterprise/utils.py
test_utils/enterprise_report_choices.py
tests/test_enterprise/api/test_views.py
tests/test_integrated_channels/test_xapi/test_utils.py

**Description**: This PR adds an api to fetch the dropdown options from EnterpriseCustomerReportingConfiguration.
**Sample Request Response**:
**(label, value) tuple**
- This should be run from either a …

feat: Added api for fetching choices in EnterpriseCustomerReportingConfiguration

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/integrated_channel/management/commands/__init__.py
integrated_channels/integrated_channel/management/commands/update_content_transmission_catalogs.py

`update_content_transmission_catalogs` now runs on all configs under active customers, not just active configs. …

maint: allowing management command to run on inactive configurations

---

enterprise/__init__.py
integrated_channels/moodle/client.py

For historical reasons/understandings the Moodle client was sending POST parameters as url params rather than a form-encoded body. This was resulting in HTTP 414 (uri too long) errors for certain course metadata (ie long descriptions). This PR refactors the client's `_post` method to set appropriate headers and pass params as a form-encoded body.
Although the client calls are mocked for testing, I've manually tested these changes with postman and python scripts.
- [ENT-5043](https://openedx.atlassian.net/browse/ENT-5043)

fix: refactor moodle _post to use body params

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/blackboard/client.py
tests/test_integrated_channels/test_blackboard/test_client.py

Similar to Canvas, Blackboard should not include most grade columns in the final grade. Fix up pre-existing settings along the way.
[ENT-4394](https://openedx.atlassian.net/browse/ENT-4394)

fix: properly weight blackboard grades

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/v1/views.py
enterprise/models.py
enterprise/utils.py
integrated_channels/integrated_channel/transmitters/content_metadata.py
tests/test_enterprise/api/test_views.py
tests/test_enterprise/test_utils.py
tests/test_integrated_channels/test_xapi/test_utils.py

For both pending and existing users, we need to detect when a bulk enrollment request attempts to create an enrollment that already exists. When we process a bulk enrolment, we should only be email notifying learners who's enrollment is new. 
- It may or may not make a migration depending on exactly what you …

Only notifying learners when an enrollment is created

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/v1/views.py
enterprise/models.py
enterprise/utils.py
tests/test_enterprise/api/test_views.py
tests/test_enterprise/test_utils.py

Change the enrollment notification emails to learners who have yet to activate their enterprise license to push them back into the activation flow rather than directly to the course.
We will click-test in staging/prod and review the sent emails as a final check.
- [ENT-5030](https://openedx.atlassian.net/browse/ENT-5030)
- - https://github.com/edx/license-manager/pull/320

feat: Change Bulk Enrollment Assignment Logic for Pending learners

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api_client/enterprise_catalog.py
enterprise/utils.py
integrated_channels/integrated_channel/exporters/content_metadata.py
tests/test_enterprise/api_client/test_enterprise_catalog.py
tests/test_integrated_channels/test_xapi/test_utils.py

fast follow to https://github.com/edx/edx-enterprise/pull/1384
To be merged after https://github.com/edx/enterprise-catalog/pull/341 goes live …

feat: exporter now only requests metadata for courses that need updating

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/views.py
tests/test_enterprise/views/test_router_view.py

Fix to a name-spacing error introduced by our CSOD workaround. This call uses the [AppConfig.label](https://docs.djangoproject.com/en/3.2/ref/applications/#django.apps.AppConfig.label) which is the last part of the path. This model is defined under `integrated_channels.cornerstone` rather than `integrated_channel`.
This bug is in production and may be affecting enrollments for CSOD learners. I tested this bug and my fix with a local console. I will try to introduce tests to cover these lines of code.
- [ENT-5115](https://openedx.atlassian.net/browse/ENT-5115)
Log lines to look for:
```
LookupError: App 'integrated_channel' doesn't have a 'CornerstoneEnterpriseCustomerConfiguration' model.
```
```
KeyError: 'cornerstoneenterprisecustomerconfiguration'
```

fix: CSOD workaround bugfix

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/integrated_channel/transmitters/content_metadata.py
tests/test_integrated_channels/test_integrated_channel/test_transmitters/test_content_metadata.py

[Jira](https://openedx.atlassian.net/browse/ENT-5097)
A create request may be made for a piece of content that already exists for a customer under a different catalog. Therefore we need to check if a content record exists under another catalog before we attempt to create one.  …

fix: allowing records to be cross catalogs

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/filters.py
enterprise/api/v1/serializers.py
tests/test_enterprise/api/test_filters.py
tests/test_enterprise/api/test_views.py

- Update EnterpriseCustomerUserFilterBackend to allow filtering by enterprise customer uuid and enterprise user role
- Add created_at to serializer to get activation date
- This should be run from either …

feat: allow filtering enterprise learners by enterprise uuid or enterprise role

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/integrated_channel/exporters/learner_data.py

In debugging two customer reported issues we discovered that we've most likely made a typo here - we should always be using completion date from the API (source of truth)n rather than what is passed with `kwags` - which on the signal side is always `now` and on the bulk side is not passed at all (`None`).
Because the `completed_date` is `None` on the bulk side we don't appropriately retransmit learner audit records in every case.
- [ENT-5095](https://openedx.atlassian.net/browse/ENT-5095) …

fix: incorrectly skipping completion transmissions

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/integrated_channel/channel_settings.py
integrated_channels/integrated_channel/exporters/learner_data.py
integrated_channels/integrated_channel/transmitters/learner_data.py
integrated_channels/sap_success_factors/client.py
integrated_channels/sap_success_factors/exporters/learner_data.py
integrated_channels/sap_success_factors/transmitters/learner_data.py
integrated_channels/utils.py
tests/test_integrated_channels/test_integrated_channel/test_exporters/test_learner_data.py
tests/test_integrated_channels/test_integrated_channel/test_transmitters/test_learner_data.py
tests/test_integrated_channels/test_sap_success_factors/test_exporters/test_learner_data.py
tests/test_integrated_channels/test_sap_success_factors/test_transmitters/test_learner_data.py
tests/test_integrated_channels/test_utils.py

this allows us to avoid retransmitting completion reports for SAP, when grade changes
What this PR does:
ENT-4752 …

feat: for SAP channel, do not consider grade when diffing audit records ENT-4752

---

.github/workflows/publish.yml

build: pin publish workflow to node 12

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/integrated_channel/exporters/learner_data.py

instead of raising clientError, since we don't want this case to be regarded as an error
if another process (such as the one detailed here https://github.com/edx/edx-enterprise/commit/c4121ae321be2b62e73bff87c9d25ec6d8550acd#diff-3c197d9e4526ecff05ae54bc67d7b9d28ccaa5008b8b526eef62bdf2f4b69f7dR54) sets ECU to inactive, we only want to inform and continue.
ENT-5207
- …

feat: when no enrollment found, log info and return

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/blackboard/admin/__init__.py
tox.ini

A small win to reduce setup complexity. Generate oauth auth URL in Django Admin once required fields are available.
- [ENT-4389](https://openedx.atlassian.net/browse/ENT-4389)
)

feat: OAuth Auth link for Blackboard Admin

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/utils.py
enterprise/views.py
tests/test_enterprise/api/test_views.py
tests/test_enterprise/views/test_enterprise_proxy_login_view.py

* Adds support for `enterprise_customer_invite_key` query parameter on EnterpriseProxyLoginView such that when a UI redirects learners through the EnterpriseProxyLoginView by passing an invite key UUID, the proxy login view can find the enterprise customer associated with the invite key and shows its logo during logistration.
- *Note*: This **must** be run if you …

fix:  enterprise invite key support for proxy login

---

integrated_channels/canvas/admin/__init__.py

A quick fix/enhancement, show an 'Authorize' link rather than a plain URL in Django Admin, [similar to how blackboard is setup](https://github.com/edx/edx-enterprise/blob/master/integrated_channels/blackboard/admin/__init__.py#L30).
Before:
After:
- [ENT-5238](https://openedx.atlassian.net/browse/ENT-5238)
- …

fix: Django admin a-tag rather than text url

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/v1/serializers.py
enterprise/api/v1/views.py
tests/test_enterprise/api/test_views.py

The Admin Portal displays all EnterprisecustomerinviteKeys for a specific enterprise customer in an **unpaginated** table. However, the existing API only supports providing data in a paginated response. This limits the frontend's ability to fetch all invite keys quickly without needing to traverse over the existing `list` endpoint, which won't be great for frontend performance or user experience.
Instead, this PR adds a `basic_list` endpoint that returns the same thing as `list` but without pagination. This `basic_list` endpoint will be used by the Admin Portal.
- `make upgrade && make requirements` have been run to regenerate …

fix: add basic_list action to EnterpriseCustomerInviteKeyViewSet

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/utils.py
integrated_channels/degreed2/exporters/content_metadata.py
tests/test_integrated_channels/test_degreed2/test_exporters/test_content_metadata.py

ENT-5292
Return 0 duration instead of erroring, when either start or end or both are not valid dates (meaning None or strings that are not formatted correctly). This allows continued processing of the remaining content metadata items instead of interrupting the flow
And yeah, also log the content metadata item and start_date and end_date parsed values for better diagnostics
There is a proposed idea that we skip invalid content metadata items entirely (how we define 'invalid' is up for discussion) but is not included in this PR …

fix: handle invalid start/end dates in duration calc ENT-5292

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/v1/serializers.py
tests/test_enterprise/api/test_serializers.py
tests/test_enterprise/api/test_views.py

- Add enterprise role assignments to enterprise customer user serializer
- This should be run from either a venv with all the lms/edx-enterprise requirements installed or if you checked out edx-enterprise …

feat: add enterprise role assignments field to EnterpriseCustomerUserReadOnlySerializer

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/v1/serializers.py
enterprise/api/v1/views.py
enterprise/models.py
tests/test_enterprise/api/test_views.py
tests/test_models.py

This PR adds the ability to easily toggle the `enable_universal_link` feature in the `EnterpriseCustomer` model. 
Toggling this has side affects as outlined in the ticket.
Test are WIP
- This should be …

Adds toggle_universal_link

---

CHANGELOG.rst
enterprise/__init__.py

Just a version bump and changelog update
- This should be run from either a venv with all the lms/edx-enterprise requirements installed or if you checked out edx-enterprise into the src directory used by …

fix: version bump, changelog update

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/integrated_channel/admin/__init__.py
integrated_channels/integrated_channel/transmitters/content_metadata.py

- fix for when searching contentmetadataitemtransmission results in:
`django.core.exceptions.FieldError: Related Field got invalid lookup: icontains`
- also fixing logging typo

fix: fix broken django admin search

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/blackboard/exporters/learner_data.py
integrated_channels/canvas/exporters/learner_data.py
integrated_channels/cornerstone/exporters/learner_data.py
integrated_channels/degreed/exporters/learner_data.py
integrated_channels/degreed2/exporters/learner_data.py
integrated_channels/integrated_channel/exporters/learner_data.py

Further investigating "pending" progress in customer integrated LMS (Cornerstone).
- use more consistently available course id's when logging
- add missing course id's to log lines where applicable
Example, when an LMS user has more than 1 course enrollment, these log messages are ambiguous without a proper course id:
```2022-01-19 20:57:56,664 INFO 1431 [integrated_channels.cornerstone.exporters.learner_data] [user None] [ip None] learner_data.py:56 - integrated_channel=CSOD, integrated_channel_enterprise_customer_uuid=6ee70f0d-3d21-4c03-9578-8eaaef273e4b, integrated_channel_lms_user=41551739, integrated_channel_course_key=None, get_learner_data_records finished. No learner data was sent for this LMS User Id because Cornerstone User ID not found for [Hera Group]```
- …

fix: more logging to debug missing completion record

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/cornerstone/client.py
integrated_channels/cornerstone/exporters/learner_data.py
integrated_channels/cornerstone/utils.py
tests/test_integrated_channels/test_cornerstone/test_exporters/test_content_metadata.py
tests/test_integrated_channels/test_cornerstone/test_exporters/test_learner_data.py

To work around some encoding and string-length limitations with Cornerstone, we've gone through a few iterations of mapping internal course_ids to external cornerstone course ids. Sometimes they were the same, sometimes base64 encoded, sometimes some form of a uuid4. Meanwhile, because of the way they're created via a click-through, CornerstoneLearnerDataTransmissionAudit would always contain the internal course_id - I checked the data and the code. The way audit records were being looked-up for course-completion events was flawed in such a way that only courses who had the same internal and external course id representation would end up getting transmitted. In other words, newer mappings who were base64 encoded, or using a uuid4, would never find the appropraite audit record to transmit …

fix: Cornerstone missing completion records

---

CHANGELOG.rst
enterprise/__init__.py
enterprise_learner_portal/api/v1/serializers.py
tests/test_enterprise_learner_portal/api/test_serializers.py

https://openedx.atlassian.net/browse/ENT-5135 …

feat: add created to enterprise course enrollment serializer fields

---

.dockerignore
Dockerfile
Makefile
docker-compose.yml
docs/development.rst
docs/getting_started.rst
docs/testing.rst

There are sometimes benefits and conveniences to having a containerized local environment versus setting up and maintaining python, virtualenv, and system dependencies (mysql-dev, etc) natively. Sometimes installing your code into the LMS container extends your testing cycle past your patience. Here is some docker/makefile config to enable `make test-shell` to launch a containerized environment containing your local development code so you can `make test` / `make upgrade` / 'profit' / etc inside a container. 
Does not run the web-service nor workers (still need to install your code into an LMS container for that), just wraps local development & dependency management inside docker to make it easier to develop - think of it as dockerized `virtualenv` for your native development system. …

feat: docker-based local work without lms

---

integrated_channels/sap_success_factors/admin/__init__.py

So we can see the value of this field, and SAP actually transmits course prices
This was a request by ECS who were trying to debug why course prices are not sent to SAP tenants right now. Turns out this field was false for the given SAP configuration. :)
ENT-5367 …

feat: show_course_price field in django admin

---

CHANGELOG.rst
enterprise/__init__.py

missed changelog in this PR: https://github.com/openedx/edx-enterprise/pull/1473
ENT-5367
- This should be run from either a venv with all the lms/edx-enterprise requirements installed or if you checked …

feat: missed changelog for ent-5367

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/utils.py
integrated_channels/sap_success_factors/exporters/content_metadata.py
tests/test_integrated_channels/test_sap_success_factors/test_exporters/test_content_metadata.py

Based on reading this doc, it seems the 'schedule' field is what we want
https://help.sap.com/viewer/9d4c9e0d04304afdbe8f1b4480d71403/2111/en-US/2be70bfe31e64399be709de794f639ee.html
https://openedx.atlassian.net/browse/ENT-5367
This PR includes AC no. 2 of that ticket
This change populates the schedule array from one of these:
- the closes course run if we are processing a course itme
- the course run items itself
it extracts the values to produce schedule as follows:
```
[{
'startDate': parse_datetime_to_epoch_millis(start) if start else '',
'endDate': parse_datetime_to_epoch_millis(end) if end else '',
'active': current_time_is_in_interval(start, end) if start else False,
'duration': f"{duration} days",
}
]
```
- `base.in` if needed in production but edx-platform …

feat: Add duration to the schedule of payload for SAP content metadata exporter

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/degreed2/client.py
integrated_channels/degreed2/models.py
tests/test_integrated_channels/test_degreed2/test_client.py

- degreed2 seems to be unable to successfully send learner audit records
- looks like we were serializing data in the client rather than the model
- integrated channel transmitter was expecing serialization in model
- test tweaks but there is more we can add to tests
Associated Splunk logs:
```
2022-03-09 14:59:48,232 ERROR 1450 [celery.app.trace] [user None] [ip None] trace.py:265 - Task integrated_channels.integrated_channel.tasks.transmit_learner_data[f5628262-9285-4ad3-864a-6d958cc8e920] raised unexpected: AttributeError("'Degreed2LearnerDataTransmissionAudit' object has no attribute 'serialize'")
File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/celery/app/trace.py", line 451, in trace_task
R = retval = fun(*args, **kwargs)
File …
```

fix: Degreed: Missing Learner Data Audit Records

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/cornerstone/admin/__init__.py

I had attempted to pull in associated objects (non-foreign keys) for some added info on this admin screen but it seems to be breaking (timing out) in prod (works locally). I want to use this view, i don't need this extra info. I wanna dump it for now.
- [ENT-5565](https://openedx.atlassian.net/browse/ENT-5565)

fix: CornerstoneLearnerDataTransmissionAudit admin view timeout

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/cornerstone/admin/__init__.py

- timeout is likely due to django admin trying to create/populate a select drop-down for the user field
- mark user as a 'raw id field'
- add back the enterprise name read-only since it wasnt the issue
- [ENT-5565](https://openedx.atlassian.net/browse/ENT-5565)

fix: CSOD Learner Audit Django Admin Timeouts

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/v1/views.py
tests/test_enterprise/api/test_views.py

https://openedx.atlassian.net/browse/ENT-5400
- We need to be able to patch `EnterpriseCustomer` to change enterprise settings
- `permissions.DjangoModelPermissions` doesn't work with @permission_required decorator so we need to override `get_permissions` 
- Only touching partial_update to minimize changes
- …

feat: allow enterprise customer partial update

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api_client/enterprise_catalog.py
integrated_channels/cornerstone/exporters/content_metadata.py
integrated_channels/cornerstone/urls.py
integrated_channels/cornerstone/views.py
integrated_channels/integrated_channel/exporters/content_metadata.py
test_utils/fake_catalog_api.py
tests/test_integrated_channels/test_cornerstone/test_views.py

A customer cannot setup their CSOD integration because the initial pull of their content by CSOD times out. This specific customer has multiple "all-content" catalogs but in theory even smaller catalogs have the potential to timeout since we do a full send every time. 
This set of changes is to add a configurable "max changes to send" size (defaulting to 1000). Whenever CSOD polls, we'll doll out the next N changes based on what our catalog diff tells us. Prioritizing creates over updates. If we have more than N changes to send, the audit records for only those first N will get updated and thus the remaining changes will be sent on the next poll by CSOD.
I tried to implement this will the least number of architectural changes possible. Also tried to keep in mind how/where the proper …

fix: chunk cornerstone content updates

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/tpa_pipeline.py
tests/test_tpa_pipeline.py

Jira ticket: https://openedx.atlassian.net/browse/ENT-5484 …

feat: setting customer identity provider config is_valid on first SSO login

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/integrated_channel/exporters/learner_data.py

We don't seem to be logging the results of grades api call, only the cert api call
There are some cases where we want to inspect if we are indeed getting correct info by calling grades api call. Since we have a task on hand to try and use cert api call as much as possible
for now I want to at least log this and see if we are getting accurate completion results
- …

add logging of grades api call

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/v1/views.py
tests/test_enterprise/api/test_views.py

fix: use enterprise customer uuid from request data

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/v1/serializers.py
tests/test_enterprise/api/test_serializers.py
tests/test_enterprise/api/test_views.py

https://openedx.atlassian.net/browse/ENT-5648
- Add admin information (only email for now) to enterprise customer serializer …

feat: add admin_users to EnterpriseCustomerSerializer

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/integrated_channel/exporters/learner_data.py
integrated_channels/integrated_channel/models.py
integrated_channels/integrated_channel/transmitters/learner_data.py
integrated_channels/lms_utils.py
integrated_channels/utils.py
test_utils/integrated_channels_utils.py
tests/test_integrated_channels/test_cornerstone/test_exporters/test_learner_data.py
tests/test_integrated_channels/test_integrated_channel/test_exporters/test_learner_data.py
tests/test_integrated_channels/test_lms_utils.py
tests/test_integrated_channels/test_utils.py

Change of logic is basically:
- if audit track: no change of behavior. Still send completions as long as incomplete_count = 0
- if non audit track: only send completion if passed_timestamp is not Null and is_passed=True. This matches with how the analytics tools report completions. This should also fix the bug where we incorrectly sent non audit tracks as completed, solely based on this other completed_date that we calculate, that does _not_ match with analytics logic. We may be able to remove that field in the future but for now I left it there, I just don't use it to calculate is_completed anymore :)
- specifically call CourseGradeFactory with create_if_needed=False, since I don't see why we need to use the get_or_create pattern here, we are simply wanting to read existing grade records …

ENT-5632 completions fix for non audit to base on passed_timestamp

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/integrated_channel/management/commands/backfill_missing_foreign_keys.py
integrated_channels/moodle/client.py
tests/test_integrated_channels/test_moodle/test_client.py

- handle orphaned content metadata lacking a config
```
Apr  7 19:45:34 ip-10-2-70-191 [service_variant=lms][integrated_channels.integrated_channel.management.commands.backfill_missing_foreign_keys][env:prod-edx-edxapp] ERROR [ip-10-2-70-191  2424] [user None] [ip None] [backfill_missing_foreign_keys.py:140] - backfill_missing_foreign_keys failed
File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/integrated_channels/integrated_channel/management/commands/backfill_missing_foreign_keys.py", line 135, in backfill_join_keys
LOGGER.info(f'ContentMetadataItemTransmission {channel_code} <{audit_record.pk}> '
AttributeError: 'NoneType' object has no attribute 'id'
```
- let moodle recreate courses it think should exist
```
2022-04-07 20:22:19,615 …
```

fix: guard backfill job

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/blackboard/admin/__init__.py
integrated_channels/canvas/admin/__init__.py
integrated_channels/cornerstone/admin/__init__.py
integrated_channels/degreed/admin/__init__.py
integrated_channels/degreed2/admin/__init__.py
integrated_channels/integrated_channel/admin/__init__.py
integrated_channels/moodle/admin/__init__.py
integrated_channels/sap_success_factors/admin/__init__.py
integrated_channels/xapi/admin/__init__.py

- improve performance & safety of the django admin pages by replacing drop-downs for enterprise customer fields
- ENT-5609
- https://github.com/openedx/edx-enterprise/pull/1495

chore: replace enterprise customer drop-downs in django admin

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/models.py
tests/test_models.py

Overrides the [SystemWideEnterpriseUserRoleAssignment.get_assignments()](https://github.com/openedx/edx-enterprise/blob/9753181f1efee616affac216efe56eec9dc2a9b6/enterprise/models.py#L2802) method to return list of (role, context) assignments where the first item in the list corresponds to the currently active enterprise for the user.
This approach should allow us to remedy the problem without changing behavior of the consumers of JWT-stored roles (e.g. in ecommerce).
https://openedx.atlassian.net/browse/ENT-5700 …

fix: override get_assignments() so that the order matters

---

CHANGELOG.rst
enterprise/__init__.py

Our PyPI lastest version is still 3.44.0, which means whoever tried to release next from 3.43.x will see a PyPI failure on release.  This PR rolls us to 3.44.1 to avoid that.
- This should be run from …

fix: no-op version bump to account for a reverted 3.44.0

---

CHANGELOG.rst
integrated_channels/moodle/client.py
tests/test_integrated_channels/test_moodle/test_client.py

- while creating, accept a `courseidnumbertaken` error as success
- similar behavior for `shortnametaken` already exists
```
Apr 13 17:59:34 ip-10-2-71-73 [service_variant=lms][integrated_channels.integrated_channel.transmitters.content_metadata][env:prod-edx-edxapp] ERROR [ip-10-2-71-73  11441] [user None] [ip None] [content_metadata.py:117] - Moodle API Client Task "_wrapped_post" failed with error code "courseidnumbertaken" and message: "ID number is already used for another course (NYIF+ECS-IBFx)" 
File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/integrated_channels/integrated_channel/transmitters/content_metadata.py", line 109, in _transmit_create
self.client.create_content_metadata(serialized_chunk)
File …
```

fix: accept duplicate course id on create

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/models.py
tests/test_models.py

Ensure that EnterpriseSystemWideUserRoleAssignment.get_assignments() can handle null values that might be returned by get_context().  See https://openedx.atlassian.net/browse/ENT-4346 for open technical debt and partial explanation of how `None` is a meaningful context.
This reverts commit 6927277aad53f2497a336730e8af52372ee316cf.
https://openedx.atlassian.net/browse/ENT-5700
Screenshots from manually testing the specific null-pointer defect:
Create a new user with no enterprise link, but _with_ an assignment record where the enterprise id is null and they don't have wildcard access:
Login and verify that there are no errors, and the user's JWT should have `roles` with a role name but no context: …

fix: Revert "Revert "fix: override get_assignments() so that active enterprise uuids come first.""

---

CHANGELOG.rst
enterprise/__init__.py

I was somehow able to merge https://github.com/openedx/edx-enterprise/pull/1536/files without a conflict.  This PR fixes the versioning. …

chore: fixup version

---

CHANGELOG.rst
integrated_channels/degreed2/admin/__init__.py
integrated_channels/degreed2/client.py
integrated_channels/utils.py
tests/test_integrated_channels/test_degreed2/test_client.py

We've been seeing errors in the integrated channel logs for Degreed2 - we're not honoring their 429's and not attempting to back-off nor retry. Seems to be holding up syncs from completing properly.
- back-off/retry all HTTP methods
- test retry
- show modified in admin
- [ENT-5741](https://openedx.atlassian.net/browse/ENT-5741)

fix: implement back-off and retry for degreed2

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/decorators.py
tests/test_decorators.py

- when no SSO is configured for an enterprise customer, do not include a `tpa_hint=None` in the enroll -> auth redirect
- [ENT-5728](https://openedx.atlassian.net/browse/ENT-5728)

fix: drop tpa_hint param in redirects when no SSO

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api_client/lms.py
enterprise/views.py

Make this signature match and use the same signature that
``openedx.core.djangoapps.embargo.redirect_if_blocked()`` now uses.
https://openedx.atlassian.net/browse/ENT-5777
A change was introduced in https://github.com/openedx/edx-platform/pull/30295 that modified the signature of `embargo.redirect_if_blocked()`, this change makes enterprise code respect that new signature.
- Checkout the [Database Migration](https://openedx.atlassian.net/wiki/spaces/AC/pages/23003228/Everything+About+Database+Migrations) Confluence page for helpful tips on creating …

fix: modify signature of EmbargoApiClient.redirect_if_blocked

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/degreed2/exporters/content_metadata.py
integrated_channels/utils.py
tests/test_integrated_channels/test_degreed2/test_exporters/test_content_metadata.py
tests/test_integrated_channels/test_utils.py

- was erroneously reporting time-to-complete as whole course availability, days between start_date and end_date of the course run
- now averaging effort (which is hours), multiplying by weeks to complete, and dividing by 8-hour days to get a rough duration in days
- [ENT-5788](https://openedx.atlassian.net/browse/ENT-5788)

fix: Degreed2 estimated time to complete in days

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/utils.py
integrated_channels/sap_success_factors/exporters/content_metadata.py
test_utils/fake_catalog_api.py
tests/test_integrated_channels/test_sap_success_factors/test_exporters/test_content_metadata.py
tests/test_utilities.py

Updating course price parsing for SAP to match the logic in enterprise catalog: https://openedx.atlassian.net/browse/ENT-5687 …

fix: update logic for parsing course price for SAP

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/degreed2/exporters/learner_data.py

Degreed2 wasn't making use of passed-in completion status from `args` and was defaulting to true which made some learner audit records improperly included for sync. Since the record had no completion timestamp, validation was failing. Solution is to use the `course_completed` passed to the exporter.
- [ENT-5803](https://2u-internal.atlassian.net/browse/ENT-5803)
- similar to https://github.com/edx/edx-enterprise/blob/master/integrated_channels/cornerstone/exporters/learner_data.py#L26

fix: degreed2 improperly tracking completion status

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/blackboard/views.py
integrated_channels/canvas/views.py
tests/test_integrated_channels/test_blackboard/test_views.py
tests/test_integrated_channels/test_canvas/test_views.py

- when using legacy enterprise_uuid urls in canvas and blackboard, handle gracefully by selecting the first available config
- expand testing to handle legacy case alongside the new config uuid case
- [ENT-5610](https://2u-internal.atlassian.net/browse/ENT-5610)

fix: correctly handle multiple oauth configs

---

.github/workflows/ci.yml
Makefile

Temporarily run CI workflow using Node 12 to get jshint functional again. Making edx-enterprise compatible with Node 16 with be done as follow-up via https://2u-internal.atlassian.net/browse/ENT-5821
- …

build: enable jshint and use Node 12 in CI

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/sap_success_factors/exporters/content_metadata.py
requirements/dev.txt
tests/test_integrated_channels/test_sap_success_factors/test_exporters/test_content_metadata.py

https://2u-internal.atlassian.net/browse/ENT-5836
SAP throws errors if we include an empty start or end date in the schedule field.  This is an issue because having an empty end date is a perfectly valid state for a course run to be in.
The schedule field is optional [per SAP docs](https://help.sap.com/docs/SAP_SUCCESSFACTORS_LEARNING/9d4c9e0d04304afdbe8f1b4480d71403/2be70bfe31e64399be709de794f639ee.html) and we were not sending over anything for schedule prior to [this PR](https://github.com/openedx/edx-enterprise/pull/1480), so hopefully this should be fine.
- `make upgrade && make requirements` have been run to regenerate …

fix: don't transmit schedule data to SAP if start or end date is empty

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/v1/serializers.py
tests/test_enterprise/api/test_serializers.py

- Add lms_user_id so that it can be used to identify admin user profiles in braze (we use admin users to determine admins to email right now). Could be useful for other things too.
- Upgrade pip-tools to 6.6.1 according to https://github.com/jazzband/pip-tools/issues/1617#issuecomment-1126245586
- It may or …

feat: add lms_user_id to serialized admin users

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/integrated_channel/exporters/learner_data.py
tests/test_integrated_channels/test_integrated_channel/test_exporters/test_learner_data.py

- when working on a customer issue we discovered incorrect completed-at dates in learner completion records
- they had all defaulted to `time.now()` despite certificate and passing timestamps being available
- discovered a formatting method which is on by default that changes a field name from `created_date` to `created`
- expanded the logic to check multiple sources for a correct or approximately correct completed date before defaulting to `time.now()`
- better logging
- [ENT-5895](https://2u-internal.atlassian.net/browse/ENT-5895)

fix: incorrect completed-at date

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/integrated_channel/constants.py
integrated_channels/integrated_channel/management/commands/transmit_content_metadata.py
integrated_channels/integrated_channel/management/commands/transmit_learner_data.py
integrated_channels/integrated_channel/tasks.py
tests/test_integrated_channels/test_integrated_channel/test_tasks.py
tests/test_management.py

Implement a simple tool to allow celery task concurrency control to help prevent integrated channel jobs from overrunning each other. Based on prior art linked in ticket. More abstract, generic library method perhaps in the future.
**Grooming Notes:** 
- scope of this ticket will be to provide a fix for the current issue in the integrated channels.  We will follow up with a future discovery ticket to see if we can abstract out to a more generic solution.
- “Fast” implementation: create a lock key string representing the unique instance of the job, try to set it in memcache with an expiration of the lock timeout length, subsequent runs can check for the existence of the key in memcache and bail out if it exists
- [ENT-5957](https://2u-internal.atlassian.net/browse/ENT-5957)
- …

feat: basic integrated channels task concurrency control

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/management/commands/nudge_dormant_enrolled_enterprise_learners.py
tests/test_enterprise/management/test_nudge_dormant_enrolled_enterprise_learners.py

feat: added nudge email for dormant enrolled enterprise learners

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/cornerstone/admin/__init__.py

- mark `session_token` read-only in Django Admin to avoid confusion and errors
- mark `session_token_modified` read-only in Django Admin to avoid confusion and errors
- https://2u-internal.atlassian.net/browse/ENT-6059

feat: mark Cornerstone session token fields read-only in admin

---

.github/workflows/ci.yml
.github/workflows/mysql8-migrations.yml

https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
Right now if you push multiple times in succession, each push triggers the workflow to run. This change cancel in-progress runs so we don't waste/hog runner resources. …

feat: cancel in progress workflows

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/integrated_channel/management/commands/backfill_missing_csod_foreign_keys.py
tests/test_management.py

Follow-on to #1603
Noticed old learner data records which have subdomains no longer in use. These we can leave in place orphaned. This PR makes the migration job continue gracefully, skipping those records. Tests have been adjusted to reflect this change.

fix: follow-on to cornerstone learner records foreign keys job

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/integrated_channel/exporters/content_metadata.py
test_utils/fake_catalog_api.py
tests/test_integrated_channels/test_cornerstone/test_views.py

[related ticket](https://2u-internal.atlassian.net/browse/ENT-5849)
TLDR- we noticed that certain pieces of content were constantly being "created" (or attempted to be) for customers through the integrated channels. The common factor between all these customers and all this content was that the customers had multiple catalogs that shared the content.
**The problem:** 
The integrated channels (roughly) work as such-
- we iterate over each customer catalog
- we collect all transmission audits under each catalogs, one by one
- specifically we filter the audit table by customer + catalog uuid
- we take the collected audits and send them to the ent catalog service and ask what work needs to be done
- we take the work that needs to be done and send it to the customer
- after successfully …

fix: overlapping content across catalogs constantly causing recreates

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/integrated_channel/exporters/content_metadata.py
tests/test_integrated_channels/test_integrated_channel/test_exporters/test_content_metadata.py

https://2u-internal.atlassian.net/browse/ENT-5849
Previous PR: https://github.com/openedx/edx-enterprise/pull/1612
Oops- `only` does not act like I expected it to. If you want to select specific fields in the Django ORM you need to use `values` or `values_list`. The param `flat` will flatten the results to just a list instead of a list of dictionaries that look like `[{'field_name': value}]`
- Checkout the [Database Migration](https://openedx.atlassian.net/wiki/spaces/AC/pages/23003228/Everything+About+Database+Migrations) Confluence page for helpful …

fix: properly selecting fields when searching for already created content items in exporter

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/canvas/utils.py
tests/test_integrated_channels/test_canvas/test_utils.py

fix: properly handling API requests to canvas instances that have no root accounts

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/cornerstone/exporters/content_metadata.py
integrated_channels/cornerstone/transmitters/content_metadata.py
integrated_channels/cornerstone/views.py
integrated_channels/integrated_channel/management/commands/backfill_missing_csod_foreign_keys.py
integrated_channels/integrated_channel/management/commands/backfill_missing_foreign_keys.py
integrated_channels/integrated_channel/management/commands/backfill_remote_action_timestamps.py
integrated_channels/integrated_channel/management/commands/reset_csod_remote_deleted_at.py
integrated_channels/sap_success_factors/exporters/content_metadata.py
integrated_channels/sap_success_factors/transmitters/content_metadata.py
integrated_channels/utils.py
tests/test_integrated_channels/test_cornerstone/test_views.py
tests/test_management.py

Previously we were not sending deleted content messages to Cornerstone when they pulled a course update. 
This PR:
- adds delete messages into to CSOD update view
- follows the SAP pattern to set an inactive field on delete transmission actions
- moved a useful snippet into a utility class, clean up old copy/paste usage
- cleans up some debug logging and adds comments
- https://2u-internal.atlassian.net/browse/ENT-6081
- https://2u-internal.atlassian.net/browse/ENT-6121

fix: refactor the way we send cornerstone content metadata deletes

---

enterprise/management/commands/seed_enterprise_devstack_data.py

Fixes a role assignment exception we encountered when trying to seed a new devstack with enterprise data.
- This should be run from either a venv with all the lms/edx-enterprise requirements installed or …

fix: fix devstack seed data script role assignments.

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/degreed2/client.py
integrated_channels/integrated_channel/transmitters/content_metadata.py
integrated_channels/sap_success_factors/client.py
tests/test_integrated_channels/test_degreed2/test_client.py
tests/test_integrated_channels/test_integrated_channel/test_transmitters/test_content_metadata.py
tests/test_integrated_channels/test_sap_success_factors/test_client.py

- Pass SAP Client status back to the main content transmission orchestration to record properly
- Have main content transmission orchestration catch/record more error states from the clients
- Degreed2 needs some tweaks too
- https://2u-internal.atlassian.net/browse/ENT-6195

fix: properly pass SAP client status back to content transmission records

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/integrated_channel/management/commands/reset_csod_remote_deleted_at.py
tests/test_management.py

Originally this job was meant to only reset the `remote_deleted_at` of content which hadn't yet been sent with the newly refactored content metadata code (hence the null remote api status code). Now, we'd like to be able to reset the `remote_deleted_at` for _all_ deleted CSOD content to force a re-transmission of the delete with the new, lower payload size.
- https://2u-internal.atlassian.net/browse/ENT-6081

feat: expand utility of CSOD deleted_at reset job

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/integrated_channel/exporters/content_metadata.py
integrated_channels/utils.py
tests/test_integrated_channels/test_integrated_channel/test_exporters/test_content_metadata.py
tests/test_integrated_channels/test_utils.py

We were truncating our content payloads before we were filtering out items we were not going to update - this was resulting in missed updates and deletes to content in the remote LMS when using `max_payload_count` less than catalog size (typical with CSOD specifically). This PR re-orders the truncate to happen later in the diff process. It also adds a test which replicates the bug behavior.
In the steady synced state, the entire customer catalog is returned as a matched item from the diff endpoint and then we filter that down (to nothing) after we compare last modified dates to determine if an update needs to be send. Because we truncate to `max_payload_count` _before_ we compare dates to filter, we were only ever filtering on an update collection of the first `max_payload_count` and a …

fix: properly truncate payload to resolve missing CSOD deletes

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/canvas/client.py
integrated_channels/canvas/utils.py

Noticed that Canvas (probably many other) integrated channels doesn't properly construct urls (naively joins strings). Strangely this doesn't seem to be interrupting customer experiences but I figured it's worth cleaning up.
- It may or may not make a migration depending on exactly what you modified, but it …

chore: cleaning up canvas url construction

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/canvas/client.py
tests/test_integrated_channels/test_canvas/test_client.py

https://2u-internal.atlassian.net/browse/ENT-6306 While investigating a customer's canvas integration, I noticed splunk errors reporting 404's when updating courses. I've updated the `update content metadata` function to now catch 404's and create the content instead. …

chore: smarter canvas client update course behavior

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/admin/__init__.py
enterprise/admin/utils.py
enterprise/admin/views.py
tests/test_admin/test_view.py

**Description** This PR updates the catalog query preview link to use POST instead of GET to enable large size of arguments
**JIRA** [ENT-6179](https://2u-internal.atlassian.net/browse/ENT-6179)
- This …

feat: Added POST support for catalog query preview

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/integrated_channel/exporters/content_metadata.py

partial revert of https://github.com/openedx/edx-enterprise/pull/1629 motivated by the logs turning out to be too noisy …

feat: remove debug logging used to investigate missing CSOD deletes

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/integrated_channel/exporters/content_metadata.py

ENT-6451 - ensure that the content_last_changed field is only updated post-transmit, to ensure that untransmitted courses get picked up on subsequent runs
- This should be run from either a venv with all …

fix: integrated channels not picking up courses to update

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/api/v1/logs/serializers.py
integrated_channels/blackboard/admin/__init__.py
integrated_channels/blackboard/exporters/learner_data.py
integrated_channels/canvas/admin/__init__.py
integrated_channels/canvas/exporters/learner_data.py
integrated_channels/cornerstone/admin/__init__.py
integrated_channels/cornerstone/exporters/learner_data.py
integrated_channels/degreed/admin/__init__.py
integrated_channels/degreed/exporters/learner_data.py
integrated_channels/degreed2/admin/__init__.py
integrated_channels/degreed2/exporters/learner_data.py
integrated_channels/integrated_channel/admin/__init__.py
integrated_channels/moodle/admin/__init__.py
integrated_channels/moodle/exporters/learner_data.py
integrated_channels/sap_success_factors/admin/__init__.py
integrated_channels/sap_success_factors/exporters/learner_data.py
integrated_channels/utils.py
test_utils/factories.py
tests/test_integrated_channels/test_api/test_logs/test_views.py

Jira ticket: https://2u-internal.atlassian.net/browse/ENT-6459
work included:
- django admin views for all channels' learner data transmission audits
- read only field updates (including api_record fields on content metadata transmission audits)
- populating user_email for each individual channel's transmission audit during the learner data export
- made fields returned by learner data transmission audit API a need to need basis
- Checkout the [Database Migration](https://openedx.atlassian.net/wiki/spaces/AC/pages/23003228/Everything+About+Database+Migra …

feat: adding admin views for all integrated channel learner data audit tables

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/api/v1/logs/serializers.py
integrated_channels/api/v1/logs/views.py
integrated_channels/blackboard/models.py
integrated_channels/canvas/admin/__init__.py
integrated_channels/canvas/models.py
integrated_channels/integrated_channel/models.py
tests/test_integrated_channels/test_api/test_logs/test_views.py

Accidentally left in unneeded values from the api view
screenshot to verify that I got it right this time 🙃 
- This should be run from either a venv with all the lms/edx-enterprise requirements installed …

chore: fixing api view that included unneeded values

---

tests/test_integrated_channels/test_api/test_logs/test_views.py

https://2u-internal.atlassian.net/browse/ENT-6465 …

fix: adding view api tests

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/integrated_channel/exporters/content_metadata.py
integrated_channels/integrated_channel/transmitters/content_metadata.py
tests/test_integrated_channels/test_integrated_channel/test_exporters/test_content_metadata.py

fix: catch update transmissions that failed and need to be resent

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/__init__.py
tests/test_enterprise/test_signals.py

__Jira Ticket:__ [ENT-6518](https://2u-internal.atlassian.net/browse/ENT-6518)
__Description:__
This PR removed tableau related code to fix a bug that was causing issues in the registration process of enterprise admins.
- It may or may not make a migration depending on exactly what you modified, but it …

fix: fixed a bug that didn't allow admins to create an account or update password

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/api/v1/logs/views.py

chore: allowing for page size specification for error reporting

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/api/v1/logs/views.py
tests/test_integrated_channels/test_api/test_logs/test_views.py

https://2u-internal.atlassian.net/browse/ENT-6532 …

fix: sorting error reporting audits backend filtering

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/constants.py
integrated_channels/integrated_channel/exporters/content_metadata.py
tests/test_integrated_channels/test_integrated_channel/test_exporters/test_content_metadata.py

feat: exec ed content is tagged and distinguishable from edx content

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/models.py

***Description***
The report configuration UI asks for a Password even when the PGP key is provided.  See the screenshot attached. 
The expected behavior is that if a PGP is provided the password should not be mandatory in the UI.
***Solution***
Make change some changes to the **Clean** method. if the PGP key or password (at least one) is present and all other requirements are fulfilled the form will be submitted successfully.
- Checkout the [Database Migration](https://openedx.atlassian.net/wiki/spaces/AC/pages/23003228/Everything+About+Database+Migrati …

fix: password is required when pgp key is provided

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/integrated_channel/exporters/content_metadata.py
tests/test_integrated_channels/test_integrated_channel/test_exporters/test_content_metadata.py

- fix for https://2u-internal.atlassian.net/browse/ENT-6448
- we were not properly accounting for failed creates or failed deletes
- added tests to cover ticket cases
- DRY'ed up a query by making function more flexible via optional args

fix: failed content deletes and creates are never retried

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/moodle/client.py

https://2u-internal.atlassian.net/browse/ENT-6662 …

fix: making moodle client return value match other channels

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/integrated_channel/transmitters/content_metadata.py
integrated_channels/integrated_channel/transmitters/learner_data.py
tests/test_integrated_channels/test_integrated_channel/test_models.py

- seeing errors in the integration logs `TypeError: can't compare offset-naive and offset-aware datetimes`
- `datetime.utcnow()` does not produce a timezone-aware datetime and needed to be swapped for a datetime aware one
- https://2u-internal.atlassian.net/browse/ENT-6661

fix: integrations log TypeErrors

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/v1/serializers.py
enterprise/models.py
tests/test_enterprise/api/test_serializers.py
tests/test_enterprise/api/test_views.py

Add file compression option on Reporting Form of frontend-admin-panel. Initially, that option was only enabled by the Django admin, not from the user request that came from the admin panel. But now users will be able to Enable compression from UI.
I apply validations on enable_compression by making a static function of compression_validation in models and using it in the serializer to make it secure.
Here is the picture of adding a button on the UI.
- Checkout the [Database Migration](https://openedx.atlassian.net/wiki/spaces/AC/pages/230 …

fix: handle file compression check and test

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api_client/lms.py
integrated_channels/degreed2/client.py
tests/test_enterprise/api_client/test_lms.py

https://2u-internal.atlassian.net/browse/ENT-6733
|https://one.newrelic.com/nr1-core/apm-features/transactions/ODgxNzh8QVBNfEFQUExJQ0FUSU9OfDY5MTM3NDQ5Mg?duration=1800000&state=bbea8bd0-d1aa-070f-243c-5787dac8cf64
https://splunk.edx.org/en-US/app/search/search?q=search%20integrated_channels%20learner_data%20NOT%20%22refresh_token%20not%20found%22%20NOT%20%22(edX%20integration)%20Final%20Grade%22%20grades_api&earliest=-7d%40h&latest=now&display.page.search.mode=smart&dispatch.sample_ratio=1&sid=1674955713.4242295
Seems like the single learner data transmission task is failing to reach the grades api, receiving a 504. I've added backoff and retry logic that will hopefully lighten the burden on the LMS with multiple simultaneous transmission jobs.
- `base.in` if needed …

fix: grades api backoff and retry logic

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/integrated_channel/exporters/learner_data.py

fix: checking for response attr in http exception handling

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/admin/forms.py
enterprise/api/v1/serializers.py
enterprise/models.py
tests/test_admin/test_forms.py
tests/test_enterprise/api/test_views.py
tests/test_models.py

***Description***
when someone creates an EnterpriseCustomerReportingConfiguration (ECRC) using the delivery_method email and tries to update the delivery_method to sftp then sftp password field is not shown on the Django admin form. Due to which 500 error occurred. 
***Solution***
I apply validation on delivery_method is that when someone tries to update this field either from the Django admin or through the front end then a proper message will be thrown to the user that you can not update the delivery_method.
Here is the ticket [ENT-1689](https://2u-internal.atlassian.net/browse/ENT-1689)
…ort in forms
- `make upgrade && make …

fix: applied validatoins on report delivery_method

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/integrated_channel/admin/__init__.py

Adding a Django Admin action which will let us (in bulk) clear the `remote_deleted_at` timestamp of `ContentMetadataTransmissionItem` records - which should mark them to be re-deleted on the next Integrated Channels transmission job run.
- https://2u-internal.atlassian.net/browse/ENT-6708
- https://2u-internal.atlassian.net/browse/ENT-6719
- https://docs.djangoproject.com/en/4.1/ref/contrib/admin/actions/

feat: adding a bulk action to resend cmti deletes

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/models.py

Bug ticket: https://2u-internal.atlassian.net/browse/ENT-6873
The enterprise product supports customers who use their custom logo for the application header. This is determined by `safe_logo_url` on the `EnterpriseCustomerBrandingConfiguration` model. This method determines whether to use an S3 URL for stage/prod or the concatenated `settings.LMS_ROOT_URL + settings.MEDIA_URL`.
It makes this choice based on the `settings.DEFAULT_FILE_STORAGE` setting, which recently updated last week from `storages.backends.s3boto.S3BotoStorage` to `storages.backends.s3boto3.S3Boto3Storage`, thus breaking the conditional to use the S3 URL in stage/prod.
This PR makes `safe_logo_url` support both the old and new values for `settings.DEFAULT_FILE_STORAGE`.
Long term, we should find another way to flag on …

fix: check against an updated settings.DEFAULT_FILE_STORAGE to determine if in stage/prod environment

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/v1/views.py
enterprise/utils.py
tests/test_enterprise/api/test_views.py
tests/test_enterprise/test_utils.py

https://2u-internal.atlassian.net/browse/ENT-6899 …

feat: surfacing subsized enrollment uuid value in bulk enrollment

---

enterprise/settings/test.py

This affects only test settings, and is mostly for consistency with production environments.
[ENT-6913](https://2u-internal.atlassian.net/browse/ENT-6913)

chore: add enterprise_subsidy_worker to ENTERPRISE_ALL_SERVICE_USERNAMES

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/v1/serializers.py
enterprise/api/v1/urls.py
enterprise/api/v1/views.py
tests/test_enterprise/api/test_views.py

Serializes EnterpriseCatalogQuery Model
Distinctly classifies model field, `content_filter` as JSON to parse data
Creates nondescript ViewSet with default Django readonly endpoints
Denotes permissions based on a Jwt Authenticated user with session
Creates general viewset route
Writes a basic test
- It may or …

feat: get all catalog queries api endpoint

---

README.rst

We're going to have a single set of contributing guidelines for all
repos in the Open edX Platform.  Update the link to the org wide
contributing guidelines instead of falling back to the ones in the
edx-platform which are out of date.

docs: Update the contributing link.

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/integrated_channel/management/commands/remove_duplicate_transmission_audits.py
integrated_channels/integrated_channel/tasks.py
tests/test_management.py

https://2u-internal.atlassian.net/browse/ENT-7052 …

feat: new management command to remove duplicate transmission audits

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/integrated_channel/management/commands/remove_duplicate_transmission_audits.py
integrated_channels/integrated_channel/tasks.py

https://splunk.edx.org/en-US/app/search/search?q=search%20duplicates%20found&earliest=-24h%40h&latest=now&display.page.search.mode=smart&dispatch.sample_ratio=1&sid=1683301288.3509271
- This should be run …

fix: reading queryset length in a mysql supported way

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/v1/views.py
tests/test_enterprise/api/test_views.py

Adds idempotency logic to create EnterpriseCustomerCatalog to prevent duplicate catalog configurations being created.
Endpoint should return an existing EnterpriseCustomerCatalog that matches the configuration intended to be created. 
Tests also added.
Updating branch, adding the CHANGELOG and bumping the version remain in body of work. 
- *Note*: This **must** be …

feat: Add idempotent catalog creation endpoint

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/integrated_channel/tasks.py

https://splunk.edx.org/en-US/app/search/search?q=search%20duplicates%20found&earliest=-24h%40h&latest=now&display.page.search.mode=smart&dispatch.sample_ratio=1&sid=1683556592.3789398
- This should be run …

fix: duplicate records reading queryset length then splicing

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/v1/serializers.py
test_utils/factories.py
tests/test_enterprise/api/test_serializers.py
tests/test_enterprise/api/test_views.py

- in order to include `auth_org_id` in GEAG requests, we need to be able to retrieve it in contexts outside enterprise (ecomm, subsidy service, etc)
- include `auth_org_id` in serializer, test factories, etc
- https://2u-internal.atlassian.net/browse/ENT-7079

feat: include auth_org_id in enterprise customer api

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/degreed2/exporters/content_metadata.py
tests/test_integrated_channels/test_degreed2/test_exporters/test_content_metadata.py

feat: include obsolete attribute in degreed content transmissions

---

enterprise/api/v1/serializers.py
enterprise/api/v1/views.py
tests/test_enterprise/api/test_views.py

This feature is being added primarily to support the use case of automated environment setup for testing learner credit 2.
I tested this in Postman against devstack, and it worked.  Trust me, I'm a programmer.

feat: add support for creating EnterpriseCustomer via API

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/v1/views.py
enterprise/models.py

fix: making sure unenrollment is saved while revoking fulfillment

---

enterprise/__init__.py
enterprise/api/v1/views.py
enterprise/models.py
enterprise/utils.py
test_utils/factories.py
tests/test_enterprise/api/test_views.py

When calling enroll_learners_in_courses (a.k.a. the bulk enrollment endpoint), gracefully handle the case when a subsidized enrollment (for learner credit 2) is being re-created after being revoked previously.
Before this change, the existing LearnerCreditEnterpriseCourseEnrollment object would not be found (due to transaction_id changing), then the view would fatally fail to create a new one due to a unique constraint on the `enterprise_course_enrollment_id` field.  After this change, it finds the existing object and updates a couple fields on it to re-use it.
ENT-7204

fix: handle case where LearnerCreditEnterpriseCourseEnrollment already exists

---

CHANGELOG.rst
enterprise/__init__.py
enterprise_learner_portal/api/v1/serializers.py
tests/test_enterprise_learner_portal/api/test_serializers.py

fix: Fixed url encoding issue with org_id in executive education course url

---

CHANGELOG.rst
enterprise/__init__.py
enterprise_learner_portal/api/v1/serializers.py

This PR prevents the org_id param addition to exec-ed course home url when auth_org_id is not present on the associated active EnterpriseCustomer record.
JIRA: ENT-7258
- This should be …

fix: prevent org_id param addition to exec-ed course home url

---

CHANGELOG.rst
consent/models.py
enterprise/__init__.py
enterprise/api/v1/serializers.py
enterprise/api/v1/views.py
enterprise/models.py
enterprise/utils.py
enterprise/views.py

- we've implemented X-Request-ID logging in a number of Enterprise IDAs via logger middleware
- we'd like to avoid adding that middleware in the core LMS platform code
- this is a proposal for a logging adapter, wont cover absolutely everything but gives us something
- based on https://docs.python.org/3/howto/logging-cookbook.html#using-loggeradapters-to-impart-contextual-information
You may ask yourself "Why doesn't he just extend `Logger` and use `logging.setLoggerClass(klass)`? Well, that seems to pop in our logger in globally.
```
from enterprise.logging import getEnterpriseLogger
logger = getEnterpriseLogger(__name__)
logger.info("...and how!")
```

feat: faux x-request-id logging in enterprise

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/integrated_channel/exporters/content_metadata.py

chore: more orphaned content transmission logging

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/integrated_channel/exporters/content_metadata.py
tests/test_integrated_channels/test_integrated_channel/test_exporters/test_content_metadata.py

The table's name is in fact not `ContentMetadataTransmissionAudit`... please look away while I go find some hole to curl up in …

fix: fixing name of table used by model fetching method

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/management/commands/update_config_last_errored_at.py
tests/test_management.py

- x ] `make static` has been run to update webpack bundling if any static content was updated …

feat: adding managent command to clear error state

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/blackboard/admin/__init__.py
integrated_channels/canvas/admin/__init__.py
integrated_channels/cornerstone/admin/__init__.py
integrated_channels/degreed/admin/__init__.py
integrated_channels/degreed2/admin/__init__.py
integrated_channels/moodle/admin/__init__.py
integrated_channels/sap_success_factors/admin/__init__.py
integrated_channels/xapi/admin/__init__.py

Currently, to force a customer’s catalog to be retransmitted (updated) through the integrated channels, our team relies on the modified at times of the customer’s catalog object in the enterprise catalog service. While this is perfectly fine to use for our immediate team members, we’d like to have a more straight forward and intuitive approach. 
A button to customers' integrated channel configuration admin page that will trigger an update on all content on the next transmission run by updating the the enterprise customer’s modified time.
On success, we will notify the user that the modified time was updated.
On error, we will notify the user that the modified time was not successfully updated.
[JIRA ENT-2713](https://2u-internal.atlassian.net/browse/ENT-6713)
- …

feat: add button to update customer modified time

---

docs/development.rst
docs/getting_started.rst

We are planning on removing paver, and
we have created an alternative Make command for
running migrations. This updates the documentation.
https://github.com/openedx/devstack/issues/1085
I haven't bumped the version or added a changelog entry because this is a minor docs change.

docs: Replace paver update_db.

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/constants.py
integrated_channels/integrated_channel/exporters/content_metadata.py
integrated_channels/integrated_channel/models.py
integrated_channels/integrated_channel/transmitters/content_metadata.py
integrated_channels/sap_success_factors/exporters/content_metadata.py
integrated_channels/sap_success_factors/transmitters/content_metadata.py
test_utils/fake_catalog_api.py
tests/test_integrated_channels/test_cornerstone/test_views.py
tests/test_integrated_channels/test_integrated_channel/test_exporters/test_content_metadata.py
tests/test_integrated_channels/test_sap_success_factors/test_exporters/test_content_metadata.py
tests/test_integrated_channels/test_sap_success_factors/test_transmitters/test_content_metadata.py
tests/test_management.py

fix: exporter sanitizing content to delete 

---

enterprise/utils.py
tests/test_enterprise/api/test_views.py
tests/test_enterprise/test_utils.py

If an enterprise learner has enrolled in the audit course mode, we would like to support an automatic upgrade to the paid (verified) enrollment track.
In [edx-platform](https://github.com/openedx/edx-platform/pull/32595), the `lms_enroll_user_in_course` function is updated to `lms_update_or_create_enrollment`to allow for an update to the course_mode.
This PR updates the name of the function and any related comments. …

chore: upgrade course_enrollment from audit to verified

---

CHANGELOG.rst
enterprise/__init__.py

Bumping the version to 4.0.1 based on the changes in https://github.com/openedx/edx-enterprise/pull/1786 …

chore: bump version for upgrade course_enrollment from audit to verified

---

.github/workflows/mysql8-migrations.yml
requirements/celery50.txt
requirements/constraints.txt
requirements/dev.txt
requirements/doc.txt
requirements/test-master.txt

- grabbing versions from edx-platform
- mysql8 migration checks needed a backport
```
pip install -qr requirements/dev.txt --exists-action w
DEPRECATION: celery 5.0.4 has a non-standard dependency specifier pytz>dev. pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of celery or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063
pip-sync requirements/test-master.txt requirements/dev.txt requirements/private.* requirements/test.txt
File "/edx/app/venvs/edx-enterprise/bin/pip-sync", line 5, in <module>
from piptools.scripts.sync import cli
File …
```

chore: upgrades to requirements

---

Makefile

- platform installs requirements before calling `make upgrade` https://github.com/openedx/edx-platform/blob/master/Makefile#L116-L136
- we should do the same so that `pip-compile` is available
- i tested this workflow on gh actions

fix: fixing upgrades workflow

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/integrated_channel/exporters/content_metadata.py
integrated_channels/sap_success_factors/exporters/content_metadata.py
tests/test_integrated_channels/test_integrated_channel/test_exporters/test_content_metadata.py

https://splunk.edx.org/en-US/app/search/search?q=search%20_sanitize_and_set_item_metadata%20NYIF%2BBOPC.4x&earliest=-24h%40h&latest=now&display.page.search.mode=smart&dispatch.sample_ratio=1&sid=1689635604.3264070
follow up/iteration on https://2u-internal.atlassian.net/browse/ENT-7406
- It may or may not …

fix: removing items to delete dependency on the catalog service

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/management/commands/monthly_impact_report.py

JIRA ->  [ENT-7410](https://2u-internal.atlassian.net/browse/ENT-7410) …

fix: variable name conflicts in monthly_impact_report command

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/degreed2/client.py
integrated_channels/degreed2/exporters/learner_data.py
integrated_channels/degreed2/models.py
tests/test_integrated_channels/test_degreed2/test_client.py
tests/test_integrated_channels/test_degreed2/test_exporters/test_learner_data.py

The Degreed v2 API incorporated the option to add the value a learner's grade. 
https://developer.degreed.com/reference/post_api-v2-completions
Add the `percentile` field to support passing the grade value.
[JIRA](https://2u-internal.atlassian.net/browse/ENT-5809) …

feat: add grade value to degreed v2

---

Makefile
docker-compose.yml

- a [keycloak](https://www.keycloak.org/) devstack entry for testing
- data is persisted to a local volume
- `make dev.up.keycloak` & `make dev.stop.keycloak`
- http://localhost:8080 for local testing
- `ngrok http 8080` for stage/prod testing

feat: keycloak devstack service

---

tests/test_integrated_channels/test_integrated_channel/test_management/test_integrated_channel_command_mixin.py

- https://2u-internal.atlassian.net/browse/ENT-7427
- concern that inactive customers were still getting the transmissions processed
- no tests existed around the core `get_integrated_channels` method
- tests confirm its working properly

feat: testing around IntegratedChannelCommandMixin

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/management/commands/manufacture_data.py

yeah idk what happened, but the import path being wrong and blowing up meant the actual enterprise tests factories weren't imported. …

chore: fixing import path error in management command

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/moodle/client.py
tests/test_integrated_channels/test_moodle/test_client.py

https://2u-internal.atlassian.net/browse/ENT-7509
This fixes an issue with constructing moodle API urls when the base URL contains a sub directory. Previously, we were dropping the subdirectory in the call to `urljoin`. Removing the first slash in the API path constant fixes that issue.
I tested this change with all of the existing moodle configs in production to ensure that none of them would break.
- Checkout the [Database Migration](https://openedx.atlassian.net/wiki/spaces/AC/pages/23003228/Everything+About+Database+Migrations) Confluence page for …

fix: allow sub directories in moodle base URLs

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/models.py

- 500 error on stage due to this method (stacktrace below)
- this is because the `courses.stage.edx.org` site is not also named `courses.stage.edx.org` so this code is not finding it and trying to create, causing a unique constraint on domain
- move name into defaults since its not part of the unique constraint
- https://docs.djangoproject.com/en/4.2/ref/models/querysets/#get-or-create
```
2023-08-14 18:05:21,785 ERROR 7622 [django.request] [user 5262769] [ip 10.97.14.69] log.py:224 - Internal Server Error: /admin/enterprise/enterprisecustomer/add/
File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/django/db/models/query.py", line 581, in get_or_create
return self.get(**kwargs), False
File …
```

fix: more flexible default site

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/integrated_channel/exporters/learner_data.py
tests/test_enterprise/management/test_manufacture_data.py
tests/test_integrated_channels/test_integrated_channel/test_exporters/test_learner_data.py

We believe tests that "claim" the grade value coming from the certificate API is a letter grade are full of baloney …

bug: swapping grades api grade_percent return value type from string to float

---

CHANGELOG.rst
enterprise/__init__.py
requirements/base.in
requirements/dev.txt
requirements/doc.txt
requirements/edx-platform-constraints.txt
requirements/test-master.txt
requirements/test.txt

replce django-fernet-field with new replica package.
https://pypi.org/project/django-fernet-fields-v2/

chore: replace deprecated package.

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/constants.py
enterprise_learner_portal/api/v1/serializers.py
enterprise_learner_portal/utils.py

##Description
**Problem**
A course that is in progress is erroneously appearing in the completed course list
**Solution**
I have updated the logic for calculating the course_status for executive education courses. Now the status is calculated on the base of CourseDetail model dates.
JIRA -> [ENT-7496](https://2u-internal.atlassian.net/browse/ENT-7496)
- *Note*: This …

fix: enrolled course card grouping behavior for exec-ed courses

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/v1/urls.py
enterprise/api/v1/views/base_views.py
enterprise/api/v1/views/enterprise_customer_catalog.py
tests/test_enterprise/api/test_views.py

We need an endpoint that supports updating the title of an enterprise customer catalog.
Added a PATCH endpoint to url `enterprise_customer_catalog` to support the PATCH request.
[JIRA](https://2u-internal.atlassian.net/browse/ENT-7583)
This PR is part of an epic to implement an edit/view learner credit plan details in support tools. Below are the previous tickets associated:
|Implementation|PR|
| ------------- | ------------- |
|Add feature flag| https://2u-internal.atlassian.net/browse/ENT-7517| 
|Create List View of Learner Credit Plans with Muted Standalone Hyperlinks|https://github.com/openedx/frontend-app-support-tools/pull/349|
|Implements Detailed Plan View with Edit Mode Button|https://github.com/openedx/frontend-app-support-tools/pull/352|
- `base.in` if …

feat: add patch endpoint to update enterprise customer catalog

---

CHANGELOG.rst
enterprise/__init__.py

Rebasing meant the changelog needed updating and the version was unaffected so it slipped my mind 🙈 
- This should be run from either a venv with all the lms/edx-enterprise requirements installed or if …

fix: adding forgotten version bump to enterprise init

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/v1/serializers.py
enterprise/api/v1/views/enterprise_customer_api_credentials.py
tests/test_enterprise/api/test_views.py

fix: put api_credentials bool in api response

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/admin/__init__.py

fix: adding api credential boolean into django

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/v1/serializers.py
test_utils/fake_enterprise_api.py
tests/test_enterprise/api/test_views.py

We need a way to determine on the FE support tools which catalogs are custom versus open courses, exec ed, everything. 
Add read only field `enterprise_catalog_query` to the `EnterpriseCustomerCatalogSerializer` so that the FE can determine if the catalog is an open course, exec ed, everything or custom. 
[JIRA Ticket](https://2u-internal.atlassian.net/browse/ENT-7697)
- Checkout the [Database Migration](https://openedx.atlassian.net/wiki/spaces/AC/pages/23003228/Everything+About+Database+Migrations) Confluence page for helpful tips on creating …

feat: adding read only field to EnterpriseCustomerCatalogSerializer model

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/utils.py
tests/test_enterprise/api/test_views.py
tests/test_enterprise/test_utils.py

Remove any references to `lms_enroll_user_in_course` and use the new function `lms_update_or_create_enrollment`. Also remove the check for the feature flag `ENABLE_ENTERPRISE_BACKEND_EMET_AUTO_UPGRADE_ENROLLMENT_MODE` and update unit tests to use `lms_update_or_create_enrollment`. …

chore: use lms_update_or_create_enrollment without feature flag

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/v1/views/enterprise_customer_sso_configuration.py
enterprise/models.py
enterprise/tpa_pipeline.py

The ideal behavior is that:
- we always tell the orchestrator to create the integrations as "active"
- we show the config as inactive until the point the enterprise is able to use their IDP
- this point should happen when the oauth complete endpoint is hit by the orchestrator
- we don't need to update the validated at every time the integration is used
- 
- *Note*: …

chore: sso orchestrator configs should start inactive and be activated upon successful configuration

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/v1/serializers.py
tests/test_enterprise/api/test_views.py

fix: remove not required fields from serializer

---

integrated_channels/degreed2/exporters/learner_data.py

Context: https://2u-internal.atlassian.net/browse/ENT-7725?focusedCommentId=741115
TLDR: An exception was being thrown due to invalid customer configuration which took us days to trace in Splunk. So, adding a try catch block in this PR with a log including customer and LMS user id for enhanced debugging.
- …

[ENT-7725] - Add try catch block for enhanced debugging

---

integrated_channels/integrated_channel/transmitters/content_metadata.py
integrated_channels/sap_success_factors/transmitters/content_metadata.py
integrated_channels/utils.py
tests/test_integrated_channels/test_sap_success_factors/test_transmitters/test_content_metadata.py

JIRA Ticket: [ENT-7715](https://2u-internal.atlassian.net/browse/ENT-7715)
Description: 
To reduce unnecessary logs, filter the API response only when a successful response is received from the SAP instance.
- It may or may not make a migration depending on exactly what you modified, but it should still be …

[ENT-7715] fix: filter the response only after a successful response status

---

enterprise/constants.py
enterprise/utils.py
integrated_channels/integrated_channel/transmitters/content_metadata.py
tests/test_enterprise/test_utils.py

JIRA Ticket: [ENT-7716](https://2u-internal.atlassian.net/browse/ENT-7716)
Description:
To prevent errors of maxing out packet sizes for the field of APIResponseRecord.
- This should be run from either a …

[ENT-7716] feat: Truncate API Response before writing to DB

---

CHANGELOG.rst
enterprise/__init__.py

chore: version bump for ENT 7715 and 7716

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/urls.py
requirements/celery53.txt
requirements/dev.txt
requirements/doc.txt
requirements/edx-platform-constraints.txt
requirements/js_test.txt
requirements/test-master.in
requirements/test-master.txt
requirements/test.txt

We somehow haven't had api-docs available for edx-enterprise for a while.  This adds them such that they exist at http://localhost:18000/enterprise/api-docs/
- *Note*: Assets will be added automatically. You just need to provide a tag (should match your version number) and title and description.
- Each step in the release build has a condition flag that checks if the rest of the steps are done and if so will deploy to PyPi.
(so basically once your build finishes, after maybe a minute you should see the new version in PyPi automatically …

feat: Add an api-docs page that lives at `[LMS_ROOT_URL]/enterprise/api-docs/`

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/degreed/exporters/learner_data.py
integrated_channels/degreed2/exporters/learner_data.py
integrated_channels/integrated_channel/exporters/learner_data.py
integrated_channels/moodle/exporters/learner_data.py
integrated_channels/sap_success_factors/exporters/learner_data.py
tests/test_integrated_channels/test_degreed/test_exporters/test_learner_data.py
tests/test_integrated_channels/test_degreed2/test_exporters/test_learner_data.py
tests/test_integrated_channels/test_integrated_channel/test_exporters/test_learner_data.py

JIRA Ticket: [ENT-7925](https://2u-internal.atlassian.net/browse/ENT-7925)
Description:
Stop sending course run metadata on integrated channels …

[ENT-7925] feat: stop learner data transmissions for course runs

---

CHANGELOG.rst
enterprise/__init__.py

fix: ENT-7993 version bump

---

enterprise/api/v1/serializers.py
enterprise/api/v1/views/enterprise_customer_catalog.py
tests/test_enterprise/api/test_views.py

This is needed to support sorting of catalog options during provisioning and editing of Learner Credit Plans.
ENT-7922 …

feat: add modified to output of catalog list endpoint

---

CHANGELOG.rst
enterprise/__init__.py
enterprise_learner_portal/api/v1/serializers.py
enterprise_learner_portal/api/v1/views.py
tests/test_enterprise_learner_portal/api/test_serializers.py
tests/test_enterprise_learner_portal/api/test_views.py

**Jira Ticket**: https://2u-internal.atlassian.net/browse/ENT-8069
**Description**: Fixed the domain issue to point to [courses.edx.org](http://courses.edx.org/) for the `resumeCourseRunUrl`.
- This …

fix: fixed the domain issue to point to "courses.edx.org" for the resumeCourseRunUrl

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/static/enterprise/sass/main.scss
package-lock.json
package.json

Part of https://github.com/openedx/axim-engineering/issues/23
This replaces the `@edx/paragon` packag to point to the `paragon` package at
the `openedx` scope(`@openedx/paragon`). Imports have been updated to use the
same locations in the new package.

chore: Update to the new version of paragon in the new scope.

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api_client/enterprise_catalog.py
integrated_channels/degreed2/client.py
tests/test_integrated_channels/test_degreed2/test_client.py

[ENT-7950] - Post skills metadata for Degreed2 

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/moodle/client.py
integrated_channels/utils.py

Description:
Removed course completion check from is_already_transmitted utility is it does not seems to be the desired flow.
JIRA:

Removed course completion check from is_already_transmitted utility

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/degreed2/client.py

version upgrade
- This should be run from either a venv with all the lms/edx-enterprise requirements installed or if you checked out edx-enterprise into the src directory used by lms, you can run this …

fix: remove logs from degreed2 client

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/integrated_channel/exporters/learner_data.py

ENT-8130: add logs to debug ENT-8130

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api_client/sso_orchestrator.py

Currently, the UI error from the SSO Orchestrator API is next to useless, and nothing is logged to splunk.
ENT-8169 …

fix: enable printing of error messages from the SSO Orchestrator API

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/management/commands/compare_discovery_and_enterprise_catalogs.py

A mgmt command to enumerate the enterprise customer catalogs and test a query modification idea. This tests the new filter in `search/all` and compares the counts to the existing catalog in enterprise catalog service (which honors the flags). The goal is for these counts to be the same after my proposed query modification.
The goal is to run this mgmt command in PROD and review the results. If the data checks out, we can make a similar mgmt command to actually alter these catalogs. Then we can remove the flag in this system and in the catalog service.
- https://2u-internal.atlassian.net/browse/ENT-7893
- https://github.com/openedx/course-discovery/pull/4236

feat: mgmt command to explore removing exec-ed cat flag

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/management/commands/add_exec_ed_exclusion_to_catalogs.py

```
20:38:43 2024-01-23 20:39:12,091 INFO 11552 [enterprise.management.commands.add_exec_ed_exclusion_to_catalogs] [user None] [ip None] add_exec_ed_exclusion_to_catalogs.py:62 - 3973a547-72c4-4cda-bd20-2fb66425a760
20:38:43 Traceback (most recent call last):
20:38:43   File "/edx/app/edxapp/edx-platform/manage.py", line 106, in <module>
20:38:43     execute_from_command_line([sys.argv[0]] + django_args)
20:38:43   File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
20:38:43     utility.execute()
20:38:43   File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
20:38:43     self.fetch_command(subcommand).run_from_argv(self.argv)
20:38:43 …
```

fix: guard against null content_filters

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/cornerstone/views.py

feat: add logs to see values

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/admin/__init__.py

- https://2u-internal.atlassian.net/browse/ENT-7893
- this is in prep for removing of the field entirely
- removing it from the UI first, leaving it in the DB in case we need to rollback
- we will be removing this field from the indexing logic shortly

feat: remove ability to edit catalog include_exec_ed_2u_courses

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/admin/__init__.py

- *Note*: Assets will be added automatically. You just need to provide a tag (should match your version number) and title and description.
- Each step in the release build has a condition flag that checks if the rest of the steps are done and if so will deploy to PyPi.
(so basically once your build finishes, after maybe a minute you should see the new version in PyPi automatically (on refresh))
- This **must** be done after the version is visible in PyPi as `make upgrade` in edx-platform will look for the latest version in PyPi.
- Note: the edx-enterprise constraint in edx-platform **must** also be bumped to the latest version in PyPi.

fix: add missing comma to catalog query fields list.

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/integrated_channel/management/commands/remove_duplicate_learner_transmission_audit_records.py

`CornerstoneLearnerDataTransmissionAudit` table is removed from the management command since it already has constraints applied on user_id and course_id which will not allow any duplication of records.
- …

fix: Added logs and removed cornerstone from loop

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/toggles.py
tests/test_enterprise/api/test_filters.py
tests/test_enterprise/api/test_views.py

Adding waffle flag for prequery search suggestions in learner portal.
[Ticket](https://2u-internal.atlassian.net/browse/ENT-8337) …

feat: adds waffle flag for prequery search

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/integrated_channel/admin/__init__.py

ENT-8277 - feat: register admin view for IntegratedChannelAPIRequestLogs

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/v1/serializers.py
enterprise/api/v1/urls.py
enterprise/api/v1/views/enterprise_group.py
tests/test_enterprise/api/test_views.py

https://2u-internal.atlassian.net/browse/ENT-8413 …

feat: CRUD api endpoints for the enterprise group table

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/v1/serializers.py
enterprise/api/v1/urls.py
enterprise/api/v1/views/enterprise_group.py
tests/test_enterprise/api/test_views.py

https://2u-internal.atlassian.net/browse/ENT-8414 …

feat: add api /learners/ endpoint to the enterprise group viewset

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/utils.py
enterprise/api/v1/urls.py
enterprise/api/v1/views/enterprise_group.py
enterprise/models.py
enterprise/signals.py
test_utils/__init__.py
tests/test_enterprise/api/test_views.py
tests/test_enterprise/test_signals.py

https://2u-internal.atlassian.net/browse/ENT-8415
ADR: https://github.com/openedx/edx-enterprise/blob/master/docs/decisions/0013-custom-groups-for-enterprise-learners.rst
in this PR:
- updates to enterprise group API:
- added extra protections to PATCH requests (checking for membership to the requested to change org)
- added `can_access_admin_dashboard` permission validation to both PATCH and CREATE requests
- New `assign_learners` endpoint
- New `remove_learners` endpoint
- Additional process on the User table post save signal to update membership records with newly created EnterpriseCustomerUser objects
- Unit tests
- `make …

feat: adding assign_learners and remove_learners api endpoints for enterprise groups

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/cornerstone/exporters/learner_data.py
tests/test_integrated_channels/test_cornerstone/test_exporters/test_learner_data.py

JIRA: https://2u-internal.atlassian.net/browse/ENT-8198 …

fix: proximus learner transmission issue

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/v1/views/enterprise_customer_user.py
tests/test_enterprise/api/test_views.py

Ensures the Waffle-based feature flags are serialized in the `EnterpriseCustomerUserViewSet` GET response such that we can stop relying on the `enterprise-customer` API endpoint in `frontend-app-learner-portal-enterprise`.
- It may or may not make a migration depending on exactly what you modified, but it …

feat: add Waffle-based enterprise_features to EnterpriseCustomerUserViewSet

---

Makefile

See https://github.com/edx/edx-arch-experiments/issues/558 …

fix: Use openedx/edx-platform since redirects are broken now

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/toggles.py
tests/test_enterprise/api/test_filters.py
tests/test_enterprise/api/test_views.py

https://2u-internal.atlassian.net/browse/ENT-8531 …

feat: add waffle flag for enterprise groups feature

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/admin/__init__.py

**Description**: This PR modifies the django admin page for EnterpriseCustomerCatalog so that the enterprise customer field is easily searchable.
**JIRA** [ENT-8404](https://2u-internal.atlassian.net/browse/ENT-8404)
- It may or may not make a migration depending on exactly what you modified, but it should …

feat: autocomplete for enterprise customer field in EnterpriseCustomerCatalogAdmin

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/integrated_channel/exporters/content_metadata.py

[ENT-8540] - debug why failing transmissions not reattempting after 24hrs

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/v1/views/enterprise_customer.py
enterprise/utils.py
tests/test_enterprise/test_utils.py

A `force_enrollment` boolean flag has been added to the "enrollment info" dict fed into the bulk enrollment endpoint.  This enables consumers of the enterprise bulk enrollment endpoint to force specific enrollments even after the enrollment deadline has passed for the course.
ENT-8525
This is one of three PRs which percolate this single boolean through multiple layers of code, all the way down to the core LMS enrollment API:
1. https://github.com/openedx/enterprise-subsidy/pull/219
2. [YOU ARE HERE] https://github.com/openedx/edx-enterprise/pull/2048
3. https://github.com/openedx/edx-platform/pull/34376

feat: pass force_enrollment when bulk enrolling learners

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/v1/serializers.py
enterprise/models.py
tests/test_enterprise/api/test_views.py

https://2u-internal.atlassian.net/browse/ENT-8503 …

feat: adding additional info to the enterprise group membership serializer

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/v1/serializers.py

We need the `applies_to_all_contexts` in the enterprise group because when we are trying to determine if we are hiding the highlights features from admins, we need to determine if they have any groups that do not have this variable set to true. 
- It may or may not make a migration depending on exactly what …

fix: adding groups variable needed on frontend

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/views.py
integrated_channels/api/v1/cornerstone/urls.py
integrated_channels/api/v1/cornerstone/views.py
integrated_channels/cornerstone/exporters/learner_data.py
integrated_channels/cornerstone/utils.py
tests/test_integrated_channels/test_api/test_cornerstone/test_views.py
tests/test_integrated_channels/test_cornerstone/test_exporters/test_learner_data.py
tests/test_integrated_channels/test_cornerstone/test_utils.py

feat: save cornerstone learner information

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/v1/views/enterprise_group.py
tests/test_enterprise/api/test_views.py

fix: allowing for existing pecus to be added to enterprise groups

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/cornerstone/views.py

Description: This is a fix PR to address the 500 server error that General Mills is receiving while fetching the courses. 
https://courses.edx.org/cornerstone/course-list?ciid=75de5567-2e9e-4c44-a28e-339635801658
- It may or may not make a migration depending on exactly what you modified, but it should still …

fix: return only active CSOD configs

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/signals.py
enterprise/tasks.py
enterprise/utils.py
tests/test_models.py

**Description:** Move the update of user preferences inside an async task to avoid request timeout. Timeout can happen if the number of user preferences to update is too large.
**JIRA:** https://2u-internal.atlassian.net/browse/ENT-8614
- It may or may not make a migration depending on exactly what you …

perf: make user pref update non-blocking

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/cornerstone/views.py
tests/test_integrated_channels/test_cornerstone/test_views.py

Description: We should not be returning courses for any inactive Cornerstone customers and gracefully handle the 500 server error. …

fix: return 404 for inactive csod configs

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/signals.py
enterprise/tasks.py
enterprise/utils.py
tests/test_models.py

**Description:** Set default language for all learners linked with an enterprise customer.
**JIRA**: https://2u-internal.atlassian.net/browse/ENT-8614 …

fix: set default language for all learners linked with an enterprise customer

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/v1/serializers.py
requirements/celery53.txt
requirements/ci.txt
requirements/dev.txt
requirements/doc.txt
requirements/edx-platform-constraints.txt
requirements/js_test.txt
requirements/test-master.txt
requirements/test.txt
tests/test_enterprise/api/test_views.py

ENT-8788
Testing
===
Before this PR (`force_enrollment` key was ignored from input):
```
$ python manage.py shell
>>> from enterprise.api.v1.serializers import EnterpriseCustomerBulkSubscriptionEnrollmentsSerializer
>>> serializer = EnterpriseCustomerBulkSubscriptionEnrollmentsSerializer(data={'enrollments_info': [{'email': 'newuser@test.com', 'course_run_key': 'course-v1:edX+DemoX+Demo_Course', 'license_uuid': '5b77bdbade7b4fcb838f8111b68e18ae', 'force_enrollment': True}]})
>>> serializer.is_valid()
True
>>> serializer.validated_data.get('enrollments_info')[0].get('force_enrollment', False)
False
```
After this PR:
```
$ python manage.py shell
>>> from enterprise.api.v1.serializers import EnterpriseCustomerBulkSubscriptionEnrollmentsSerializer
>>> serializer = …
```

fix: support `force_enrollment` in serializers used by bulk enrollment

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/v1/views/plotly_auth.py
tests/test_enterprise/api/test_views.py

**JIRA:** [ENT-8666](https://2u-internal.atlassian.net/browse/ENT-8666)
- This should be run from either a venv with all the lms/edx-enterprise requirements installed or if you checked out edx-enterprise …

fix: add enterprise audit enrollment reporting status in plotly auth token

---

CHANGELOG.rst
enterprise/__init__.py
enterprise_learner_portal/api/v1/views.py
pytest.local.ini
setup.cfg
tests/test_enterprise_learner_portal/api/test_views.py

Passes in a dictionary used for computation of course run resume URLs in the `patch()` method of the `EnterpriseCourseEnrollmentView`.
ENT-8608
- *Note*: Assets will be added automatically. You just need to provide a tag (should match your version number) and title and description.
- Each step in the release build has a condition flag that checks if the rest of the steps are done and if so will deploy to PyPi.
(so basically once your build finishes, after maybe a minute you should see the new version in PyPi automatically (on refresh))
- Trigger the '[Upgrade one Python dependency](https://github.com/openedx/edx-platform/actions/workflows/upgrade-one-python-dependency.yml)' action against master in edx-platform with new version number to generate version bump PR
- This …

fix: fix the PATCH method of ``EnterpriseCourseEnrollmentView``.

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/signals.py
enterprise/tasks.py
enterprise/utils.py
tests/test_models.py

**JIRA:** https://2u-internal.atlassian.net/browse/ENT-8614 …

revert: fix: set default langauge for all learners linked with an enterprise customer

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/v1/serializers.py
enterprise/api/v1/views/enterprise_group.py
tests/test_enterprise/api/test_views.py

Additionally adding activation date to the membership serializer …

feat: splitting out group membership serializer learner id into lms user ID and ecu ID

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/admin/views.py
enterprise/constants.py
tests/test_admin/test_view.py

...so that we can support customers with a very large number of learners ENT-8850 …

feat: limit the number of resulting learners in Django admin manage learners view

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/middleware.py
tests/test_middleware.py

fix: update language cookie if langauge cookie is not same as user's language preference

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/v1/serializers.py
enterprise/api/v1/views/enterprise_group.py
enterprise/management/commands/remove_expired_pending_group_memberships.py
enterprise/models.py
tests/test_enterprise/management/test_remove_expired_pending_group_memberships.py

fix: hard deleting expired group memberships

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/admin/__init__.py

https://2u-internal.atlassian.net/browse/ENT-8884
Search by:
- membership uuid
- group uuid
- enterprise customer uuid
- ECU ID
- PECU email …

fix: allowing for search lookup of group members in django admin

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/tasks.py

Adds debugging log lines for using `create_recipients` …

chore: debugging log lines

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/tasks.py
tests/test_enterprise/api/test_views.py
tests/test_enterprise/test_tasks.py

https://2u-internal.atlassian.net/browse/ENT-8929
We were attempting to look up membership uuid's after they have been deleted. To fix this, we need to update the model lookup from `enterprise_group_membership_model().objects` to `enterprise_group_membership_model().all_objects`. …

fix: update enterprise model lookup in removal email task

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/v1/views/enterprise_group.py
tests/test_enterprise/api/test_views.py

https://2u-internal.atlassian.net/browse/ENT-8942 …

fix: only creating membership records for relevant ECUs

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/v1/views/enterprise_group.py
tests/test_enterprise/api/test_views.py

https://2u-internal.atlassian.net/browse/ENT-8953 …

feat: allowing for group members to be revived by reassigning

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/v1/serializers.py
enterprise/api/v1/views/enterprise_group.py
tests/test_enterprise/api/test_views.py

https://2u-internal.atlassian.net/browse/ENT-8974 …

feat: allowing for group members to be specified when fetched

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/v1/serializers.py
enterprise/api/v1/views/enterprise_group.py
tests/test_enterprise/api/test_views.py

Frontend admin portal need the ability to send a removal request of all member records should the members table has "all rows selected". In those situations, we won't have individual records/emails to specify to this endpoint but will know that the request applies to the entire group.
- It may or may not …

feat: allowing for group members removal endpoint to support remove all

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/signals.py
tests/test_enterprise/test_signals.py

feat: submit ` create_enterprise_enrollment` task on commit

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/admin/__init__.py

On the [Enterprise Group creation form](https://internal.courses.edx.org/admin/enterprise/enterprisegroup/add/), updating the Enterprise Customer field to be an autocomplete element rather than a dropdown.
JIRA: https://2u-internal.atlassian.net/browse/ENT-9059
- It may or may not make a migration depending …

Updating autocomplete field for Enterprise Group creation form

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/admin/__init__.py
enterprise/api/v1/views/enterprise_subsidy_fulfillment.py
test_utils/__init__.py
tests/test_consent/api/test_views.py
tests/test_enterprise/api/test_views.py

Additionally, this fixes a bug whereby users with the `enterprise.can_manage_enterprise_fulfillment` or
`enterprise.can_access_admin_dashboard` permissions in at least one enterprise could successfully authenticate against these endpoints for *any* enterprise.
ENT-9088 …

fix: cancel-fulfillment endpoint is now idempotent

---

.github/workflows/ci.yml
CHANGELOG.rst
enterprise/__init__.py
enterprise/admin/forms.py
enterprise/rules.py
enterprise/signals.py
integrated_channels/integrated_channel/exporters/content_metadata.py
integrated_channels/integrated_channel/models.py
tests/test_enterprise/test_signals.py

Also removes Python 3.8 from the CI matrix.
ENT-9107 …

fix: submit the create_enterprise_enrollment task with a configurable countdown

---

enterprise/models.py
enterprise/signals.py
tests/test_enterprise/test_signals.py

Also, update ECE.unenrolled everywhere we update ECE.unenrolled_at. This field seems to have been completely overlooked. I'm not sure if we use the `unenrolled` field anywhere, but it certainly can be confusing to anyone looking at the database.
ENT-8991

feat: atomically re-activate ECE when re-activating SCE

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/toggles.py
tests/test_enterprise/api/test_filters.py
tests/test_enterprise/api/test_views.py

fix: add waffle flag for enterprise customer support tool

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/integrated_channel/admin/__init__.py
tests/test_admin/test_admin.py

Description:
Fixed search fetch crashing because of server taking too long for api request logs.
JIRA:
https://2u-internal.atlassian.net/jira/software/c/projects/ENT/issues/ENT-9175

Fixed search fetch crashing because of server taking too long for api request logs

---

CHANGELOG.rst
enterprise/__init__.py
enterprise_learner_portal/api/v1/serializers.py

Serializes the `course_key` attribute from the CourseDetails model from the federated content connector.
This should not be merged until all related PRs are merged AND the `import_course_runs_metadata` job in production has completed successfully
Related PRs: 
- https://github.com/edx/federated-content-connector/pull/25
- https://github.com/edx/edx-internal/pull/11330
- https://github.com/edx/edx-internal/pull/11341 …

fix: serialize 'course_key' from the CourseDetails model

---

CHANGELOG.rst
enterprise/__init__.py

Bumping up version num to 4.22.3
- This should be run from either a venv with all the lms/edx-enterprise requirements installed or if you checked out edx-enterprise into the src directory used by lms, you …

feat: adding enterprise-customer-support-endpoint version bump

---

.github/workflows/publish.yml

The CI workflow "[build-and-publish](https://github.com/openedx/edx-enterprise/actions/runs/10265100939/job/28449802130#logs)" is failing due to an incompatible Python version in the CI workflow after updating the requirements. 
To resolve this issue, I have upgraded the Python version in the CI workflow file.
- Python Requirements Update by @edx-requirements-bot in https://github.com/openedx/edx-enterprise/pull/2193
- chore: bump version by [mahamakifdar19](https://github.com/mahamakifdar19) in https://github.com/openedx/edx-enterprise/pull/2196
- `make upgrade && make requirements` have been run to regenerate …

chore: update CI workflow to use Python 3.11

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/v1/serializers.py
tests/test_enterprise/api/test_views.py

Add `created` field to response
https://2u-internal.atlassian.net/browse/ENT-9302 …

feat: add created time to response 

---

CHANGELOG.rst
docs/decisions/0014-enterprise-catalog-sync-catalogs.rst
enterprise/__init__.py
enterprise/api_client/client.py
enterprise/api_client/enterprise_catalog.py
enterprise/models.py
tests/test_enterprise/api_client/test_enterprise_catalog.py
tests/test_models.py

[Jira Ticket](https://2u-internal.atlassian.net/browse/ENT-8661)
The EnterpriseCatalogQuery model is synced to a corresponding [CatalogQuery model](https://github.com/openedx/enterprise-catalog/blob/0c832240bd67a1748406d126fd0305eeb63733a2/enterprise_catalog/apps/catalog/models.py#L54) in enterprise-catalog.  Currently, if we save a EnterpriseCatalogQuery with a content_filter value that is a duplicate of another, and try to update the corresponding CatalogQuery, the update will fail and the two entities will be in an inconsistent state.
When saving an EnterpriseCatalogQuery model with a changed content_filter, we will now check to see if the new content_filter already exists in enterprise-catalog, and raise a ValidationError if it does, showing an error on the admin page.
**Merge …

fix: don't allow saving duplicate EnterpriseCatalogQuery content_filter

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/admin/__init__.py
tests/test_admin/test_admin.py

Adding option to show soft deleted group memberships in django admin
JIRA: https://2u-internal.atlassian.net/browse/ENT-9116
**Testing**
Setup:
EnterpriseCustomerUser `Davidson Jones` is part of soft deleted group membership by marking their record as "is_removed" = 1
EnterpriseCustomerUser `Jackson LLC` is not part of soft deleted group membership and their record has "is_removed" = 0
1. Keeping default behavior to only show non-soft deleted results:
2. Filtering by `is_removed` = No shows non-deleted results (Jackson LLC):
3. Filtering by `is_removed` = Yes shows only soft-deleted result (Davidson Jones):
4. Searching for soft deleted group membership displays warning
- `test-master.in` if …

Feat: Add option to show soft deleted group memberships in django admin

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/v1/views/enterprise_subsidy_fulfillment.py
enterprise/event_bus.py
enterprise/models.py
requirements/base.in
requirements/common_constraints.txt
requirements/dev.txt
requirements/doc.txt
requirements/edx-platform-constraints.txt
requirements/js_test.txt
requirements/test-master.txt
requirements/test.txt
tests/test_enterprise/api/test_views.py
tests/test_enterprise/test_event_bus.py

event type: org.openedx.enterprise.learner_credit_course_enrollment.revoked.v1
event_name: LEARNER_CREDIT_COURSE_ENROLLMENT_REVOKED
The motivation for emitting this event is to support event-driven creation of openedx_ledger.Reversal objects.
ENT-9213
Merging of this PR is blocked until we can merge and release https://github.com/openedx/openedx-events/pull/380

feat: emit learner credit unenrollment event

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/models.py
enterprise/signals.py
tests/test_enterprise/api/test_views.py
tests/test_enterprise/test_signals.py

I had originally tried emitting this event from the `/cancel_enrollment`
API endpoint, but in reality the LMS and Enterprise dashboards were
calling the `/change_enrollment` endpoint.  The former is called by
enterprise-subsidy on transaction reversal, i.e. NOT learner-initiated.
The latter is learner-initiated, and that's the original goal of this
work.
Changes in this commit:
* Update the event emission to live closer to the fulfillment
model itself (inside `revoke()`).
* Ensure that when an EnterpriseCourseEnrollment is unenrolled, the
related Fulfillment subclass is revoked. This is a best-effort to
improve internal consistency during learner-initiated unenrollment.
* Consumers of the various enrollment models are now expected to call
helper functions to …

fix: send LEARNER_CREDIT_COURSE_ENROLLMENT_REVOKED from the correct place.

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/integrated_channel/exporters/learner_data.py

feat: add logging to debug SAP SF transmission issues

---

.github/workflows/mysql8-migrations.yml

This code does not have any dependencies that are specific to any specific
version of ubuntu.  So instead of testing on a specific version and then needing
to do work to keep the versions up-to-date, we switch to the ubuntu-latest
target which should be sufficient for testing purposes.
This work is being done as a part of https://github.com/openedx/platform-roadmap/issues/377
closes https://github.com/openedx/edx-enterprise/issues/2204

build: Switch to ubuntu-latest for builds

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/v1/serializers.py
enterprise/models.py
enterprise/utils.py
enterprise/views.py
test_utils/fake_enrollment_api.py
tests/test_admin/test_view.py
tests/test_enterprise/views/test_grant_data_sharing_permissions.py
tests/test_models.py

edx-rest-api-client was doing a wildcard import of the underlying
Slumber exception.  This wildcard impart has been droped in the latest
release 6.0.0
This change updates the edx-enterprise code to not rely on this
indirection to import the exception class.
Relevant change: https://github.com/openedx/edx-rest-api-client/commit/f3a7cd00565c62e45a9e39590e44d152ceafc277#diff-d34240bacb445782a73762a7380c1c64efc25ded2afb18245bf2256fda8157ff

fix: Don't import HttpClientError from edx-rest-api-client

---

CHANGELOG.rst
enterprise/__init__.py

Version 4.25.14 was tagged in git but the version was not bumped in the
package so the release automation failed.
https://github.com/openedx/edx-enterprise/actions/runs/10907374740
Moving the last unreleased change to the next minor version so that we
can release it.

fix: Bump the version again.

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/toggles.py
tests/test_enterprise/api/test_filters.py
tests/test_enterprise/api/test_views.py

Adds feature flag `ENTERPRISE_GROUPS_V2` for groups v2 work.
https://2u-internal.atlassian.net/browse/ENT-8782 …

feat: add waffle flag for groups v2 features

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/v1/views/enterprise_customer.py
tests/test_enterprise/api/test_views.py

Adds pagination to the support tool customer list view
> 1. visit link http://localhost:18000/enterprise/api/v1/enterprise-customer/support_tool/? and verify that the response is paginated 
>2. check that you can filter by customer name via query param `user_query`  …

feat: add pagination to the support tool customer list

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/blackboard/exporters/learner_data.py
integrated_channels/canvas/exporters/learner_data.py
integrated_channels/cornerstone/exporters/learner_data.py
integrated_channels/degreed2/exporters/learner_data.py
integrated_channels/moodle/exporters/learner_data.py
integrated_channels/sap_success_factors/exporters/learner_data.py
tests/test_integrated_channels/test_blackboard/test_exporters/test_learner_data.py
tests/test_integrated_channels/test_canvas/test_exporters/test_learner_data.py
tests/test_integrated_channels/test_cornerstone/test_exporters/test_learner_data.py
tests/test_integrated_channels/test_degreed2/test_exporters/test_learner_data.py
tests/test_integrated_channels/test_moodle/test_exporters/test_learner_data.py
tests/test_integrated_channels/test_sap_success_factors/test_exporters/test_learner_data.py

Description:
added content_title, progress_status in get_learner_data_records for derived classed of learner data exporters.
JIRA:
https://2u-internal.atlassian.net/jira/software/c/projects/ENT/issues/ENT-9516

Added content_title, progress_status in get_learner_data_records for derived classed

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/v1/serializers.py
test_utils/fake_catalog_api.py
tests/test_enterprise/api/constants.py
tests/test_enterprise/api/test_views.py

Exposes `best_mode_for_course_run` in `DefaultEnterpriseEnrollmentIntentionSerializer`, which will be used when attempting bulk enrollment for enrollable default enterprise enrollment intentions. That is, the bulk enrollment API accepts a `mode` property, which `best_mode_for_course_run` will be passed.
- It …

fix: serialize `best_mode_for_course_run` field in `DefaultEnterpriseEnrollmentIntentionSerializer`

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/v1/views/enterprise_customer.py

feat: add new endpoint to unlink the logged in user

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/management/commands/monthly_impact_report.py

**Description**: This PR fixes the query for the monthly impact report command. The table column names were updated.
**JIRA**: [ENT-9584](https://2u-internal.atlassian.net/browse/ENT-9584)
- This should …

fix: fixed query for monthly impact report command

---

CHANGELOG.rst
enterprise/__init__.py
tests/test_enterprise/api/test_views.py

This PR cover up test cases for the changes made in https://github.com/openedx/edx-enterprise/pull/2279 …

feat: add test cases for newly added unlink_self endpoint

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/v1/serializers.py
tests/test_enterprise/api/test_views.py

https://2u-internal.atlassian.net/browse/ENT-9741 …

fix: ensure correct `admin_users` in EnterpriseCustomerUserViewSet response

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/v1/views/enterprise_customer_reporting.py

feat: removed custom pagination for reporting configurations

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/constants.py
enterprise/models.py
enterprise/utils.py

1. During stage QA, it was observed that a course run with only an `honor` seat was not enrollable via the LMS bulk enrollment API when realizing default enterprise enrollment intentions. It was determined that this was due to relying on a constant `BEST_MODE_ORDER` that didn't include audit/honor seat modes; as such, when trying to enroll in this `honor`-only course run, it was falling back to attempt to enroll in a non-existent `audit` seat, resulting in a 409 on the LMS bulk enrollment API. This PR removes `BEST_MODE_ORDER` to singularly rely on the existing `COURSE_MODE_SORT_ORDER` instead, which includes `honor`.
2. When calling the `/enterprise/api/v1/default-enterprise-enrollment-intentions/learner-status/` LMS API locally with a default enrollment intention configured for course …

fix: use single constant for course mode priority; only fetch catalog list with resolved course run

---

.github/workflows/mysql8-migrations.yml

chore: update github actions cache from v2 to v4

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/v1/views/enterprise_customer_members.py
enterprise/models.py

Couldn't figure out an easy way to get this concatenation syntax working correctly (CONCAT function was tried previously), so now just falling back to one field (username) instead. This should not impact production data as the vast majority of users have data populated in the auth_userprofile table, but this will give us better testable data on stage.
- *Note*: This …

fix: Fixed the query fetching enterprise customer members

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/v1/views/enterprise_customer_members.py

[Jira Ticket](https://2u-internal.atlassian.net/browse/ENT-9467)
This change adds support for the `page_size` query parameter on the `enterprise-customer-members` endpoint.
The link is [http://localhost:18000/enterprise/api/v1/enterprise-customer-members/{enterprise-uuid}](http://localhost:18000/enterprise/api/v1/enterprise-customer-members/%7Benterprise-uuid%7D)
- Add `?page_size=1` to url to test pagination
- Confirm page size is still 10 by default when omitting `page_size`
- Confirm `page_size` still works with `user_query` param
Check that each row has an enterprise_customer_user dict with info like first/last name and an enrollment count
Add ?user_query=test to url to make sure it is only filtering for either emails or names that contain the user query
- …

feat: Add page_size support to enterprise-customer-members endpoint

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/v1/serializers.py
enterprise/api/v1/views/enterprise_customer_members.py
tests/test_enterprise/api/test_serializers.py

Adds sorting support to the `enterprise-customer-members` endpoint to allow a user to sort by a member's `joined_org` date and member's `name`. 
https://2u-internal.atlassian.net/browse/ENT-9861
Testing instructions:
1. add users to an enterprise via the `Manage learners` page: http://localhost:18000/admin/enterprise/enterprisecustomer/7dbf461e-8d3d-4a4a-9b20-9c9121f04806/manage_learners 
2. go to the `enterprise-customer-members` endpoint and verify that you can sort the results by `joined_org` and `name` via the following parameters: 
-`sort_by=name`: http://localhost:18000/enterprise/api/v1/enterprise-customer-members/7dbf461e-8d3d-4a4a-9b20-9c9121f04806?sort_by=name
- `sort_by=name&is_reversed=true`
- `sort_by=joined_org`: http://localhost:18000/enterprise/api/v1/enterprise-customer-me …

feat: adds sorting support to enterprise-customer-members endpoint

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/moodle/client.py

fix: Log all learner transmissions

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/v1/views/enterprise_customer_support.py

[Jira Ticket](https://2u-internal.atlassian.net/browse/ENT-9884)
User results from the enterprise-customer-support endpoint that are filtered by user name/email, will return customer results from *any* enterprise customer.
- Check out branch into edx-enterprise
- Install edx-enterprise version on local devstack
- Test that when `enterprise-customer-support` is called with 'user_query', that no users outside of the enterprise are returned
- Sample query: `http://localhost:18000/enterprise/api/v1/enterprise-customer-support/{enterprise customer uuid}?user_query={term to filter name/email by}&page=1`
- `make upgrade && make …

fix: enterprise-customer-support should only return learners from given customer

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/management/commands/validate_default_enrollment_intentions.py
enterprise/models.py
tests/test_enterprise/management/test_validate_default_enrollment_intentions.py

Introduced validate_default_enrollment_intentions.py to check that all DefaultEnterpriseEnrollmentIntention objects have a valid content_key which actually belongs to at least one of the related customer's catalogs.
ENT-9941

feat: new mgmt command to validate default enrollment intentions

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/management/commands/validate_default_enrollment_intentions.py
tests/test_enterprise/management/test_validate_default_enrollment_intentions.py

When testing in prod, I found that Verizon Skills Forward was skipped because it only had a custom/curated catalog (catalog query was NULL). Greatest() in MySQL returns NULL if any input is NULL (unlike PostgreSQL), so adding Coalesce() with an arbitrarily old date is necessary to mimic the PostgreSQL behavior.
ENT-9941

fix: Do NOT skip validating intentions which have NO related catalog queries

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/management/commands/validate_default_enrollment_intentions.py

ENT-9941
Relevant docs
===
Testing
===
Before this PR, invoking the management command in devstack results in this ambiguous error (despite unit tests running via SQLite functioning properly):
```
File "/edx/app/edxapp/edx-platform/./manage.py", line 106, in <module>
execute_from_command_line([sys.argv[0]] + django_args)
File "/edx/app/edxapp/venvs/edxapp/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
utility.execute()
File "/edx/app/edxapp/venvs/edxapp/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
self.fetch_command(subcommand).run_from_argv(self.argv)
File "/edx/app/edxapp/venvs/edxapp/lib/python3.11/site-packages/django/core/management/base.py", line …
```

fix: cast datetime.datetime to DateTimeField as required by Coalesce()

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/toggles.py
tests/test_enterprise/api/test_filters.py
tests/test_enterprise/api/test_views.py

[ENT-10106](https://2u-internal.atlassian.net/browse/ENT-10106)
> To de-risk changes where possible, we would like to avoid an instant cutover from querying Algolia in the Enterprise Learner/Admin Portal MFEs by enterprise-specific attributes (e.g., `enterprise_customer_uuids`) to non-enterprise-specific attributes (e.g., `enterprise_catalog_query_uuids`). Instead, we’d like to expose a Waffle flag for an percentage-based incremental migration from the current filtering strategy to the new. …

feat: expose catalog_query_search_filters_enabled feature flag

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/v1/views/analytics_summary.py
enterprise/api_client/xpert_ai.py
enterprise/settings/test.py

**Ticket:** [ENT-10098](https://2u-internal.atlassian.net/browse/ENT-10098)
**Description:** Migrated analytics_summary API to Xpert API v2. I've also created a [PR](https://github.com/edx/edx-internal/pull/12424) in `edx-internal` to include `client_id` in environment variables.
**Dependency**: We need to merge and deploy `edx-internal` [PR](https://github.com/edx/edx-internal/pull/12424) before merging this PR. …

chore: migrate analytics_summary API to Xpert v2

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/management/commands/backfill_ecu_table_user_foreign_key.py
enterprise/models.py
enterprise/utils.py
integrated_channels/utils.py
tests/test_enterprise/management/test_backfill_ecu_table_user_foreign_key.py
tests/test_models.py

Part 3 of #2338 .
Should be merged after other two parts are merged and deployed.
To Do:
Edit save() method or something to make sure any record added after merge will add the correct value to `user_fk`. …

Refactor  add foreign key to ecu part 3

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/management/commands/backfill_ecu_table_user_foreign_key.py
tests/test_enterprise/management/test_backfill_ecu_table_user_foreign_key.py

fix: add historical table to management command for ecu

---

CHANGELOG.rst
enterprise/__init__.py
requirements/base.in
requirements/ci.txt
requirements/dev.in
requirements/dev.txt
requirements/doc.in
requirements/doc.txt
requirements/edx-platform-constraints.txt
requirements/js_test.txt
requirements/test-master.in
requirements/test-master.txt
requirements/test.in
requirements/test.txt
setup.py

Makes `edx-braze-client` a dependency for dev and test, but no longer for `base.in`. This _may_ allow us to remove `edx-braze-client` in edx-platform, which installs edx-enterprise and its dependecies based on edx-enterprise's `base.in`.
This also includes edx-braze-client in `setup.py` as an extra requirement. You can try this out from within edx-enterprise as follows:
```
pyenv local enterprise-with-braze # activates my virtual environment for test installation
pip freeze | grep braze
pip install . # installs edx-enterprise into your test virtualenv
pip freeze | grep braze
pip install .[braze] # install with the extra requirement "braze"
pip freeze | grep braze
```
- `test-master.in` if …

build: remove braze from base requirements

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/v1/serializers.py

[Jira Ticket](https://2u-internal.atlassian.net/browse/ENT-10190)
Adds the `group_uuid` field to the group membership api payload.
1. checkout this branch
2. Select enterprise customer and group member
3. visit this link: https://localhost:18000/enterprise/api/v1/enterprise-group-membership/?lms_user_id={insert group member id}&enterprise_uuid={insert enterprise customer uuid}
4. verify that the `group_uuid` field is present in results and matches the relevant group uuids …

fix: add group_uuid to group membership endpoint payload

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api_client/braze.py
enterprise/tasks.py

We don't want to raise a warning about braze when code is loaded, only when a caller attempts to _use_ `BrazeClient`.  See explanation in https://github.com/openedx/edx-enterprise/pull/2364.
- This should …

fix: move BrazeClient import warning to BrazeAPIClient.__init__()

---

CHANGELOG.rst
enterprise/__init__.py
enterprise_learner_portal/api/v1/serializers.py
tests/test_enterprise/api/test_serializers.py

The enterprise_course_enrollments API serves the data for the enrollment cards on the Learner Portal dashboard, serving the course_run_url powering the “Start”/”Resume” CTA amongst other metadata.
This PR sends the course_id as an additional parameter to GetSmarter dashboard.
This will remove the intermediary step of landing on the GetSmarter dashboard. Instead, the “Start course” / “Resume” CTA from the Learner Portal dashboard for Exec Ed course cards would link directly to the OLC, without the learner needing to go through the Dashboard.
The existing GetSmarter dashboard link URL used today will now also accept _course_id_. When passed, the URL will authenticate via SSO through the _org_id_ and subsequently redirect on its own to the _course_id_.
The course_id reflects …

feat: updated the _get_course_run_url to pass external_identifier as a parameter

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/v1/views/enterprise_group.py
enterprise/utils.py
tests/test_enterprise/api/test_views.py

[Jira Ticket](https://2u-internal.atlassian.net/browse/ENT-10246)
Currently we allow learner emails to be entered via csv file, and do not restrict them to the email casing they registered with.  As such, we need to support looking up existing `User` records in a case-insensitive manner.
- Deploy this change locally
- Using Admin Portal, invite a learner to a group via csv, where their email in the csv does *not* match the casing their email was originally registered with
- Verify the learner is invited to the group successfully, and no duplicate `PendingEnterpriseCustomerUser` records are created in the process
- `make upgrade && …

fix: assign_learners use case insensitive lookup with received email addresses

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/utils.py

[Jira Ticket](https://2u-internal.atlassian.net/browse/ENT-10246)
Fix for https://github.com/openedx/edx-enterprise/pull/2367.
- Deploy this change locally
- Using Admin Portal, invite a learner to a group via csv, where their email in the csv does *not* match the casing their email was originally registered with
- Verify the learner is invited to the group successfully, and no duplicate `PendingEnterpriseCustomerUser` records are created in the process
- Checkout the [Database Migration](https://openedx.atlassian.net/wiki/spaces/AC/pages/23003228/Everyt …

fix: assign_learners unpack args dictionary before using in query filter

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/integrated_channel/exporters/content_metadata.py

[ENT-10198] - chore: add logs for debugging

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api_client/xpert_ai.py
tests/test_enterprise/api/test_views.py

Ticket: [ENT-10381](https://2u-internal.atlassian.net/browse/ENT-10381)
Description: Xpert AI v2 endpoint returns a list for our client id. I have fixed the endpoint to return content from 1st element of the list.
- It may or may not make a migration depending on exactly what you modified, but it should …

fix: handling the xpert v2 response correctly

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/utils.py
enterprise/views.py
tests/test_enterprise/views/test_program_enrollment_view.py

fix: fix unit tests that broke due to path() returning UUID objects

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/admin/__init__.py

Making the OnboardingFlow available in django admin  …

fix: adding OnboardingFlow to django

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/xapi/client.py
integrated_channels/xapi/utils.py

fix: Added more logs for xapi transmissions debugging

---

CHANGELOG.rst
enterprise/__init__.py
integrated_channels/xapi/client.py

fix: Added full xapi response for debugging

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/api/v1/serializers.py
requirements/celery53.txt
requirements/ci.txt
requirements/common_constraints.txt
requirements/dev.txt
requirements/doc.txt
requirements/edx-platform-constraints.txt
requirements/js_test.txt
requirements/test-master.txt
requirements/test.txt
tests/test_enterprise/api/test_filters.py
tests/test_enterprise/api/test_views.py
tests/test_enterprise_learner_portal/api/test_views.py

Background:
---
About two weeks ago edx-platform upgraded DRF from 3.14->3.16.1 and enterprise team started noticing the `POST /api/v1/pending-enterprise-learner` endpoint stopped being idempotent. It would return 400 errors instead of 204 No Content on duplicate requests.
Root Cause:
---
DRF 3.15 introduced a feature to automatically add uniqueness validators to a model serializer if any are found on the underlying model. While this feature is nice, it broke assumptions in the logic for many of our serializers.
Solution:
---
Disable the new feature for affected model serializers by overriding the `Meta.validators` attribute.
ENT-10865

fix: upgrade djangorestframework and skip automatic validators

---

CHANGELOG.rst
enterprise/__init__.py
enterprise/admin/__init__.py

Previously, we were rendering the entire Enterprise Customer User table as a dropdown which was causing it to error out on prod because of the amount of users. This PR replaces it with a raw_id_field instead.
[Jira ticket 
](https://2u-internal.atlassian.net/browse/ENT-10949) …

fix: fixing the user dropdown to not render all users
